### ISSUE TITLE
Proper success and error handling after submitting a manual deposit

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-payments#1139]
On success, there should be some kind of feedback to the merchant. At the very least, a notice. Triggering a manual deposit will change the whole Deposits Overview UI, and obviously there will be a new row in the Deposits list. So, at the very least, the `overview` section will need to be refreshed, and the new deposit will need to be added to the Deposits data store. Maybe a full-page reload would be the most pragmatic approach.

If there's an error while triggering a manual deposit, the error message should appear in the modal, and allow the merchant to retry.

If the error is due to a mismatch between the amount was available when the modal was open and the amount that's available *now*, then ideally the UI should refresh itself so the retry has a chance to succeed.

Related: 458-gh-woocommerce-payments-server

**Comment by jessepearson** [comment]
The work here was split across #1335 and also #1437. 

At present the success displays as a snackbar as shown in the designs: paJDYF-Rf-p2 . On success, the Overview and List components refresh to show the new data. 
The error also just displays as a snackbar, but the components do not reload. We can have them reload so that if for some reason the button should not have displayed it will be removed. It's just a matter of moving the `invalidateResolutionForStoreSelector` calls from the `try` to a `finally` at the end.

**Comment by jessepearson** [comment]
The server is going to return several types of error messages, so I have created a new issue to tackle handling those:
https://github.com/Automattic/woocommerce-payments/issues/1588
For support purposes, they do show in the logs.

#1437 has set up success/error messages, however, I noticed that if there is an error, the Instant Deposit button remains and it is not clickable. I am working to resolve that.

**Comment by jessepearson** [comment]
Closed via #1597
