### ISSUE TITLE
Style the "Instant Deposit" button and modal

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/woocommerce-payments#1141]
Follow the designs in paJDYF-Rf-p2

**Comment by jessepearson** [comment]
Styling of the button and modal was completed in #1335.

The Instant Deposit button does not match the styling exactly due it does not match one of the default button types:
https://developer.wordpress.org/block-editor/reference-guides/components/button/
Also, to note, not all button types are available due to outdated WordPress components are being used.
