### ISSUE TITLE
Use error boundaries to limit propagation of JS errors in React code

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#1147]
Currently, a JS error causes the entire app to unmount (as witnessed in https://github.com/Automattic/woocommerce-payments/issues/1145).

We should have **[error boundaries](https://reactjs.org/docs/error-boundaries.html)** at (likely) various levels of our view hierarchy so as to avoid unmounting the entire app and render useful messaging to the user (and perhaps log / track the error).

**Comment by a-danae** [comment]
Hey @dechov! Some doubts over here.

Regarding the granularity of the error boundaries:
I’ve added the error boundary to the highest level component of each page. That would still make the whole app to unmount, but at least we’d display a message.
Going down from there, what would be a good criteria to decide which components should be within boundaries? I was thinking on wrapping high-level components, like cards and tables. Maybe we’d want to wrap some lower level components as well, or maybe there’s a better approach for doing this.

Regarding logging/tracking:
Not sure if I’m getting this right. I guess it’s not in the browser’s console because that’d be added by React when the error is thrown, right? If so, logging how?
Tracking as with tracks? PCYsg-kxu-p2

**Comment by dechov** [comment]
Hey @a-danae – good questions, and I don't necessary have good answers TBH, just a vague hunch that errors deep down in the view hierarchy shouldn't crash the whole app :-)

I'm inclined to think we can just have one in the `<Page>` component rather than adding to each page individually, as you mentioned in the PR. Having another one per `<Card>` (including tables) sounds great to me as well. One criterion to apply might be something like "would it be likely / logical for this piece to fail independently of others".

I'd say don't worry about the logging part – it was just a thought, and would need further consideration (FYI I just brought it up in p1633388941118600-slack-C0208C3BXHP).

**Comment by a-danae** [comment]
Thanks for clarifying and thanks for bor bringing up the question in Slack, Paul! I'd call that a good answer btw ^-^
