### ISSUE TITLE
Add flags and reporting mechanism for Elevated Risk / Fraudulent transactions

### ISSUE THREAD

**Issue by GeoJunkie** [Automattic/woocommerce-payments#1225]
Currently, WC Pay uses the default Stripe [Risk Evaluation information](https://stripe.com/docs/radar/risk-evaluation) to determine whether to decline potentially fraudulent transactions. Since [Elevated Risk payments are allowed by default](https://stripe.com/docs/radar/risk-evaluation#elevated-risk), but merchants are [ultimately held responsible for those payments](https://stripe.com/us/legal#processing-transactions-disputes), they should have a more visible way to identify these transactions, and report them.

Currently, the only way to identify Elevated Risk payments is to proactively go to **Payments > Transactions**, click the three dots menu, and activate the **Risk Level** column.

![](+)
Image Link:  

This will allow them to see Elevated Risk transactions, but then the only way to report them is to send an email to `support@stripe.com`. Although there is a reporting mechanism within Stripe, WC Pay users can't access it.

This should be more accessible to help Stripe (and subsequently WC Pay) better detect fraudulent transactions. As indicated in [Stripe's documentation](https://stripe.com/docs/radar/risk-evaluation#feedback-on-risk-evaluations):

> While we utilize information across our network to evaluate a payment, you may have additional information about a payment as a result of a customer interaction. Stripe’s machine learning models respond to feedback you share with us, and you can help improve our fraud detection algorithms by refunding and reporting payments that you believe are fraudulent.

That "reporting payments that you believe are fraudulent" process should be seamless.

One way to implement this together could be on the Orders page, where a flag could be added, and an option to report a transaction to Stripe.

Background: 3657491-zen

-----------

Refinement of the issue: We need to update the fraud metabox to contain the elevated data from Stripe (as Design shares down in the issue) and also add the action button

**Comment by aheckler** [comment]
Huge +1 for this. The fact that we don't surface transactions with Elevated risk very well at all came up here: p1674197730666089-slack-C03EE4CPPK5

**Comment by zmaglica** [comment]
I am not 100% certain which teams this issue belongs, so I will tag you @dwainm and @LCmry, so you might decide which team is most suitable for this issue. I am moving this from the Engineering review queue since the issues keep piling up here and in most cases, the team who will work on the issue can take the communication to the architects or whoever might be helpful without Porter being a proxy between them.

**Comment by vbelolapotkov** [comment]
@dwainm routing this to your team since it looks like risk/fraud tools enhancement.

**Comment by eduardoumpierre** [comment]
Hey @elizaan36! Could you help us to understand how it should look and behave? The initial suggestion is to add a flag and a button to the order page that would report it as fraudulent to Stripe. Thanks in advance!

**Comment by elizaan36** [comment]
hey @eduardoumpierre Is this different to what was already implemented on the Order details page? 

<img width="776" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/176db4bb-0751-4eb8-871b-ad906120d2f2">

<img width="760" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/074d2fb9-d8f2-4afd-8346-8e8138b2aecd">

Screenshots are from the design P2:
https://wp.me/paJDYF-6rY /#order-details

**Comment by eduardoumpierre** [comment]
Hey @elizaan36!

> Is this different to what was already implemented on the Order details page?

As part of the FRT project, we've implemented the original layout that you linked from Sigma, but with changes in the "Risk evaluation" box.

<img width="292" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/16882226/7eb8ccb6-544d-45c4-ab50-9c5f46afef30">

---

> Screenshots are from the design P2

The "Risk evaluation" box should work to give visual feedback to the merchant. However, we also need to implement an action to report the transaction to Stripe. The merchant should be aware of the consequences of this action and advised to use it only if they suspect the order is fraudulent. We also need to decide whether to always display the action button or only when the risk level is high.

As a dev note: We can report the payment by [using the `fraud_details` parameter](https://docs.stripe.com/api/charges/update#update_charge-fraud_details) on the Charge request.

**Comment by allie500** [comment]
We have a spike planned to help us address this issue. As a result, I'm moving this one to on-hold / blocked until that spike is completed.

**Comment by elizaan36** [comment]
> The merchant should be aware of the consequences of this action and advised to use it only if they suspect the order is fraudulent. We also need to decide whether to always display the action button or only when the risk level is high.

Got it. Thanks for the additional context. Could we estimate how often transactions will be reported to Stripe or how big of a need this is from the feedback so far? 

I'm asking because my first instinct is to put the reporting mechanism on the transaction itself within WooPayments, the details page and potentially the listing. If it's not a frequent action, it may be sufficient to click through the "View more details" link and take action from the transaction details.

**Comment by aheckler** [comment]
@eduardoumpierre @elizaan36 

Just to clarify, since I think there's maybe some confusion here: the original issue here has basically two parts.

1. If Stripe suspects a given transaction is fraud, WooPayments should be better at surfacing that to the merchant, and advising them on what to do next.
2. If, after Step 1, the merchant determines the transaction is indeed fraud, WooPayments should have a way to report that to Stripe, in order to improve Stripe's modeling.

IMHO, the first step is more important here, as I imagine Step 2 will happen quite rarely.

More details from Stripe's docs on elevated risk transactions, which they allow by default: https://docs.stripe.com/radar/risk-evaluation#elevated-risk

Right now, if Stripe determines a transaction is "elevated" risk, we surface that in two places. First, on the Payments > Transactions page, in a column that is unfortunately _hidden by default_.

![Screenshot taken on 2024-05-01 at 10 26 55 UTC@2x](https://github.com/Automattic/woocommerce-payments/assets/5512652/fcbf2fa0-f525-4f16-bc6b-182a23efcf9c)

Second, on the transaction details page, with no real attention called to it:

![Screenshot taken on 2024-05-01 at 10 27 40 UTC@2x](https://github.com/Automattic/woocommerce-payments/assets/5512652/bd8ca6d7-4313-436f-83f5-735a9c00ac5a)

As of now, we advise merchants to watch for those elevated risk transactions and do the following:

> For Elevated transactions, you should try to contact the customer before fulfilling the order. If you do not receive a response, consider refunding the order as a precaution.

Source: https://woocommerce.com/document/woopayments/fraud-and-disputes/card-testing/#monitor-transactions

To that end, it would help if elevated risk transactions were flagged as such on the WC core order page, as there is currently no warning there at all.

![Screenshot taken on 2024-05-01 at 10 37 54 UTC@2x](https://github.com/Automattic/woocommerce-payments/assets/5512652/2b97b15c-6786-4d85-a044-f646454dae74)

It would also seem natural to add a new setting to the FRT configuration that controls this, something like so:

![Screenshot taken on 2024-05-01 at 10 46 13 UTC@2x](https://github.com/Automattic/woocommerce-payments/assets/5512652/c2597898-4d94-454d-b5d9-c96784b44637)

> We also need to decide whether to always display the action button or only when the risk level is high.

Worth noting that when the risk level is High, Stripe has by default already blocked the transaction from occurring, so I'm not sure it still makes sense for the merchant to report it?

**Comment by elizaan36** [comment]
hey @aheckler Thank you for this context, and your suggestions make perfect sense. 

> flagged as such on the WC core order page, as there is currently no warning there at all.

To clarify, on the order details does this metabox not appear for you on that transaction?
<img width="202" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/d38d7b14-8d82-4b34-b3fa-f233e89656d2">

**Comment by aheckler** [comment]
> To clarify, on the order details does this metabox not appear for you on that transaction?

Nope. I'm not sure where that screenshot is from even, since I don't see that string in WooPayments itself.

https://github.com/search?q=repo%3AAutomattic%2Fwoocommerce-payments%20%22moderate%20risk%20of%20fraudulent%20activity%22&type=code

**Comment by elizaan36** [comment]
Sounds like there's an opportunity to add the Elevated category to the [existing risk evaluation box](https://github.com/Automattic/woocommerce-payments/issues/1225#issuecomment-2072500091). The current implementation may only show the box when the transaction was blocked. @eduardoumpierre Do you think that could be a good next step?

**Comment by eduardoumpierre** [comment]
Hi @elizaan36!

> The current implementation may only show the box when the transaction was blocked.

As part of FRT, we just implemented the "Fraud & Risk" box that is similar to the one you linked, but it's not the same. As @aheckler highlighted, the "Risk evaluation" box is not currently implemented.

> Do you think that could be a good next step?

I agree that implementing the "Risk Evaluation" box would be a good next step, but I think it would be a box on its own, and not be part of the "Fraud & Risk" box. In the future, we could also add more actions, like reporting such orders to Stripe.

It is important to note that Stripe is responsible for generating the risk assessment, so customization by the merchant is not available. Therefore, we can possibly consider replacing the "Adjust Risk Filters" link with a link to our documentation.

How does it sound to you @elizaan36?

**Comment by eduardoumpierre** [comment]
Hey @aheckler!

> It would also seem natural to add a new setting to the FRT configuration that controls this

That's a great idea! However, before we proceed, let's check if it's feasible with the current implementation as the order is blocked even before reaching Stripe.

**Comment by aheckler** [comment]
> let's check if it's feasible with the current implementation as the order is blocked even before reaching Stripe.

Good point. The bottom line for me is that we should flag elevated risk orders _somehow_, even if not in the FRT box (though IMHO that is the most logical place for it given its purpose).

**Comment by elizaan36** [comment]
> I agree that implementing the "Risk Evaluation" box would be a good next step, but I think it would be a box on its own, and not be part of the "Fraud & Risk" box.

Curious why it would need to be a box on its own? From a merchant perspective, ideally they would only need to learn one pattern for where they can reference important fraud information. I'd be concerned if the box changes between "blocked" and "elevated" assessments it may cause confusion.

Could we reuse the same component and build in Stripe's risk assessment there?

**Comment by eduardoumpierre** [comment]
> Curious why it would need to be a box on its own?

Since they represent different aspects of fraud information, I was concerned it could be too much information for the same box, but it makes sense to have a box to be the reference for fraud information as you said!

I created a mock for the block with the Stripe Risk Level and the Fraud and Risk outcome:
<img width="290" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/16882226/d1b1063c-4ba8-4449-96de-111eaa15a6b9">

@elizaan36 Please, let me know your thoughts about it!

**Comment by aheckler** [comment]
I might adjust the text to something like this:

> This order has a moderate risk of being fraudulent. We suggest contacting the customer before fulfilling it. If you do not receive a response, or if anything seems suspect, consider refunding the order as a precaution.

Otherwise, looks good!

**Comment by elizaan36** [comment]
@eduardoumpierre Really sorry about the delay on this one. We already chatted in Slack and I wanted to share a quick sketch with some copy updates that might make the connection clearer.

<img width="309" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/4dd884d2-2084-474d-8ed5-39f52d85e9f2">

@aheckler I used an abbreviated version of your copy to keep it max 4 lines, WDYT? 

Also added "self-defined" to the store risk filters copy to clarify that these are settings the merchant can configure themselves. The merchant may be confused that one box is "Elevated" and the other is green, and I think a small tweak in the copy can make that connection clearer.

The "Adjust risk filters" link directs to the "Fraud protection" Settings section. This is so the merchant can have a next step in case they're concerned that the store risk filters aren't strong enough.

As a next step for this project, I think there should be some connection or link to the [Stripe documentation](https://docs.stripe.com/radar/risk-evaluation#risk-outcomes) from the Fraud protection settings and our docs. This could answer some questions for merchants who want to know more!

**Comment by aheckler** [comment]
> I used an abbreviated version of your copy to keep it max 4 lines, WDYT?

I think the copy itself is fine, but I'm not sure if I'm a fan of the two separate sections inside the box. I'm no designer, but what if we did something like this?

![Screenshot taken on 2024-06-13 at 01 32 43 UTC@2x](https://github.com/Automattic/woocommerce-payments/assets/5512652/8372fe03-3ce2-43b0-9921-9581b70500ed)

**Comment by elizaan36** [comment]
hey @aheckler Thanks for this. I chatted with Eduardo about this in Slack because I had the same reservations about the two separate sections. I do think there's potential that the two messages and colors could cause confusion such as, "If it’s elevated then why is it green?" Also, "why did it pass my risk filtering if there’s a chance of fraudulent activity?"

Your solution would be less confusing for sure. However, in the future we will add the "Held for review" category to the merchant's risk tools, in which it might make sense to keep them separate. 

In my Slack thread with Eduardo (which now I realize should have been in this issue!) he mentioned that since these two pieces of information are coming from different places and mean different things he has reservations about hiding one or the other. However, it would be a good project to combine these items into a more coherent system for the merchant. In order to do that I think we'd need to have a complete merchant risk tools system that includes the "Held for review" category.

Anyway, long story to say that's why I compromised with only tweaking the copy to try to clarify the different messages. @eduardoumpierre Do you think it's possible to prioritize adding the "Held for review" category to merchant tools to align with this new risk level?

cc @rogermattic In case you have additional thoughts or feedback on this.

**Comment by eduardoumpierre** [comment]
Hey @elizaan36!

> Do you think it's possible to prioritize adding the "Held for review" category to merchant tools to align with this new risk level?

I don't expect that we will work on it in the near future since it's not on our 2024 roadmap. 

> Your solution would be less confusing for sure. However, in the future we will add the "Held for review" category to the merchant's risk tools, in which it might make sense to keep them separate.

We can always include this change as part of the project when the time comes, so since we don't have a plan to include the "held for review" feature for now, I wouldn't take that feature into account.

**Comment by rogermattic** [comment]
Thanks for pinging me here @elizaan36 ! 
I'm coming here with a slightly limited understanding of the issue :) 

>that's why I compromised with only tweaking the copy to try to clarify the different messages.

I understand, this is the latest version of the design that you proposed above, isn't it?

![image](https://github.com/Automattic/woocommerce-payments/assets/94967682/019e98dc-73af-4ebf-aeaa-be8e903fe169)

If so, then I think even if these are separate _sections_ within the box, I personally don't mind it that much. It reads well and the link to `adjust the filters` is a massive improvement. Sending merchant to actually adjust the filters will give them a bit more understanding why `no action was taken`. I think it could be even more integrated (the link with the section about the action taken) cause the relate to the same thing. 

I agree with the need to add the `Held for review` category.

When it comes to the design suggested by @aheckler above:

![image](https://github.com/Automattic/woocommerce-payments/assets/94967682/853a5293-bd4c-49c9-b664-f087f796b83b)

I really like the body copy, however, I'm not a big fan of what the label says: 
`Elevated fraud risk, order allowed` as it isn't that easy to understand. I think saving the space is not the main concern here, so we can ensure we display it in the easiest way to understand. 

I think we can also start thinking how this labels (e.g. `elevated` ) can have a consistent look throughout all the Woo dashboard. I think it would help merchant to connect the dots.

**Comment by elizaan36** [comment]
> I understand, this is the latest version of the design that you proposed above, isn't it?

Yep, that's the latest. Thanks for your input, Magda! @aheckler Let us know what you think about keeping the separate labels for the reasons above.

**Comment by aheckler** [comment]
> Let us know what you think about keeping the separate labels for the reasons above.

👍 Let's do it.

**Comment by rogermattic** [comment]
Great @aheckler !
 @allie500 is there anything that I could do to help moving this issue forward?

**Comment by allie500** [comment]
> @allie500 is there anything that I could do to help moving this issue forward?

@rogermattic 👋  I'll bring it up during our team call tomorrow. Then I can follow up with you here.

**Comment by rogermattic** [comment]
Hey! I noticed some activity in this ticket and was wondering if you need some design support in testing this issue or anything else? Just let me know :)

**Comment by eduardoumpierre** [comment]
Hey, @rogermattic! The elevated risk information was added on https://github.com/Automattic/woocommerce-payments/pull/9515. Here is what it's looking like for each scenario:

| Scenario | Meta box |
|--------|--------|
| Processed with another payment method | ![Screenshot 2024-10-02 at 12 03 31](https://github.com/user-attachments/assets/7e53503c-62ea-47e2-a603-a294e4d6c28f) |
| Order created while Fraud and Risk was disabled | ![Screenshot 2024-10-02 at 11 42 32](https://github.com/user-attachments/assets/f3b6bfb1-170e-45e9-a5a4-4358d4e31042) |
| Order created before this PR | ![Screenshot 2024-10-02 at 11 42 03](https://github.com/user-attachments/assets/b043d5d7-9c9a-4205-a023-a9354d811bfb) |
| Normal risk level | ![Screenshot 2024-10-02 at 11 43 02](https://github.com/user-attachments/assets/05bf80fa-9424-44eb-b8f2-32635d5849a4) |
| Elevated risk level | ![Screenshot 2024-10-02 at 11 41 49](https://github.com/user-attachments/assets/a92ff53c-3a49-4c9e-86a6-9b972e7e850c) | 
| Blocked order | ![Screenshot 2024-10-02 at 11 41 26](https://github.com/user-attachments/assets/2a8ca51f-6763-483f-a957-5c7aa909d3a7) |

Let me know if you have any feedback to provide! It has been already merged, but we can always update it before the next release if needed.

**Comment by rogermattic** [comment]
Hey @eduardoumpierre  !

Thanks for this helpful breakdown of the cases! 

> Let me know if you have any feedback to provide! It has been already merged

I think this works well as it is, though I can see some opportunities for improvement (e.g., visual tweaks like using a badge component for the risk status). 

However, I believe the best approach is to close this issue as is and log a new one with suggested improvements once I have a chance to review it holistically—likely not before the end of the year. The badges could then be applied across the Transactions list and other relevant areas, but I don't want to block this issue or leave it unresolved. 😊

cc: @elizaan36
