### ISSUE TITLE
Support formatting additional currencies

### ISSUE THREAD

**Issue by jrodger** [Automattic/woocommerce-payments#1389]
We're using the Currency package from WooCommerce Admin to format our currencies. We might come across currencies that aren't in the package's list of [supported currencies](https://github.com/woocommerce/woocommerce-admin/blob/04be3fc7f28924938fa898bf465230992dc68170/packages/currency/src/index.js#L215).

For a USD transaction on a store using USD we show the following on the transaction detail page:
![image](https://user-images.githubusercontent.com/686419/110926569-775f7680-831c-11eb-823a-3668294b3767.png)

Where there's space, we disambiguate which dollar we're showing with "USD" after the amount. Apart from that, this is simple and clear.

For a CAD transaction on a store using USD we have this:
![image](https://user-images.githubusercontent.com/686419/110926759-b2fa4080-831c-11eb-8118-970db3325d63.png)
The currency symbol after key amounts becomes more important here and we have an extra field showing the total amount in the store's currency. So far so good.

For currencies that the Currency package doesn't know about we have a [little workaround](https://github.com/Automattic/woocommerce-payments/blob/93da61e6ba717f50fbc8ee86a468b19645e55f67/client/payment-details/summary/index.js#L113) in WooCommerce Payments. Instead of defaulting to something or not showing anything we simply use the currency code to show currency of the amount. So for a NZD transaction on a store using USD:
![image](https://user-images.githubusercontent.com/686419/110927269-564b5580-831d-11eb-9e80-921fd6ed5489.png)
Or a USD transaction on a store using NZD:
![image](https://user-images.githubusercontent.com/686419/110927347-6f540680-831d-11eb-9f60-517bb7a2bcf0.png)
So things can get a little confusing here, especially where we repeat "NZD" after the amount.

We have 2 options here:

1. Where we're using the raw currency code as the symbol, let's not add the same thing again after the amount.
2. Add AUD and NZD to the Currency package (and add this as a note in our process for adding new countries in the future).

We could also do both. Personally, I think we should do option 2 and consider tackling option 1 if things are still confusing (given the range of presentment currencies we support).

**Comment by jessy-p** [comment]
Tested for using NZD on US store - looks good, no repetition.
![image](https://user-images.githubusercontent.com/32092402/127847820-4b9f0a76-b737-410e-8969-52a9e879c34c.png)

Conversion also not ambiguous.
![image](https://user-images.githubusercontent.com/32092402/127847969-4238832b-63d3-4930-9b49-5c6eee4b4cb4.png)

**Comment by kalessil** [comment]
Thanks for looking into the NZD, can we also ensure following (country-code -> currency code) is also rendering consistently?

```
			AU => AUD
			CA => CAD
			CH => CHF
			HK => HKD
			PL => PLN
			SG => SGD
```

If so, we could close the issues as it will be covered by the PR.

**Comment by jessy-p** [comment]
Facing an issue on `fix/1301-1389-improve-currency-formatting` branch, where I am not getting all the currencies on Multicurrency selector. Could be because of the conflicts or some other issue. 
Screenshot on `fix/1301-1389-improve-currency-formatting` branch
![Screenshot 2021-08-03 at 10.02.06 AM.png](https://images.zenhubusercontent.com/607f1d1a52a3081b859b1066/27f979ae-4d45-43fe-a95e-17775bdc3fe6)

On `develop` branch, I have all the currencies
![Screenshot 2021-08-03 at 9.56.56 AM.png](https://images.zenhubusercontent.com/607f1d1a52a3081b859b1066/8906f886-63d1-4563-b099-c24fd25af21e)

So as I cannot add all the currencies I want on `fix/1301-1389-improve-currency-formatting` branch, I've had to add all the currencies on the `develop` branch and then I checked the display on both branches.

**AUD : `develop`**
![image.png](https://images.zenhubusercontent.com/607f1d1a52a3081b859b1066/58c08acf-c637-42cd-904d-5ac81f8fd9e6)
![image.png](https://images.zenhubusercontent.com/607f1d1a52a3081b859b1066/942faa78-4a4a-4ff3-9971-f9e67d67bf3e)

**AUD : `fix/1301-1389-improve-currency-formatting`**
![image.png](https://images.zenhubusercontent.com/607f1d1a52a3081b859b1066/2706b8a4-43b7-46e4-aef6-97e1aadfc55e)
![image.png](https://images.zenhubusercontent.com/607f1d1a52a3081b859b1066/5843590c-5d02-4170-9763-6299f154a1b5)

**CAD : `develop`**
![image.png](https://images.zenhubusercontent.com/607f1d1a52a3081b859b1066/d24c76bb-d200-477d-8846-f15c590682dc)
![image.png](https://images.zenhubusercontent.com/607f1d1a52a3081b859b1066/26be258e-070b-4cbb-9e6e-3125c2ae16cc)

**CAD : `fix/1301-1389-improve-currency-formatting`**
![image.png](https://images.zenhubusercontent.com/607f1d1a52a3081b859b1066/85163e27-85d5-47be-b805-657f32f5f3c3)
![image.png](https://images.zenhubusercontent.com/607f1d1a52a3081b859b1066/625a5308-e85d-4275-a787-027d1040a08a)

**CHF : `develop`**
![image.png](https://images.zenhubusercontent.com/607f1d1a52a3081b859b1066/a6ca333d-6fdb-4436-92e0-4cb03947452c)
![image.png](https://images.zenhubusercontent.com/607f1d1a52a3081b859b1066/a913a77a-bfd3-4b3d-a9e2-62cd85ab5c80)

**CHF : `fix/1301-1389-improve-currency-formatting`**
![image.png](https://images.zenhubusercontent.com/607f1d1a52a3081b859b1066/c9a02bfb-1c6d-4a1d-8156-2d052be8c2a2)
![image.png](https://images.zenhubusercontent.com/607f1d1a52a3081b859b1066/14e0ee53-6593-4ace-8b82-b55548c1f727)

**HKD : `develop`**
![image.png](https://images.zenhubusercontent.com/607f1d1a52a3081b859b1066/91da39d1-4720-4aea-8cb8-2184a8d84600)
![image.png](https://images.zenhubusercontent.com/607f1d1a52a3081b859b1066/f5aacd1d-d805-4c99-ac00-af573ccbbabf)

**HKD : `fix/1301-1389-improve-currency-formatting`**
![image.png](https://images.zenhubusercontent.com/607f1d1a52a3081b859b1066/2d0c971e-3c94-4b7f-a2ff-e88c9ce5622a)
![image.png](https://images.zenhubusercontent.com/607f1d1a52a3081b859b1066/5fa37ac1-5226-40ec-966b-10403795a35d)

**PLN : `develop`**
![image.png](https://images.zenhubusercontent.com/607f1d1a52a3081b859b1066/2b916243-55f2-437d-8d5b-712aea9a7ba3)
![image.png](https://images.zenhubusercontent.com/607f1d1a52a3081b859b1066/443a1700-eb72-4482-9276-01992914d76f)

**PLN : `fix/1301-1389-improve-currency-formatting`**
![image.png](https://images.zenhubusercontent.com/607f1d1a52a3081b859b1066/f2aa6cd6-cb60-4cef-b532-2b174c6f6178)
![image.png](https://images.zenhubusercontent.com/607f1d1a52a3081b859b1066/01427811-cdcb-4013-8bfd-af61be54bcc5)

**SGD :`develop`**
![image.png](https://images.zenhubusercontent.com/607f1d1a52a3081b859b1066/099daf05-24c9-44e7-9b87-2eccdacdcf8b)
![image.png](https://images.zenhubusercontent.com/607f1d1a52a3081b859b1066/c2fe948e-1352-44c3-9f90-95aa692cbaeb)

**SGD : `fix/1301-1389-improve-currency-formatting`**
![image.png](https://images.zenhubusercontent.com/607f1d1a52a3081b859b1066/e1464d21-0e39-4356-aaad-8d52710c77f9)
![image.png](https://images.zenhubusercontent.com/607f1d1a52a3081b859b1066/dffb5306-4035-4829-9098-6297012cf2c0)

**Comment by tpaksu** [comment]
Explicit prices showing duplicate symbols is to be fixed in https://github.com/Automattic/woocommerce-payments/pull/2668 .

**Comment by naman03malhotra** [comment]
@tpaksu can we close this issue now?

**Comment by tpaksu** [comment]
@naman03malhotra sure, long has passed since this one, if anything related comes up, it deserves a new issue. Go ahead.
