### ISSUE TITLE
Can an Apple developer sandbox be used to develop the Apple Pay feature?

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-payments#1419]

**Comment by asumaran** [comment]
### Short answer:

Yes

### Long Answer:

In order to be able to use Apple Developer sandboxes we need to purchase a subscription to the Apple Developer program. It costs $99/year for individuals/single person businesses. There are other memberships plans that we might be interested https://developer.apple.com/support/compare-memberships/

To set up a testing environment for Apple Pay I followed the steps provided here https://developer.apple.com/apple-pay/sandbox-testing/ and ended up testing it with my own instance of `woocommerce-gateway-stripe`

It worked perfectly. I was able to purchase products using multiple testing cards. If we decide to use this approach to work with Apple pay I can put together a guide explaining the process of setting up the sandbox environment.

| Product Page  | Product Page |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/1025173/112702524-cdc2ce00-8e61-11eb-9f74-bf79869a4681.png" width="300"/>  | <img width="300" src="https://user-images.githubusercontent.com/1025173/112702847-dff13c00-8e62-11eb-8ee9-4aee29c3239e.png"> |

#### Considerations

- For testing, Apple requires us to create "[Tester Accounts](https://help.apple.com/app-store-connect/#/dev8b997bee1)" they are basically limited iCloud accounts. (we need to use a completely new email that was never used in any iCloud account) Also, we need to log out from our own iCloud accounts in the apple device we are testing. In my case I'm using an iMac and then log in with the "Tester Account".
- To be able to use the Wallet app we need to link the device we are using (iMac, in my case) with an iPhone. And use any of the [testing cards](https://developer.apple.com/apple-pay/sandbox-testing/) Apple provides.
  - This is a problem since signing in with a tester account in our Apple devices affects people like me who actively uses iCloud/Apple services (Contacts, Calendars, Apple Music, iCloud Drive, etc, etc.). So it would be convenient to purchase another iPhone only for testing.
    - Note: I haven't tested with iPad or any other iOS device or iOS Simulators
  - For people who has a laptop with Touch ID it's not necessary to use an iPhone since the Wallet app can be configured directly on the laptop.

**Comment by v18** [comment]
Closing this as done. Thank you @asumaran !
