### ISSUE TITLE
Write new e2e test: System / Subscriptions / Renewal by action scheduler

### ISSUE THREAD

**Issue by zhongruige** [Automattic/woocommerce-payments#1494]
Write a new e2e test that covers the following flow:
* System / Subscriptions / Renewal by action scheduler

**Comment by veljkho** [comment]
Hi @zhongruige 
There are 2 ways to implement Action Scheduler, by a plugin and by a library. I think it's not a problem to choose which way to go, but the problem could be in testing this. The action scheduler works in the future and we may not be able to wait for it to execute in order to test if the renewal subscription works. Do you have any thoughts on this or suggestions on how to make a test for this, I'm not yet familiar with Action Scheduler. Thanks!

**Comment by zhongruige** [comment]
Hi @veljkho!

When we looked at this a bit, @rrennick pointed out that AS does not run in our docker environment and the suggestion made is to use the browser to run the pending non-recurring actions. Let me know if this is something that we can potentially use here for these tests.
