### ISSUE TITLE
Define all used dependencies explicitly in package.json

### ISSUE THREAD

**Issue by diegocurbelo** [Automattic/woocommerce-payments#1616]
After adding new dependencies #1609 the rule `import/no-extraneous-dependencies` was turned `off` as there were some implicit defined dependencies being used.

We should consider turning the rule on, and define all dependencies (ex: moment.js) explicitly in package.json as it's easier to fix version conflicts.

**Comment by naman03malhotra** [comment]
@Automattic/harmony checking if this is under your radar as part of prioritization call.

**Comment by deepakpathania** [comment]
@naman03malhotra We didn't look into this in our last sprint planning, maybe because the labels we used didn't surface this. I think we should agree on maybe using `category: devops` for dependency-related issues as well? Would make it easier to filter out relevant issues for us.

Also, we might not be able to get to it right now due to bandwidth constraints but I have noted it down in my list to have a look at it for future.

**Comment by naman03malhotra** [comment]
>I think we should agree on maybe using category: devops for dependency-related issues as well?

I think it aligns more with `category:ops`
Can you please go through the backlog once and switch the labels? I'll make the changes to the docs to ensure we apply the correct label in the future

>we might not be able to get to it right now due to bandwidth constraints but I have noted it down in my list to have a look at it for future

Just pinged you here so that you can pull this issue in your backlog and handle it according to team's priorities.
