### ISSUE TITLE
Spike: Styling UPE

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-payments#1626]
To use UPE, we'll need to make sure it can be styled to fit within the WooCommerce checkout UI and compatible with WordPress/WooCommerce theming.

Questions to answer:
- Can theme styles be passed through to UPE?
- Can UPE meet design requirements to work within WooCommerce checkout UI?

The output of this spike will be 1 or 2 P2 posts describing your findings on or before Monday, May 3rd.

**Comment by c-shultz** [comment]
@jarekmorawski, for both of these:
>- Can theme styles be passed through to UPE?
>- Can UPE meet design requirements to work within WooCommerce checkout UI?

It would help to get some really specific design direction with the kinds things that we should specifically target to achieve with the styling. Can you give us the top 1 to 3 requirements in these areas (screenshots are welcome) that we should target with this spike? We'll want to narrow on the things that would be deal breakers for using UPE.

**Comment by jarekmorawski** [comment]
Absolutely! In general, we want to check if we can make UPE look like it was built using WC/Gutenberg's native UI components. The goal is to see how close to it we can get with UPE's current customization options. Please let me know if I can clarify anything.

Here's a design that I put together earlier to give us some direction.

![image](https://user-images.githubusercontent.com/79307566/116208829-98035480-a741-11eb-83d5-491d7a48af44.png)

**Can theme styles be passed through to UPE?**

- Can UPE inherit CSS properties from the page it's nested in? (fonts, colors, backgrounds, borders (width, color, style), paddings, margins, input styles)
- Would merchants have to set up UPE style separately from other checkout elements?
- If so, how much work would require building a UPE customizer?

**Can UPE meet design requirements to work within WooCommerce checkout UI?**

General
- Is UPE responsive and mobile-friendly?
- Can we adjust validation behavior? (position, text length, font size, color)
- Can we control what triggers validation?

Tabs
- Can we stack icons and labels in payment methods tabs horizontally, instead of vertically?
- Can we decide how many payment tabs are displayed by default?

Inputs & buttons
- Can we change the appearance of the “…” menu button that displays other payment methods?
- Can we change the button's label? (Replace the "...")
- Can we theme the list that appears when the “…” menu button is selected? (https://d.pr/i/0Q6Bb3)
- Can we select from overarching input behaviors IE: contained vs standard? (https://share.getcloudapp.com/YEuRrEXY)
- Can we inject our own elements, f.e. icons with tooltips, inside inputs?

Layout
- Can we pre-fill or better yet, hide fields that are duplicative with fields that already exist in the checkout? IE: country and zip code for credit card.

**Comment by c-shultz** [comment]
>Can UPE inherit CSS properties from the page it's nested in? (fonts, colors, backgrounds, borders (width, color, style), paddings, margins, input styles)

@jarekmorawski Do you know if there are common areas or style attributes of checkout that themes tend to modify? We'll need to find a way to pass through or otherwise provide customization of specific styles supported by UPE. Background and font colors seem like the big ones. Anything else you would highlight for this spike?

**Comment by jarekmorawski** [comment]
> Do you know if there are common areas or style attributes of checkout that themes tend to modify?

It looks like they can modify everything – from layout to colors and fonts. As we've discussed on Slack, I'd like to know if it's possible to identify commonly used properties that we could group and bundle up in different themes or present to merchants in a simplified configuration interface. In other words, I wonder if we can globalize some appearance settings.

For example, if all fonts, borders, and backgrounds had one color, merchant could customize only those three to make UPE match the store theme, rather than go through each property and set tab label color separately from field label color.

**Comment by bborman22** [comment]
I'm working up a P2 with more details now, but I did have a working example up here: https://tall-marten.jurassic.ninja/shop/
If you add a product then go to the checkout page, after some loading time, you'll see the UPE replace the regular payment options. I didn't do any extra work on where and when the UPE is loaded, so that overall placement isn't final, just a quick hack to test out some styling.

I was able to get a lot of the styles from the theme to pass in to the UPE! I wanted to get this out today as I'm writing up the P2 in case there is any early feedback.

**Comment by jarekmorawski** [comment]
This is brilliant, @bborman22! I'm very impressed that you figured it out so quickly. 🤗 I look forward to digging into the details in your P2 post. Out of curiosity, from code's perspective, do you think the payment method tabs could also follow the input styles? I mean background color and border style. This could take us one step closer to a fully automated customization.

> after some loading time, you'll see the UPE replace the regular payment options.

What do you think might be the cause? Do you believe we may have some control over it in the future?

**Comment by bborman22** [comment]
Yeah, I think we could pass along some styles for the Tabs, it looks like it accepts all the necessary properties. I'll focus on the background and borders at first and see where that gets us!

For the timing delay, there are ways we could improve that I believe, including small tricks to help (like loading the payment option collapsed until the content loads maybe?). But there will always be some delay as it has to create a PaymentIntent from Stripe, so it has to wait for a request to make a few hops out to Stripe and then back again.

**Comment by jarekmorawski** [comment]
> Yeah, I think we could pass along some styles for the Tabs, it looks like it accepts all the necessary properties. I'll focus on the background and borders at first and see where that gets us!

Can't wait to see the results! I have a good feeling about this.

> But there will always be some delay as it has to create a PaymentIntent from Stripe, so it has to wait for a request to make a few hops out to Stripe and then back again.

Good to know that. So far all the demos I've seen were rather fast but I know how cumbersome iframes can be. I wonder if we could display the component anyway (even without the contents) and either use skeleton or a spinner to let customers know it's loading properly. Do you think it'd be possible given that UPE is an iframe?
