### ISSUE TITLE
General settings available in new settings screen

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-payments#1634]
Merchant can manage all WCPay settings in new screen:
![image](https://user-images.githubusercontent.com/6209518/115416436-a33c0a80-a1ac-11eb-8320-acac18279f81.png)

**Comment by c-shultz** [comment]
Can/should we break this out further? Maybe remove the advanced settings?

**Comment by Ferdev** [comment]
The design has been updated since this issue was created. This is how it looks now:
![shot-2021-04-26-16-27-18](https://user-images.githubusercontent.com/130142/116099678-7b690d00-a6ac-11eb-969e-4b44e15f17f8.png)

@c-shultz I think I'm gonna split in two this issue, and move the advanced settings into another one, if that sounds good to you.

**Comment by Ferdev** [comment]
I've created the issue for the advanced settings and I've put it in the backlog: https://github.com/Automattic/woocommerce-payments/issues/1688
