### ISSUE TITLE
"Update WooCommerce Payments business details" task

### ISSUE THREAD

**Issue by samueljseay** [Automattic/woocommerce-payments#1657]
This is to add a new task "Update WooCommerce Payments business details" (For detailed designs see paJDYF-18j-p2)

It is dependent on the task list being implemented in #1656

![Screenshot 2021-04-22 at 1.26.41 PM.png](https://images.zenhubusercontent.com/5ef92fa5c1c43622578a0d39/1c48282a-9e2a-49dc-9411-c10cec21792c)

Requirements:

- [ ] Move the `TaskItem` component to `@woocommerce/experimental` and publish
- [ ] The task should use the L1 priority styling (L1 was decided in P2 discussion)
- [ ] TBD where this task takes you when clicked
- [ ] TBD what information is required to determine if the task is complete
- [ ] TBD what analytics tracking is required

cc @pmcpinto

**Comment by samueljseay** [comment]
@elizaan36 any thoughts on what the behaviour for this one should be? Thanks so much for your input on all these issues, its appreciated. 🙇

**Comment by elizaan36** [comment]
I believe this comes from a change in the Stripe account so would direct users to the KYC/Stripe dashboard. @LevinMedia could you confirm?

**Comment by jeffstieler** [comment]
Looks like we can use the `accountStatus` and look for `restricted_soon`:

https://github.com/Automattic/woocommerce-payments/blob/0ece4e0791971a08e622134ff60d0e417e083392/client/account-status/index.js#L123-L130

**Comment by LevinMedia** [comment]
Thanks @jeffstieler What you shared above looks correct to me as well 👍

**Comment by jeffstieler** [comment]
After further investigation, I think this will need to be revised to a 2 or 3 point issue. It would be a 1 only if we were adding the task to the WC-Admin home screen.

I think we need to move the [`TaskItem` component](https://github.com/woocommerce/woocommerce-admin/blob/main/client/task-list/task-item.tsx) to the experimental package for use in this repo - otherwise we will be duplicating a LOT of code.

**Comment by jeffstieler** [comment]
> TBD what information is required to determine if the task is complete

As far as I can tell, we don't (already) have the data needed to display the task as complete after the details have been entered because the account status will change from `restricted_soon`/`restricted` to `complete`. If we want to show the task as completed we'd need to create a flag denoting that the task was visible at one point. I'm not sure if that's worth it - but I leave it to y'all. @elizaan36 @LevinMedia

**Comment by LevinMedia** [comment]
Heya @jeffstieler! @elizaan36 and I think it's best to add the flag. It's not exactly and edge case, and not adding a flag would break the task pattern.

**Comment by elizaan36** [comment]
Yup. Since this required task appears on the home screen _and_ overview screen it should follow the task list pattern of being displayed as complete and moved to the bottom of the list. Just to confirm, it would be marked as complete in both places regardless of the user's entrypoint?

Admittedly I don't know the amount of effort to create a flag denoting it was visible, but seems worthwhile from a UX standpoint.
