### ISSUE TITLE
[GlobalStep] Extra Column without a title is displayed in downloaded CSV file for the transaction table.

### ISSUE THREAD

**Issue by gglobalstep** [Automattic/woocommerce-payments#1721]
## Bug Description:
Extra Column without a title is displayed in downloaded CSV file for the transaction table.

## Environment:
Woocommerce Version : WooCommerce 5.2.2 
WooCommerce Payments: v2.4.0
WordPress version: (v5.7)

**PC**:
Windows 10, Mac 10.14.6
Chrome(Version 90.0.4430.93) 
Firefox(Version 87.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins 
1. Complete setup wizard using United States address as a store address and selecting WC Payments on Business Details step.
1. On the Home page select Setup WooCommerce Payments task to trigger KYC flow.
1. Complete the KYC flow.
1. Add some products.
1. Go to frontend and purchase some products with WooCommerce payments.
1. Go to WP admin, Payments->Transactions.
1. Click on Download button present at transaction table header.
1. Note that CSV file gets downloaded.
1. Open the CSV.
1. Observe that extra Column without a title is displayed in CSV.

## Actual Result:
Extra Column without a title is displayed in the downloaded CSV file for the transaction table.

## Expected Result:
Only the Columns mentioned on "Payments->Transactions" page should be displayed in the downloaded CSV file.

## ScreenShot:
![#1721](https://user-images.githubusercontent.com/41110392/117023365-adb2e400-ad16-11eb-9858-cfd7128449d4.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by naman03malhotra** [comment]
Thanks, @gglobalstep for reporting this issue.

I took a closer look at this and this is happening due to an additional column which is at the start of the table, the one with the info icon.

Most of the row items are clickable and take you to the payments details page. IMO, that info column is not serving any purpose, or am I missing anything?

Instead, we can add a new column `TransactionId` which will be exclusive for the CSV export, which can be helpful for the merchant.

Screenshots of table and csv export after fix:
![image](https://user-images.githubusercontent.com/15019298/117318252-dc13f900-aea7-11eb-95c7-f542a0e1ee37.png)

![image](https://user-images.githubusercontent.com/15019298/117318863-6d836b00-aea8-11eb-9b10-17745340d8a7.png)

I wanted to discuss this before implementing the fix.

cc @dmvrtx @shendy-a8c

**Comment by shendy-a8c** [comment]
> Most of the row items are clickable and take you to the payments details page. IMO, that info column is not serving any purpose, or am I missing anything? We can consider removing that.

Which column are you referring to as "info column"?

Anyway, in the CSV file, having the header of the transaction id column named `TransactionId` sounds good to me.

**Comment by naman03malhotra** [comment]
>Since it's a design change, though minor, we can ask @LevinMedia if that's OK.

Good idea 👍 

>By the way, is it possible to have that column intact and just add the header name to the tx id column in CSV, or the number of columns between the rendered table and CSV table have to be stricly the same?

I tried doing the same at first so that we don't have to change the design.

So presently we have a pseudo column with an empty label at the start of the table to accommodate space for the info icon. If we add a header name to that column then that will show up in the table header.

There is an option to hide the column which will prevent it from rendering in the table but it will still show in CSV, but in our case, we would need that column with an empty label to accommodate the info icon, which is causing the CSV file to have a column with empty label.

There are a few ways to solve this:
- Remove the info icon and replace that pseudo column with `transactionId` just for the CSV file. (Design change, fastest fix)
- Another way to achieve this would be with a custom function that can process and manipulate data for columns and rows just for the export, but I feel that would be an overdo.
- Make changes in `@woocommerce/csv-export` component to accommodate an extra prop that will control the rendering of a specific column or should not export column without a label.

**Comment by dmvrtx** [comment]
I am more inclined to the last option: filter out columns without labels. This way it will generate output which is consistent with the transactions screen.

**Comment by LevinMedia** [comment]
@dmvrtx @naman03malhotra - If we want a quick fix I like the suggestion of removing the info icon and replacing the sudo column with TransactionID exclusively in the CSV. That would work for me. 

Otherwise, if you want to try the last option so that it doesn't export rows without labels, that's fine too.

**Comment by naman03malhotra** [comment]
FYI: @gglobalstep we found a new issue related to CSV export -> https://github.com/Automattic/woocommerce-payments/issues/1881 while fixing this issue.
