### ISSUE TITLE
Spike: UPE Font Source

### ISSUE THREAD

**Issue by bborman22** [Automattic/woocommerce-payments#1723]
During the spike on styling the UPE, one of the bigger gaps was in dynamically determing the font source to load into the UPE. While there is a workaround to use a setting field to provide the font source, it would be much better to get this source dynamically from the theme. Some possible paths to get things started:

- Scraping the HTML for a relevant `<link>` element and grab the `href` value
- Using [document.styleSheets](https://developer.mozilla.org/en-US/docs/Web/API/Document/styleSheets) to parse for the font stylesheets
- Using the font family name to try to generate the font path (this would be assuming a particular font source like Google Fonts, but could be used in conjunction with other solutions perhaps?)

Once the font source has been found, it can be [loaded into the `stripe.elements` call](https://github.com/Automattic/woocommerce-payments/blob/dab57024c7d27d8919a8bf0e91c4cf2579a799f6/client/checkout/classic/index.js#L48-L54).

[Stripe docs on this process](https://stripe.com/docs/js/elements_object/create)

The [draft PR for styling UPE](https://github.com/Automattic/woocommerce-payments/pull/1703) is a good starting point to minimize any set up time.

**Comment by superdav42** [comment]
After much testing I have come up with the below code which we can include to automatically load fonts to be used with UPE:
```js
const fontRules = [],
		sheets = document.styleSheets,
		fontDomains = [
			'fonts.googleapis.com',
			'fonts.gstatic.com',
			'fast.fonts.com',
			'use.typekit.net',
		];
	for ( let i = 0; i < sheets.length; i++ ) {
		if ( ! sheets[ i ].href ) {
			continue;
		}
		const url = new URL( sheets[ i ].href );
		if ( -1 !== fontDomains.indexOf( url.hostname ) ) {
			fontRules.push( {
				cssSrc: sheets[ i ].href,
			} );
		}
	}

	const elements = api.getStripe().elements( {
		fonts: fontRules,
	} );
```
To see how I got to this code I started by trying to parse the rules in each stylesheet to find and font-face rules with this code. The idea was to send all possible fonts used on the page to the stripe iframe.
```js
	const fontRules = [],
		sheets = document.styleSheets;
	let rules = null;
	for ( let i = 0; i < sheets.length; i++ ) {
		try {
			rules = sheets[ i ].cssRules || sheets[ i ].rules || []; // Exceptions will be thrown here if the stylesheet comes from a different origin.
			for ( let j = 0; j < rules.length; j++ ) {
				if ( '[object CSSFontFaceRule]' === rules[ j ].toString() ) {
					fontRules.push( {
						family: rules[ j ].style.fontFamily,
						src: rules[ j ].style.src, // Maybe blocked by CORS policy.
						weight: rules[ j ].style.weight,
					} );
				}
			}
		} catch ( e ) {
			// Can't read css file include it directly.
			fontRules.push( {
				cssSrc: sheets[ i ].href,
			} );
		}
	}

	const elements = api.getStripe().elements( {
		fonts: fontRules,
	} );
```
There were two issues with this approach. First it's impossible in recent browsers to access the rules in css loaded from a separate domain. So it's not possible to read the rules in the [CSS file from google fonts](https://fonts.googleapis.com/css?family=Source+Sans+Pro%3A400%2C300%2C300italic%2C400italic%2C600%2C700%2C900&subset=latin%2Clatin-ext&ver=3.4.0) using this method. The code above will inject all css files which can't be read by js into the stripe iframe. Any font face rules in the css files that can be read are forwarded to the stripe iframe.

With custom font rules some sites will still fail to load the fonts because the stripe iframe will be on a separate domain from the WordPress site. Sites which are self-hosting fonts must serve the font files with the header `Access-Control-Allow-Origin: https://js.stripe.com` or `*` to follow CORS policies which are in most modern browsers. Few themes include font files in the theme's folder most use Google fonts if they use webfonts at all. Fewer merchants will have the knowledge or time to configure their webserver to send the proper headers.

I think the best course of action is to dynamically determine which third party fonts are being used and to pass them to the stripe iframe. Other custom fonts are tricky to get to work and are mostly just used for icons anyway. A filter should be offered so builders could include any custom fonts if they desire. [This PR](https://github.com/Automattic/woocommerce-payments/pull/1737) will add the first code above to the PoC PR.

**Comment by bborman22** [comment]
Marking as closed as we landed on and implemented a solution for fonts!
