### ISSUE TITLE
Onboarding customer multi-currency

### ISSUE THREAD

**Issue by ismaeldcom** [Automattic/woocommerce-payments#1778]
#### Implement the onboarding flow using a vertical stepper

For more details about the implementation and details refer to paJDYF-1gf-p2

The flow includes the following 3 steps:

### 1. Add currencies

- Allow to search by currency name, symbol or code. Replaces the content below with results (vertical overflow). And revert to default state on delete.
- Scrolling container with recommended currencies (initially based on the store’s location). And alphabetical list of all currencies available to the store (minus those recommended above).
- **Add currencies** button updates the count on currency selection. Clicking it will advance to step 2.

<img width="1270" src="https://user-images.githubusercontent.com/7670276/117949699-af7e3800-b312-11eb-8096-4fa72c5c05a8.png" />

<img width="504" src="https://user-images.githubusercontent.com/7670276/117950884-ebfe6380-b313-11eb-8168-7f0b2318d859.png" />

### 2. **Review store settings**

- Clicking “Preview” will load the home page in a modal allowing the merchant to see the store notification messaging, and provide the opportunity to interact with the currency switcher in the navigation.
- Store settings from the multi-currency settings page.

<img width="588" src="https://user-images.githubusercontent.com/7670276/117951165-2ec03b80-b314-11eb-9af1-2a752d3b73fe.png" />

### 3. **Setup complete**

- Primary action redirect back to the home screen.
- Secondary action redirect to multi-currency settings.

<img width="596" src="https://user-images.githubusercontent.com/7670276/117954830-b3608900-b317-11eb-9196-8ad67e79587e.png" />

**Comment by ismaeldcom** [comment]
I think we should plan to create issues for the components that we can share between the onboarding and settings (legacy/new) pages. At least the currency search and 2 store settings would be easy to share. What do you think?

**Comment by LevinMedia** [comment]
@tpaksu Here's an update on how we'd like to deal with currencies that have already been added to the store.

<img width="833" alt="Screen Shot 2021-08-30 at 7 09 01 PM" src="https://user-images.githubusercontent.com/4500952/131430323-163c1ee2-994d-4eb5-987c-5be0488e8a13.png">

In the case where euro is added because of a payment method (or potentially another currency in the future), we'll add a line of text under the first paragraph, and remove euro as an option from the recommended currencies. This keeps the vertical stepper all about ADDING new currencies, and not providing the option to disable something that's already been enabled. We tried a few different approaches to allow for that, however we scrapped all of them as it was never quite clear enough what was actually enabled already, and what we were recommending to enable now. 

If a customer's default currency is one of the recommended currencies, we should never show it in the recommended list.

**Comment by tpaksu** [comment]
@LevinMedia that approach raises another question, if the user has some currencies enabled before, will we allow the user to pass to the second step without selecting a new currency? 

And another thing I'm not very clear, if the user completes the onboarding, will the overview link send the user to the currency settings page, instead of the wizard?

**Comment by LevinMedia** [comment]
>if the user has some currencies enabled before, will we allow the user to pass to the second step without selecting a new currency?

No we wouldn't, since the aim of this flow is adding NEW currencies, if they de-selected all the recommended, and didn't add anything else. 

>if the user completes the onboarding, will the overview link send the user to the currency settings page, instead of the wizard?

Could you give me more detail in what you mean by "Overview link"? 

Essentially we have to let merchants have access to the MC setting screen in case they happen to add Euro by way of the payment methods. With that in mind, the only way a merchant should find themselves in this flow is by clicking the inbox note.  (or task list, if we go that route in the future) Once a merchant has completed this flow once, they should be directed straight to the MC settings screen, even if the click the inbox note again.  Clicking the MC settings tab should always take you directly to MC settings.

**Comment by tpaksu** [comment]
> Could you give me more detail in what you mean by "Overview link"? 

Yes, thank you, I was talking about the inbox note or the task list links in the WCPay overview page. 

But still, I've got doubts about the currency selection. For example, a merchant in Poland wants to use EUR, USD and PLN in their store, and they've selected the store currency as USD. Next, they added P.24 as a payment provider, which enables PLN and EUR automatically, and after that they want to complete the MC onboarding, They'll see that the currencies they want to enable are already enabled, so they won't select anything else from the list.  The only way they would go through to complete the onboarding would be adding a temporary currency to reach the next step, then disabling it again in the MC settings page. Otherwise it would stay as an unfinished task in the "Things to do next" list. 

> With that in mind, the only way a merchant should find themselves in this flow is by clicking the inbox note.  (or task list, if we go that route in the future) Once a merchant has completed this flow once, they should be directed straight to the MC settings screen, even if the click the inbox note again.  Clicking the MC settings tab should always take you directly to MC settings.

Ok, I was letting the user to reach this flow by the task list item, so I should rethink that flow to match the specs above.

**Comment by LevinMedia** [comment]
>Otherwise it would stay as an unfinished task in the "Things to do next" list.

Standard tasks should always have a menu item that lets you dismiss the task, so in the example you provided above, it could be removed from the task list. That said - as I mentioned above, I think we should only rely on the inbox notification as a trigger for now. These also feature a prominent dismiss button, so we shouldn't run into the issue you noted above.

**Comment by tpaksu** [comment]
I still think we should allow the user to pass to the next step if they have some enabled currencies. We don't allow them to remove any currency, only add new ones, and by allowing them to continue, we would allow them to keep the existing enabled ones. 

Just refresh the page on the second step to understand what I mean :)
