### ISSUE TITLE
Create UPE Payment Gateway

### ISSUE THREAD

**Issue by bborman22** [Automattic/woocommerce-payments#1826]
The goal of this issue is to lay the groundwork and unlock future UPE development. The end result will be a new UPE payment gateway that is hidden behind a feature flag and that renders the UPE element during checkout. Styling the UPE and completing a checkout with the UPE will be accomplished in other issues.

Inspiration for the structure of the payment gateway can be found with the [Sepa](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/payment-methods/class-sepa-payment-gateway.php), [Sofort](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/payment-methods/class-sofort-payment-gateway.php), and [Giropay](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/payment-methods/class-giropay-payment-gateway.php) payment gateways. These also contain the logic for a feature flag that can be used.

Inspiration for the contents of the UPE payment gateway and the rendering of the element can be found in this proof of concept: https://github.com/Automattic/woocommerce-payments/pull/1714

**Goals**
- Create UPE payment gateway
- Implement feature flag to enable/disable UPE
- Render UPE element on checkout page

**Comment by bborman22** [comment]
After some clarification, it should be noted that the goal of the feature flag would be to replace the existing CC with UPE when enabled. If this turns out to be too much for one issue, we can break off that replacement aspect and leave this issue to just enable UPE side by side with CC.

**Comment by frosso** [comment]
I think it makes sense to replace the existing CC one with the UPE one - maybe at creation here: https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payments.php#L202-L214

That way we can persist the [Gateway ID](https://github.com/Automattic/woocommerce-payments/blob/0a614ceec2861e01d9a3d89a26b42eab3855f8aa/includes/class-wc-payment-gateway-wcpay.php#L30) between UPE and the default CC one, which would allow for the settings to be saved and seamlessly migrated when we will enable it!

**Comment by FangedParakeet** [comment]
It appears to me that the Giropay, SEPA, and Sofort gateways will only remain for testing purposes; while since we are apparently planning to offer UPE initially on an opt-in basis until eventually it becomes default (as described here -> paJDYF-1CR-p2#comment-6091) the CC gateway and UPE gateway will never be enabled at the same time, instead simply unkowingly passing each other by, like ships in the night. 

This basically leads me to believe that using the same gateway ID and choosing between either UPE or CC at creation, like @frosso suggested, is probably the right way to go. I don't think the changes in #1705 will affect this, because the CC Gateway still uses the same gateway ID. I also think I'll still be able to enable UPE as a checkbox setting, just like the other payment methods, but I'm getting a little lost in the gateway hierarchy thinking about it, so I'll have to try before I can buy that one.

**Comment by frosso** [comment]
@FangedParakeet I believe that PR can be closed, since we shouldn't need the gateway classes anymore - checking with the team.

**Comment by harriswong** [comment]
From the description/goals of this issue, part of creating UPE gateway and its feature flag is to replace the existing "WooCommerce Payments" payment method. My understanding is that when the feature flag is enabled, "WooCommerce Payments" here becomes UPE gateway.

![image](https://user-images.githubusercontent.com/572862/118842740-b236db00-b886-11eb-9180-c0e70841755e.png)

If this is the case, the work in https://github.com/Automattic/woocommerce-payments/pull/1705 is no longer needed. UPE as its own gateway includes all gateways. 

Also, +1 on keeping the gateway ID. if we are keeping the Gateway ID, the settings store under `wp_options` will indeed continue to work without the need to run migration script (maybe we need to clean up the serialized settings under the option_name `woocommerce_woocommerce_payments_settings` though so we don't have old settings floating around. But old settings allow backward the plugin to be backward compatible.)
