### ISSUE TITLE
UPE Save Payment Method

### ISSUE THREAD

**Issue by bborman22** [Automattic/woocommerce-payments#1870]
There has been some work on UPE saving payment methods in this [proof of concept](https://github.com/Automattic/woocommerce-payments/pull/1714). That branch should provide some guidance for how we can approach saving a payment method while using the UPE. There is also an [additional issue for handling Sofort](https://github.com/Automattic/woocommerce-payments/issues/1636) saved payment methods as it requires a bit of a workaround. 

While this item is in queue, I hope to gather any additional details on the future of UPE and saved payment methods here as well.

**Comment by superdav42** [comment]
The changes in https://github.com/Automattic/woocommerce-payments/pull/1919 to update the payment intent allow the payment method to be saved but there is trouble using saved payment methods. Currently when you try to use a saved payment method it tries to redirect to the UPE payment flow which does not work at all. When a saved payment method is used it should use the existing payment processing in the CC payment gateway. The UPE payment gateway needs to be updated to check if a saved method is being used and process the token directly instead of redirecting. This likely will mean copying a lot of code from the CC gateway to the UPE gateway.
