### ISSUE TITLE
[GlobalStep] Some contents on the Payment pages and Checkout page fails to translate to the respective language.

### ISSUE THREAD

**Issue by gglobalstep** [Automattic/woocommerce-payments#1894]
## Bug Description:
Some contents on the Payment pages and Checkout page fails to translate to the respective language

## Test Instructions:
https://github.com/Automattic/woocommerce-payments/wiki/Release-testing-instructions-for-WC-Payments-2.5.0#translations-related-testing

## Environment:
Woocommerce Version: WooCommerce 5.3
WooCommerce Payments: v2.5.0

PC:
Windows 10, Mac 10.14.6
Chrome(Version 90.0.4430.93) 
Firefox(Version 88.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins 
1. Complete setup wizard using United States address as a store address and without selecting WC Payments on Business Details step.
1. Go to Plugins->Add New->Upload plugin.
1. Install and activate WooCommerce Payments plugin v2.5.0.
1. Go to Payments->Set up to trigger KYC flow.
1. Complete the KYC flow.
1. Go to Settings->General.
1. Change language to one of these 4 languages: German, Italian, Spanish, French.
1. Click “Save Changes”.
1. Go to Dashboard > Updates.
1. Click on “Update Translations” button.
1. Now visit Payments->Deposits/Transactions/Disputes/Settings.
1. Note that some content fails to translate to respective language.
1. As a customer visit to Checkout page.
1. Observe that Some contents on the Payment pages and Checkout page fails to translate.

## Actual Result:
Some contents on the Payment pages and Checkout page fails to translate to the respective language.

## Expected Result:
All the contents on the Payment pages and Checkout page should get translated to the respective language.

## Screenshot:
![#1894_4](https://user-images.githubusercontent.com/41110392/119504297-779ed800-bd89-11eb-92ff-a856fd111a72.png)
![#1894_5](https://user-images.githubusercontent.com/41110392/119504305-7a013200-bd89-11eb-90e6-724110d741ad.png)
![#1894_6](https://user-images.githubusercontent.com/41110392/119504312-7a99c880-bd89-11eb-871e-3850630c4e94.png)
![#1894_7](https://user-images.githubusercontent.com/41110392/119504319-7b325f00-bd89-11eb-8ca6-e92e22c93826.png)
![#1894_1](https://user-images.githubusercontent.com/41110392/119504327-7cfc2280-bd89-11eb-9be5-f2ec454416ea.png)
![#1894_2](https://user-images.githubusercontent.com/41110392/119504336-7e2d4f80-bd89-11eb-8489-fcdec8873ed5.png)
![#1894_3](https://user-images.githubusercontent.com/41110392/119504347-7ff71300-bd89-11eb-9536-244cfd2c1031.png)
![#1894_8](https://user-images.githubusercontent.com/41110392/119508906-ca7a8e80-bd8d-11eb-8f24-fd34aa02d0e7.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://inquisitive-de.jurassic.ninja
Site address (URL): https://inquisitive-de.jurassic.ninja
WC Version: 5.3.0
REST API Version: ✔ 5.3.0
WC Blocks Version: ✔ 5.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.2.6
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.18
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.3.0
WC Database Prefix: wp_
Total Database Size: 8.22MB
Database Data Size: 5.76MB
Database Index Size: 2.46MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_segments: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_subscribers: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.42MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.19MB + Index: 0.16MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
mailpoet_page: 1
page: 7
post: 2
product: 21
product_variation: 7
revision: 1
shop_order: 17
shop_order_refund: 3
shop_subscription: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (12) ###

Query Monitor: by John Blackbourn – 3.7.1
Code Snippets: by Code Snippets Pro – 2.14.1
Companion Plugin: by Osk – 1.18
Creative Mail by Constant Contact: by Constant Contact – 1.3.8
Facebook for WooCommerce: by Facebook – 2.5.0
Google Ads & Marketing by Kliken: by Kliken – 1.0.7
Mailchimp for WooCommerce: by Mailchimp – 2.5.1
MailPoet 3 (New): by MailPoet – 3.60.12
WooCommerce Blocks: by Automattic – 5.1.0
WooCommerce Payments: by Automattic – 2.5.0
WooCommerce Subscriptions: by WooCommerce – 3.0.12
WooCommerce: by Automattic – 5.3.0

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.9
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.6.0 (update to version 3.7.0 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://inquisitive-de.jurassic.ninja
Subscription Statuses: wc-active: 2
WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

WooCommerce Payments: wc-active: 2

### Payment Gateway Support ###

WooCommerce Payments: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions


### Action Scheduler ###

Complete: 76
Oldest: 2021-05-25 06:56:10 +0000
Newest: 2021-05-25 11:30:08 +0000

Pending: 4
Oldest: 2021-05-26 09:49:41 +0000
Newest: 2021-06-25 11:03:31 +0000


### Status report information ###

Generated at: 2021-05-25 13:11:41 +00:00
`
```
</details>

**Comment by shendy-a8c** [comment]
Asked here: p1622022968061300-slack-C01BZUL57SQ.

**Comment by v18** [comment]
I see two bugs here:

**Bug 1 - translations not downloaded for German at all**
Steps to repro:
1. create jurassic ninja site w/ woocommerce, w/out jetpack
2. install snippets, add:
define( 'WCPAY_DEV_MODE', true );
3. add US address in woocommere onboarding wizard
4. install woocommerce-payments 2.5.0-test-2 ([release](https://github.com/Automattic/woocommerce-payments/releases/tag/2.5.0-test-2)), go through KYC flow
5. Go to Settings->General. Change language to German (Deutsch)
6. Go to Dashboard > Updates (wp-admin/update-core.php). Click on “Update Translations” button.
Bug: See that translations were not downloaded for "WooCommerce Payments" on that page, even though they're downloaded for other plugins.

<img width="300" alt="no-german-translations-downloaded" src="https://user-images.githubusercontent.com/11487924/119804115-042cd000-bf1b-11eb-98d8-f7d3d9e7a5ba.png">


**Bug 2: Spanish translations downloaded, but some translations strings are not being translated even though they're translated in the project**
1. create jurassic ninja site w/ woocommerce, w/out jetpack
2. install snippets, add:
define( 'WCPAY_DEV_MODE', true );
3. add US address in woocommere onboarding wizard
4. install woocommerce-payments 2.5.0-test-2 ([release](https://github.com/Automattic/woocommerce-payments/releases/tag/2.5.0-test-2)), go through KYC flow
5. Go to Settings->General. Change language to Spanish (Español)
6. Go to Dashboard > Updates (wp-admin/update-core.php). Click on “Update Translations” button.
7. See translations are downloaded for Spanish for WooCommerce Payments
<img width="250" alt="spanish-translation-downloaded-for-wcpay" src="https://user-images.githubusercontent.com/11487924/119806507-38a18b80-bf1d-11eb-9d35-8762d288ba66.png">
8. Go to the settings pages for WooCommerce Payments and see that some strings are not translated to Spanish, even though they have translations done as part of the project

Here are examples of missing spanish translations - highlighted in red and orange. I'll share the translation string for the red ones below:

<img width="500" alt="spanish-deposits" src="https://user-images.githubusercontent.com/11487924/119806615-540c9680-bf1d-11eb-998a-bbfb1cc3f12c.png">


<img width="500" alt="spanish-settings" src="https://user-images.githubusercontent.com/11487924/119806609-52db6980-bf1d-11eb-8eb5-c648145ce3d0.png">


`%s – your first deposit is held for seven days`  - translation string is here:
https://translate.wordpress.com/projects/woocommerce/woocommerce-payments/es/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=640367&filters%5Btranslation_id%5D=9920832

`Payment Request Buttons are enabled. To use Apple Pay, please use a live WooCommerce Payments account.` - translation here:
https://translate.wordpress.com/projects/woocommerce/woocommerce-payments/es/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=640214&filters%5Btranslation_id%5D=9921051

Translation strings can be found from here by using the 'Filter' menu right above the table:
https://translate.wordpress.com/projects/woocommerce/woocommerce-payments/es/default/

It's really strange because some translations are correctly being displayed.

**Comment by v18** [comment]
How translations work on WooCommerce Payments:

1. We add strings to the extension by using `__()` functions, etc (as per usual)
2. There's a translation project for WCPay here:  [https://translate.wordpress.com/projects/woocommerce/woocommerce-payments/](https://translate.wordpress.com/projects/woocommerce/woocommerce-payments/)
3. The translation project is hosted on WordPress.com, and the strings are downloaded from .com rather than the WordPress.org translation project as usual. This is done using a filter (done in #1592).

Other potentially relevant PRs can be found here:
https://github.com/Automattic/woocommerce-payments/pulls?q=is%3Apr+author%3Adiegocurbelo+

**Comment by jrodger** [comment]
> Bug 1 - translations not downloaded for German at all

I've only looked into this first bug so far. It works on my local site and doesn't work when I setup a Jurassic Ninja site following the reproduction steps. So this is good!

On my local site the call to `https://translate.wordpress.com/api/translations-updates/woocommerce` to fetch the language packs looks like this:

```
Array
(
    [locales] => Array
        (
            [0] => de_DE
        )

    [plugins] => Array
        (
            [woocommerce-payments] => Array
                (
                    [version] => 2.4.0
                )

        )
)
```

That returns me the expected language pack details and everything works.

On my Jurassic Ninja site, using the `woocommerce-payments 2.5.0-test-2` release changes the version parameter in the request to `2.5.0`, which makes sense. However, we don't get any language packs back for that version.

In the case of this first bug at least, it could just be a server-side configuration issue? I had a quick look, but I can't see any reference to versions in the translation project. I'll keep digging.

> Hmmm, what is this translation for

I had a quick look, it's the Hello Dolly plugin.

**Comment by v18** [comment]
> release changes the version parameter in the request to 2.5.0, which makes sense. However, we don't get any language packs back for that version.

This is interesting. My first instinct was that no translations are created for version 2.5.0 yet in the translation project because it's a future version... however in bug 2 Spanish translations _are_ downloaded for 2.5.0.

> > Hmmm, what is this translation for
> I had a quick look, it's the Hello Dolly plugin.

It was such a cool feeling to see the words from the image jump into text 🤭 😄

**Comment by jrodger** [comment]
After a bit more digging:

> My first instinct was that no translations are created for version 2.5.0

I think this is correct. We have created translations for `2.5.0test2` but we're sending a version of `2.5.0` to the translation server. So they aren't matching.

> however in bug 2 Spanish translations are downloaded for 2.5.0.

Props to @vbelolapotkov, it looks like these are being downloaded from .org as a fallback (https://translate.wordpress.org/projects/wp-plugins/woocommerce-payments/).

![image](https://user-images.githubusercontent.com/686419/119995818-e6687500-bfc5-11eb-8dbf-134e7ebdeb42.png)

(You can see the extra details by disabling the `.lp-show-latest p` css rule)

> It was such a cool feeling to see the words from the image jump into text 🤭 😄

I certainly didn't attempt to copy and paste from your screenshot...

So, we need to figure out if we can upload translations for pre-release versions just using the version number, or if we can change the version number of the plugin to match the test version. I'll P2 all this so we can discuss it.

**Comment by gglobalstep** [comment]
This issue is also observed on the Payments->Overview page and Transactions/deposits tables.
Please refer to the screenshots below:
![#1894_1](https://user-images.githubusercontent.com/41110392/120320480-db804e00-c2ff-11eb-907e-ae16ca7050a3.png)
![#1894](https://user-images.githubusercontent.com/41110392/120320486-dd4a1180-c2ff-11eb-94d6-3f6c7ad7dacd.png)

**Comment by vbelolapotkov** [comment]
> This issue is also observed on the Payments->Overview page and Transactions/deposits tables.
> Please refer to the screenshots below:

I assume those strings are pretty new and not translated yet.

**Comment by thracefulton** [comment]
I've got a user with a similar issue getting FR translations to apply to various parts of the WC Pay dashboard. 4444693-zen 

I've reviewed their po file and found strings such as `Deposit Schedule` have translations present but do not translate.

<img width="1177" alt="Screen Shot 2021-11-10 at 18 52 39" src="https://user-images.githubusercontent.com/88570946/142088797-bd6968e5-dd80-4fd9-be42-88dd96de4c29.png">

**Comment by ismaeldcom** [comment]
After a brief look at this, looks like every translation in `.tsx` files are not loaded. And the reason is that JS translations are loaded from `.json` files generated by `wp i18n make-json` and it only looks for `.js` files.

Taking as example the previous comment, if we look for `Deposit Schedule:` in `wp-content/languages/plugins/woocommerce-payments-es_ES.po` we will notice that there is a `#: client/transactions/list/index.tsx:73` entry, but not in `wp-content/languages/plugins/woocommerce-payments-es_ES.json` were all the JS translation are extracted.

I made a quick test, manually adding `Deposit Schedule:` to `wp-content/languages/plugins/woocommerce-payments-es_ES.json` and it works as expected.

To fix this we will need to update `make-json` to support other extensions like `ts/tsx` or rename the file paths comments in the `.pot` file.

I'll update the issue to mark it as high priority, because `.tsx` translations are missed in every language.

**Comment by kalessil** [comment]
Did a quick research, the issue is probably here: https://github.com/wp-cli/i18n-command/blob/master/src/MakePotCommand.php#L619. It's only js-files that are picked up, @Automattic/pulsar will look into the fix.

**Comment by liviopv** [comment]
This issue also seems to affect certain strings when WC Payments is loaded in the Checkout Block:
<img width="801" alt="Markup 2021-12-02 at 12 01 44" src="https://user-images.githubusercontent.com/14153300/144418474-1dbfba99-3480-460e-9fc4-279de858387d.png">

User-report in: 4563005-zen
