### ISSUE TITLE
Adjust card brand icons stroke

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#1946]
## Description

Card brand icons have too thick stroke when compared to other payment methods.

@jarekmorawski to provide updated SVG

**Comment by jarekmorawski** [comment]
Hi there! I've attached two SVG files with and without the border. I'd be great if we could add the border around each of the 4 icons in code so that it's always the same thickness as other brand icons.

For the other file, I've defaulted the thickness to 1px and outlined it so it's no longer a stroke.

Let me know if either works for you!

[cards_icons.zip](https://github.com/Automattic/woocommerce-payments/files/6614291/cards_icons.zip)

**Comment by frosso** [comment]
@jarekmorawski thanks! I think it might be a bit harder to target the individual shapes in the SVG and add the border around them. Embedding the border around all the SVGs will probably ensure that the border is more consistent at different viewports.

I'll defer to @harriswong, who picked up the issue :)

**Comment by harriswong** [comment]
Going forward with the `cards_outline.svg`. I attached the before and after screenshots in [the PR](https://github.com/Automattic/woocommerce-payments/pull/2093).
