### ISSUE TITLE
[Deposits UI] Multiple deposit currencies and instant deposits

### ISSUE THREAD

**Issue by kalessil** [Automattic/woocommerce-payments#1969]
When an account has deposit accounts in multiple currencies, the instant deposit dialogs might not work as expected:

![Screenshot from 2021-05-31 12-06-10](https://user-images.githubusercontent.com/1577185/120180380-f70a2c80-c20b-11eb-8b27-0bde2896e683.png)
![Screenshot from 2021-05-31 12-07-36](https://user-images.githubusercontent.com/1577185/120180104-aa265600-c20b-11eb-964b-8daae7cf8833.png)
![Screenshot from 2021-05-31 12-08-36](https://user-images.githubusercontent.com/1577185/120180109-abf01980-c20b-11eb-9b38-57ed42dc18db.png)

The second dialog should use Euro as currency and the next payout is should be 100 Euro.

**Comment by RadoslavGeorgiev** [comment]
Thank you for adding the issue, @kalessil! 🙌 

Assuming that this is live data, could you test whether the USD instant deposit works and mention the result here?

**Comment by kalessil** [comment]
We tested it before merging, the USD instant deposit was functioning.

**Comment by haszari** [comment]
What's `MDC` ? Multiple Deposit Currencies? @kalessil could you clarify that term please to help me understand 😁

**Comment by kalessil** [comment]
@haszari : that's multiple deposit currencies.

Relates to the situation when a merchant sets several deposit accounts in several currencies.
E.g. for sending USD balance to USD bank account and EUR balance to EUR bank account.

**Comment by haszari** [comment]
Thanks for explaining @kalessil – I've updated the title so it's clear to all.

**Comment by naman03malhotra** [comment]
@kalessil any idea on the priority of this issue?

**Comment by naman03malhotra** [comment]
@Automattic/helix checking if this is under your radar, as part of the prioritization call.

**Comment by haszari** [comment]
There's no work planned for this in the immediate timeframe (this quarter). There are projects to improve deposits this year so we may look at this as part of those.

If there are more reports of merchants impacted by this we can raise the priority and handle as maintenance.

**Comment by haszari** [comment]
FYI I've added `component: deposits` label so we can use that label to track ALL work related to deposits - regular speed and instant speed too. Note there are only [2 open issues for `component: instant deposits`](https://github.com/Automattic/woocommerce-payments/labels/component%3A%20instant%20deposits) so we might not need that label any more.

**Comment by Jinksi** [comment]
As of WCPay 5.8.0, this issue should not occur since the instant deposit button will only appear in the UI for USD account balances for US-based accounts only ([public docs](https://woocommerce.com/document/woocommerce-payments/deposits/instant-deposits/) / [wcpay-server code ref](https://github.com/Automattic/woocommerce-payments-server/blob/5c45694ce9f9837dc8bb8f4a88a3df5de43e5f0d/server/wp-content/rest-api-plugins/endpoints/wcpay/service/class-deposit-service.php#L365-L369)).

Example of button placement in new UI:
<img width="690" alt="image" src="https://user-images.githubusercontent.com/3147296/233944779-7ac22086-4451-485c-8645-d5caba37c73f.png">

The instant deposit button is not rendered for an ineligible account/currency:
<img width="694" alt="image" src="https://user-images.githubusercontent.com/3147296/233945589-cf6a277d-6e5e-435d-8c39-523aa614b0ad.png">

**Comment by Jinksi** [comment]
I think it is safe to close this issue since only USD deposit accounts are eligible for instant deposits.
