### ISSUE TITLE
[port] Use cart totals for Payment Request Button in the product page

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-payments#2019]
Port over the code from Stripe based on the work for this issue:

https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1563

**Comment by RadoslavGeorgiev** [comment]
We cannot use cart totals (and don't properly do it in the Stripe gateway either) because we need access to a temporary cart. That's in the works for code, but in any case, there is a more detailed issue on the topic here: https://github.com/Automattic/woocommerce-payments/issues/3372. I'm closing this one as a duplicate.
