### ISSUE TITLE
Base fee for Australian accounts incorrect on Overview screen

### ISSUE THREAD

**Issue by thenbrent** [Automattic/woocommerce-payments#2059]
With version 2.5.0, the account details card on the **Payments > Overview** screen displays an incorrect % value in the **Base Fee** for an Australian account.

The fee displayed is 1.8%, when the correct base fee is 1.75% (presumably this a rounding error).

<img width="999" alt="wcpay-overview-australian-fees" src="https://user-images.githubusercontent.com/235523/121009856-fd824080-c7d7-11eb-9fbc-9914672d5882.png">

**Comment by thenbrent** [comment]
The same issue is present on the **Transactions > Payment details** screen, where the fee is rounded to 1.8%, even though 1.75% is charged. Example screenshot:

<img width="978" alt="wcpay-transaction-payment-details-australian-fees" src="https://user-images.githubusercontent.com/235523/121009703-d62b7380-c7d7-11eb-97cd-a327db1d5a60.png">

The correct fee is being charged. If 1.8% was being levied here, the fee would have been AUD 0.73 instead of 0.72. It's just a display issue.

**Comment by jrodger** [comment]
I've doubled checked and in both cases the unrounded rate is being returned by the server, so this is "just" a case of correcting the rounding in the plugin code.

**Comment by aprea** [comment]
Hey @thenbrent, I just wanted to confirm the expected behavior here.

We currently display fees in two areas of the dashboard, the "Account details" section and the payment timeline (as per your screenshots above).

I just wanted to confirm that we should always display these fees with the minimum number of decimal places (with a maximum of 2 decimal places).

For example, a 2% fee would display as 2%, rather than 2.0% or 2.00%.

And a 2.9% fee would display as 2.9% rather than 2.90%.

This seems consistent with our [fees schedule doc](https://docs.woocommerce.com/document/payments/faq/fees/).

Should we also follow this rule when displaying discounted fees?

For example, imagine the following example:

Base fee = 2.9% + $0.30 per transaction
Discount = 30%

New fee = 2.03% + $0.21 per transaction

See below for how the "Account details" section would look like in this scenario:

<img width="694" alt="Screen Shot 2021-06-11 at 3 48 04 pm" src="https://user-images.githubusercontent.com/1527164/121637574-edff4200-cacc-11eb-9e80-ae8d294fbcc0.png">

Does this look okay or do we need to apply some additional rounding to the discount fee rate?

If we use the same scenario but lower the fee discount to 25% we would get:

Base fee = 2.9% + $0.30 per transaction
Discount = 25%

New fee = 2.18% + $0.23 per transaction

Though note that 2.18% is a little misleading because we're rounding to 2 decimal places.

The actual fee is 2.175% if we consider:

2.9 * ( 1 - 0.25 ) = 2.175

Is this acceptable? Any other thoughts here? p.s. sorry for the novel 😅

**Comment by aprea** [comment]
Just realized that Brent is AFK until the 18th, pinging a few other people here in case they're able to help: @shendy-a8c, @vbelolapotkov, @jrodger

**Comment by jrodger** [comment]
> p.s. sorry for the novel

Thanks for writing it all up! For a "show the fee here" sort of issue it's surprisingly complicated.

Firstly, the main thing for this issue is ensuring that these Australian base fees display correctly. We'll want to have that fixed for the 1.6.0 release in a few weeks. If we can create a more general solution then that would be fantastic, but we always have the option of creating follow-up issues to tackle later. That said, I think we can do a general fix here.

@LevinMedia gets the final say here, but I would propose:

* Display these fees with the minimum number of decimal places possible (as you proposed).
* Let's do a maximum of 3 decimal places (e.g. 2.175%). That should cover most of the discount fee cases without causing layout issues in the UI. We round fees to the nearest cent anyway, so for the vast majority of transactions that percentage will give the same fee amount.

**Comment by LevinMedia** [comment]
Thanks for the write up @aprea ! @jrodger your proposal sounds good 👍
