### ISSUE TITLE
Add breadcrumbs to individual currency screens

### ISSUE THREAD

**Issue by LevinMedia** [Automattic/woocommerce-payments#2092]
In order to improve ease of navigation, add the bread crumbs that were included in the original designs. 

<img width="570" alt="Screen Shot 2021-06-08 at 2 13 12 PM" src="https://user-images.githubusercontent.com/4500952/121258482-cce7e880-c863-11eb-99f3-e4ff4383605a.png">

7KVvtMQgJxVAUcPPxTB29r-fi-241%3A888

**Comment by jessepearson** [comment]
Initially the Store settings page was added, which added the different links at the top to navigate back to the Currencies page, but that was commented out for the time being since the Store settings were not being used. I added the page back in the branch in this PR: https://github.com/Automattic/woocommerce-payments/pull/2131 . You should be able to check that out to see if that works. 

I did try to get the links working like were in the design, but it is not possible without additional JS to make it behave in that fashion. This is due to it's using the legacy settings API to generate everything. 

If the designs need to match, we'd probably need to create a React component just for the page title to make it work as expected.

**Comment by LevinMedia** [comment]
@jessepearson is it not possible to implement that bread crumb in the same way that we're doing it on the shipping screens? I assumed that used the legacy settings API as well. 

<img width="1254" alt="Screen Shot 2021-06-11 at 6 47 54 AM" src="https://user-images.githubusercontent.com/4500952/121696669-2711c500-ca81-11eb-91ef-1840ba8b18d7.png">

**Comment by jessepearson** [comment]
@LevinMedia It is possible, yes. That specific page is built through custom admin templates, so we will look into that.

**Comment by LevinMedia** [comment]
@jessepearson got it - it may also be worth looking at how it was implemented in the new WCpay settings screens as well. They're using the same breadcrumb pattern when viewing the customization screen for express checkouts, perhaps they built a component that you could reuse. 

<img width="1332" alt="Screen Shot 2021-06-16 at 9 43 06 AM" src="https://user-images.githubusercontent.com/4500952/122259674-43e63800-ce87-11eb-942f-c2685ac1d8ed.png">
