### ISSUE TITLE
Enabled currencies table design updates

### ISSUE THREAD

**Issue by LevinMedia** [Automattic/woocommerce-payments#2096]
The following updates should be made to align the enabled currencies table with the original designs

<img width="551" alt="Screen Shot 2021-06-08 at 3 00 54 PM" src="https://user-images.githubusercontent.com/4500952/121263376-62867680-c86a-11eb-989b-4bd101b0c5aa.png">

- [ ] Remove `border-top` from the first child of the enabled currencies list  
- [ ] The default currency should not be editable (remove the edit icon)
- [ ] The default currency should use the `is-shady` card background color to differentiate it from the other rows in the table. 
- [ ] Reduce the size of the emoji flags to 24px
- [ ] remove edit / delete icons, replace with single tertiary style `Edit`  button. (Remove currency button should be added to an individual currencies page

**Comment by jessepearson** [comment]
> remove edit / delete icons, replace with single tertiary style Edit button. 

The icons were used due to that's what was used in the payment methods for the new grouped settings, like in the screenshots here: https://github.com/Automattic/woocommerce-payments/pull/1850 . Since the component(s) will be able to be reused, this seemed like it worked best to keep everything looking the same.

I am not sure how to see these options other than the screenshots, but I see a "Manage" link in this PR: https://github.com/Automattic/woocommerce-payments/pull/1841 . I feel like that was removed, though, as it came before the one previously mentioned. 

> (Remove currency button should be added to an individual currencies page

Like the above, this was modeled after the new settings, which includes the delete icon in the row. From a UX standpoint, I feel like this is a more logical solution, as the merchant would be able to manage which currencies they want to add/remove all from a single page.

With that being said, these can be changed, but I don't think they should be 😁

**Comment by LevinMedia** [comment]
@jessepearson having given this some more thought, I think you're correct. Let's keep the trash can icons on the list, (they should be the same grey color as the payments list) but replace the edit icon with the word manage, separated from the delete button without the vertical pipe. The manage action on those screens was deleted simply because there was nothing to manage. :D
