### ISSUE TITLE
Cache UPE theming values

### ISSUE THREAD

**Issue by bborman22** [Automattic/woocommerce-payments#2161]
The goal of this issue is to cache the UPE theming values that are generated during checkout. This cache will server 2 purposes: 
- To give a slight performance boost during checkout
- To keep a reference to the themes when they can't be generated at load time (thinking about the My Account > Add Payment Method page).

**Comment by brezocordero** [comment]
Adding a few notes to whoever picks up the issue.
If we decide to use a transient to store the UPE appearance (Another option would be to store it on the settings, with an option to reset it):
1) Check if the transient exists, if yes, [pass it to UPE](https://github.com/Automattic/woocommerce-payments/blob/cd60e648d16e5f659b23a9f03bffca182826c018/includes/payment-methods/class-upe-payment-gateway.php#L493) checkout js on a localized var.
2) On the checkout, if the value is present, [do not call the function to get the appearance](https://github.com/Automattic/woocommerce-payments/blob/cd60e648d16e5f659b23a9f03bffca182826c018/client/checkout/classic/upe.js#L219).
3) If the value is not present, call the function to get the appearance and store it. [Pass the value](https://github.com/Automattic/woocommerce-payments/blob/cd60e648d16e5f659b23a9f03bffca182826c018/client/checkout/classic/upe.js#L405) so that it can be stored on the transient.
4) Delete the transient[ at least on theme switch](https://developer.wordpress.org/reference/hooks/switch_theme/)
