### ISSUE TITLE
Add missing currency formatting data

### ISSUE THREAD

**Issue by luizreis** [Automattic/woocommerce-payments#2246]
The [locale-info.php](https://github.com/woocommerce/woocommerce/blob/b19500728b4b292562afb65eb3a0c0f50d5859de/i18n/locale-info.php) from WC Core doesn't have settings for all WC currencies. We should complete that list based on http://cldr.unicode.org/ and provide a fallback while we support WC versions that don't have the complete list.

**Comment by dechov** [comment]
We'll need to use that WC core locale info for the admin as well – see https://github.com/Automattic/woocommerce-payments/issues/2251. Multi-currency use case aside, some notable omissions are supported settlement currencies for currently supported countries: NZD and SEK. (Also the [Norwegian currency code](https://github.com/woocommerce/woocommerce/blob/77127f93af6edd0384810a3e440fbddcbea5a751/i18n/locale-info.php#L220) isn't quite right.)

**Comment by tpaksu** [comment]
I have two questions:

1) Do we have a limitation for this? For example the list having the locales only Open Exchange Rates is supporting, or only Stripe has support etc? I need this info for normalizing the data, most locales have alternatives, such as *en-GB* and *en-US*, so I need to know which will be supported by WC to complete the list. 

Maybe looking at the WCPay multi-currency list and complete the relevant ones might be a good idea instead of using all the locales supported in the CLDR. Any ideas?  

2) This will be fixed on WC right? Or should we add a filter to complete the WC `locale-info.php` list with a second list on WCPay? I mean something like this:

```php
$locale_info         = include WC()->plugin_path() . '/i18n/locale-info.php';
$locale_info         = apply_filters("woocommerce_payments_additional_locales", $locale_info);
$currency_by_country = wp_list_pluck( $locale_info, 'currency_code' );
```

**Comment by tpaksu** [comment]
What's our limit on this issue? All the currencies that Open Exchange Rates service supports, or all the ones in the CLDR? Also this fix needs to be done on WC repository, right?

**Comment by dmallory42** [comment]
@tpaksu I would say all currencies returned by the `get_woocommerce_currencies()` function would be a great place to start, as this is what we use the build the currency list that we display in the Multi-Currency plugin. @luizreis - do you agree?

And yes, my understanding is that this would be a PR to the `woocommerce` repository.

**Comment by luizreis** [comment]
> @tpaksu I would say all currencies returned by the `get_woocommerce_currencies()` (https://github.com/woocommerce/woocommerce/blob/a5cd695e629e1c4c48b257646b60c0d92f479509/includes/wc-core-functions.php#L475) function would be a great place to start, as this is what we use the build the currency list that we display in the Multi-Currency plugin. @luizreis - do you agree?
> 
> And yes, my understanding is that this would be a PR to the `woocommerce` repository.

I agree. Since this change is to introduce better formatting for WooCommerce core, we should strive to implement all the currencies supported by default in `get_woocommerce_currencies`.

**Comment by tpaksu** [comment]
Hello all,

I know this is taking too long, but CLDR wasn't easy to locate related stuff (for me at least)

I've mined the CLDR and produced an output: https://cloudup.com/cx2PDFB5lbF, and these currencies are missing in the CLDR json files: **BTC, GGP, IMP, JEP, PRB**. I'll try to adapt the output more like `locale-data.php` format, but this type of format (CLDR) will give us more control of what we output when. So I needed to ask, how should we proceed?

1) Use the format that `locale-data.php` uses
2) Keep the format in the JSON and normalize it, slowly convert WC plugins to adapt new format
3) Keep the format that `locale-data.php` uses, but extend it with the new keys on JSON

Since the JSON also contains the locale data (which will be useful for geolocating and displaying the correct format) the first option would miss that opportunity.

**Comment by luizreis** [comment]
> I've coded a tool that reads the CLDR and produces this output: https://cloudup.com/cx2PDFB5lbF, but these currencies are missing in the CLDR json files: **BTC, GGP, IMP, JEP, PRB**, so they are not included.

I think that's okay. Those are probably not that common and stores that use them can easily change the formatting using a filter.

> I'll now try to adapt the output more like `locale-data.php` format, but this type of format (CLDR) will give us more control of what we output when. So I needed to ask first, how should we proceed?
> 
> 1. Use the format that `locale-data.php` uses
> 2. Keep the format in the JSON and normalize it, slowly convert WC plugins to adapt new format
> 3. Keep the format that `locale-data.php` uses, but extend it with the new keys on JSON
> 
> Since the JSON also contains the locale data (which will be useful for geolocating and displaying the correct format) the first option would miss that opportunity.

IMO, as part of the Multi-Currency MVP, we shouldn't worry too much about adding the entire locale data to WooCommerce Core. So I'd say that we should keep the `locale-data.php` format to avoid breaking other integrations and just add the missing currencies settings to that file (option 1).

If we can figure out a way to add the language part of the locale to the current file format without requiring changes to every other place that it's used, I think we should go for it. But, right now, we shouldn't spend too much time trying to figure this out. Adding full locale support and the CLDR settings to Core seems like a bigger project than the original intention for this issue and could be quite complex as, ideally, we should keep it backward compatible.

**Comment by tpaksu** [comment]
> I think that's okay. Those are probably not that common and stores that use them can easily change the formatting using a filter.

👍 me thinks so too.

> IMO, as part of the Multi-Currency MVP, we shouldn't worry too much about adding the entire locale data to WooCommerce Core. So I'd say that we should keep the locale-data.php format to avoid breaking other integrations and just add the missing currencies settings to that file (option 1).

Sure, that makes sense for the MVP, and for later, I'll keep the utility that produces it to extend to our needs. CLDR data has all the info (except metric and weight units) to cover the formatting issues based on locale.

**Comment by tpaksu** [comment]
I've compiled a JSON with the data I could parse from CLDR, you can see it here: https://cloudup.com/cCSwg8jarL8 I have one problem about it though, it contains duplicate data for locales, for example, ~35 countries use Euro as the currency, and the locale array per country data has the same locales duplicated. 

I think I can separate it to another array and give reference to it, but with a single `locale-info.php` file, I can't return multiple values. 

Maybe I can use a reference to another `country.locale` value. For example `DE` would have all the locales, and `ES` would have `'locales' => 'DE'` string that tells to look to `DE` locales array. 

The file is (with the above issue) ~20K lines long, I believe it would halve the file size by eliminating the duplicates. Or since it's a server-side file and will be used without downloading to the client (like that at least), we can keep the duplicates and use that file as it is now (~20K lines).

*Note:* Don't mind about the file being a JSON, I'm using it to quickly visualise the output, I'll convert it to PHP Array and replace `locale-info.php`.

**Comment by luizreis** [comment]
> I think I can separate it to another array and give reference to it, but with a single `locale-info.php` file, I can't return multiple values.

@tpaksu - sorry for the delay in replying here. As we talked on Slack, I think defining the locales in an array before the `return` statement and referencing it on the `locales` attribute for each country, like `['AD' => [ 'currency_code' => 'EUR', ..., 'locales' => $locales['EUR'] ]`, would be a good approach. It would preserve the full locale data, without resorting to lookups, while removing the locales duplication.

**Comment by tpaksu** [comment]
@luizreis @dmallory42 how do you think we should provide a fallback for older WC core versions? Should we also include the full `locale-info.php` in this repository and load it if the check for the `locale` key is missing in the `AT` country info (for example)? What do you think?
