### ISSUE TITLE
Format customer currency based on the customer's language

### ISSUE THREAD

**Issue by luizreis** [Automattic/woocommerce-payments#2247]
Some currencies, like CAD, are formatted differently depending on the language. We should add support for these cases in the Customer Multi-Currency plugin, possibly by making use of the locale data and the `wcpay_multi_currency_{currency_code}_format` filter.

**Comment by tpaksu** [comment]
I think this needs to be done before we start fixing issues #2375 and #2098 to have the necessary base for currency formatting, right? I'm putting #2098 to on-hold. 

BTW, I think we can add global support for this by hooking into `wc_price`, since every price in WC-Core seems to use that filter before display, but this only affects the output rendered on the server. The same algorithm needs to exist also in `@woocommerce/currency` library for the client side renders too. 

Also we might need to add some currency format modifiers to the arguments array, such as overriding the currency to;

- display the amount in a different currency, 
- override the visual format to another currency (read the paragraph below)
- switching between short and extended modes
- flag to enable/prevent using country and locale info while formatting with the currency code if geolocation is enabled
- etc

Also one more thing that I want to share, we talked with @LevinMedia yesterday on this thread p1626094273027600-slack-C01B8KNUYSW and he told me regardless of the currency the price belongs, the prices should be rendered with the base currency format and in extended mode on the admin pages. For example, when the price is `CHF 1'000.00` on the frontend, and the base currency is EUR, the admin should see `1 000,00 CHF` to keep visual consistency with other prices. 

So, instead of displaying this on the admin side:

```
Base currency: EUR

Product A			 CHF 1'000.00
Product B			$1.000,00 USD
Product C			1 000.00 € EUR
```

The admin would see

```
Base currency: EUR

Product A			1 000.00 CHF
Product B			1 000.00 $ USD
Product C			1 000.00 € EUR
```

What do you think? Can we start this prior #2357 gets merged?

/cc @dmallory42 @luizreis @ismaeldcom
