### ISSUE TITLE
Discount fee - newly supported countries

### ISSUE THREAD

**Issue by pmcpinto** [Automattic/woocommerce-payments#2255]
Shared by @oneillo [here](https://github.com/Automattic/woocommerce-payments-server/issues/892)

We want to test the impact of two discounted fee offers in the following countries:

UK
Australia
Canada
Ireland
New Zealand
The offers will be the similar in structure to the ones implemented in #835, but adapted for the local currencies in each country. Similar to prior experiments, we want to deliver one of the offers at random via inbox note directly to eligible merchants, like in Automattic/woocommerce.com#10118.

Ideally, we are able to launch this as close to 6/29 as possible, but I understand we'll need to wait on this [issue](https://github.com/Automattic/woocommerce-payments-server/issues/545) before we can run this test.

It's possible we'll want to expand this test to Spain, France, Italy, and Germany, but I'm waiting for confirmation on this. If it were to be expanded, we'd want to target an 8/5 launch for this test.

I'm also waiting on confirmation of the target audience criteria. I'll share that along with the final offer details and copy for the inbox notes as soon as it's been finalized.

**Comment by pmcpinto** [comment]
Hey @oneillo do you have news about this?

**Comment by oneillo** [comment]
@pmcpinto - yes! Thanks for the prompt.

Given the performance of the current experiment, we are going to try this one last time for now using a different design. Instead of using inbox notes, we'll be testing this via emails to subscribed merchants. 

I think we can close this issue. I'll need some dev support eventually to figure out how to implement a discounted fee for someone through the email process, but it will take some time before I get to that point.

**Comment by pmcpinto** [comment]
Thanks for the update. I'll close this issue.
