### ISSUE TITLE
Add a currency switcher to the cart widget

### ISSUE THREAD

**Issue by ismaeldcom** [Automattic/woocommerce-payments#2259]
If the merchant has enabled _"Add a currency switcher to the cart widget"_ in Multi-currency store settings. We need to add it. This is a quick solution to get Multi-currency working without the need to manually adding a widget/block to the store.

**Comment by jessepearson** [comment]
@LevinMedia Were you able to look into some of the more popular themes to see if the default cart widget is automatically included in those themes? I believe that's where we left off, we were wanting to see if this would be a good option to get the currency switcher into the shop with the check of a box rather than having to add a widget.

My concerns here would be that when the cart widget is included, most times it's hidden. For instance with Storefront, the cart widget is added by default, but it's hidden. This means that if we were to inject the currency switcher into the cart widget, it wouldn't display until someone hovered over the header cart. On mobile, there's no header cart, so the currency switcher would never be shown.

I am not saying all of this because it's hard to do or can't be done, I just don't want it to be looked at as a magical option that is just going to make the switcher appear.

**Comment by dmallory42** [comment]
Just adding the `on hold` status until we know which way we're going to implement this.

**Comment by LevinMedia** [comment]
Closing the issue - Upon further investigation @jessepearson and I have decided that the cart widget is not a reliable place to automatically add a currency switcher widget - usage of the cart widget is not consistent enough amongst top themes, so including a setting to activate it somewhere that might not be in use is undesirable.

Instead we'll be integrating the currency switcher widget directly in the store front header, and creating docs for themes to include support for the widget in their own themes. 

Related: 
https://github.com/Automattic/woocommerce-payments/issues/2264
https://github.com/Automattic/woocommerce-payments/issues/2265
