### ISSUE TITLE
Integrate the currency switcher widget into the storefront header and mobile menu

### ISSUE THREAD

**Issue by LevinMedia** [Automattic/woocommerce-payments#2264]
In order to best support the new multi-currency experience, we should directly integrate the currency switcher widget into the storefront header and mobile menu: 

<img width="1686" alt="Screen Shot 2021-06-18 at 10 03 32 AM" src="https://user-images.githubusercontent.com/4500952/122594946-91e07480-d01c-11eb-86ac-ddb1c82ae314.png">

<img width="316" alt="Screen Shot 2021-06-18 at 9 56 30 AM" src="https://user-images.githubusercontent.com/4500952/122594986-9b69dc80-d01c-11eb-9bc8-c5b506c7c2d7.png">

We'll use this integration to create documentation for other theme developers and store builders to integrate the widget directly into their themes as well.

**Comment by jessepearson** [comment]
I believe we should be able to do this strictly using hooks to get the widget into the Storefront header. Something we need to account for is the Storefront Powerpack that allows site owners to rearrange the header as they see fit. There appears to be a filter for this: https://github.com/woocommerce/storefront-powerpack/blob/trunk/includes/customizer/header/customizer.php#L230

There's also the designer that we may have to account for. The filter for that is here: https://github.com/woocommerce/storefront-powerpack/blob/trunk/includes/customizer/designer/class-sp-designer.php#L996

We also need to add a toggle for this so we don't force it into the header, due to if there's a child theme it could break their site. 

The mobile menu in Storefront is the primary navigation that you see on the desktop version, just changed with CSS via media queries. The Menu button you tap to open the menu is hidden on desktop, but appears on mobile. Again, this is all just included with hooks, so we should be able to inject the widget once, and then place it with css... https://github.com/woocommerce/storefront/blob/trunk/header.php#L44

**Comment by jessepearson** [comment]
@LevinMedia I started working on this, and I want to ask if you'd rather have the widget show up down with the breadcrumbs? On desktop, it can be added inline to the right, and mobile it can be just below them. On desktop, that area is already vacant, as the breadcrumbs container is full width. On mobile, this would make it so the switcher is available without having to go into the menu to change the currency.

I feel like this would make it more prominent and less likely to conflict with any additional configuration done with the Powerpack. This should also make it work with all of our [Storefront child themes](https://woocommerce.com/product-category/themes/storefront-child-theme-themes/) out of the box, as well.

**Comment by jessepearson** [comment]
@LevinMedia Thanks for the chat earlier. Per our discussion, we are going to integrate the currency switcher widget in the same row as the breadcrumbs, floating to the far right. The option in the settings that allows merchants to toggle the automatic widget will default to on.
