### ISSUE TITLE
No error message shown when initiating Stripe redirect from non-Settings page

### ISSUE THREAD

**Issue by dechov** [Automattic/woocommerce-payments#2266]
If "Edit details" redirect link on "Overview" page fails, no error message will show, because errors are only handled by specifically adding an error message to the settings page:

https://github.com/Automattic/woocommerce-payments/blob/add641f73da3863d17d0b831ea35054e8b7c4f9f/includes/class-wc-payments-account.php#L320-L327

This may or may not also be an issue on the Connect screen with the "Finish Setup" button, which uses the same `add_notice_to_settings_page` function.

Marking low priority, partly because the error isn't terribly useful anyway.

**Comment by htdat** [comment]
### To replicate the issue

We can hack a bit with this code so that method `redirect_to_login` always throw an exception, and then method `add_notice_to_settings_page` will be called:

```diff
Index: includes/class-wc-payments-account.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/includes/class-wc-payments-account.php b/includes/class-wc-payments-account.php
--- a/includes/class-wc-payments-account.php	(revision 33b010ef8c898b3bef12a62d55c8db9a5f089b6e)
+++ b/includes/class-wc-payments-account.php	(date 1626326357133)
@@ -318,6 +318,7 @@
 
 		if ( isset( $_GET['wcpay-login'] ) && check_admin_referer( 'wcpay-login' ) ) {
 			try {
+				throw new Exception('just_a_test');
 				$this->redirect_to_login();
 			} catch ( Exception $e ) {
 				$this->add_notice_to_settings_page(
``` 

### My preliminary research on this issue: 

- [Method `add_notice_to_settings_page`](https://github.com/Automattic/woocommerce-payments/blob/33b010ef8c898b3bef12a62d55c8db9a5f089b6e/includes/class-wc-payments-account.php#L749-L757) is using the traditional `admin_notices` filter to display errors. 
- Actually, the error message is output to browsers, however, its display was suppressed by this class `woocommerce-layout__notice-list-hide`:

![Markup on 2021-07-15 at 16:32:02](https://user-images.githubusercontent.com/10045087/125765582-db1847dc-ba1c-4c47-8d38-f6b44fc41c29.png)

- Actually, this is the intention of `woocommerce-admin` to hide these admin notices from [the pages powered by it](http://github.com/woocommerce/woocommerce-admin/blob/015e2c0a736bed46b64a3385f63226ac5be81dda/src/Loader.php#L937-L944).

### Possible solution 

I thought of a way to hack around the limit by WooComerce Admin however that seems not a good choice. We may follow its convention.

Instead, I am thinking this way: 

- When clicking `Edit Detials`, it will call out to a local endpoint to get the redirect URL.
- If there is any error, it will display the error on this `Overview` screen.
- Otherwise, it will redirect users to a Stripe Connect link normally. 

I am still on the way to explore this but if someone has other ideas, feel free to let me know :D

**Comment by naman03malhotra** [comment]
>When clicking Edit Detials, it will call out to a local endpoint to get the redirect URL.

Do you mean to say you'll create a new endpoint to get the redirect URL or call the redirect URL to see if there is an error and then choose the behavior accordingly (either display error or redirect).

Also, the redirect URL is already present in the client store.
https://github.com/Automattic/woocommerce-payments/blob/5aefa3eb392b990a5fde0d76e3c40aa323f8808b/client/components/account-status/index.js#L70

I am not sure if there is any other method in PHP that can render normal notices. I came across `wc-add-notice`:
https://github.com/Automattic/woocommerce-payments/blob/98ab3e60077be7aac1d468575c894d4e3dd81be1/includes/class-wc-payment-gateway-wcpay.php#L473
But I am not sure If it'll work, maybe we can check this out.

Though we can explore your approach in-depth, I have a suggestion.

So we can pass a custom class to `add_notice_to_settings_page`. We can pass something like `notice-error overview-error` and on the client-side, we can use a query selector to get the message from the rendered element using class selector
https://github.com/Automattic/woocommerce-payments/blob/5aefa3eb392b990a5fde0d76e3c40aa323f8808b/includes/class-wc-payments-account.php#L323-L325


For example: `document.querySelector('.overview-error').innerText`
 
We can render the extracted text inside a Notice component, maybe inside a `useEffect`. I haven't tried it but should work.

**Comment by htdat** [comment]
@naman03malhotra Responding to your great comment above: 

> Do you mean to say you'll create a new endpoint to get the redirect URL or call the redirect URL to see if there is an error and then choose the behavior accordingly (either display error or redirect).

Yes, that's what I meant. But it takes more effort to build up a new API endpoint. If possible, I would avoid this route.

> Also, the redirect URL is already present in the client store.
https://github.com/Automattic/woocommerce-payments/blob/5aefa3eb392b990a5fde0d76e3c40aa323f8808b/client/components/account-status/index.js#L70

`accountLink` here looks like this 

```
wp-admin/admin.php?page=wc-admin&path=%2Fpayments%2Foverview&wcpay-login=1&_wpnonce=589b7e56ac
```

It will reload the whole page and the PHP code will decide whether or not to show an error (with filter `admin_notices`) - [code ref](https://github.com/Automattic/woocommerce-payments/blob/add641f73da3863d17d0b831ea35054e8b7c4f9f/includes/class-wc-payments-account.php#L319-L329)

Therefore, we're not able to use it too. It circles back to my idea to build up a new API endpoint. 

> I came across wc_add_notice. 

I don't think `wc_add_notice` works for our issue here. Actually, it is used for managing notices on the front-end as all notices are attached to shoppers' sessions. - [code ref](https://github.com/woocommerce/woocommerce/blob/a35e91f5eee6be66cf4e36239ea2a0f1ac96798f/includes/wc-notice-functions.php#L74-L80).

> So we can pass a custom class to `add_notice_to_settings_page`. We can pass something like `notice-error overview-error` and on the client-side, we can use a query selector to get the message from the rendered element using the custom class we passed
https://github.com/Automattic/woocommerce-payments/blob/5aefa3eb392b990a5fde0d76e3c40aa323f8808b/includes/class-wc-payments-account.php#L323-L325

Hmm.. this still looks like a hack IMHO. Ideally, I think we should not use `$this->add_notice_to_settings_page` when we're sure we're on a wc-admin-powered page.

---- 

I then stepped back and see if `woocommerce-admin` and WCPay client have any pattern for handling this error notice and found out on page Payments > Overview, `wcpay-connection-success` param is handled and displayed with a successful notice. I think we can follow up on this pattern.

**Comment by htdat** [comment]
> This may or may not also be an issue on the Connect screen with the "Finish Setup" button, which uses the same `add_notice_to_settings_page` function.

Currently, `add_notice_to_settings_page` is used in two other places: 

1, When finalizing connection after the OAuth flow: 
https://github.com/Automattic/woocommerce-payments/blob/e7a2f906d3b9cd1740c86f387f22ca92b14cf057/includes/class-wc-payments-account.php#L581-L588

2., When trying to start the Stripe OAuth process: 

https://github.com/Automattic/woocommerce-payments/blob/e7a2f906d3b9cd1740c86f387f22ca92b14cf057/includes/class-wc-payments-account.php#L359-L367

Since both of them belongs to the Connect screen, I think we can switch them to use function `redirect_to_onboarding_page` and take advantage of its optional param `$error_message`: 
https://github.com/Automattic/woocommerce-payments/blob/e7a2f906d3b9cd1740c86f387f22ca92b14cf057/includes/class-wc-payments-account.php#L236
