### ISSUE TITLE
Unable to Start Setup

### ISSUE THREAD

**Issue by jrodger** [Automattic/woocommerce-payments#2288]
The "Finish Setup" button just reloads the setup page and doesn't redirect to Stripe onboarding. The issue isn't present in 2.5.0 and only occurs on the `develop` branch since that release (I haven't investigated where the issue might have been introduced more than that).

![image](https://user-images.githubusercontent.com/686419/122818235-da27bd00-d2d0-11eb-8044-e3d4f400779d.png)

There seems to be a problem with the URL escaping somewhere along the line. The button sends:
```
Array
(
    [page] => wc-admin
    [amp;path] => /payments/connect
    [amp;wcpay-connect] => 1
    [amp;_wpnonce] => 459eb0265d
)
```

Marking this as high priority because we need to have it fixed before the 2.6.0 release on Wednesday.

**Comment by dechov** [comment]
Looked into it – this is because of the change in how the URL is passed, from a "top-level" script param to being nested inside an object [[diff](https://github.com/Automattic/woocommerce-payments/commit/74472eab2e994f53078f333cdb781ca184fe1667#diff-3863b4f88d0515e080fadc56af3c5e38e942afb96e569cb000ae6a594e8bea4aL242-R243)]. Only [top-level values are decoded](https://core.trac.wordpress.org/browser/tags/5.7.1/src/wp-includes/class.wp-scripts.php#L508) (TIL!), so nesting it this way necessitates manual decoding (e.g. as was done [here](https://github.com/Automattic/woocommerce-payments/blob/17260ea23de16d2b5e9be30967bce8a25e6fea8d/client/connect-account-page/index.js#L113-L114) in the newer flow).

**Comment by kalessil** [comment]
Suggested approach: p1624342984257600/1624301419.246100-slack-CGGCLBN58
