### ISSUE TITLE
UX Updates for Edit Currency Settings

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#2335]
There are a few UX changes required for the edit currency settings page originally mentioned by @LevinMedia in https://github.com/Automattic/woocommerce-payments/issues/2280#issuecomment-870986954:

> For zero-decimal currencies, I'm wondering whether we should even allow None as an option for price rounding?

> @dmallory42 @luizreis after giving this a test, I agree that we should make 1 the minimum rounding option for non-decimal currencies. Also where we're showing the preview of a non decimal currency, we shouldn't show the decimal - for example, with yen - this should simply read 1700

<img width="1332" alt="Screen Shot 2021-06-29 at 4 30 43 PM" src="https://user-images.githubusercontent.com/4500952/123880448-8849ed00-d8f7-11eb-836d-4e7f4cc149d1.png">

> I also noticed when testing this that decimal currencies are defaulting to no rounding, rather than to 1.00 - could we please update that to match this screen shot too?

<img width="1332" alt="Screen Shot 2021-06-29 at 4 35 42 PM" src="https://user-images.githubusercontent.com/4500952/123880729-22aa3080-d8f8-11eb-8914-4d468c87a11f.png">

**Comment by luizreis** [comment]
> I also noticed when testing this that decimal currencies are defaulting to no rounding, rather than to 1.00 - could we please update that to match this screen shot too?

@LevinMedia - did you test with a new currency? We didn't include an automatic migration for existing settings because the plugin is not yet enabled for merchants. The defaults were updated [here](https://github.com/Automattic/woocommerce-payments/pull/2280/files#diff-a6e2cb95b46bc88cda58f15af486f9b4c871fca222fa8bcc649cd3908c1b65dfR374) and [here](https://github.com/Automattic/woocommerce-payments/pull/2280/files#diff-b17bf67925ece08a12ad748cd870705e5d668d3fa19214040f4841daaf712cdcR336).
