### ISSUE TITLE
Refactor WC_Payments_API_Intention to support Setup Intents

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#2422]
Currently, the function `WC_Payments_API_Client::get_intent` returns a `WC_Payments_API_Intention`, whereas the function `WC_Payments_API_Client::get_setup_intent` simply returns an array representing the `WP_REST_Response` sent back from the Payments Server. This creates a lot of unnecessary branching logic in sections such as this one: 

https://github.com/Automattic/woocommerce-payments/blob/ca0d60fdabdc9501c165fc8b423b23bc629043dd/includes/class-wc-payment-gateway-wcpay.php#L955-L980

The two have very similar fields, with Setup Intents differing by lacking any charge objects, so I think it should be possible to encapsulate and deserialize both of these REST responses into `WC_Payments_API_Intention` instances. I don't think this will require a massive effort, but will have some impact on both the UPE payment gateway, the existing WCPay card gateway, and all relevant tests in between.

**Comment by RadoslavGeorgiev** [comment]
Just dropping a note here, as this is something we'll likely be changing soon.

---

IMO it would make sense to have two separate classes in order to be stricter. It'd suggest the following:

1. `WC_Payments_API_Intention` should become `WC_Payments_API_Payment_Intention`.
2. The old `WC_Payments_API_Intention` class (name) should be used as a base for both Payment and Setup intentions.
3. Introduce a new `WC_Payments_API_Setup_Intention` class.

```mermaid
classDiagram
    WC_Payments_API_Intention <|-- WC_Payments_API_Payment_Intention
    WC_Payments_API_Intention <|-- WC_Payments_API_Setup_Intention
    WC_Payments_API_Intention : +string id
    WC_Payments_API_Intention : +string status
    WC_Payments_API_Intention : ...
    WC_Payments_API_Intention: +get_id()
    WC_Payments_API_Intention: +get_status()
    WC_Payments_API_Intention: ....()
    class WC_Payments_API_Payment_Intention{
      +array charge
      +get_charge()
    }
    class WC_Payments_API_Setup_Intention{
      +array payment_method_options
      +get_payment_method_options()
    }
```

In addition, those two classes need to be added as response formats to the correct request classes.

**Comment by RadoslavGeorgiev** [comment]
Another note: Let's add a proper request class once this is done.

**Comment by naman03malhotra** [comment]
After a discussion with @htdat we have the following timelines for this issue:
Estimated Dev Complete date: 24th May Wednesday
Estimated Shipping date: 26th May Friday

**Comment by naman03malhotra** [comment]
As discussed with @htdat, this is estimated to be dev complete by the end of this sprint.
