### ISSUE TITLE
Incorrect ZIP code error message confuses customers

### ISSUE THREAD

**Issue by billrobbins** [Automattic/woocommerce-payments#2602]
When an order fails ZIP code validation, there is an error message telling them to update the ZIP code.  Sometimes users update the shipping ZIP code since the error doesn't specify.  It would be great to clarify that the _billing_  zipcode failed validation so it's not confusing to users.

<img width="558" alt="Markup 2021-07-27 at 20 19 56" src="https://user-images.githubusercontent.com/1138631/127527283-f185ef21-7342-486c-9a41-94523c26c9fa.png">

4178877-zen

**Comment by jrodger** [comment]
I've seen a few instances of the confusion this error message can cause, so I was going to give it a high priority but I don't think it quite hits that threshold.

@jarekmorawski, I was wondering if this might be a good issue to consider as part of your work on error messaging? Or where you focusing more on the error messages the merchant seeing in the admin dashboard?

**Comment by jarekmorawski** [comment]
👋 Thanks for the ping, @jrodger. Indeed I'm currently focusing on the error notes in the admin dashboard, but if this message is confusing customers, it's definitely a problem worth solving ASAP.

To be clear, is this error caused by merchant's account blocking purchases with a failed zip code check? I tested it on my site, but the only error I'm getting is:

> Billing ZIP is not a valid postcode / ZIP.

The transaction goes through even when the zip code check fails.

As for the error note itself, is it handled by Stripe? If not, perhaps we could change it something like this (inspired by [this support doc](https://support.cratejoy.com/support/solutions/articles/43000495292--the-zip-code-you-supplied-failed-validation-errors)):

> We couldn't verify the postal code in your billing address. Make sure the information is current with your card issuing bank.

**Comment by jrodger** [comment]
Thanks for taking a look @jarekmorawski. Where are you seeing the "Billing ZIP is not a valid postcode / ZIP" error message?

> The transaction goes through even when the zip code check fails.

I think this is a difference in behaviour between test mode and live mode...which is annoying. I'll try and track down why we seem to be getting different behaviour.

**Comment by jarekmorawski** [comment]
> Where are you seeing the "Billing ZIP is not a valid postcode / ZIP" error message?

On checkout (red notice about all the fields) when I purposely enter an incorrect postcode.

**Comment by jrodger** [comment]
Ah, got it, thanks.

That explains the difference between the 2 messages then. The "<field name> is not a valid postcode / ZIP" comes from WooCommerce core [here](https://github.com/woocommerce/woocommerce/blob/8fa6265ef7b791439adc22e27cb56fa0abf2383e/includes/class-wc-checkout.php#L788).

So to answer your original question, yes, the error in the screenshot should be the error that Stripe returns when there was an issue checking the ZIP code....I just can't replicate it right now.

**Comment by travislima** [comment]
Hey everyone,

Travis from Woo Customer Success here. I'm working with a customer who is experiencing this issue. He sent in a video to showcase or recreate the issue. Hope this helps: https://share.getcloudapp.com/yAuy9B5w

**Comment by geektzu** [comment]
@jrodger 

Looks like the error message could be from:

Line: 1166 or 1201
wc_add_notice( $message, 'error', $data );


Definition of wc_add_notice found from https://woocommerce.wp-a2z.org/oik_api/wc_add_notice/
function wc_add_notice( $message, $notice_type = 'success', $data = array() ) {
  if ( ! did_action( 'woocommerce_init' ) ) {
    wc_doing_it_wrong( __FUNCTION__, __( 'This function should not be called before woocommerce_init.', 'woocommerce' ), '2.3' );
    return;
  }

  $notices = WC()->session->get( 'wc_notices', array() );

  // Backward compatibility.
  if ( 'success' === $notice_type ) {
    $message = apply_filters( 'woocommerce_add_message', $message );
  }

  $message = apply_filters( 'woocommerce_add_' . $notice_type, $message );

  if ( ! empty( $message ) ) {
    $notices[ $notice_type ][] = array(
      'notice' => $message,
      'data'   => $data,
    );
  }

  WC()->session->set( 'wc_notices', $notices );
}


I think we just need to change:

wc_add_notice( $message, 'error', $data ) to wc_add_notice( $message, 'billing address error', $data );

As the $notice_type is only used to add on to the message.
  $message = apply_filters( 'woocommerce_add_' . $notice_type, $message );

**Comment by leonardola** [comment]
Hi there, I could not simulate the error. Can you please post some more details on how to get this error?
>Error: The zip code you supplied failed validation?

All I can see is this one:
> Billing ZIP Code is not a valid postcode / ZIP.

Steps taken:
- Add any product to cart
- Go to checkout
- Type invalid zip code on the field Zip Code
Neither the the order nor the transaction went through

I've tested both UPE and regular checkouts

The reported error seems to be generated here: 
https://github.com/Automattic/woocommerce-payments/blob/develop/includes/wc-payment-api/class-wc-payments-api-client.php#L1388

**Comment by jrodger** [comment]
> Can you please post some more details on how to get this error?

The issue is to do with the ZIP code not matching the provided card details, as opposed to the code just being in the wrong format or not existing.

In a live environment this is pretty easy to simulate, just put in the wrong address for your card. However, I'm struggling a little bit to replicate this in a test environment. We can use Stripe's [test cards](https://stripe.com/docs/testing#cards-responses), I think `4000000000000010` is the one we want. I just haven't been able to replicate the correct account setup to get it failing.
