### ISSUE TITLE
WC Payments ignoring currency options settings

### ISSUE THREAD

**Issue by martynmjones** [Automattic/woocommerce-payments#2658]
**Summary:**

With WooCommerce Payments active, the settings for `Currency Options` in `WooCommerce > Settings > General` appear to be ignored.

With number of decimals set to 0 and position right, this is the result I get:

<img width="1018" alt="Markup 2021-08-04 at 15 50 23" src="https://user-images.githubusercontent.com/40762232/128203798-f70a3f88-ef9b-4bbe-8c3a-acd73d5e21d6.png">

_Left WC Payments active, Right not active_

**Tickets**
4197690-zen

**Comment by LevinMedia** [comment]
In order to resolve this - lets ignore, or not apply any CLDR formatting for the store's default currency. This should only be the case on the front end of a store (customer facing prices) The only exception to this rule would be the addition of the currency code (explicit format) to things like the order totals in the cart / checkout.  The addition of the explicit format should only happen if merchant is using the multi currency feature (That specific case will be resolved by the issue @jessepearson is working on for the patch release. )

We should continue to use CLDR formatting for all prices through out the admin for consistency and clarity.
