### ISSUE TITLE
When payment failed for Giropay / sofort, got WSOD

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#2665]
Tested with wcpay 2.8.1.

1. Enable giropay and sofort payment method from wcpay settings page.
2. Purchase with giropay / sofort.
3. Fail the payment.
4. You will see this error:
```
Notice: Trying to access array offset on value of type null in /srv/users/user082cb71c/apps/user082cb71c/public/wp-content/plugins/woocommerce-payments/includes/payment-methods/class-upe-payment-gateway.php on line 466

Warning: Cannot modify header information - headers already sent by (output started at /srv/users/user082cb71c/apps/user082cb71c/public/wp-content/plugins/woocommerce-payments/includes/payment-methods/class-upe-payment-gateway.php:466) in /srv/users/user082cb71c/apps/user082cb71c/public/wp-includes/pluggable.php on line 1340

Warning: Cannot modify header information - headers already sent by (output started at /srv/users/user082cb71c/apps/user082cb71c/public/wp-content/plugins/woocommerce-payments/includes/payment-methods/class-upe-payment-gateway.php:466) in /srv/users/user082cb71c/apps/user082cb71c/public/wp-includes/pluggable.php on line 1343
```

Error thrown from [here](https://github.com/Automattic/woocommerce-payments/blob/2.8.1/includes/payment-methods/class-upe-payment-gateway.php#L466).

**Comment by vbelolapotkov** [comment]
cc @Automattic/heisenberg

**Comment by waclawjacek** [comment]
The problem seems to be caused by [`wp_safe_redirect( wc_get_checkout_url() );`](https://github.com/Automattic/woocommerce-payments/blob/664b40c84bb3660d3e5810fa0c3a86ca11a1888b/includes/payment-methods/class-upe-payment-gateway.php#L533) attempting a redirect by setting the `Location` HTTP header.

Since a PHP notice was displayed, headers were already sent and redirect cannot be performed, even though the notice itself seems harmless.

This is because [here](https://github.com/Automattic/woocommerce-payments/blob/664b40c84bb3660d3e5810fa0c3a86ca11a1888b/includes/payment-methods/class-upe-payment-gateway.php#L466) the code expects an array but receives `NULL`:

```php
$payment_method_details = $intent->get_payment_method_details();
$payment_method_type    = $payment_method_details['type'];
```
