### ISSUE TITLE
Additional notice needed before removing currency required for payment methods

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#2682]
Additional UPE payment methods have been added that require certain currencies to be available for them to work, such as Bancontact and giropay. When adding these methods, we will enable the proper currency for the merchant, but there's not a notice to the merchant before the currency is removed. 

Currencies can be removed via the trash/delete icon in the Enabled Currencies table, or via the checkbox list when clicking the Add currencies button. There is already a notice that displays via a modal when the trash icon is used, so that can be updated. If the currency is removed via the checkbox list it is instant, so we may want to either not allow removal in this fashion, or display a notice before removing currencies this way.

**Comment by jessepearson** [comment]
There was a Slack discussion about this here: p1629134085336100-slack-C01B8KNUYSW

My thoughts were to have a property  and method similar to this in the `MultiCurrency` class:

```
protected $dependent_currencies = [];

public function get_dependent_currencies() {
	return apply_filters( 'wcpay_multi_currency_dependent_currencies', $this->dependent_currencies );
}
```

The filtered property would be something along these lines:
```
$dependent_currencies = [
	[
		'currency'  => 'EUR',
		'dependent' => 'WooCommerce Payments',
		'reason'    => 'Used for UPE payment methods.',
	],
	[
		'currency'  => 'PLN',
		'dependent' => 'WooCommerce Payments',
		'reason'    => 'Used for UPE payment methods.',
	],
];
```

This would allow MC to check to see if the currency had a dependency somewhere else, including payment methods in WCPay, or anything outside of WCPay where another developer has tied in via the filter. From there, the notice of removing the currency could include information about the dependency.

**Comment by jessepearson** [comment]
Noting that I reached out to the architecture guild here: p1629380133051200-slack-C0208C3BXHP

**Comment by tpaksu** [comment]
Since the currency list is rendered via React, we need to append a notice component to each list-item, or the modal before user removes the currency, I think we should split this into two parts:

#### Multi-currency part

We need to be able to add notices with filters such as:

```php 
add_filter( 'wcpay_multi_currency_add_currency_notice_eur', function() {
    return __('This is used by Sofort, Giropay, P24, iDeal and Bancontact, so 
        removing this would prevent your customers from using those payment methods', 
        'woocommerce-payments');
});
```

Then on the React side, we can collect those strings via REST API (wp/data), or a global JS object, and display it inside a notice per currency.

#### UPE part

We can use the filter to add notices for each enabled currencies in the UPE code. If MC isn't enabled, the filters will run for nothing, so it won't cause any harm.

So we would do this in a method which will be ready for MC to be separated from WCPay.
