### ISSUE TITLE
[Checkout] Unable to show wcpay payment form on payment method change

### ISSUE THREAD

**Issue by debba** [Automattic/woocommerce-payments#2694]
Bug Description:

Unable to show wcpay payment form on payment method change in Checkout page.

Environment:

Woocommerce Version : WooCommerce 5.5.2
WooCommerce Payments - 2.8.3

PC:
Windows 10, Mac 10.14.6, Ubuntu 20.04
Tested on Firefox(Version 90.0,2)

Steps To Reproduce:
    
1.  As a customer add a product to the cart and go to checkout
2.  Select 'WooCommerce Payments', first time the payment form will be shown
3.  Select another payment method
4.  Back to 'WooCommerce Payments', the payment form it won't be shown

**Comment by jessepearson** [comment]
@debba I looked into this and wasn't able to replicate in Chrome or Firefox. The below is what I am seeing:

![Screen Capture on 2021-08-16 at 09-48-54](https://user-images.githubusercontent.com/4634416/129566433-7f3e10c3-4ea3-4cd8-8c65-d174d2de4fba.gif)

If I am not testing this properly, please let me know. Otherwise we would suggest conflict troubleshooting as outlined here: https://docs.woocommerce.com/document/how-to-test-for-conflicts/

**Comment by debba** [comment]
Hello,
thanks for replying.
Checking better now, I found the plugin which is responsible for this issue: WooCommerce Smart COD.

**Comment by jessepearson** [comment]
@debba Glad we could help 👍
