### ISSUE TITLE
UPE - Checkout with cart total under 50 cents

### ISSUE THREAD

**Issue by bborman22** [Automattic/woocommerce-payments#2700]
When trying to checkout with a cart total under 50 cents USD, UPE throws an error when trying to mount. This has been mentioned by a few merchants and they called out that this 50 cent limit should only be applied after shipping cost has been added in. Due to how UPE works though, we need to create the intent before we know the shipping costs which will cause this error. We will need to find a workaround for this issue so that it does not throw an error until shipping costs are calculated in to the total.

**Steps to Reproduce**
1. With UPE enabled and currency set to USD, create a product with a cost of 0.40 USD.
2. Go to checkout with just one of those products.
3. When the payments area begins the load it will throw the following error: `Error: Amount must be at least $0.50 usd`

![UPE-50cent-error](https://user-images.githubusercontent.com/68524302/128916275-8c3b5622-e3fa-4e4b-b08c-6b29bb05beb3.png)

**Comment by bborman22** [comment]
It should also be checked when using a non-USD currency to see when the lower price limit error occurs (basically when does currency conversion happen) and how best to catch it in that scenario as well.

**Comment by FangedParakeet** [comment]
@bborman22, in answer to your last question, [here is a list](https://stripe.com/docs/currencies#minimum-and-maximum-charge-amounts) of minimum values for their corresponding currencies. 

I'm trying to think how best to handle this scenario...We could round up the value to 1 when we load the UPE, if the total is greater than zero, but below the minimum threshold. Then if the value remains too low after shipping has been selected, presumably updating the intention with this invalid amount or confirming the intention after updating the amount would throw an error, which appears to be expected behaviour: the parent gateway will throw an error when confirming the payment if the amount is too low, so that appears acceptable to me.

**Comment by melindahelt** [comment]
Discussion at https://wordpress.org/support/topic/minimum-spend-error-message-appearing-before-delivery-is-inputted/#post-14755536 on how this error shuld only trigger after typing in the address. Currently it's triggering before adding in the address, which creates confusion for customers.

**Comment by bigjuju4fr** [comment]
Hello,

i also have the same error when using the woocommerce payments but the root cause is different. I am living in Germany and using EUR as currency. Please check the above screenshot. Could you please help ?

![image](https://user-images.githubusercontent.com/69798792/129269431-8d33d295-0b2b-43e9-9259-a3ab05be97cd.png)

Every personal information have been entered (postal adress, name and so on) and shipping fees have been calculated. The amount for this purchase is about 20 EUR. For every amount, i am also getting this error message.

If i am trying to revert to the old experience from the settings. the form is not loading and there is no error message and the placeholder for payment is remain empty.

At the moment this plugin is no use for me.
Thank you for your help.

Regards

**Comment by FangedParakeet** [comment]
@bigjuju4fr I think your error is actually related to Automattic/woocommerce-payments-server#1066. The issue here is that there is a payment capability for giropay or Sofort missing from your store's connected Stripe account. If you are able to manage your store's Stripe account, you can manually update these capabilities following [these instructions](https://stripe.com/docs/connect/dashboard/managing-individual-accounts#updating-capabilities), but from inside WooCommerce Payments, I do not currently believe there is a pathway for you to do this.

We are working with Stripe to backfill this capability for all connected accounts by region, which, since you mention you are based in Germany, could be completed for you as soon as by the end of today. You may be able to follow progress on the aforementioned issue; otherwise if you'd like more information regarding your specific store, I'd recommend getting in touch with our customer service team and opening a ticket, so that we can give your case some more personalised attention. Apologies for any inconvenience you've experienced already!

**Comment by pchapp01** [comment]
Hi, 

My business has been in a holding pattern since the new 'WooCommerce payments' was rolled out in Early August as most of my sales are less than 50c.

Roughly when could I expect a fix to be implemented? 

Thanks in advance.
