### ISSUE TITLE
WCPay Subscriptions phase 3: Documentation

### ISSUE THREAD

**Issue by chickenn00dle** [Automattic/woocommerce-payments#2818]
Epic for tracking documentation necessary for subscriptions feature.

We're tracking documentation in a spreadsheet/project thread. This issue is a placeholder for all that we need to document for MVP launch. 

We can add issues for individual docs/changes if that helps coordinate the work, but for now I'm treating the spreadsheet (and later P2) as the authority on this work. 

See also pbDlC7-o0-p2#comment-650 and paJDYF-2rf-p2

**Comment by chickenn00dle** [comment]
- Automatic Renewals: PCYsg-iAH-p2

**Comment by mattallan** [comment]
- Developer doc for third-party subscription extensions to add their features/compatibility code with WCPay Subscriptions

**Comment by chickenn00dle** [comment]
- Testing flows instructions ✅

**Comment by haszari** [comment]
Recent discussion of best practice for migrating between gateways (internal P2) (pbUcTB-nU-p2):

> What is the best process to migrate subscriptions over from another payment gateway to WC Pay?

As part of this epic we could look at whether we need a doc specifically on migrating subscriptions between different gateways, and specific guidance for switching to WC Pay. Related to migrating up/down from Subscriptions (pro) extension - #2868

**Comment by haszari** [comment]
We're tracking documentation in a spreadsheet/project thread. This issue is a placeholder for all that we need to document for MVP launch. 

We can add issues for individual docs/changes if that helps coordinate the work, but for now I'm treating the spreadsheet (and later P2) as the authority on this work. pbDlC7-o0-p2#comment-650

(also added this info to description)
