### ISSUE TITLE
WP Rocket is removing the credit card fields when UPE is enabled (early access)

### ISSUE THREAD

**Issue by diegocurbelo** [Automattic/woocommerce-payments#2823]
### Describe the bug

When using WP Rocket's `Disable WordPress Embeds` feature, the UPE Credit Card form fields are not loaded.

This `Disable WordPress Embeds` setting "prevents others from embedding content from your site, prevents you from embedding content from other (non-allowed) sites, and removes JavaScript requests related to WordPress embeds."

The actual error in the console is:
```
Uncaught TypeError: Cannot read property 'apiFetch' of undefined
at Object.<anonymous> (upe_checkout.js:1)
at n (upe_checkout.js:1)
at Object.<anonymous> (upe_checkout.js:1)
at n (upe_checkout.js:1)
at Module.<anonymous> (upe_checkout.js:1)
at n (upe_checkout.js:1)
at upe_checkout.js:1
at upe_checkout.js:1
```

### To Reproduce
- Enable `The new WooCommerce Payment checkout experience` in WC Pay
- Check `Disable WordPress Embeds` in WP Rocket settings

This only occurs when both WP Rocket's `Disable WordPress Embeds` and WC Pay's `UPE early access" are enabled. If either is turned off, it's fine.

### Screenshots
https://d.pr/i/eMamvx

### Additional context
- 4252138-zd-woothemes

**Comment by davipontesblog** [comment]
Updated the user, please let them know once this is addressed: 4412856-zd-woothemes

**Comment by selectedselections** [comment]
Reported again with another caching plugin here: 4412856-zen (wp super cache)

**Comment by zmaglica** [comment]
WP Rocket removed that functionality. More info can be found [here](https://github.com/wp-media/wp-rocket/issues/3773). I downloaded the latest WP Rocket version and the option that is shown on the video is not there.

**Comment by zmaglica** [comment]
I am going to close this ticket because WP Rocket removed this functionality.  Regarding the WP Super cache plugin, I installed it on my local environment with default settings enabled, and I didn't have any issues with payments fields. The payment fields rendered successfully. 

If the problem persists, make sure to tell the end user to update WP Rocket to the latest version. For WP Super cache plugin, if problem persists,  feel free to open another issue since this specific issue is not related to the mentioned plugin in this issue.
