### ISSUE TITLE
[GlobalStep] "Invalid payment method" error is displayed upon clicking "Delete" button twice on "Add Payment method" screen.

### ISSUE THREAD

**Issue by gglobalstep** [Automattic/woocommerce-payments#2865]
## Bug Description:
"Invalid payment method" error is displayed upon clicking "Delete" button twice on "Add Payment method" screen.

## Environment:
Woocommerce Version : WooCommerce 5.6.0
WooCommerce Payments - 3.0.0-test-2

PC:
Windows 10, Mac 10.14.6
Chrome(Version 92.0.4515.131) 
Firefox(Version 90.0.2)
Safari: v14.1.2

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins.
1. Upload and activate the WooCommerce Payments v3.0.0-test-2 plugin. 
1. Complete the setup wizard.
1. Complete the KYC flow.
1. Go to Store page and add any product to the cart.
1. Completing the checkout using any test card and save the card during checkout.
1. Go to "Payment Methods".
1. Click on "Delete" button twice.
1. Observe that "Invalid payment method" error is displayed.

## Actual Result:
"Invalid payment method" error is displayed upon clicking "Delete" button twice on "Add Payment method" screen.

## Expected Result:
Payment method should be get deleted without any error.

## Video:

https://user-images.githubusercontent.com/41110392/132382278-7ef89cd9-bcce-42a0-8c7c-31db314acf6b.mp4

**Comment by mgascam** [comment]
Hi there,

I started to work on this issue as part of my onboarding on the Team Pulsar but I believe this is not related to WC Payments so I am going to transfer to the WooCommerce repo.

My findings so far:

- When the user double-clicks in the 'Delete' cta, it fires multiple GET requests to `my-account/delete-payment-method/:payment_method_id`. Please note that all these requests will have the same payment_method_id

- The requests are handled by `delete_payment_method_action` in `woocommerce/includes/class-wc-form-handler.php`

- My understanding is that the first request is processed correctly and as a result the payment method is deleted. The problem seems to be when the next request, with the same payment_method_id, is handled. When we try to retrieve the token for the same payment_method_id, an error is thrown since it does not exist anymore.

![Markup on 2021-09-30 at 16:59:01.png](https://images.zenhubusercontent.com/6151eaf2cacd680dad2b3af4/1a37e8fa-a276-4ad3-a966-ccce718ea916)

**Comment by kalessil** [comment]
@mgascam, thanks for looking into the issue.

Any proposals on how this could be fixed? 
If we create a new issue for WC, mentioning a few options will not hurt at all (or if the fix is trivial, we can make a PR to address it as well).

**Comment by mgascam** [comment]
> @mgascam, thanks for looking into the issue !
> 
> Any proposals on how this could be fixed? If we create a new issue for WC, mentioning a few options will not hurt at all (or if a fix is trivial, we can make a PR to address it as well).

@kalessil thanks for having a look  

I'd tackle this issue from both frontend and backend:

On the backend, I was thinking that maybe we should not throw an error if the token is null, so I would remove the `is_null(token)` from the `if` clause. But I ignore if this can have implications, so I should test this option in depth.

On the frontend I think we should prevent the user to click more than once. Disabling or debouncing the cta could be an option here? I haven't checked the code but maybe I can find something

I am creating the issue on the public repo now, I am happy to add my thoughts to it and maybe jump in later. What do you think?

**Comment by kalessil** [comment]
@mgascam: sounds good. If we can make a PR to prevent double-clicking, that would be great - I'd say give it a try.

**Comment by mgascam** [comment]
I am closing this issue in favor of ["Invalid payment method" error is displayed upon clicking "Delete" button twice on "Add Payment method" screen.](https://github.com/woocommerce/woocommerce/issues/30862) in the woocommerce/woocommerce repo.
