### ISSUE TITLE
Implement an extension of WCS_Background_Repairer that can get status of the background process.

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#2908]
### Description
Implement a way to get the status of background process that can answer these questions:
- How do I know when it’s finished?
- How many items are still in progress?
- Has it stopped? Its been running for days.
- How long until it finishes?

We will be extending `WCS_Background_Repairer`.

**Comment by james-allan** [comment]
Thanks for creating this issue @shendy-a8c!

Will you be creating a new extended class (eg `xyz extends WCS_Background_Repairer`) and if so will that class live in WC Payments or WC Subscriptions?

While working on #2894 I realised that instead of checking if there is data to migrate, it would be easier to check if the migrators have data to migrate. 

Thats a long way of saying, I'll need some changes to the current `WCS_Background_Repairer` or to this new class enables checking if there's data to migrate. Either a public [`get_items_to_repair()`](https://github.com/woocommerce/woocommerce-subscriptions/blob/trunk/includes/upgrades/class-wcs-repair-line-item-has-trial-meta.php#L49) or a new public function that checks if the `get_items_to_repair()` return is empty.

**Comment by shendy-a8c** [comment]
> Will you be creating a new extended class (eg xyz extends WCS_Background_Repairer)

I think it makes sense to create a new class extending `WCS_Background_Repairer`.

> will that class live in WC Payments or WC Subscriptions?

I assume WC Payments under sub-branch of `feature/stripe_billing`. I'm still not clear about how we currently handle class definition conflict between WC Payments and WC Subscriptions, where to put new feature at, how to sync between the two, or is that part of base package project?

> While working on #2894 I realised that instead of checking if there is data to migrate, it would be easier to check if the migrators have data to migrate.

Hmm.. Is that enough? That'll work if migrator is guaranteed scheduled when downgrade / upgrade is triggered, ie when WC Subscriptions is activated / deactivated.

> Either a public get_items_to_repair() or a new public function that checks if the get_items_to_repair() return is empty.

Is a public method that returns boolean enough? Also, do you think this new subclass of `WCS_Background_Repairer` needs to be a singleton?

**Comment by james-allan** [comment]
> I think it makes sense to create a new class extending WCS_Background_Repairer.

👍 

> I'm still not clear about how we currently handle class definition conflict between WC Payments and WC Subscriptions, where to put new feature at, how to sync between the two, or is that part of base package project?

Sorry! I recall you asked this question somewhere but I don't think I answered it. It is part of the base package project but I can give you a brief explainer. 

The WC Subscriptions (plugin) will include a copy of the Subscriptions core package + additional functionality/features. 
WC Payments will include a copy of the Subscriptions core package. 

To avoid conflicts, only 1 instance of the core package will be loaded at once. The one included in WC Subscriptions will take precedence. 

So, if a store has WC Payments and WC Subscriptions (plugin) active - WC Payments won't load any of its subscriptions functionality and therefore won't load its copy of the base. If a store doesn't have WC Subscriptions active, then WC Payments will load its copy of the basic subscription functionality. 

So there won't be any file/class def conflicts since only 1 instance of subscription functionality will be loaded at once.

> where to put new feature at

So if this new class is added to WC Subscriptions core we will have access to it in WC Pay via the base, WC Subscriptions will have access to it as well. I don't really have a preference though. WC Subscriptions (plugin) may eventually want to add similar functionality to its background repairer/migrator classes but if that's the case, we can use this new WCPay class as inspiration. 

This is a long way of saying that I'm fine if we add the new class to WC Payments in the `woocommerce-payments/includes/subscriptions/` folder. This project will have a bunch of files so we should add a subdirectory to that folder something like `/data-migration/`

> Hmm.. Is that enough?

Yeah sorry, I wasn't very clear. No, it on its own won't be enough, will need the other functions too. I mean that I'll need a function that determines if there is data to migrate in addition to the functions which return the data migrations progress. Basically, I'll need a function that can be used like this:

```php
// The site upgrades, we need to check if there is data we need to upgrade.
// If this function returns true, we will schedule the migratory to start.
public function has_data_to_migrate () {

    // $this->upgrade_migrators is an array of WCS_Background_Repairer
    foreach ( $this->upgrade_migrators as $migrator ) {
        if ( $migrator->has_data_to_migrate() ) { // <- this is the new function
            return true;
        }
    }

    return false;
}

--------

class xyz extends WCS_Background_Repairer {

...

/**
 * Determines if this migrator has data it needs to migrate.
 */
public function has_data_to_migrate() {
   return ! empty( $this->get_items_to_repair() );
}
```

Because `get_items_to_repair()` isn't public, I can't check if the `WCS_Background_Repairer` has data it needs to migrate and that's 1 of the things I'll need. 

----

It might be best to just ignore me 😆 If you start on this, I can add the new function I'll need later. 

> Also, do you think this new subclass of WCS_Background_Repairer needs to be a singleton?

I don't think so since we will have a bunch of data migrators.

**Comment by haszari** [comment]
@james-allan  @shendy-a8c What should we do with this issue & PR - is it still relevant, or should we close?

**Comment by james-allan** [comment]
We can close this. As far I know we aren't looking to build a fully-fledged background upgrade/downgrade process.
