### ISSUE TITLE
CI: Fix unit tests for PHP 7.0

### ISSUE THREAD

**Issue by vbelolapotkov** [Automattic/woocommerce-payments#2970]
Follow up from #2945 

### Describe the bug

There are issues with loading dependencies in unit tests for combination of WC 4.4, WP 5.4, PHP 7.0.

### To Reproduce

1. Update compatibility.yml file to run tests with combination above.
2. Push PR.
3. See tests are failing.

### Actual behavior

Tests fails see failed checks in #2945 e.g. [this one](https://github.com/Automattic/woocommerce-payments/runs/3675736404)

### Expected behavior

Ideally we should be able to run tests with it as well.

### Additional context

Two ways to fix it:

1. Add imports manually to bootstrap.
2. Add some autoloader for PHPUnit 6.5.14 (not sure if there is a solution for that).

Slack thread: p1632307719018700/1632161800.465400-slack-CGGCLBN58

**Comment by jrodger** [comment]
Since WooCommerce will be increasing the [minimum version of PHP to 7.2](https://developer.woocommerce.com/2022/01/05/new-requirement-for-woocommerce-6-5-php-7-2/), we're not going to spend time getting this going in our CI pipeline.

We have added to our testing notes so that we do at least some of our manual testing on the minimum version of PHP.
