### ISSUE TITLE
Flag not rendering in preview on page load for Gutenberg Block Widget

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#3004]
### Describe the bug

While working on a fix for #3003, I noticed a small visual issue affecting the widget *preview* for the Gutenberg Block Widget (note that the actual widget on the site works as expected, this relates to previewing the widget in `Appearance -> Widget` or while editing a page using the Gutenberg editor.

It seems that the flag does not render on first page load, even when it is enabled in the settings. For example, this is what the page looks like on first load. Notice that it looks like the SVG for the flag is getting added (rather than the emoji flag which is expected):

<img width="1189" alt="Screenshot 2021-09-28 at 11 21 35" src="https://user-images.githubusercontent.com/11770181/135071531-8f6f6dec-f421-44ef-948f-31451cae9dcd.png">

If I use the settings pane on the right hand side of the screen to toggle 'Display flag' off and on, the flag will start to display correctly in the preview:

<img width="1175" alt="Screenshot 2021-09-28 at 11 21 43" src="https://user-images.githubusercontent.com/11770181/135071630-e7f652b4-d0cb-44c4-a54e-6a5a8c014f78.png">

### To Reproduce

1. Go to `Appearance -> Widgets`
2. Add the new "Currency Switcher Block" widget, click on the widget to open the settings, and make sure `Display Flags` is enabled on the settings pane on the right. Save your changes using the button on the top right corner of the screen.
3. Verify the flag displays correctly in the preview.
4. Refresh the page, verify the flag is not displayed in the widget, even though `Display Flags` is enabled in the settings.
5. Toggle the `Display Flags` setting off/on. Verify the flags now display correctly.

### Actual behavior

The flag does not render on first page load in the preview, even when Display Flags is checked.

### Expected behavior

The flag should render.

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Comment by malithsen** [comment]
This looks like a side effect of https://github.com/Automattic/woocommerce-payments/pull/2186 
Enabling `print_emoji_detection_script` converts emoji's to images. Looking at the description of the above issue, this behavior seems to be an acceptable drawback. cc @ismaeldcom

**Comment by ismaeldcom** [comment]
@malithsen Yes! It's caused by `print_emoji_detection_script`. But like we only need to enable emoji compatibility in the MC settings page (for now), maybe we could fix this issue in an easy way. Apart from that, the behaviour of this issue is a bit strange, it should load fine even with the compatibility script if it loads later.

**Comment by malithsen** [comment]
@ismaeldcom Had another look at this after a while. You're right, limiting the above script to MC settings page seems like a good option. It works the second time because `options` gets re-rendered when toggling the "Display Flag", which overrides the initial Unicode-to-img conversion done in the compatibility script.  I opened #3605
