### ISSUE TITLE
Remove duplicative task list item for additional payment methods

### ISSUE THREAD

**Issue by LevinMedia** [Automattic/woocommerce-payments#3060]
the payment methods early access task list item is duplicative with the inbox note, let's remove the tasklist item in favor of the inbox note. 

<img width="1282" alt="Screen Shot 2021-10-06 at 7 54 18 PM" src="https://user-images.githubusercontent.com/4500952/136313472-fbb48ee4-b54e-402c-87b7-c9e1730bc57d.png">

cc: @elizaan36

**Comment by elizaan36** [comment]
hey @a-danae 👋 
Wanted to check in and inquire on what's the status of this issue (I believe you're working on both https://github.com/Automattic/woocommerce-payments/pull/3134 and https://github.com/Automattic/woocommerce-payments/issues/3129

Removal of these two tasks in the extended task list is a dependency for our current work on a new task here: https://github.com/woocommerce/woocommerce-admin/issues/7720

Since the new task we'd like to implement in WC Admin will only appear once WCPay is installed, we risk a massive amount of user confusion with three similarly worded tasks. 😆 Thanks!

cc @mattsherman @pmcpinto

**Comment by a-danae** [comment]
Hey @elizaan36! 🙂 

I only have to adjust the tests and it would be ready to go. I'm expecting to finish https://github.com/Automattic/woocommerce-payments/pull/3134 tomorrow, and #3129 this week. Sorry for missing this ping btw, and thanks for the heads up!
