### ISSUE TITLE
UPE element throws an error when website url is not provided while onboarding

### ISSUE THREAD

**Issue by naman03malhotra** [Automattic/woocommerce-payments#3078]
### Describe the bug

If a merchant decides to add a description instead of the website URL while onboarding, and then tries to checkout with UPE, they will see the following error.
![image](https://user-images.githubusercontent.com/15019298/136576366-14020374-b658-4829-a2b6-1f458e5cfa79.png)

```
Invalid value for elements.create('payment'): business.name should be a string. You specified: null.
``` 

### To Reproduce

1. Onboard a new merchant
2. Enter description instead of website URL in the form
3. Complete onboarding.
4. Add some items in the cart and try to checkout with UPE, you should observe the same error.

### Additional context
p1633648396479600/1633385342.439400-slack-C02BHNRN6R1

**Comment by mdmoore** [comment]
@naman03malhotra I haven't been able to reproduce this by using a description instead of a URL. It doesn't appear that setting/field is in use since `business.name` is actually referencing `accountDescriptor` which is the account statement descriptor setting. 

https://github.com/Automattic/woocommerce-payments/blob/c95906d5ce1f2fd05df2bb3ccdf8ade86dbfb5d5/includes/payment-methods/class-upe-payment-gateway.php#L574

Let me know if you're still able to reproduce this. Business name isn't required when creating a payment intent, so perhaps we could remove it.
