### ISSUE TITLE
Clicking on "publish" multiple times for variable subscriptions creates multiple products in Stripe

### ISSUE THREAD

**Issue by a-danae** [Automattic/woocommerce-payments#3192]
### Describe the bug

Multiple products get created in Stripe for the same WC product when clicking multiple times on the "Publish" button for variable subscriptions.

### To Reproduce

1. With Subscriptions enabled on WCPay, go create a new product
2. Select "Variable subscription". Add an attribute and mark it to be used for variations https://d.pr/i/JpfufI 
3. Create variations for the attributes. Add a price and frequency for them https://d.pr/i/KL0DBf
4. When publishing the product, click on "Publish" three times
5. Go to the "Products" screen in Stripe, and notice there are three products with their variations for the single product you published in WC. If you delete the product in WC, only one instance of the product with its variations gets deleted.

### Actual behavior

Multiple products get created in Stripe instead of a single one when clicking on "Publish" multiple times in WC.

### Screenshots

Video of the behavior https://d.pr/v/x5CJBM

### Expected behavior

I'd expect only a single product with its variation to be created on Stripe, even when clicking on "Publish" multiple times. The delay between clicking on "Publish" and the button having a "loading" state also happens with non-subscription variable products, so I wouldn't expect that to be different.

### Desktop (please complete the following information):

* OS: macOS
* Browser: chrome
* Version: 94.0.4606.81

**Comment by chickenn00dle** [comment]
Thanks for the bug report @a-danae 💯 

I was able to replicate this on my end as well. Digging into the issue, it looks like each click of the publish button for variable subscription products triggers both the `save_post` and `woocommerce_save_product_variation` hooks we register to here: https://github.com/Automattic/woocommerce-payments/blob/7b9a4c4ed5a8926fab291b564d4828eef23d56a8/includes/subscriptions/class-wc-payments-product-service.php#L503-L504

The one triggered by `save_post` looks to be correctly filtering out repeated attempts to schedule the creation of new products, but the `maybe_schedule_product_create_or_update` hook doesn't. My guess for why this might be happening is this hook fires in response to an ajax call while saving variations, and so they are all creating in isolation? I'm not too sure yet, but will begin working on a PR for this shortly 👍

**Comment by james-allan** [comment]
Closing this in line with a discussion we had in Helix.

For completeness, we agreed that this is a pretty extreme edge case. Since the original issue was filed, we discovered that this only impacts users of Chrome, and hitting the publish button many, many times is a pretty unlikely user interaction.

In terms of impact, even if you found yourself a victim of this, the impact would be to have multiple products in Stripe that are unused and unlinked to any products in WC. That's a very low impact given it will be invisible to merchants. With that in mind, and with the possible approaches discussed on #3509, we've decided the tradeoffs aren't worth fixing this edge case. 

 _Internal ref:_ pdjTHR-sb-p2#comment-620
