### ISSUE TITLE
Change the "Automatic Recurring Payments" tooltip text

### ISSUE THREAD

**Issue by aprea** [Automattic/woocommerce-payments#3234]
### Description
A tooltip appears in the "Automatic Recurring Payments" column next to WooCommerce Payments on the **WooCommerce → Settings → Payments** page.

When hovered, it reads:
> Supports automatic renewal payments with the WooCommerce Subscriptions extension.

This is incorrect when the WooCommerce Subscriptions extension is **not installed**. i.e. WCPay itself will power the subscriptions functionality via Stripe Billing.

<img width="1068" alt="Screen Shot 2021-09-24 at 11 19 34 am" src="https://user-images.githubusercontent.com/1527164/134604955-913f1566-4cfb-45ea-975a-82eaa4a2ead7.png">

### Acceptance criteria

* Remove the tooltip next to WooCommerce Payments on the **WooCommerce → Settings → Payments** page if WooCommerce Subscriptions is not installed.

### Testing instructions

Switch to the `feature/stripe_billing` branch, then:

**Scenario 1 - WooCommerce Subscriptions not installed**

1. Ensure WooCommerce Subscriptions is not installed.
2. Navigate to **WooCommerce → Settings → Payments**.
3. Hover the checkmark icon in the "Automatic Recurring Payments" column next to WooCommerce Payments.
4. Observe no tooltip is shown.

**Scenario 2 - WooCommerce Subscriptions installed and active**

1. Ensure WooCommerce Subscriptions is installed and active.
2. Navigate to **WooCommerce → Settings → Payments**.
3. Hover the checkmark icon in the "Automatic Recurring Payments" column next to WooCommerce Payments.
4. Observe a tooltip is visible and reads "Supports automatic renewal payments with the WooCommerce Subscriptions extension."

**Comment by mattallan** [comment]
Hey all 👋 
I was just looking at the PR changes for this issue and I was thinking of what options we have for approaching this:

1. Remove the tooltip when the Subscriptions extension isn't installed
2. Keep the tooltip, but re-word it when the Subscriptions extension isn't installed.
   - Something like: "Supports automatic renewal payments with Subscriptions powered by WooCommerce Payments."
3. Change the wording so that the tooltip works for all cases (extension or no extension)
  - Some options:
     - "Supports automatic renewal payments with Subscriptions."
     - "Supports automatic renewal payments."

I'm kinda in favour of keeping it simple and going with number 3 to avoid having to juggle whether WC Subscriptions plugin is active in Core, but I'm keen to hear what others think :)

**Comment by a-danae** [comment]
Option 3 sounds better to me as well. I didn't see other instances in the core where we checked whether WC Subscriptions was active, so I'm in favor of keeping the core plugin-agnostic. Especially for something small like this that could be solved by rephrasing a string. Just my 2c 🙂

**Comment by haszari** [comment]
See also #3402 - there are some other bits of UI we should tweak.

**Comment by james-allan** [comment]
Closed via #55

**Comment by james-allan** [comment]
wait nvm this is the wcpay issue. 🤦‍♂️

**Comment by shendy-a8c** [comment]
Closed by https://github.com/Automattic/woocommerce-payments/pull/3550.
