### ISSUE TITLE
Stripe localization not working with Weglot translation plugins

### ISSUE THREAD

**Issue by kantsverma** [Automattic/woocommerce-payments#3390]
### Describe the bug

I am using the https://weglot.com/ plugins to translate the website its working fine for everything except the Credit Card Section on the checkout page it's loading from Stripe using iframe and that's why it's not able to translate. There is feature to translate page wise using Visual Editor to translate the content but Stripe CC section i not loading even on that due to CORS original issues.
  
### To Reproduce

1. Go to Click over here https://cammo.fr/
2. Click on Add some product on the cart and then go to checkout 
3. On the checkout page you can see the Credit card section on payment is not translating to English and French is the default so its working fine for that

### Actual behavior

Instead Stripe support the localization https://stripe.com/docs/payments/payment-element  so it should work with the Woocommerce as well 
### Screenshots

https://prnt.sc/1zvpxzl

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### Additional context

![image](https://user-images.githubusercontent.com/6929043/142161538-92d0df8f-50e6-4f09-ad67-63a26affeefc.png)

**Comment by ismaeldcom** [comment]
Hi @kantsverma! I see that you already solved the issue, after testing your site:
<img width="408" alt="Screenshot 2021-11-18 at 13 42 57" src="https://user-images.githubusercontent.com/7670276/142417723-71064a18-69d9-45d9-b1a8-8b5fc530edd0.png">

There is not much we can do on our side. Because like you already know, Stripe Elements uses an iframe. In this case, Weglot should support this behaviour and provide a solution for those cases.

I'm going to close this issue, but feel free to reopen it again or create a new one if you have any other issues in the future 🙂

**Comment by kantsverma** [comment]
Hi @ismaeldcom 

Yes, issues are resolved but not using the proper way by following the Weglot or Stripe documentation. I used the woocommerce hooks to switch the site language on the change languages of Weglot  Buttons.
