### ISSUE TITLE
Unable to checkout with UPE using card when using Arabic as website language

### ISSUE THREAD

**Issue by jessy-p** [Automattic/woocommerce-payments#3547]
### Describe the bug
When trying to checkout using a card, got the error "Invalid integer: 06"

### To Reproduce
1. Set up a test WooCommerce store for the US, installed WooCommerce Payments, and enabled UPE.
2. In WordPress Settings -> Website Language, set it to Arabic.
3. Try to checkout using a credit card by providing US address and test card payment details.

### Actual behavior
Checkout fails with error "Invalid Integer: 06" 
The relevant part of error response:
   ```
 "code": "parameter_invalid_integer",
    "doc_url": "https://stripe.com/docs/error-codes/parameter-invalid-integer",
    "message": "Invalid integer: ‎06",
    "param": "payment_method_data[card][exp_month]",
```

### Screenshots
![image](https://user-images.githubusercontent.com/32092402/146746435-331cdd1c-e4d7-488d-a23c-61b9a51dbfb5.png)

### Expected behavior
Able to checkout using the card payment method in every language setting.

### Additional context
1. Works when UPE is not enabled.
2. Works when I switch back to English as the Website Language.

**Comment by malithsen** [comment]
Had a brief look at this, the request UPE Element makes has the RTL mark (<200e>) in the payment data fields, which I guess is triggering the error

**Comment by brianyu28** [comment]
Looked into this one as well. Per @malithsen's comment, looks like the card number, month, and date fields all get the `&lrm;` (left-to-right mark) prepended to each field's value. This seems to happen in the UPE whenever the `dir` attribute is set to `rtl` (which is set on the `html` tag in `language_attributes`).

We can "fix" the problem by adding `dir="ltr"` to the `wcpay-upe-element` element, but that's not a perfect solution because then the labels on the input fields end up being left-aligned instead of right-aligned. But otherwise I'm not sure if this is something we have control over, might need to be a change on Stripe's end.

**Comment by achyuthajoy** [comment]
@jessy-p I'm not able to replicate this problem on my end. Followed the steps mentioned and tried checking out with Card & SEPA Debit. Checkout works as expected.

Not sure whether I'm missing anything.

**Comment by jessy-p** [comment]
Works now, checking with Stripe if its a fix from their end.

**Comment by jessy-p** [comment]
Closing the issue, retested and working fine, was fixed by Stripe.
