### ISSUE TITLE
Apple Pay verification fails when using an alternate folder structure 

### ISSUE THREAD

**Issue by nicdwilson** [Automattic/woocommerce-payments#3565]
### Describe the bug

There is a problem with Apple Pay verification when using a different folder structure. (Bedrock for example – https://roots.io/bedrock/)

The variable $domain_name is taken from the site_url, which may contain a sub-directory, in this [line](https://github.com/Automattic/woocommerce-payments/blob/cbf5b9e441960058fd33eb7c3542d9586daede6c/includes/class-wc-payments-apple-pay-registration.php#L69)

### To Reproduce

Install WordPress on an alternate folder stucture, such as `www.example.com/wp`

### Actual behavior

An alternate folder structure results in the error:

`You passed an invalid URI for your domain name. It must not contain a port, path, query, or fragment, and should be just a bare top-level domain, such as https://www.example.com`

### Expected behavior

I would expect the domain name to be passed correctly without port, path, query, or fragment

### Additional context

Raised in forums [here](https://wordpress.org/support/topic/apple-pay-invalid-uri-with-custom-folder-structure/#post-15186119).

**Comment by jrick1229** [comment]
Seen here as well: 33478460-hc

**Comment by rashedripon** [comment]
[Another user experienced the same](https://wordpress.org/support/topic/apple-pay-invalid-uri-with-custom-folder-structure/#post-15504693).

**Comment by stuartduff** [comment]
Reported here 4909006-zen

**Comment by stuartduff** [comment]
Reported here: 4936227-zen

**Comment by Phil13-AT** [comment]
same problem found

**Comment by RemonRoben** [comment]
I had the same issue.
My fix was:
Changing the get_site_url() with $_SERVER['HTTP_HOST']
On the line# 69 of woocommerce-payments\includes\class-wc-payments-apple-pay-registration.php

**Comment by kaushikasomaiya** [comment]
Reported at 35299568-hc

**Comment by ironicmoka** [comment]
I tried to speed up things a little bit with a [pull request](https://github.com/Automattic/woocommerce-payments/pull/4206), I hope I did it right and that can help.

**Comment by DevGregory** [comment]
Has anyone heard from WooCommerce regarding a fix for this? I'm using a subdomain and facing issues with Apple Pay domain verification. Example: store.example.com

**Comment by darcie** [comment]
5205731-zen reported this as well.

**Comment by RemonRoben** [comment]
> Has anyone heard from WooCommerce regarding a fix for this? I'm using a subdomain and facing issues with Apple Pay domain verification. Example: store.example.com

* temporary fix *
Changing the get_site_url() with $_SERVER['HTTP_HOST']
On the line# 69 of woocommerce-payments\includes\class-wc-payments-apple-pay-registration.php

**Comment by ricardo** [comment]
This should be fixed in the next WooCommerce Payments release - 4.3.0

**Comment by csmcneill** [comment]
5707272-zen is reporting this issue.

- WCPay version: 5.0.1
- Multisite with subdirectories
- Store is under the `/books/` subdir but Apple Pay is trying to find the file at the host directory.
- A file _was_ created at the host directory—kind of. Instead of hosting it at `.well-known/apple-developer-merchantid-domain-association` it was hosted at `.well-known/apple-developer-merchantid-domain-association/apple-developer-merchantid-domain-association`

**Comment by ricardo** [comment]
The [PR](https://github.com/Automattic/woocommerce-payments/pull/4206) closing this issue fixes which domain is passed on to Apple. It previously sent the URL with a subfolder, but now sends the root domain URL for verification.

It doesn't fix _where_ the domain association file is hosted. If it's a subfolder installation, it may not be possible to automatically host it in the root of the domain, so this may require manually uploading the file, e.g through FTP. - We provide a link to troubleshooting docs when domain verification fails.

> it was hosted at .well-known/apple-developer-merchantid-domain-association/apple-developer-merchantid-domain-association

@csmcneill This looks weird. Maybe the user tried to upload it manually, but ended up with a different folder structure? Otherwise, can this be reproduced?

**Comment by csmcneill** [comment]
@ricardo I haven't been able to reproduce this (I spent some time using WCPay on multisites last week for a workshop), but I wanted to log the interaction here just in case other users have a similar issue down the line. It's very possible that the user tried to add this manually and messed things up 😅 

**Edit**: The user was able to resolve this by relocating the file via SFTP.
