### ISSUE TITLE
Add information to the "Capture Later" settings that only card payment method will be enabled with this setting.

### ISSUE THREAD

**Issue by jessy-p** [Automattic/woocommerce-payments#3567]
### Description
If a user has enabled UPE and added additional payment methods and then enables "Authorization and Capture Later",  only the card payment method is shown and other payment methods disappear. We should add this information in the settings to avoid confusion.

### Acceptance criteria
It is clear to the user that enabling "Authorization and Capture Later", would allow only card payment method in checkout.

### Testing instructions
1. Enable UPE and add new payment methods that appear in checkout
2. In Payments -> Settings, enable "Authorization and Capture Later"

### Dev notes
This issue can be fixed once Stripe releases a feature to attach the capture later setting to each payment method, slated for April 2022.

### Additional context
https://wordpress.org/support/topic/update-3-4-payment-method-disapear-if-authorization-checked/

**Comment by aheckler** [comment]
4658483-zen

**Comment by cesarcosta99** [comment]
For reference, [the design](https://www.figma.com/file/Igkr3nOx0UoGDlHrsJ4eux/%5BStripe%5D-Universal-Payment-Element-(UPE)?node-id=1496%3A82905) specifies we should display a modal asking the user to confirm they really want to enable manual capture.

When manual capture is enabled, the payment method list should looks like this:
![image](https://user-images.githubusercontent.com/10233985/148553403-f792bc97-53a8-4e7e-a0f0-e55ec06c6b22.png)

**Comment by jbordonado** [comment]
It was mentioned that Stripe would release a change in April 2022 that would make it possible to specify capture_method (automatic or manual) per payment method type (card, bancontact, eps, ...).
I asked about it in the relevant thread and they replied that it should be possible (while linking to an example with "card" payment type). 
It turns out it is not released yet, because I tried the following:
- enable the setting "capture later" (i.e. `capture_method = manual` at the root level of the PaymentIntent request)
- specify `capture_method = automatic` at the payment method level for all the types except "card"

And it gave me the following error: `The following payment method types ["bancontact", "eps", "giropay", "ideal", "sofort", "p24"] can only be used with PaymentIntents that have capture_method=automatic. Please retry by creating a PaymentMethod with capture_method=automatic. (invalid_request_error)`

I asked that they check again on the status of this change here: p1650007877645699/1631891076.182900-slack-C9976E5MJ

Depending on their answer, we have several possibilities:

- The change is to be released very soon

1. In case of "capture later" setting enabled, specify `capture_method: automatic` for the additional payment methods so that they all can be displayed and used on checkout. This means the design of the Settings page should be updated to reflect that the "capture later" setting is on a "best effort basis", i.e. we capture later if possible ("card" payment method), otherwise it fallbacks to an automatic capture (additional payment methods)
2. We decide anyway that we don't want to show any additional payment methods (UPE) in case the "capture later" setting is enabled, since those payment methods don't support the manual capture for now and they are not coherent with the setting that the merchant enabled --> follow the initial plan (see design mentioned above)

- The change is not to be released any time soon

Follow the initial plan (see design mentioned above): confirmation modal when enabling the "capture later" setting + greyed out additional methods on the Settings screen (to make sure the merchant is aware that these won't be displayed on checkout page)

**Comment by jbordonado** [comment]
Based on the latest answers from Stripe, capture later is only supported by the following payment methods: card, klarna and afterpay.

We have 2 solutions:

- Option 1

We just make some design changes to show that the additional payment methods won't be active (available at checkout), as it was mentioned in this comment: https://github.com/Automattic/woocommerce-payments/issues/3567#issuecomment-1007425305

That is: a modal to confirm the activation of the manual capture + greyed out other payment methods once it is enabled

- Option 2

When capture later is enabled, we can create a payment intent such as:
- card payment method is shown at checkout and will capture later
- other payment methods are also shown at checkout and will capture automatically

We can do that by setting capture_method=automatic at the root level and override it only for the 'card' payment method in the PaymentIntent request to Stripe.

In that case, we would need a design proposition to explain the expected behaviour to the merchant whe he enables the "capture later" setting.

------
I'm moving the issue to the Product Review pipeline so that we can reach a decision on this topic.

**Comment by RadoslavGeorgiev** [comment]
Let's proceed with option #1 for now, and when done, keep option #2 open for design discussions.
