### ISSUE TITLE
Place order button doesn't translate

### ISSUE THREAD

**Issue by ryanr14** [Automattic/woocommerce-payments#3619]
This came from 4672395-zen, but it looks like the Place order button doesn't translate while seemingly the rest of WooCommerce Payments does? I tried using both French and Spanish and didn't have any luck.

<img width="617" alt="image" src="https://user-images.githubusercontent.com/867748/149059953-029de210-87c7-4340-a327-d5503d9a7dff.png">

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/867748/149059969-33fac8e6-373e-413d-a2c9-97423ac8fd19.png">

**Comment by RadoslavGeorgiev** [comment]
@ryanr14 I tried to recreate the issue. After switching the language initially, I did not see the translated button, but after heading to WP Admin > Updates, and updating translations, the button got translated:

![image.png](https://images.zenhubusercontent.com/5f2d57d80f11ae56d6a5daa8/1f1a9502-0fcd-44aa-8e68-9c0c72ffa003)

What I see untranslated is the personal data processing warning, but that's just because it has not been translated yet. I verified that the text is translatable and uses the `woocommerce` textdomain, meaning that core might need further translations, but that is not an issue with the code.

Closing this issue, as we have not been able to confirm it, and there have been no further reports.
