### ISSUE TITLE
MultiCurrency Analytics queries need to be optimised

### ISSUE THREAD

**Issue by daquinons** [Automattic/woocommerce-payments#3651]
### Describe the bug
The Analytics for MC are performing some very expensive instructions that are hard to handle for stores with bigger data needs.

See context here p1642420573036800/1642197321.014500-slack-CGGCLBN58

We need to optimise the instructions found [here](https://github.com/Automattic/woocommerce-payments/blob/d619c4d5464899ba36cb187f8cfc7eebe7615238/includes/multi-currency/Analytics.php#L237-L243)

**Comment by RadoslavGeorgiev** [comment]
Asked for status here: p1665052811192039/1642197321.014500-slack-CGGCLBN58

**Comment by dmallory42** [comment]
I was asked by @daquinons to add a bit more context to this issue as it may effect how it is estimated.

The reason that these conversions need to happen in the SQL queries is to support showing calculations for order amounts in the correct currency. As discussed in #4632, we modify the analytics queries to see if we need to perform currency conversions on the figures. 

The `wp_wc_order_stats` table expects all data to be stored in the store default currency, which we do by using a hook at the time of order ([src](https://github.com/Automattic/woocommerce-payments/blob/eefed9832911aa4953edb3c2b5a2c8f22e05cb80/includes/multi-currency/Analytics.php#L194)), however the data stored in `wp_postmeta` is also used by some of the analytics queries such as calculating summary totals, and this data is stored in whichever currency the order was placed in.

This means we need to add joins to get the conversion rate used at time of order for each order, and use `CASE WHEN` statements to see if a conversion needs to be performed or not.

I think the only way to improve performance here would be to completely change the approach being used, which is difficult to do because of backwards compatibility. We are slightly limited here because the only thing we can do without modifying Core code is to hook into the queries to modify them, or hook into the frontend JS (perhaps we could move some of the computation to this side, but we'd still need to perform the computation).

The new Custom Order Tables (fix implemented in #4632) will help here, because it means the table that is being joined on each query is much smaller (previously, we'd join on the `postmeta` tables). 

My feeling here is that this issue could be explored more, but there's likely not going to be any easy/quick wins unfortunately. In general, the performance is acceptable but seems to gradually degrade depending on the size of the store. For example, with MyForexFunds we ended up needing to disable the queries because they were so computationally expensive. Hopefully, COT will already be providing improvement here, but we probably will need to think about this more at some point.

**Comment by RadoslavGeorgiev** [comment]
Let's validate this once custom order tables have been rolled out.

**Comment by dwainm** [comment]
Mentioned in slack, causing issues for a high volume merchant: p1674024754648289-slack-CGGCLBN58

**Comment by dwainm** [comment]
Optimization work has already started in two important areas. I'm closing this in favor of these two issues: 

https://github.com/Automattic/woocommerce-payments/issues/6852
https://github.com/Automattic/woocommerce-payments/issues/6814
