### ISSUE TITLE
Disputes export: dispute curency is missing in the exported file

### ISSUE THREAD

**Issue by kalessil** [Automattic/woocommerce-payments#3689]
As per the description.

**Comment by KarlisJ** [comment]
### What's happening

We're using frontend functions
```
downloadCSVFile(
	generateCSVFileName( title, getQuery() ),
	generateCSVDataFromTable( csvColumns, csvRows )
);
```
to perform the download. The resulting CSV doesn't contain Currency because `csvColummns` and `csvRows` are created from table data which doesn't contain Currency as we're not displaying currency in the table. 

Technically, we could add Currency to the export as JS receives Currency in the response from the backend. However, it would create inconsistency between what the user sees in the table and what he gets in export. 

---

The same problem is true for Transactions export (as we're not displaying currency we aren't including it in export as well) but it's a less significant problem there because in most cases export is not generated in JS.

For transactions, we're using the same JS functions only if the table contains all records ( there's only one page). In most cases, there is more than 1 page of results and we're hitting a dedicated endpoint that enqueues job to send full export. 

In this (backend generated) report we are including significantly more fields (including currency) as well perform some formatting for numbers depending on the currency. 

---

I see a deeper issue here, that we're providing 2 different reports but the user doesn't have the option to choose from which one is used. We could fix the issue of missing currency rather simply by adding it to the export that we're generating now but in the long run, I see JS function as a quick win for developers but a huge loss for merchants as they are getting limited reports. 

IMHO, we should ditch the JS-generated reports and always hit a dedicated endpoint that enqueues proper full reports. For transactions, this wasn't a big issue as the table quickly grows over the default page size of 25, but for disputes, there should be more confusion about the differences in exports. 
(would be great to check the actual numbers from production DB by running `SELECT stripe_account_id, count(*) as count from <disputes/transactions-tables> GROUP BY stripe_account_id ORDER BY count DESC`)

**Comment by kalessil** [comment]
Fixing the existing JS-based export sounds good - if there is inconsistency with listing and export, that is aligned with transactions, so go for it.

> ditch the JS-generated reports and always hit a dedicated endpoint that enqueues proper full reports

it was a request to move over onto server-side export generation, as transactions export does now, so it'll be a new issue at some point (one of the next sprints).

**Comment by KarlisJ** [comment]
> if there is inconsistency with listing and export, that is aligned with transactions, so go for it.

Not sure I understood this line. 
1. Should we also update the JS-generated export for transactions to include currency?
2. Is that ok to include disputes currency only in export but not in the table?

**Comment by kalessil** [comment]
> Should we also update the JS-generated export for transactions to include currency?
Nope, transactions export already has currencies fields AFAIK

> Is that ok to include disputes currency only in export but not in the table?
Yes
