### ISSUE TITLE
Flags doesn't render on Windows using Chrome for the Currency Switcher Widget

### ISSUE THREAD

**Issue by deepakpathania** [Automattic/woocommerce-payments#3749]
### Describe the bug

The currency switcher widget shows country flags along with the currency which doesn't render properly on Windows using Chrome, the same works as intended on Windows using Firefox and Mac using Chrome. 

On mac using Chrome it looks like:
![Screenshot 2022-02-04 at 2 36 59 PM](https://user-images.githubusercontent.com/68396823/152502017-0c53d65e-eded-400e-b6f6-904c43964704.png)

On Windows using Chrome it looks like:
![screenshot](https://user-images.githubusercontent.com/68396823/152501846-7d9766b2-4a9e-4598-ac23-924db25e5827.PNG)

### To Reproduce

1. Go to Pages->Add new->Add block
2. Select currency switcher.
3. Toggle the `Display flags` option in settings.
4. Notice on windows using chrome the flag doesn't show, published page [here](https://screeching-potter.jurassic.ninja/with-storefront-theme/) with just that for reference.

### Desktop (please complete the following information):

* OS: [e.g. iOS] MacOS Big Sur v11.4
* Browser [e.g. chrome, safari] Chrome
* Version [e.g. 22] 97.0.4692.99

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### Additional context

Reported here: p1643726477526619-slack-C011ENB20Q1

**Comment by ismaeldcom** [comment]
It's a known issue and the reason why we added [`... in supported devices` here](https://github.com/Automattic/woocommerce-payments/commit/05a08fe9f4d0e4c2cd9429d2224fc9556ed12962). The only solution to display flags in not supported devices will be creating a custom select element, but we (included design team) decided that it was not worth the effort.

**Comment by deepakpathania** [comment]
@ismaeldcom Could we mention this somewhere so that GS doesn't report this as an issue again for future testing cycles?

**Comment by ismaeldcom** [comment]
Sure! But I wonder where it could be a good place. Is there a wiki page or P2 that GS checks for every report?

**Comment by deepakpathania** [comment]
Not sure, maybe the [critical flow section ](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#multi-currency-block-widget-for-currency-switcher)that they use for this flow could be used.

**Comment by ismaeldcom** [comment]
That sounds like a good place, thanks for pointing it out. Added:
<img width="916" alt="image" src="https://user-images.githubusercontent.com/7670276/169821020-43608006-94e1-45b4-afb4-970b8353b4f0.png">

**Comment by bonniec0** [comment]
Hi there,

I was looking into this issue with the flags not rendering on certain devices & I think I may have found a relatively simple solution. I understand not wanting to create a custom select element, however I think you could achieve the same thing by adding a div that opens a container containing a number of labels for the relevant radio input for the currency. It is essentially the same setup as you have currently, but using radio buttons rather than a select button.

You would only need to change the javascript to listen for changes on the radio elements rather than on the select element in order to submit the form.

I've made a quick codepen to demonstrate what I mean - https://codepen.io/bonnie_c/pen/dygWbgR


This would allow SVGs of the flags to be used so that they would display on all browsersand it would remain fully conifgurable by the user so they could add flags/codes/names/symbols to suit their needs.

There would also be the added benefit that the dropdown could feature the full name of the currency to avoid any potential confusion, whereas the button itself could display just the code to save space (as shown in the codepen).

Moreover, this would give the added flexibility that the user could easily order the currencies to show a more used currency first if they so wished, by using the CSS 'order' property on the relevant label (I have added this in the codepen too, to demonstrate what I mean).

Please let me know what you think, as I believe it would entice many more users to use woocommerce payments (& reduce the number support enquiries) if the multi-currency aspect was simpler to customise.

Thank you,
Bonnie
