### ISSUE TITLE
Track redirect to platform checkout

### ISSUE THREAD

**Issue by brianyu28** [Automattic/woocommerce-payments#3904]
### Description

Track when returning platform checkout customer is redirected to platform checkout from merchant site

### Acceptance criteria

* Implement `woocommerceanalytics_platform_checkout_redirect` event

### Additional context
pdpOw2-mz-p2

Split into a separate issue from #3829

**Comment by malithsen** [comment]
Hi @alefesouza thanks for working on this issue. This issue was originally created to track the automatic redirection of a returning platform user to platform checkout without going through the OTP modal. Automatic redirection functionality is being implemented under 504-gh-Automattic/woopay and it's not yet merged to the trunk. Currently the redirections via OTP are indirectly tracked with [`PLATFORM_CHECKOUT_OTP_COMPLETE`](https://github.com/Automattic/woocommerce-payments/blob/65df1f437f3784e932f53a7398fd478d5df5baf9/client/checkout/platform-checkout/email-input-iframe.js#L297)

As #4375 doesn't address the original goal of this issue and given that this issue is linked in a few places in the PT(pdpOw2-mz-p2), I am reopening the issue instead of creating another one.

**Comment by alefesouza** [comment]
Already included on #4328.
