### ISSUE TITLE
Allow merchants to only enable credit card on UPE

### ISSUE THREAD

**Issue by leonardola** [Automattic/woocommerce-payments#4114]
### Describe the bug
If you try to enable UPE but don't want to enable a new payment method only credit card. You have to go back in the browser history or select a new payment method and then disable it later. This is not very intuitive and can make merchants end up with misconfigured sites.

### To Reproduce
- With Upe disabled
- Go to Payments > Settings
- Click on Enable in your store under "Enable the new WooCommerce Payments checkout experience"
- Try to save without selecting any other payment method

### Screenshots
<img width="786" alt="Screen Shot 2022-04-08 at 5 41 31 PM" src="https://user-images.githubusercontent.com/6342964/162527224-c42d0bb1-5df1-49a2-aefe-d7992646dc61.png">

### Expected behavior
Merchants should be able to activate upe with credit card only

**Comment by rogermattic** [comment]
Hey @leonardola and @vladolaru (thanks for pinging me on Slack re: this :) ) 

Considering that the first step, (before the user gets into the stepper) looks like this:
<img width="1229" alt="Screenshot 2022-12-09 at 10 38 05" src="https://user-images.githubusercontent.com/94967682/206673013-c8e0eec4-cd93-4e58-9e2a-e460c9e49af5.png">

I agree, they should be able to go through the wizard without having to enable any additional payment methods, if they just want to explore what's available. That's why I like one of the solutions suggested by @vladolaru on Slack:

> Include a credit cards list item at the top of the list (the same way it is in the settings view) with a checkbox that is pre-checked and disabled since the credit cards payment method is mandatory for UPE. If we take this route, maybe the copy of the Add payments methods button could be changed to something like “Start with these payment methods” to capture better the fact that there might be no adding of payments methods at the moment and that it is just a starting point, not something definitive.

I was also able to find some old designs in our Figma, displaying the Credit/Debit cards checkbox in the stepper too:
<img width="699" alt="Screenshot 2022-12-09 at 10 58 02" src="https://user-images.githubusercontent.com/94967682/206676019-327a5ac4-dc93-4dee-beb2-2b735a6c545e.png">


My slight concern with changing the CTA depending on the user selection is that it might be confusing, so I made this mockup, that could work, that includes the additional labels `Required` (on credit cards, so that the user knows that they cannot unselect this item) and `You can always change add more payment methods later` below the selection box. That should reassure the user that they can always go back to this in the future

<img width="700" alt="Screenshot 2022-12-09 at 11 06 24" src="https://user-images.githubusercontent.com/94967682/206677608-53b57b21-520b-46af-92a6-5d2c214bad31.png">


Let me know your thoughts :) 

CC: @elizaan36

**Comment by vladolaru** [comment]
Thank you, @rogermattic, for providing such comprehensive input!

I like where this is going! 😋

Let me **summarize** so I can be sure we are aligned on what needs changing:
1. Add the **Credit card / debit card** list item at the top, with the checkbox pre-checked and disabled, and add a secondary  `Required` label under the item's main label.
2. Add the `You can always change add more payment methods later.` description (with secondary styling) below the payment method(s) selection box. Any notifications that might pop up when selecting payment methods (like the Sofort-related one in the screenshot you provided) will appear _after_ this description.
3. **I am not sure about this** since you didn't explicitly mention it, but the designs feature it: change the button label from `Add payments methods` to `Continue`. Personally, I like the `Continue` label better as it is more agnostic and captures all the scenarios. If it helps, this button (and pretty much the entire second step) was introduced in #2405 and there is no mention of the copy for it. Please advise on this one!

Let me know if I missed anything..

**Comment by rogermattic** [comment]
Thanks @vladolaru 

1. Correct.
2. Correct!
3. Thanks so much for linking issue #2405 🙌  I like the `Continue` label better too, for the exact reasons that you mentioned! Using `Continue` as a label is clear and flexible enough (covers the use cases we need to cover), so let's do this 👍

**Comment by vladolaru** [comment]
Just perfect @rogermattic!

One minor nag about the wording of `You can always change add more payment methods later.`. I think it should be `You can always change or add more payment methods later.` (the `or`)

**Comment by vladolaru** [comment]
@rogermattic I noticed another styling inconsistency: the payments select box headline `Payments accepted at checkout` is not currently styled as in the above designs (wrong font size and weight).
![Annotation on 2022-12-12 at 14-39-38](https://user-images.githubusercontent.com/8830539/207047477-e68b1b0d-91d8-4300-a8a5-89216c610a17.png)

I will also include this fix since we are tackling the micro-styling of this box:
<img width="635" alt="Screenshot 2022-12-12 at 14 41 35" src="https://user-images.githubusercontent.com/8830539/207047905-38355474-e3b2-4ee7-bc80-6f031802c34e.png">
