### ISSUE TITLE
Refactor the direct post table queries found in the `WC_Payments_DB` class to use `wc_get_orders()`/`WC_Order_Query`

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-payments#4151]
### Description

With [Custom Order tables coming to WooCommerce Core](https://developer.woocommerce.com/2022/01/17/the-plan-for-the-woocommerce-custom-order-table/), direct DB queries that fetch orders by post meta will need to be reworked/updated to work with orders stored in custom tables.

There are a few functions in the `WC_Payments_DB` class which are querying order IDs and order meta that will need to be updated:
 - [ ] [`orders_with_charge_id_from_charge_ids()`](https://github.com/Automattic/woocommerce-payments/blob/ca0aa7a9160647e3612bffc8b9e0f935bea3acd1/includes/class-wc-payments-db.php#L46-L52) - Retrieve orders from the DB using a list of corresponding Stripe charge IDs.
 - [ ] [`order_id_from_meta_key_value()`](https://github.com/Automattic/woocommerce-payments/blob/ca0aa7a9160647e3612bffc8b9e0f935bea3acd1/includes/class-wc-payments-db.php#L93-L99) - Retrieve the latest order ID from the DB using a meta key value pair.

This issue is to look at replacing these queries with `wc_get_orders()`/`WC_Order_Query` alternatives.

### Dev notes

There's a wiki on how to search for orders using custom meta here: https://github.com/woocommerce/woocommerce/wiki/wc_get_orders-and-WC_Order_Query#adding-custom-parameter-support

### Additional context

**Project thread:** pdjTHR-Xp-p2
**Exploration p2:** pdjTHR-YX-p2

**Comment by jbordonado** [comment]
I'd like to note that one of the problem of using the current `orders_with_charge_id_from_charge_ids()` function is that we will not show any order ID in the Payments > Transactions page when COT is enabled without syncing. Instead, we will only see `N/A` since we are still looking inside the `wp_posts` table).

As for the `order_id_from_meta_key_value()` function, we will not be able to process various webhooks related to disputes  and refunds, and the order info will also not be added to the list of disputes (amongst other side-effects on transactions and disputes).

**Comment by RadoslavGeorgiev** [comment]
Once this is fixed, let's check if #4554 got fixed for free as well.

**Comment by james-allan** [comment]
Reopening as this was only partially fixed in #4590

**Comment by james-allan** [comment]
> Reopening as this was only partially fixed in https://github.com/Automattic/woocommerce-payments/pull/4590

Nvm. I misinterpreted this issue. I was thinking of #4147
