### ISSUE TITLE
WC Pay + Order Status Manager, cannot customize OSM emails

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#4167]
### Describe the bug

Activating WC Pay on a site with SkyVerge's Order Status Manager plugin makes the OSM emails impossible to customize.

### To Reproduce

1. Start with a WC test site with WC Pay installed and active.
2. Download [Order Status Manager](https://woocommerce.com/products/woocommerce-order-status-manager/). Install and activate it.
3. Go to WooCommerce > Settings > Order Status > Emails.
4. Create an example email template there.
5. Once you save, click Customize Email. You just get this:

<img width="1007" alt="Screenshot taken on 2022-04-20 at 17 46 36 UTC@2x" src="https://user-images.githubusercontent.com/5512652/164291444-21a9eabc-6dba-4ba4-948e-235e44568b70.png">

6. Deactivate WC Pay in another tab.
7. Refresh the above pag. Now you get this:

<img width="955" alt="Screenshot taken on 2022-04-20 at 17 47 34 UTC@2x" src="https://user-images.githubusercontent.com/5512652/164291586-ae5e3d4b-13ae-4dd8-bffc-8a379f76ce64.png">

This only seems to affect emails made by OSM, not core WC emails. Nothing shows in any logs that I can find: WC core logs, WC Pay logs, `WP_DEBUG_LOG`, JS console, all have nothing.

4960673-zen

**Comment by nikolas4175-godaddy** [comment]
Hey @aheckler 👋  Our support team at SkyVerge is seeing several reports of this issue with Order Status Manager emails and one with Memberships emails as well, both of which we've been able to replicate when WC Pay v4.0+ is installed. The issue doesn't seem to be present with WC Pay v3.9.3.

In both cases, our plugin emails are setup as extensions of the `WC_Email` class.

We've started sending merchants with this issue over to y'all in ZD since it looks like the fix will need to be in WC Pay based on our testing. Let me know if there's anything else I can help with from our end, happy to pitch in here!

**Comment by dnusca** [comment]
Hi @aheckler, I can confirm the issue as well in other plugins which register custom emails via the `woocommerce_email_classes` filter.

It seems to be caused by the `WC()->mailer()` method being called in the `init` method of the [WC_Payments](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payments.php#L288) class.

Also referencing this [issue](https://github.com/Automattic/woocommerce-payments/issues/4182), which appears to be the same problem.

**Comment by namiokuzono** [comment]
Just in case I am leaving this thread here for reference p1650884880649129-slack-C07414X4N
