### ISSUE TITLE
Refunds returning Error: Missing required param: type.

### ISSUE THREAD

**Issue by johndcoy** [Automattic/woocommerce-payments#4297]
Creating this bug a bit prematurely but it appears we have a tren of similar reports:

Slack thread: p1652734042278589-slack-C7U3Y3VMY

5211256-zen
5247437-zen
27146040-hc

 
Describe the bug

When processing a refund the order fails to refund and leaves the following order note:

>Error: Missing required param: type.

Screenshot
Screenshot link: https://d.pr/i/4o1qHs

To Reproduce

Cannot reproduce

Additional context

Failed transaction in Stripe Express:

https://dashboard.stripe.com/connect/accounts/acct_1JnNv52HnsTv7cV6/payments/pi_3L3OHo2HnsTv7cV61JP5rO8W

**Comment by aheckler** [comment]
Some discussion of this also here: p1653331519159749-slack-CGGCLBN58 with more tickets listed.

**Comment by luizreis** [comment]
@FangedParakeet and I have investigated this a bit more and the error comes from [this line](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payment-gateway-wcpay.php#L1526). Due to #4313 some UPE orders might not have the `_payment_method_id` in the meta, which leads to a request to `/payment_methods/:id` with an empty ID. This request is then interpreted as a request to `/payment_methods`, but it lacks the required parameters causing the error in the order notes.

A simple fix to this issue would be grabbing the payment method type using the payment intent when `_payment_method_id` is empty. This would be enough to fix the refund issue for every affected order, but it wouldn't address the original issue of orders not having that data.

**Comment by csmcneill** [comment]
5266322-zen

**Comment by aheckler** [comment]
Here's a list of other tickets affected by this:

- 5236132-zen
- 5219319-zen
- 5217285-zen
- 5249713-zen
- 5245510-zen
- 5267129-zen
- 5257589-zen
- 5245331-zen
- 5262722-zen
- 5164151-zen (error shows up in mobile app logs, but the ticket is about something else)

**Comment by aheckler** [comment]
Chats about this I found in Looker:

- 35433131-hc
- 4921125-hc
- 35529355-hc
- 35512357-hc
- 34426127-hc
- 35459249-hc

**Comment by cgehrke9** [comment]
5267129-zen

**Comment by brianyu28** [comment]
This has been fixed in https://github.com/Automattic/woocommerce-payments/pull/4322 and the fix was released in WooCommerce Payments 4.2.1.
