### ISSUE TITLE
Payment fails if not compatible with all payment types included in Payment intent (invalid_request_error)

### ISSUE THREAD

**Issue by Brianmitchtay** [Automattic/woocommerce-payments#4492]
### Describe the bug
When a payment intent is sent to Stripe via WooCommerce Payments, all enabled payment types are included in the array of payment types on the payment intent. Because of this, if the payment is not compatible with **all** enabled payment types, it will fail.

In the instance where this issue surfaced 5397304-zen, the user had customers which had initiated subscriptions in $USD via Credit/Debit Card payments, and then when the user changed to a third party currency switcher tool, disabling the built-in Multi-currency functionality, recurring $USD payments began to fail, because the `Bancontact` method, which was enabled, was not compatible with $USD payments, despite these payments using the `Credit/Debit Card` type 

I should note that since my WCPay test environment is US based I have been unable to test/reproduce this behavior.

### To Reproduce

1. In a EUR denominated shop, enable WCPay multi-currency functionality, as well as the `Bancontact` payment method.
2. Initiate a $USD denominated Subscription paid Via `Credit/Debit Card`
3. Deactivate Multi-currency Functionality
4. Attempt to process renewal for $USD denominated subscription
5. See error message: `The currency provided (usd) is invalid for one or more payment method types on this PaymentIntent. The payment method type bancontact only supports the following currencies: eur. Either correct the provided currency, or use a different PaymentIntent to accept this payment method type. (invalid_request_error)`
6. Disable the `Bancontact` payment type
7. See that the payment functions, despite having multi-currency disabled

### Actual behavior

The payment fails, despite $USD being valid with the type of payment being requested (`Credit/Debit Card`)

### Expected behavior

I would expect a $USD denominated payment to function regardless of whether an incompatible payment type is enabled. Or at least for the error message to indicate that they payment has failed due to multi-currency functionality being disabled if that is the reason.

Further I would expect that since this payment is of the `Credit/Debit Card` type, only that type would be included in the array of payment types in the Payment Intent.

### Desktop (please complete the following information):

* OS: [macOS Monterey v 12.4]
* Browser [Chrome]
* Version [Version 103.0.5060.134 (Official Build) (arm64)]

### Additional context

From their logs:

```
'payment_method_types' =>
array (
0 => 'card',
1 => 'bancontact',
2 => 'eps',
3 => 'giropay',
4 => 'ideal',
5 => 'sofort',
6 => 'p24',
),
'off_session' => 'true',
)
2022-07-19T20:14:49+00:00 ERROR The currency provided (usd) is invalid for one or more payment method types on this PaymentIntent. The payment method type bancontact only supports the following currencies: eur. Either correct the provided currency, or use a different PaymentIntent to accept this payment method type. (invalid_request_error)
```

**Comment by csmcneill** [comment]
I've been able to reproduce this without disabling the multicurrency option.

Discussion in p1687333283300519-slack-C3NCP7ZJ6 related to 6430073-zen

Here's @Brianmitchtay's steps above, but modified a bit to cover how I was able to reproduce:

1. In a EUR denominated shop, enable WCPay multi-currency functionality, as well as the Bancontact payment method.
2. Initiate a kr SEK denominated Subscription paid Via Credit/Debit Card.
3. Attempt to process renewal for kr SEK denominated subscription.
4. See error message: `Error: The currency provided (sek) is invalid for one or more payment method types on this PaymentIntent. The payment method type bancontact only supports the following currencies: eur. Either correct the provided currency, or use a different PaymentIntent to accept this payment method type`.
5. Disable the Bancontact payment type.
6. Retry the renewal payment; it succeeds.

As this no longer seems to be an edge case, I'm flagging this to @Automattic/pulsar (APMs). TBD if we may need to coordinate with Sigma (multicurrency) and Quark (WC Subs).

![Markup on 2023-06-21 at 20:17:02](https://github.com/Automattic/woocommerce-payments/assets/82999806/f13ec9c5-6698-4217-be32-2b2cbd50570a)

**Comment by csmcneill** [comment]
I've tested this with split UPE and legacy UPE and can reproduce it in both scenarios.

I'm flagging this to a couple of teams because it touches on multiple aspects:
- @Automattic/quark due to Subscriptions
- @Automattic/pulsar due to APMs
- @Automattic/sigma due to multicurrency

There has been some discussion about this in p1688506467464339-slack-C055WHLA98D but this issue essentially prevents anyone offering Subscriptions while also offering APMs with a default currency of EUR from processing subscription renewals. It affects [this](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#renew-subscription-automatically) critical flow and [this](https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#subscription-with-upe) critical flow.

I'm also ccing @vbelolapotkov here as we've been trying to get this prioritized for ~3 weeks.

**Comment by dwainm** [comment]
@csmcneill Are we expecting the payment currency to be automatically adjusted to match the selected APM's supported currencies?

**Comment by csmcneill** [comment]
@dwainm In this situation, I don't believe so.

My understanding of this issue is that there are some APMs that are only compatible with specific currencies. However, if a subscription is purchased...

1. While these APMs are enabled.
2. In a non-EUR currency.

...the renewals fail. In my steps noted [here](https://github.com/Automattic/woocommerce-payments/issues/4492#issuecomment-1601883900), we'd expect for the subscription to renew in SEK since it was purchased in SEK.

**Comment by dwainm** [comment]
@csmcneill This error comes from the payment provider as far as I can see (the error is not in the server or client code base). Why are they allowing payment for a subscription but not allowing its renewal? I think we'd need to start by asking Stripe about this specific example here.

**Comment by thenbrent** [comment]
> Why are they allowing payment for a subscription but not allowing its renewal?

@dwainm I'm not entirely across this issue, but skimming it previously, I thought the cause was that the renewal payment request including all APMs incorrectly, even when those are not being used for the renewal payment. That request should only use the payment method (i.e. card) for the renewal so the renewal can go through regardless of currency.

This issue may also be related to the regression recently that lead to missing meta data (IIRC, it was `payment_context` meta missing, as discussed in this P2: paJDYF-8Yd-p2)

**Comment by dwainm** [comment]
Thanks for clarifying @thenbrent . I'm not very clued up with how renewals work and that explanation makes sense. From my current point of view, I don't think this is related to the currency or the conversion so not really related to multi-currency functionality (or that multi-currency is contributing to the error here). We'll be happy to help with anything if that becomes the case, but at this stage I couldn't find anything that could contribute.

**Comment by vbelolapotkov** [comment]
Asked @FangedParakeet and @timur27 to investigate here: p1691503660845959-slack-CGGCLBN58
