### ISSUE TITLE
Apple Pay: fix errors on web registrations

### ISSUE THREAD

**Issue by dpaun1985** [Automattic/woocommerce-payments#4511]
### Describe the bug

When a domain is registered, we saw a burst of domain registration errors.
Possible causes: 
1. `apple_pay_bad_status_code ` - meaning when `<domain>/.well-known/apple-developer-merchantid-domain-association` is accessed, we get a non 200 HTTP response
2. `apple_pay_unsupported_country` - meaning the merchant is in an unsupported country. Supported countries: https://support.stripe.com/questions/country-availability-for-apple-pay 

Context: p1657312179990539-slack-C9976E5MJ

**Comment by a-danae** [comment]
I'm opening this issue again because the changes introduced in the PR that closed this issue were reverted by https://github.com/Automattic/woocommerce-payments/pull/4758. The reason is explained in [this other GH issue](https://github.com/Automattic/woocommerce-payments/issues/4712). 

cc @Automattic/pulsar

**Comment by ricardo** [comment]
As it was discussed in the thread p1663082254010359/1662580488.851089-slack-CGGCLBN58 we shouldn't prevent the errors from happening, nor check the registration requirements ourselves, as this would be unreliable.

Instead, we can provide a permanent warning notice telling users that the domain could not be verified, and a call to action to retry it. E.g link: [Retry domain verification].

As far as I understand the error notices mentioned in #4551, they were not permanent and only showed up when the registration request happened.

If they disappear after page refresh, we can check the state of the domain verification from settings and provide a permanent warning notice, otherwise we could consider adding the call to action to retry to the error notice from #4551 itself.

**Comment by kalessil** [comment]
Adding the issue to Pulsars backlog so we could re-iterate the implementation here.

**Comment by dpaun1985** [comment]
@ricardo, at this point, if the domain verification failed, a generic warning message is shown, and it is persistent:
<img width="1663" alt="Screenshot 2023-01-09 at 18 36 15" src="https://user-images.githubusercontent.com/82826872/211359605-b6790309-c193-4568-ad92-88fd390b47b5.png">
Should I add clarifications in this warning, or create a new warning message in order to add clarifications on how to verify the domain (and keep also the old warning message) ?
I would go with the first option. What do you think ?

**Comment by ricardo** [comment]
@dpaun1985 Immediately upon the domain registration request, the user should see a specific error on why the registration failed ([src](https://github.com/Automattic/woocommerce-payments/blob/2ef37ccdb7f499278a53829ae217ee770b62d428/includes/class-wc-payments-apple-pay-registration.php#L427)).

If the user then refreshes the page, that generic error message is displayed ([src](https://github.com/Automattic/woocommerce-payments/blob/2ef37ccdb7f499278a53829ae217ee770b62d428/includes/class-wc-payments-apple-pay-registration.php#L418)).

From a UX perspective, I guess it would be ok to keep the persistent generic warning, but it may be unclear to the user how to retry the domain registration, so I think we could fix this in 2 ways:
- Add a call to action link with something like "Retry domain verification", which basically points to a domain registration endpoint and either successfully verifies the domain, or displays the specific error message immediately upon the request to Apple Pay. Or;
- The "Learn more" link should point to a clear step-by-step in the documentation on how to retry the domain verification. Currently, that is disabling and re-enabling express checkouts.

**Comment by dpaun1985** [comment]
> From a UX perspective, I guess it would be ok to keep the persistent generic warning, but it may be unclear to the user how to retry the domain registration, so I think we could fix this in 2 ways:
> 
> * Add a call to action link with something like "Retry domain verification", which basically points to a domain registration endpoint and either successfully verifies the domain, or displays the specific error message immediately upon the request to Apple Pay. Or;
> * The "Learn more" link should point to a clear step-by-step in the documentation on how to retry the domain verification. Currently, that is disabling and re-enabling express checkouts.

Indeed, I would go with the 2nd option ( the "learn more" link pointing [here](https://woocommerce.com/document/woocommerce-payments/payment-methods/apple-pay/#domain-registration)) . There are well described the steps and the actions that have to be made in order to successful register the domain. 
If we go with the first option, I think the merchant will retry domain verification action, without fixing the root cause.

What do you think about this @ricardo  ? should we go with the second option ? or the first one ? 

Or we can have both, the "retry domain verification" link and also the "read more" link. This way we could have a better UX, and also give the context needed to the merchant.

**Comment by ricardo** [comment]
As we discussed via DM earlier today, the docs were updated to add a section for `#triggering-domain-registration` for backwards compatibility, and @dpaun1985 is going to fix the existing notice to point to the correct section of the docs.
