### ISSUE TITLE
Payment methods deselected

### ISSUE THREAD

**Issue by hsingyuc** [Automattic/woocommerce-payments#4629]
### Describe the bug
When quickly selecting more than one payment method, only the first one is selected.  And if there are selected methods already, quickly selecting the rest of the payment methods; only the last one will be selected.

### Screenshots
https://user-images.githubusercontent.com/56378160/186328647-6e2e0175-75f3-44a1-96e9-33f7dbc41320.mov

### To Reproduce
1. Go to WooCommerce -> settings -> payments
2. Find `Payments accepted on checkout` section
3. Click on the `enable in your store` button
4. Select at least two or three payment methods quickly
5. See only the first one is selected

### Actual behavior
When quickly selecting more than one payment method, only the first one is selected

### Expected behavior
When quickly selecting more than one payment method, all the selected payment methods should be selected

**Comment by zmaglica** [comment]
Tested and confirmed on the latest version of WooCommerce Payments plugin.

**Comment by jessy-p** [comment]
To explore if possible to fix or if it needs UI changes.

**Comment by nagpai** [comment]
Writing my thoughts here to help troubleshoot. My understanding may be incomplete / incorrect and I will iterate :).

The issue seems to be linked to a [1.5 second delay](https://github.com/Automattic/woocommerce-payments/blob/develop/client/components/payment-methods-list/payment-method.js#L64) added to the checkbox component, as a design requirement ( check linked P2 post ) . In a few cases, Payment Methods have an additional check for some requirements, and may show a modal asking users to complete it, if it isn't done. The delay was added to take care of this. 

Checkboxes that are checked quickly within 1.5 seconds, seem to be getting unchecked, except the last one that is selected. I am trying to find out the exact code that is causing it to get unchecked. The issue goes away if we reduce the delay to about 500ms ( I tested this ), however it will defeat the design requirement of showing a backend check in process ( for modal ). 

Probable solutions at the moment  that I can think aloud:

Check if the Payment method has any checks pending ( if not pending then set `delayMsOnCheck` to zero or a very small value ). If there is a pending check for the payment method, disable all other payment methods for 1.5 seconds and show the modal. WDYT @mordeth  ?

Context 
paJDYF-2rk-p2

( Props @tpaksu 🙌  )

**Comment by tpaksu** [comment]
> Check if the Payment method has any checks pending ( if not pending then set delayMsOnCheck to zero or a very small value ). If there is a pending check for the payment method, disable all other payment methods for 1.5 seconds and show the modal.

No need to check for any requirements for a LPM to lower the number, I believe it should stay as is, and if one checkbox is processing, others should be unclickable. What do you think? Maybe it'll be better to ask the design team.

**Comment by nagpai** [comment]
@tpaksu - Sorry about my late reply. In the above PR, I have added new actions to insert or remove only the selected payment method from the latest enabled_payment_method_ids state array. If you get time, do take a look and let me know if it would work well. ( This is my first PR involving WP Data / Redux :D )

**Comment by nagpai** [comment]
The PR mentioned above - #5171 fixes the issue on the list that is visible within Payments > Settings, after UPE has been already activated. 

Similar issue seems to occur when we enable UPE for the first time. This uses a similar but a different 

![image](https://user-images.githubusercontent.com/4162931/203923927-d33fcf1d-df54-4963-b57b-206634a70f23.png)


Created an issue here 
https://github.com/Automattic/woocommerce-payments/issues/5193
