### ISSUE TITLE
Refactor the queries in Analytics that use post meta queries

### ISSUE THREAD

**Issue by deepakpathania** [Automattic/woocommerce-payments#4632]
### Description

With [Custom Order tables coming to WooCommerce Core](https://developer.woocommerce.com/2022/01/17/the-plan-for-the-woocommerce-custom-order-table/), direct DB queries that fetch orders by post meta will need to be reworked/updated to work with orders stored in custom tables.

This issue is to look at the direct postmeta queries in `Analytics.php`  and replace it with `wc_get_orders()`/`WC_Order_Query`.

#### Dev notes
There's a wiki on how to use wc_get_orders() with custom meta [here](https://github.com/woocommerce/woocommerce/wiki/wc_get_orders-and-WC_Order_Query#adding-custom-parameter-support), however I don't know how that DB query will translate to using something like wc_get_orders().

If it's not a simple task, we might have to go with some other approach where we surround this with a if/else condition and use this WP post query on stores not using custom order tables and then write a new query to fetch the orders in custom order tables. We should try to avoid having direct DB queries as they won't work for any custom data stores that stores may have implemented.

#### Additional context
Project thread: pdjTHR-Xp-p2
Exploration p2: pdjTHR-YX-p2

**Comment by dmallory42** [comment]
Hi folks, I just want to add some context here in case it would be useful.

I don't think that it would be possible to replace these queries with something like `wc_get_orders()` because of how the queries work. What we're doing here is hooking into a filter to modify existing `WHERE`, `JOIN`, `SELECT` clauses which are made by the Analytics pages by WC Admin ([example](https://github.com/woocommerce/woocommerce/blob/9479568e3d9e30b7bf41b6369f837ae26885e0b8/plugins/woocommerce-admin/docs/examples/extensions/sql-modification/woocommerce-admin-sql-modification.php#L134)). We're modifying the query to try to ascertain whether we need to perform currency conversions on the figures. 

This is necessary because the `wp_wc_order_stats` table expects all data to be stored in the store default currency (which we do by using a hook at the time of order ([src](https://github.com/Automattic/woocommerce-payments/blob/eefed9832911aa4953edb3c2b5a2c8f22e05cb80/includes/multi-currency/Analytics.php#L194)), but the data stored in `wp_postmeta` is also used by some of the analytics queries, and this data is stored in whichever currency the order was placed in.

> we might have to go with some other approach where we surround this with a if/else condition and use this WP post query on stores not using custom order tables and then write a new query to fetch the orders in custom order tables. 

I haven't explored it deeply (I don't have in depth knowledge of how COT works under the hood), but I think this may be the simplest solution.
