### ISSUE TITLE
Use PHP to add tasks to the tasks list instead of the deprecated JS filter

### ISSUE THREAD

**Issue by gpressutto5** [Automattic/woocommerce-payments#4652]
### Description

We are using a deprecated feature to add tasks to WC task lists using the `woocommerce_admin_onboarding_task_list` filter in JavaScript, which is deprecated.

> We did indeed change the way tasks should be added to the task list (it can still be done using the filter), but the preferred way is using our PHP classes, similar [to this](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Admin/Features/OnboardingTasks/TaskLists.php#L132-L150).

### Acceptance criteria

* Tasks should keep behaving the same as they do now.
* We should not use [DeprecatedTasks](https://github.com/woocommerce/woocommerce/blob/945a55adbc7691fd263ee4c07bc8d3dbf932d2e0/packages/js/data/src/onboarding/deprecated-tasks.ts) anymore.
* Custom tasks should be added to the task lists using PHP. ([Docs](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/docs/features/onboarding-tasks.md))

### Dev notes

- This is the list of tasks in JS: https://github.com/Automattic/woocommerce-payments/blob/584cc4766845f23898a399c9973fa1a4540e4bd4/client/overview/task-list/tasks.js
- This is where we use the deprecated `woocommerce_admin_onboarding_task_list` filter: https://github.com/Automattic/woocommerce-payments/blob/56595f45b9e083c2d3e2374c7e528199267b7980/client/index.js#L267
- Here's an example of adding tasks using PHP: https://github.com/Automattic/woocommerce-payments/blob/096e5a51594988889d3fbc217f1eb6e325d9b125/includes/class-wc-payments-tasks.php#L34

### Additional context

Discussion: p1661434201828299-slack-C01SFMVEYAK
Onboarding tasks docs: https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/docs/features/onboarding-tasks.md

**Comment by jessy-p** [comment]
This issue impacts Onboarding, Account management, General purpose communications and communication tools, so assigning to Moltres (based on team responsibilities Pc2DNy-3z-p2) @daquinons. Assigning as part of Gamma Triage process PcreKM-yM-p2.

Tagging as part of re-evaluating older issues in the backlog, please have a look and close if no longer relevant.

**Comment by vladolaru** [comment]
This is tricker than intended because WooPayments has three uses for tasks:
1. The overview page task list: a custom rendered task list with non-core behavior (collapsible tasklist)
2. Tasks pushed into the Things to do next core list (like KYC, WPCOM connection, and Go Live tasks)
3. Tasks registered in PHP (the recommended way): the Disputes task that is added to the Things to do next task list (see [here](https://github.com/Automattic/woocommerce-payments/blob/77fd16b38861eb5189109868cc6f4118a8e91657/includes/class-wc-payments-tasks.php#L39-L39))

The deprecated filter applies to the second category only. To remove it's usage we would need to double our JS tasks in PHP also, since removing the JS tasks is not a readily available option because of our task list custom JS rendering.

**Comment by gpressutto5** [comment]
Thanks for explaining, @vladolaru. I'm closing this issue.
