### ISSUE TITLE
[Spike] Replace intl-tel-input input with Calypso phone input component

### ISSUE THREAD

**Issue by mordeth** [Automattic/woocommerce-payments#4718]
### Description
This spike evaluates the benefit of replacing the intl-tel-input phone input library with the Calypso phone input component in favor of bundle size.

**Comment by vbelolapotkov** [comment]
@anu-rock @timmy5685 routing this one to you since telephone input is used in account settings.

**Comment by anu-rock** [comment]
I think this issue can be closed as it was fixed by https://github.com/Automattic/woocommerce-payments/pull/7611 which uses a new telephone input component added in WooCommerce via https://github.com/woocommerce/woocommerce/pull/40335. Pinging the issue author @mordeth to verify and close as needed.

**Comment by mordeth** [comment]
Indeed, this spike can be closed as it is no longer relevant. Nevertheless, I've identified two instances in the code where 'intl-tel-input' is still being utilized, and we may consider replacing it with https://github.com/woocommerce/woocommerce/pull/40335.

**Comment by mordeth** [comment]
A new issue, #8581, has been opened to remove all occurrences of `intl-tel-input`.
