### ISSUE TITLE
Multiple UPE - compatibility with other payment gateways

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-payments#4721]
### Description
This is part of the Multiple UPE project (https://github.com/Automattic/woocommerce-payments/pull/3968).

This issue is to verify if other payment gateways can be enabled with WCPay after merging this [POC](https://github.com/Automattic/woocommerce-payments/pull/3968). Maybe check with @Automattic/axiom to get a list of plugins we should check against.

### Acceptance criteria
- After upgrading WCPay with the [POC](https://github.com/Automattic/woocommerce-payments/pull/3968), buyers are able to continue their checkout with the existing payment gateway plugins they installed.
- If it's not compatible, we can create other tickets to follow-up.

**Comment by leonardola** [comment]
@harriswong 

These are the payment gateways we take care of:
- [eWAY](https://href.li/?https://github.com/woocommerce/woocommerce-gateway-eway)
- [GoCardless](https://href.li/?https://github.com/woocommerce/woocommerce-gateway-gocardless)
- [PayFast](https://href.li/?https://github.com/woocommerce/woocommerce-gateway-payfast)
- [PayPal Advanced](https://href.li/?https://github.com/woocommerce/woocommerce-gateway-paypal-advanced)
- [PayPal Checkout](https://href.li/?https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout)
- [PayPal Here](https://href.li/?https://github.com/woocommerce/woocommerce-gateway-paypal-here)
- [PayPal Payments](https://href.li/?https://github.com/woocommerce/woocommerce-paypal-payments)
- [PayPal Powered by Braintree](https://href.li/?https://github.com/woocommerce/woocommerce-gateway-paypal-powered-by-braintree)
- [PayPal Pro](https://href.li/?https://github.com/woocommerce/woocommerce-gateway-paypal-pro)
- [PayPal Pro Hosted](https://href.li/?https://github.com/woocommerce/woocommerce-gateway-paypal-pro-hosted)
- [Purchase Order Gateway](https://href.li/?https://github.com/woocommerce/woocommerce-gateway-purchase-order)
[SnapScan](https://href.li/?https://github.com/woocommerce/woocommerce-gateway-snapscan)

But I don't think any of them would be affected by this change. The gateway that would potentially be affected is the [Stripe](https://github.com/woocommerce/woocommerce-gateway-stripe) one

**Comment by harriswong** [comment]
Thank you so much for the list @leonardola!

**Comment by mdmoore** [comment]
While working on WCPay token behavior in Multiple UPE, I've tested Stripe Gateway quite a bit. There is a problem in the POC branch where WCPay is removing all non-WCPay tokens. That will be fixed when https://github.com/Automattic/woocommerce-payments/pull/4670 is merged in. Otherwise, Stripe works well.

**Comment by FangedParakeet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/4721?planning-poker) with Zenhub @mdmoore @timur27

**Comment by mdmoore** [comment]
I was unable to obtain proper credentials for 1 of the above mentioned payment gateway extensions(Snapscan), but all others are co-existing just fine alongside the split-UPE implentation in its current state. Checkouts are processing as expected. I don't foresee having the UPE split into multiple gateways causing any problems with other gateways. 

There was a [concern regarding tokens](https://github.com/Automattic/woocommerce-payments/pull/4670#discussion_r961627226), since we are now adding/reading/deleting tokens from multiple gateways. However, proper checks are in place to ensure we only touch WCPay gateways, those with IDs prefixed with `woocommerce_payments`. So, all things considered, I'm confident that split-UPE won't introduce any conflicts with payment gateways already installed on merchant shops.
