### ISSUE TITLE
Multiple UPE - Verify re-mounting/re-rendering of the checkout page will populate the correct UPE payment methods.

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-payments#4722]
### Description
This is part of the Multiple UPE project (https://github.com/Automattic/woocommerce-payments/pull/3968).

When an item is added to the `/checkout` page, the checkout page should re-render and should recalculate its tax and shipping based on its multicurrency settings etc. This issue is to verify that this continues to work in the [multiple UPE branch](https://github.com/Automattic/woocommerce-payments/pull/3968).

There are also concerns around `/checkout` + some addons that allow subscription items to be added directly. On these `checkout` pages, if a subscription item is added, the page should re-render and only shows the payment methods that allow subscription. 

### Acceptance criteria
- Changing quantity should re-calculate tax and shipping. Checking out with the selected payment method should work.
- Changing currency should change the available payment methods on the `/checkout` page. 
- Adding subscription products should re-render the page and show the payment methods that allow subscription.

### Additional info
Check p1662469528429629-slack-CGGCLBN58 for some context.

**Comment by Mayisha** [comment]
In the POC branch the payment methods section and the order summary section seem to be re-rendered as expected. Here is some of the cases I tested and the results-
🟢 With multiple currency enabled, when the currency is changed (e.g change from Euro to USD) the whole checkout page re-renders and the other UPE methods are hidden except `credit card/debit card`. This experience is same as the `develop` branch.
🟢 With subscription product payment methods renders same as the `develop` branch.
🟢 Installed `Update Cart on Checkout for WooCommerce` to update the quantity of the products on checkout page (as by default quantity change option is present on the cart page only not on checkout page). Changing the quantity of a product reloads the order summary section and the payment options.
⚠️This [slack thread](https://href.li/?https://a8c.slack.com/archives/CGGCLBN58/p1662469528429629) shared in the description  is about a bug about with free products and `WooCommerce Checkout Add-Ons`. When a user goes to the checkout page with a free product and selects an add-on, this re-renders the order summary and payment methods section but there is not input box for cards. The same error exists in this branch too. This should be fixed by the existing ticket https://github.com/Automattic/woocommerce-payments/issues/4764

<img src="https://user-images.githubusercontent.com/33387139/194560234-97d9b526-1f6e-46c6-9875-fd43c5cd3344.png" height="50%" width="50%" />
<img src="https://user-images.githubusercontent.com/33387139/194560245-5213e386-c14a-41aa-a1a1-571127cbf4f1.png" height="50%" width="50%" />

**Comment by Mayisha** [comment]
@harriswong please check if I missed anything :eyes:

**Comment by harriswong** [comment]
Thanks for checking this through @Mayisha! 

Double checking against the pre-mortem notes (paJDYF-5qJ-p2).
> How switching currency affects UX? E.g. PM for EUR is selected, currency switched to USD.

✅  This is checked.

> Anything with Taxes or Shipping when switching PMs? (create ticket)

I think this is also checked off right? When we switch payment methods in this branch, tax and shipping adjust accordingly?

**Comment by Mayisha** [comment]
> Anything with Taxes or Shipping when switching PMs? (create ticket)

This one seems also covered. Basically when a customer switches the payment method the order summary (that includes tax and shipping) does not change. Because the extra charge that comes with the corresponding payment method is charged from the merchant's deposit after the payment is done. So even on trunk there is no refresh or re-rendering happens on payment method change (keeping the tax and shipping same as before)
But I have tested this with the `Payment Gateway Based Fees` extension that allows merchants to set a specific charge per payment method so that the customer pays this extra charge based on the selected method during checkout. Both on the `develop` and the `POC` branch the order summary section (including subtotals, tax, shipping etc. ) re-renders when the payment method is changed. :tada:

**Comment by harriswong** [comment]
LGTM thanks for checking! :shipit:

**Comment by mdmoore** [comment]
@harriswong @Mayisha It appears the research on this was wrapped up and everything was working well. Just want to double check if we're good to close this?

**Comment by harriswong** [comment]
Yup! Thanks for checking. Closing the issue.
