### ISSUE TITLE
Multiple UPE - Fraud questions

### ISSUE THREAD

**Issue by harriswong** [Automattic/woocommerce-payments#4723]
### Description
This is part of the Multiple UPE project (https://github.com/Automattic/woocommerce-payments/pull/3968).

This topic came up in one of our discussions and we didn't have time to dive deep into it. This issue is to answer the following questions:

1. How auth now / capture later will work in such setup?
2. How to rate limit fraudsters with captcha?
3. Does multiple UPE create new attack vectors for fraudsters / hackers?

### Acceptance criteria
- Find the answers to the above questions.

**Comment by FangedParakeet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/4723?planning-poker) with Zenhub @mdmoore @timur27

**Comment by timur27** [comment]
Whoever works on this might be interested in [this P2 post](https://wcpay.wordpress.com/2022/11/04/fraud-risk-tools-exploration-of-server-side-rules-with-split-authorization-and-capture/).

**Comment by frosso** [comment]
@FangedParakeet @mdmoore @timur27 any concerns on setting the final estimate to "3"?
@timur27 if you're ok with that vote, feel free to change your estimate to 3.
@FangedParakeet @mdmoore if you'd like to change your estimate to a lower value, feel free to do so!

**Comment by FangedParakeet** [comment]
I'd consider this one day's investigation, one day's explanation of findings, and one day allowing for some unforseen surprises along the way. I wouldn't expect anything too scary to rear its head during this task, since I don't think we're fundamentally changing the UPE payment flow (yet), but the radius of vulnerability described by this somewhat broad issue could cover many different areas of WCPay.

Looking at the scale in the [capacity planner](https://docs.google.com/spreadsheets/d/1PslBbx3LoxEYrW3flvIYsfccI8aN1EADkjFZ6TY-1kg/edit#gid=1839705830), a two-pointed item is an extra-small issue where we hedge our bets by rounding it up; I don't think I'd describe this as a simple enough discussion that it could ever be settled within a day, but I think it is probably a small, two-pointed issue that I wouldn't mind hedging my bets by rounding up to three.

However, @timur27, if you strongly disagree, I can accept being a little less conservative and scoring this merely two points instead. Let me know how you feel!

**Comment by timur27** [comment]
Looking at the capacity planner now I agree, that it can be 3 and I agree with your argumentation. Let's proceed with three story points. Thanks! 👍

**Comment by mdmoore** [comment]
### How auth now / capture later will work in such setup?
Nothing changes with auth and capture. When manual capture is enabled, all payment methods except card are disabled. Card payments can still be authorized and captured later.

### How to rate limit fraudsters with captcha?
The conversation around rate limiting came up because the split-UPE will create multiple payment intents per checkout(for now), which was similar to the problem with card testing. Since the time the question was asked, [rate limiting has been imposed on the creation of payment intents](https://href.li/?https://github.com/Automattic/woocommerce-payments-server/blob/5ad3af36d291fbffe652916176c31e3c90c5b3eb/server/wp-content/rest-api-plugins/endpoints/wcpay/service/class-payment-fingerprint-service.php#L193-L198). The rate limit is currently set to 10 per minute per IP hash which means there is potential for customers to be rate limited under some conditions using the split-UPE. For that reason, there's been some discussion on creating a server side flag(paJDYF-6WA-p2#comment-15794) to increase the limit for merchants that have enabled split-UPE. I'll be sure an issue opened for this 👍.

### Does multiple UPE create new attack vectors for fraudsters / hackers?
The current split-UPE implementation doesn't change the flow of payment processing, it only multiplies the process that's currently in place. With that in mind, it doesn't appear the split-UPE will open up any new attack vectors.
