### ISSUE TITLE
Payment form absent when item with price added to cart via AJAX on a free order

### ISSUE THREAD

**Issue by jessy-p** [Automattic/woocommerce-payments#4764]
### Describe the bug
When an item with price 0 is added to the cart, it is expected that the payment form does not need to be displayed on the Checkout page. But, when an item with a price is added to the cart via AJAX on the checkout page, the payment form should appear, because it is no longer a 0 priced order.

### To Reproduce
1. Set up a product with a price of 0.
2. Set up two shipping types - Free Shipping and Flat rate at a non-zero cost
3. Add 0 priced item to cart and go to checkout page. Free shipping should be selected by default, so that order total is 0
4. Switch to Flat rate shipping on Checkout page so that order total is non-zero

### Actual behavior
The payment section loads, but there is no credit card form.

### Screenshots
<img width="399" alt="image" src="https://user-images.githubusercontent.com/32092402/191159136-d8c3c832-b081-47b4-92ed-711f999a1254.png">

### Expected behavior
When order total is 0 on Checkout page load, but is then updated to be non-0, the credit card form should appear and customer should be able to place the order.

### Additional context
p1662469528429629-slack-CGGCLBN58

**Comment by timur987** [comment]
Tested the bug described in this issue in application to WooCommerce.com in local dev. environment with WCPay `4.5.1` (the same version we have on production now):


https://user-images.githubusercontent.com/115007291/206260860-f5e6c751-85c7-411e-b33b-e58804f793d1.mov

It looks like the bug is there, but...

Retested once again and it looks like updating to `5.1.2` didn't help with showing the payment form properly:

https://user-images.githubusercontent.com/115007291/206454003-04dbdfa5-cbdd-4111-899d-9fcc3492791d.mov

Comments for the last video:
1. Checked that a user doesn't have a payment method saved
2. Open a checkout for a physical product with Free Shipping enabled (totat cart amount is `0.00`).
3. Switched to Flat Rated shipping that costs `$10`, it led to showing a payment form that doesn't have fields for putting CC data (no number, expiration date, and cvv)
4. After the page refresh (and guess since the total cart amount was greater that `0`) the payment form was shown properly

**Comment by jessy-p** [comment]
When fixed, please retest #5277  with the same fix.

**Comment by hamadgill** [comment]
any news on a fix ?

**Comment by fashuvo** [comment]
The main reason the payment form is absent is because two resources (`upe_checkout.js`, `checkout.css`) are not loading when we update cart total from zero to some other amount (_one way to do that is to switch from free shipping to paid shipping_). The files load when checkout page is refreshed, but they don't load when the cart total is updated via AJAX.

Based on my discussion with other colleagues, one way to resolve the issue could be to load the resources separately, even if the cart total is zero.

**Comment by jessy-p** [comment]
Adding the below code to `register_scripts` in `WC_Payment_Gateway_WCPay` makes the page load the needed scripts. Need to verify if this can be a proper solution.
```
if( ! WC()->cart->needs_payment() ) {
	WC_Payments::get_gateway()->tokenization_script();
	WC_Payments::get_wc_payments_checkout()->enqueue_payment_scripts();
}
```

**Comment by hamadgill** [comment]
Sorry, can you explain further how to add and test this code? Where and how exactly.

Thanks

**Comment by csmcneill** [comment]
Hey @hamadgill—can you update to the latest version of [WooCommerce Payments](https://woocommerce.com/products/woocommerce-payments/?aff=10486&cid=1131038) and let us know if that resolved your issue?

**Comment by hamadgill** [comment]
> Hey @hamadgill—can you update to the latest version of [WooCommerce Payments](https://woocommerce.com/products/woocommerce-payments/?aff=10486&cid=1131038) and let us know if that resolved your issue?

Okay, I will test it and let you know the results.

**Comment by hamadgill** [comment]
Issue is fixed in recent update , Thank you.
