### ISSUE TITLE
Unable to refund a successful charge after a blocked payment

### ISSUE THREAD

**Issue by tijosh** [Automattic/woocommerce-payments#4771]
### Describe the bug

If a payment is blocked by a Radar rule (such as a postal code check failure), but there's a subsequent successful charge, that successful charge may not be able to be refunded.

The event says `A request to create a refund failed` with the body:

> "message": "This PaymentIntent (pi_abcdefghijklmnopqrstuvwxyz) does not have a successful charge to refund."
"type": "invalid_request_error"

Reported in 5436424-zen, 5303793-zen, 5564572-zen

p1655764075000849-slack-C7U3Y3VMY

### To Reproduce

Difficult so far to reproduce. Blocking with a Radar rule and subsequently successfully charging the `pi_` has proven to work in testing. Merchants continue to encounter this, though.

### Actual behavior

Order shows as refunded in WooCommerce, but the refund has failed in Stripe.

### Screenshots

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/35117248/190873178-309e306d-521d-4ba4-816d-897c65063ed6.png">

### Expected behavior

Order is refunded correctly.

**Comment by Brianmitchtay** [comment]
Seeing this come up again in 5606797-zen

In this case the refund attempt is trying to refund the Charge ID of one of the blocked payments, rather than the later charge ID of the successful payment. On the user's end they are getting an error in their order notes saying that there is no successful charge to refund. 

![CFLnyD.png](https://user-images.githubusercontent.com/45057772/193938139-83e8efaf-6aaa-42e8-aa72-62af1b0aa728.png)+)
Image link: https://user-images.githubusercontent.com/45057772/193938139-83e8efaf-6aaa-42e8-aa72-62af1b0aa728.png

**Comment by deepakpathania** [comment]
This happens in case an old `_charge_id` gets associated with an order and the subsequent webhook doesn't update it because of an existing one. 
We added overriding of meta keys by the latest webhook in #4854 and thus in the above scenario, the subsequent successful charge would get successfully linked to the order, as a result of which refund would work. It should be released as a part of `4.9.0` release scheduled for Oct 19th, 2022.

Closing this now, if the issue persists in subsequent releases, we can re-open to investigate further.
