### ISSUE TITLE
Why not using setcookie method?

### ISSUE THREAD

**Issue by sulmanpucit** [Automattic/woocommerce-payments#4776]
### Describe the bug
I was wondering why the PHP `setcookie` method is not being used [here](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payment-gateway-wcpay.php#L446). Any specific reasons for this?

I have not debugged in details. But this part seems to be causing issue with custom login and redirect  filter where they have `check_admin_referer` in place. It is resulting in nonce verification failure.

### To Reproduce
1. Install the Avada theme & plugins
2. Add a Login element on a page
3. Try to login from page created in step 2.

### Actual behavior
Due to `$_COOKIE[ LOGGED_IN_COOKIE ] = $cookie;` [wp_get_session_token](https://developer.wordpress.org/reference/functions/wp_get_session_token/) seems to be returning invalid token on `login_redirect` filter when custom login is used with `check_admin_referer` check. 

### Screenshots
<img width="1429" alt="Screenshot 2022-09-19 at 4 38 48 PM" src="https://user-images.githubusercontent.com/934675/191009107-92a84554-3d47-4c06-9a83-56258ce87f12.png">

### Expected behavior
Should be using PHP `setcookie` method.

### Desktop (please complete the following information):

* OS: All
* Browser All
* Version All

### Smartphone (please complete the following information):

* Device: All
* OS: All
* Browser All
* Version All

### Additional context
N/A

**Comment by RadoslavGeorgiev** [comment]
> I was wondering why the PHP setcookie method is not being used [here](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payment-gateway-wcpay.php#L446). Any specific reasons for this?

`setcokie` sets a header, which will be sent to the browser, meaning that the cookie will be accessible within PHP only from the next request, not the current one. This is not what we are seeking here.

We have this code in place in order to make sure that a nonce, generated before the user was registered and logged in during checkout, would still be verifiable afterwards. In order to avoid this conflict, we'll probably need to add some conditions to https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payment-gateway-wcpay.php#L445-L447.

**Comment by zmaglica** [comment]
Hi. Is this issue still relevant? Can I close it?
