### ISSUE TITLE
Multiple UPE - Saved Payment Methods Compatibiltity in Blocks Checkout

### ISSUE THREAD

**Issue by mdmoore** [Automattic/woocommerce-payments#5111]
### Describe the bug
On the `poc/upe-instances-multiplied` branch, checking out and saving non-UPE(card) payment methods from blocks checkout currently fails with following error message: 

`We're not able to process this request. Please refresh the page and try again.`

![image](https://user-images.githubusercontent.com/3473953/201412354-f267e8dc-7035-4031-99f0-291fbc754acb.png)

### To Reproduce: 

1. Enable UPE
2. Start a blocks checkout session
3. Attempt to pay using card while **Save payment information to my account for future purchases.** is checked

### Acceptance Criteria

- While UPE is enabled, completing checkout from blocks checkout with a credit card should process without error
- Cards can be saved when checking out from blocks checkout
- Changes made should be merged into `poc/upe-instances-multiplied`, not develop.

**Comment by mdmoore** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/5111?planning-poker) with Zenhub @FangedParakeet @timur27

**Comment by FangedParakeet** [comment]
I optimistically expect this to not require large amends, but voted `3` simply because the cause of this error is not immediately obvious or necessarily known at all, so I rounded my estimate up slightly.

**Comment by timur27** [comment]
> The root cause and the fix are relevant only to the Blocks implementation. There was nothing found/changed in the classic checkout flow. 

:bug: What exactly is wrong?
There is no `payment_method` field in the `payment_data` of the request body when the `/checkout` endpoint is being hit. Instead, there is a `paymentmethod` field provided. While [generating the payment method](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/blocks/generate-payment-method.js#L39-L48), we provide the `paymentMethod`, which is then [sanitized during the request dispatching](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/src/StoreApi/Routes/V1/Checkout.php#L581-L593), giving us `paymentmethod` in effect.

🤔 Why does this work with the UPE methods?
When processing the payment for UPE payment methods, [we also provide the field as ](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/blocks/upe-fields.js#L242)`paymentMethod`. However, [during the request handling](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/payment-methods/class-upe-payment-gateway.php#L431-L531), our current implementation is not getting the value of the `payment_method` from the request. Instead, `self::GATEWAY_ID` is used as a value for the `wc_payment_method` query argument. Regardless of whether this makes sense, I would like to focus on our current issue instead of changing the focus to this investigation. One thing essential for us at the moment is that neither `payment_method` nor `paymentMethod` is taken from the request body.

🤔 Why does this work with the saved card payment method?
While registering the payment method, [savedTokenComponent is used](https://github.com/Automattic/woocommerce-payments/blob/develop/client/checkout/blocks/index.js#L42), and the field is provided as `payment_method` as [part of the woocommerce-blocks implementation](https://github.com/woocommerce/woocommerce-blocks/blob/trunk/assets/js/blocks/cart-checkout-shared/payment-methods/saved-payment-method-options.js#L95).

:question: Why was the UI field updated to `payment_method` instead of updating the payment processing to take the `paymentMethod` field?
To not break saved payment method handling, which is provided by blocks (see the point above).
