### ISSUE TITLE
Multiple UPE - SEPA Payment Method Labels

### ISSUE THREAD

**Issue by mdmoore** [Automattic/woocommerce-payments#5114]
### Describe the bug
Under some condition(s), stored SEPA payment method labels are not appearing in all caps on the **My Account > Payment Methods** page. Instead, they're appearing as _Sepa iban_. The same is occuring in **Payment Options** section of blocks checkout.

<img src="https://camo.githubusercontent.com/f31acc22382119385d21b2e50b46fa5c5a5ec9c3fdecde90aab99bdfba79bb9c/68747470733a2f2f63646e2d7374642e64726f706c722e6e65742f66696c65732f6163635f313130343230362f675948647459" />

### To Reproduce

I haven't been able to reproduce this yet. It was discovered and reported in [this comment](https://github.com/Automattic/woocommerce-payments/pull/4670/#pullrequestreview-1174793520). 

1. Add a SEPA payment method at **My Account > Payment Methods > Add Payment Method** if one doesn't already exist
2. Navigate to **My Account > Payment Methods** and inspect the SEPA IBAN label

### Acceptance Criteria
The SEPA IBAN label should appear in all caps like so: 

<img src="https://user-images.githubusercontent.com/3473953/201150034-5024deac-d617-4b06-a543-41c7959ee238.png" />

**Comment by mdmoore** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/5114?planning-poker) with Zenhub @FangedParakeet @timur27

**Comment by timur27** [comment]
I was between `2` and `1` and went with `1` finally as it seems to be a straightforward change (probably another class field is provided for some pages or something similar), although we don't know the place yet and this made me think about `2` SP. When I now saw that majority voted for `2`, I was also okay with going in this direction since this estimate was taken into consideration by myself too.

**Comment by FangedParakeet** [comment]
I thought it should be a simple fix, but rounded up my estimate, as there might not be consistent steps to reproduce this issue, since this was an issue that I always encountered, but that @mdmoore was unable to replicate. I thought adding a little buffer might be helpful, since there is some uncertainty involved. On the other side of the coin, maybe it's just all in my head/local environment and this will be even simpler scenario to solve after all. 😆

**Comment by mdmoore** [comment]
It turns out that if the payment method label isn't one of those included in WooCommerce by default, [only the first character is capitalized](https://github.com/woocommerce/woocommerce/blob/abcd2a799ac3ba9c9a797ae1ff223a026d130849/plugins/woocommerce/includes/wc-core-functions.php#L1572). I wasn't able to reproduce this initially because WooCommerce Stripe was active on my site and it already [takes care of capitalizing SEPA IBAN](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/8be44eaf07ec3c980afb21cff22717bb1892fffd/includes/class-wc-stripe-payment-tokens.php#L49-L55).
