### ISSUE TITLE
Fix Duplicate Charges: Retry server(API) calls with idempotency headers

### ISSUE THREAD

**Issue by htdat** [Automattic/woocommerce-payments#5189]
### Acceptance criteria

Add `try/catch` mechanisms to crucial server calls (ex. creating intentions), and use the same idempotency header for all of those calls within the same PHP request.

We should not try to use the same header within separate PHP requests (calls to the client), this is already explained in the results in this comment paJDYF-6wC-p2#comment-15189

### Testing instructions

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'
4. Observe expected behaviour

### Additional context

paJDYF-6wC-p2#comment-15189

**Comment by dmvrtx** [comment]
> we don’t have the necessary logic to detect whether an error is a communication/server error (which should be retried), or one which requires the intent to be updated before further attempts

This point from the referenced discussion is highlighting why this issue is hardly doable on its own. After investigating server API I couldn't find a reliable way to determine if retry attempt is warranted. On the contrary, I believe that retries are something that should be handled on the server side.
