### ISSUE TITLE
Title and Description

### ISSUE THREAD

**Issue by SiR-DanieL** [Automattic/woocommerce-payments#532]
It is not possible for customers to change the title and description shown on the frontend. It is possible for other gateways, eg. Stripe:

![](https://d.pr/i/xDOrOD+)
**Image Link**: https://d.pr/i/xDOrOD+

**Comment by aprea** [comment]
Hi @LevinMedia, just wondering if you're able to provide a design review and feedback for the in-progress implementation?

## Old settings page

| Before | After |
|-|-|
|<img width="986" alt="old-settings-page-before" src="https://user-images.githubusercontent.com/1527164/121299726-338b0600-c939-11eb-991a-d171264ba7bb.png">|<img width="983" alt="old-settings-page-after" src="https://user-images.githubusercontent.com/1527164/121299759-3ede3180-c939-11eb-83f1-f811437e03c3.png">|

The question mark tooltip content:
- **Title:** `This controls the title which the user sees during checkout.`
- **Description:** `This controls the description which the user sees during checkout.`

These were borrowed from the Stripe plugin.

## New settings page
| Before | After |
|-|-|
|<img width="1059" alt="new-settings-page-before" src="https://user-images.githubusercontent.com/1527164/121299871-5ddcc380-c939-11eb-9305-3c1cd95366de.png">|<img width="1057" alt="new-settings-page-after" src="https://user-images.githubusercontent.com/1527164/121299892-6634fe80-c939-11eb-89c0-c92efd26a33c.png">|

---

For reference, this is what the Stripe payment gateway settings page looks like:

<img width="676" alt="old-settings-page-stripe" src="https://user-images.githubusercontent.com/1527164/121299977-85cc2700-c939-11eb-9151-92b97214a521.png">

**Comment by LevinMedia** [comment]
Heya @aprea ! Unfortunately, I think we should still hold off on adding this feature request. This issue should have been closed a long time ago, my apologies for that! 

Per the comment from @dechov above - disallowing merchants to change this was a deliberate choice. Now with the addition of the UPE around the corner, we're actually going to have to change the `title` property of the gateway dynamically in the checkout depending on how many payment methods are displayed, since it must describe one, or many available payment options available in the gateway. 

For additional context see p1622845195042100/1622845127.041900-slack-C022N4CHJ65
