### ISSUE TITLE
Multiple UPE - Create and implement split-UPE feature flag

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#5353]
### Description

Please see #5271 for more context on the necessity of this change.

For as long as we have been working on the split-UPE branch, we have simply re-used the existing UPE flag. Sadly this makes it challenging to roll this feature out gradually and also prevents us from downgrading as a fallback to the original undivided UPE. For this reason, we have decided to create a new split-UPE flag that we can use in parallel alongside the current UPE flag (`_wcpay_feature_upe`). This issue is to create this flag and implement it once and for all, hopefully following the wisdom shared in #5271.

This is a belated retroactive refactor that means we will have to undo some of our current work, in order to return previous UPE functionality and maintain it alongside the split-UPE code. This will probably be quite unpleasant. I'm sorry. 

### Acceptance criteria

* A new feature flag will be created for the split-UPE branch.
* Existing UPE feature flag will remain (`_wcpay_feature_upe`).
* A user should be able use the non-UPE checkout, UPE checkout, **and** split-UPE checkoutby enabling the respective feature flag. The split-UPE flag will override the existing UPE flag, but if the split-UPE flag is disabled, the user should be able to use either the legacy checkout or the UPE checkout, depending on the status of the single-UPE flag (`_wcpay_feature_upe`).
* Tests should be duplicated and separated for the split-UPE feature (separate tests for single-UPE and split-UPE).

### Additional context

#5271 
pc2DNy-2qG-p2#comment-3837

**Comment by FangedParakeet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/5353?planning-poker) with Zenhub @mdmoore @timur27

**Comment by timur27** [comment]
I gave `8` SPs because my hunch is we might face unexpected obstacles down the road. I also described some possible improvements [here](https://github.com/Automattic/woocommerce-payments/issues/5271#issuecomment-1371164973), which I took into account while estimating but which aren't necessary to be included in the scope.  

The main blocks in this puzzle for me are: 
1. Introduce a feature flag and the mechanism to manage three states from now on (`non-UPE`, `UPE`, and `split UPE`).
2. Bring the old implementation for `UPE` back without breaking the `split-UPE`. This includes not only back-end changes but the changes in the approach of rolling out the front-end scripts + adding some new ones similar to the `upe.js` we have.
3. Tests decoupling
4. Ensuring Blocks checkout works as well (well, this one is always on my list 😄 ).
5. Adjust Stripe Link compatibility (not sure if anything significant is needed there).
6. Performing extensive manual testing as part of code review, which I expect will take more time than the usual tasks or features we worked on recently.

I hope it's just me being a bit more pessimistic today, so I am happy to be convinced by someone that we can go with a lower estimation.

**Comment by FangedParakeet** [comment]
I think this will be at a minimum a single sprint's worth of time, which is why I am loathe to reduce my estimate from `5` SPs. However, I would be open to increasing the estimate in order to account for encountering unexpected surprises along the way. 

I voted for `5` SPs, because in my mind, referencing @timur27's list of puzzle blocks, 1, 2, and (maybe) 3 should be the minimum acceptance requirements for this issue. 4, 5, and 6 are things that in an ideal world would just magically work without any effort, but which I would not be opposed to opening new child issues for once this main work were completed. In that sense, `8` SP is probably a more realistic total estimate, but includes a buffer for unknowns that I would instead ignore until they arose. 

Either approach sounds good to me though, so between `5` and `8` points, I'll gladly bend a knee before your wisdom.

**Comment by timur27** [comment]
> 4, 5, and 6 are things that in an ideal world would just magically work without any effort, but which I would not be opposed to opening new child issues for once this main work were completed

no objections here 👍 

> This scope of [this](https://github.com/Automattic/woocommerce-payments/issues/5271#issuecomment-1371164973) refactor will extend a little further beyond the frontiers of our work, but as long as it doesn't cause too many headaches, I think it will be worthwhile.

I'm fine with keeping this refactor in mind with a note, as you mentioned, `as long as it doesn't cause too many headaches`.

> Either approach sounds good to me though, so between 5 and 8 points

Let's apply the majority rule and since you voted `4` and `5`, I'm ok with `5` SPs. I updated my estimate.
