### ISSUE TITLE
SameSite cookie warnings in checkout

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#546]
The following warnings concerning Stripe cookies appear in the JavaScript developer console when entering checkout. It does not appear to prevent successful checkout, however

> A cookie associated with a cross-site resource at https://stripe.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

> (index):1 A cookie associated with a cross-site resource at http://stripe.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**Comment by vbelolapotkov** [comment]
It's unclear what should we do here, if anything. Sending it for engineering review to continue exploration.

**Comment by zmaglica** [comment]
I think that the person who will be assigned to do this issue can perform their own research and ping Architects if needed. The main reason why I moved this issue is that we do know what needs to be done, and research and communication between different parties for more context and help can be the responsibility of the assigned person.

This is the part of the Gamma backlog porter duty to reduce the number of the issues in the Engineering review column.

**Comment by naman03malhotra** [comment]
This issue is not reproducible anymore.
