### ISSUE TITLE
Documentation for WCPAY_DEV_MODE

### ISSUE THREAD

**Issue by helgatheviking** [Automattic/woocommerce-payments#5461]
`define( 'WCPAY_DEV_MODE', true );`

Sets the plugin into a developer's testing mode.. so you can use and test the plugin without a real account. But you have to go look that up in source every time. Could that be added to the plugin's readme.txt (and/or readme.md) file so it's publicly documented?
﻿

**Comment by csmcneill** [comment]
Hey @helgatheviking! We have public-facing documentation about this feature here: https://woocommerce.com/document/woocommerce-payments/testing-and-troubleshooting/dev-mode/

The `README.md` file also has some information about testing WooCommerce payments here: https://github.com/Automattic/woocommerce-payments#test-account-setup

Since we already have this information added to the `README.md`, I'll go ahead and close this issue.

**Comment by csmcneill** [comment]
I'm flagging @aheckler here to see if we want to add anything additional about WCPay to the `README.md`.

**Comment by helgatheviking** [comment]
Hmm... should have seen the link in the readme. I did actually look there! :sweat_smile:

**Comment by helgatheviking** [comment]
@csmcneill Hi Chris... as a follow up. Does `WCPAY_DEV_MODE` get the plugin working on a local site? If not, is there anything I can do for that?

**Comment by aheckler** [comment]
@helgatheviking WooCommerce Payments sites must be able to connect to WordPress.com, even in dev mode. Thus, it’s not possible to run WooCommerce Payments locally unless you expose that local site to the Internet with [ngrok](https://ngrok.com/) or a similar tool.
