### ISSUE TITLE
Subscriptions decimal points format is unexpectedly governed by customer currency

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#5488]
### Describe the bug

When customer currency is set to zero-decimal currency, eg. JPY, the price format on My Account > Subscriptions page is changed accordingly. This is unexpected. I think the currency format should follow the currency of when the subscription was purchased.

### To Reproduce

1. Enable [multi currencies](https://woocommerce.com/document/woocommerce-payments/currencies/multi-currency-setup/#section-2) and add some currencies, eg `EUR` and `JPY`.
2. Buy a couple of subscriptions with different currencies. You can switch currency by adding `currency` parameter in the query string of a shop or product page, eg. `/shop?currency=JPY`
3. Go to My Account > Subscriptions page.

### Actual behavior

Notice when customer currency is set to a zero-decimal currency, ie `/shop?currency=JPY`, the prices shown have no decimal points. When customer currency is set to a non zero-decimal currency, ie `/shop?currency=USD`, the prices shown have decimal points.

### Screenshots

https://user-images.githubusercontent.com/73803630/215522440-fa388e48-284e-4345-8a36-2625e102b06c.mov

### Expected behavior

The currency format should follow the currency of when the subscription was purchased.

### Additional context

This might not only affect subscription but it was what I observed when I was testing a PR (https://github.com/Automattic/woocommerce-payments/pull/5432).

**Comment by zmaglica** [comment]
Hi @dwainm . It looks like that team Sigma could work on this issue. Do you maybe have it under your radar? I have to prioritize it and if you folks are planning to work on the issue, perhaps you could include it in your backlog and prioritize it according to your plans and bandwidth.

**Comment by dwainm** [comment]
Hi @zmaglica , I'll add it to our backlog for the next sprint.

**Comment by jessepearson** [comment]
I started looking into this the other day and compared how prices are built between the Orders page and the Subscriptions page, and the totals on the Orders page go through `WC_Payments_Explicit_Price_Formatter->get_explicit_price` via the `woocommerce_get_formatted_order_total` filter. This makes each total on the Orders page reflect the currency formatting of the order itself.

The Subscriptions page totals are built differently and will likely require some _finessing_ in order for them to reflect the formatting based on the currency from the subscription itself. The amounts get passed through `wc_price()` , and that's where the formatting comes from. Even though the correct currency is passed to `wc_price()`, there are no formatting options passed (such as the decimal and thousands separators), so the formatting from the current selected currency is used.

**Comment by jessepearson** [comment]
I have this _mostly_ fixed in the PR, however, I have found something that I don't see an easy fix for. When the My Subscriptions page is loaded, the `get_my_subscriptions` method calls `wcs_get_users_subscriptions`, which gets all of the customer's subscriptions. Subs are just orders, so as they are being "read", their props are added, including prices like the totals. While this is happening, the current currency selected governs any sort of rounding for totals. So, if there's a subscription for 10.99 and JPY is in the selector, the total gets rounded to 11 due to JPY is a zero decimal currency.

**Comment by jessepearson** [comment]
The issue in the above comment is also present when you view a single subscription in the My Account area.

I think at this point I need to create tests for my PR and submit it for review, as it fixes the initial issue, but not the secondary issue.

The secondary issue may only be able to be fixed by a hack where we return the value found in the database for when `wc_get_price_decimals()` is called during the call to the `myaccount/subscriptions.php` template via the `woocommerce_before_template_part` action.

Also noting that `wcs_get_users_subscriptions` is called at least 3 times when that template is loaded, seems inefficient.

**Comment by jessepearson** [comment]
Created new issue for the additional bug mentioned above:

* https://github.com/Automattic/woocommerce-payments/issues/7537
