### ISSUE TITLE
Include the client IP and/or site URL in requests sent to server

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#5498]
### Description

In some instances it can be helpful in debugging and troubleshooting issues to know where a request sent to server originated.

To give one example, when a WCPay Subscription is paused unexpectedly it can be helpful to confirm the request originated from the expected live site - not a staging or development environment.

The feature request has broader use too if there's ever a situation looking through logs where it might be useful to confirm where the request came from. eg Sites experiencing the identity crisis issue (IDC).

### Acceptance criteria

* All server requests include the IP address and/or URL to identify the current site sending the request.

**Comment by zmaglica** [comment]
I am putting this into engineering queue since we have to check with other parties (legal, ...) to check all necessary details.
Furthermore, we can get IP address and host from the client request and use it according to our needs. I am not sure do we use them (log them). In acceptance criteria, this data is already available, since PHP natively provides client IP and client host. I am not certain how we use the host and IP after that, so it might be a good idea to provide more context on where to use IP (or host) and in what situations.

**Comment by haszari** [comment]
The goal here is to add info to request logs that allows support folks or merchants to confirm the origin of requests sent to WCPay server. This could be the site URL or IP, or it could also potentially be a unique key or hash value – anything that can help identify if the request came from the primary site vs. a staging or duplicate/dev site.

**Comment by htdat** [comment]
It sounds like our internal log tool on the server side has already had all needed info here. See more paJDYF-7bJ-p2#comment-16184

Instead of working on anything code-related, we might update our documents for devs and HEs.

**Comment by haszari** [comment]
@james-allan – in light of @htdat 's comments, and our limited ability to definitively know where requests are coming from, do you think we need this issue open anymore? Maybe we can close (no next step).

**Comment by james-allan** [comment]
I think this is good to close. Any attempt we would have made to include the site URL and IP address would have the same trustworthy issue as the site URLs already sent by the Jetpack connection.

The site URL is already included in our logs and if we want to pursue including the IP address in server logs, we'll need to update the server to include it.
