### ISSUE TITLE
Currency off in analytics when using WCPay Multicurrency with another gateway

### ISSUE THREAD

**Issue by jobthomas** [Automattic/woocommerce-payments#5584]
### Describe the bug

When using the WCPay native currency switching, the results I get for South African Rand, are very off from what they should be in the analytics. 

* Enable ZAR as currency
* Pay for an item in another gateway different from WCPay, e.g. Stripe.
* Check in Analytics

10 USD should be about 180 ZAR. 

This album is 15 EUR on my site, so R290 is fairly on point (it's 290.32 when I just checked). It's logical that my checkout then is 580 ZAR (the equivalent of 30 EUR):
 
![Screenshot 2023-02-20 at 15 07 20](https://user-images.githubusercontent.com/8783673/220117315-77c149f9-4a3d-4650-86f8-b8acbb7ea743.png)

However, when I go to Analytics > Orders, the corresponding order there is 542.42 EUR. I have no idea where that would be coming from, especially since the conversion from EUR to ZAR was correct.

![Screenshot 2023-02-20 at 15 09 53](https://user-images.githubusercontent.com/8783673/220117866-1ab4ad40-fae3-4edc-bdc3-cb6be46688f4.png)

### Note

Not part of a ticket, but found out while troubleshooting another ticket.

**Comment by htdat** [comment]
Hi @jobthomas, I could not replicate the issue. I've tested on my site with WCPay latest stable version 5.4.0. 

#### The page for this order (via WP Admin > WooCommerce > Orders): 

![edit-order](https://user-images.githubusercontent.com/10045087/220279864-bc3f10b3-ee65-46dc-b696-2c7e09f46ff4.png)

#### WP Admin > Analytics > Orders: 

![analytics-order](https://user-images.githubusercontent.com/10045087/220280517-3fb0f686-48a1-47cd-ae5c-0fe5dcb9a6d4.png)

#### Transaction detail for this payment under WP Admin > Payments > Transaction: 

![wcpay-transaction-details](https://user-images.githubusercontent.com/10045087/220279973-65276e68-34ef-43e9-9ad5-ad6325d5b788.png)

---- 

> However, when I go to Analytics > Orders, the corresponding order there is 542.42 EUR. I have no idea where that would be coming from, especially since the conversion from EUR to ZAR was correct.

Based on my test above, this would be the converted value to your store currency (EUR) and it's shown in the transaction detail. 

I guess that this might be a conflict with another plugin/theme or you use an older version of WCPay?

**Comment by jobthomas** [comment]
I've gone back and reviewed: the tricky part is that I used WC Pay to enable the currency switcher, but in this case, I used Stripe to pay for the subscription. Happy to move this to a different repo if that makes more sense.

**Comment by htdat** [comment]
> Happy to move this to a different repo if that makes more sense.

@jobthomas - I think it makes sense to keep it here (see more below). I've also updated the issue description and title a bit to reflect this new bit of information.

> the tricky part is that I used WC Pay to enable the currency switcher, but in this case, I used Stripe to pay for the subscription.

This could explain why the issue happened on your site only. The magic is function [update_order_stats_data](https://github.com/Automattic/woocommerce-payments/blob/0638affce68d58555f2bd2dd19f266895b54b2ac/includes/multi-currency/Analytics.php#L201-L201) that converts the shopper currency (ZAR in this case) to the store default currency (EUR in this case). 

However, this function relies on the order meta `_wcpay_multi_currency_stripe_exchange_rate` that's only available when checking out with WCPay.

@dmallory42 as the PR author @Automattic/sigma @Automattic/moltres, would love to have your opinions on this issue? I am uncertain if we have any plan to support this specific use case between WCPay native multicurrency feature and another payment gateway.

**Comment by jobthomas** [comment]
Happy to give you access to my test site by the way if you need to review further. 

My two cents: if we offer a currency switcher via WC Pay we should make that other payment gateways (especially those that we support) should be able to use it as well, otherwise we need to build in a conditionality where we hide the payment gateways if another currency than the store default one is used.

**Comment by dmallory42** [comment]
Thanks for raising this issue @jobthomas! 

This isn't a use case we originally considered when developing the Multi Currency functionality. I'm in agreement here that we should either add analytics support for orders made in other payment gateways, or prevent checking out in another gateway when using multi-currency unless it is supported. 

This issue would be on the radar of @Automattic/sigma now. 🙂

**Comment by johndcoy** [comment]
Another report of this from 43434717-hc

order paid for using wc pay ( Screenshot 1 ) shows as USD in reports (Screenshot 2 ) and analytics ( Screenshot 3 )

Thes above chat is a WordPress.com user.

Screenshot 1:
![Screenshot 2023-05-13 at 11 04 44 AM](https://github.com/Automattic/woocommerce-payments/assets/4634416/cc2b0918-f988-4ccf-bfef-f73a9b3b4015)

Screenshot 2:
![Screenshot 2023-05-13 at 11 07 48 AM](https://github.com/Automattic/woocommerce-payments/assets/4634416/ffbac8e6-f8d1-4676-b2fc-b5dd29a460fd)

Screenshot 2:
![Screenshot 2023-05-13 at 11 08 43 AM](https://github.com/Automattic/woocommerce-payments/assets/4634416/70a917ac-ff50-41d7-8b89-b64bd1d6b613)

**Comment by jessepearson** [comment]
@johndcoy From the screenshots it looks like you're referencing the reports under WooCommerce > Reports. This is an issue we are not able to correct. We initially brought this to the WC core dev team when we were developing the MC feature, and they informed us that the WC core reports were no longer being actively worked on in favor of the Analytics section.

I've tried to find this conversation, but it was 2 years ago and I am not sure if it was P2, Slack, or GitHub.

**Comment by johndcoy** [comment]
@jessepearson Correct, only the second screenshot was specific to Reports while the others were from Analytics. I only mentioned it because the user did but I'm good with the focus only being on Analytics.

**Comment by jessepearson** [comment]
@johndcoy Okay, gotcha. The same site was brought up in a slack thread I was pinged on, so I have been looking into it. I found that there are some meta values not added to the order, and that's likely the reason. I haven't been able to replicate the issue directly, but I did find if I delete those same meta values from my order, I have the same results.

Basically there should be an exchange rate and default currency on the order. The exchange rate saved is used for the analytics conversion. Since it's not present, it's doing a 1:1 conversion from KRW to USD.

This is what Dat mentioned above as the possible cause of what Job is seeing, however, I don't think the two are related. I think Job's instance is a possible fluke in conversions, because if the data was missing it would be a direct 1:1 conversion like we're seeing on this other site.

The slack thread is here: p1684481168894269-slack-C7U3Y3VMY

As mentioned there, the only solution I see to fix this would be manually enter the conversion data into their order. The conversion would just be based on the amounts listed in the order. We would need to make sure the customer is okay with us manually updating that. If we can't do it via phpMyAdmin, we'd need to do it via ssh (if the db is writable). If neither of those work, an external plugin or one off plugin would be needed.

**Comment by jessepearson** [comment]
@jobthomas Are you still able to replicate this issue in your store with the latest versions of everything? I get the correct amounts. The product cost is 10 USD and I selected ZAR on the front end and checked out, making the cost 153 ZAR. The conversion back is 10.02 USD due to price rounding settings.

![Screenshot 2023-05-24 at 8 29 46 AM](https://github.com/Automattic/woocommerce-payments/assets/4634416/43396c49-b5c1-4782-9486-0d2e7b7b5795)

**Comment by jobthomas** [comment]
I can no longer reproduce it.

**Comment by jessepearson** [comment]
> I can no longer reproduce it.

Thanks for taking a look and testing it again @jobthomas
