### ISSUE TITLE
Deposits overview shows wrong deposit timing information

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#5662]
### Describe the bug

If I have my deposit schedule set to **Monthly > Last day of the month**, but then I look at the **Payments > Overview** page, it says "Deposits set to monthly on the 31st." This could potentially be confusing, as not all months have 31 days.

### To Reproduce

1. WC + WC Pay test site + Stripe account set up.
2. Under Payments > Settings, set the deposit schedule to the last day of each month.
3. Go to Payments > Overview.
4. Observe:

![Screenshot taken on 2023-03-01 at 15 45 18 UTC@2x](https://user-images.githubusercontent.com/5512652/222189812-faf970eb-7f52-49de-8911-7cc6162abdb1.png)

**Comment by james-allan** [comment]
This will be fixed in https://github.com/Automattic/woocommerce-payments/pull/5617. 🙂 

The deposit screen will now say: "Deposits set to monthly on the last day of the month." when that option is chosen

<img width="714" alt="Screenshot 2023-03-02 at 5 36 35 pm" src="https://user-images.githubusercontent.com/8490476/222362034-3740534a-32a1-46ed-b9ed-87a6534997ec.png">

**Comment by aheckler** [comment]
Ahh, sorry for the dupe report then! 👍
