### ISSUE TITLE
Simplify deposits UI - Add note about deposit schedule

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#5699]
### Description

This issue is part of the larger Epic to add the Payments Overview Deposits card (https://github.com/Automattic/woocommerce-payments/issues/5686).

As part of this issue, the card should altered to include the following acceptance criteria: 

### Acceptance criteria 

* "**Deposit history**" heading
* "Your deposits are dispatched **automatically every `{frequency}`**" note. 
* Note should support all valid deposit schedule states, including [temporarily disabled aka deposits suspended](https://woocommerce.com/document/woocommerce-payments/deposits/why-deposits-suspended/).

![image](https://user-images.githubusercontent.com/8490476/223959681-dbeb3c00-1572-4f31-b984-15016a2bcf08.png)

### Designs

P2: paJDYF-7fi-p2

![image](https://user-images.githubusercontent.com/8490476/223936763-804af22f-2f9d-41f3-98e9-0017b0cf4d43.png)

### Additional context

Project: pdjTHR-2i5-p2

**Comment by brucealdridge** [comment]
Merchants are currently unable to set the deposit schedule to `manual` but there are cases where this can happen, either when the account is in the new account waiting period (this is handled in #5727) or when [deposits are suspended](https://woocommerce.com/document/woocommerce-payments/deposits/why-deposits-suspended/)

**Comment by haszari** [comment]
> Merchants are currently unable to set the deposit schedule to manual but there are cases where this can happen, either when the account is in the new account waiting period (this is handled in https://github.com/Automattic/woocommerce-payments/issues/5727) or when [deposits are suspended](https://woocommerce.com/document/woocommerce-payments/deposits/why-deposits-suspended/)

Thanks for the heads up @brucealdridge – there's a state not covered explicitly in the design. Clarifying this. 

- [Stores can have deposits blocked by the platform for fraud/risk reasons](https://woocommerce.com/document/woocommerce-payments/deposits/why-deposits-suspended/). 
- When this happens, there's a special WCPay flag to indicate the status - `deposits_blocked`. 
  - The deposit schedule is also set to `manual` in Stripe to suspend automatic payouts. 

### Existing UI
When in this state, the existing UI currently shows the deposit schedule as `Deposit schedule: Temporarily suspended`:

![image-13](https://user-images.githubusercontent.com/4167300/226737915-980d38e9-cfde-4321-800e-6096c1e5621a.jpeg)

## New UI should be consistent, design TBC
The new UI should show this state consistently. We don't yet have a design for this, though we can adapt something in the mean time (implementing this note & state is not blocked on design IMO). 

Sketching out a proposal for the new UI:

**Next deposit**

Your deposits are temporarily suspended (learn more)

# Next steps
- Whoever works on this issue should add all necessary states for the message (including temporarily suspended due to `deposits_blocked`). Please adapt the wording above, use existing link etc. 
  - I've added to acceptance criteria to ensure it's not missed.
- @elizaan36 let us know if you have feedback or designs for this state. I've only considered the schedule summary note – there might be implications for balances etc or other UI elements.
- When this is demoable we can check in with stakeholders (design, product, fraud) and handle any design changes as follow up.

**Comment by elizaan36** [comment]
> @elizaan36 let us know if you have feedback or designs for this state. I've only considered the schedule summary note – there might be implications for balances etc or other UI elements.

How does the status of `Estimated`, `Pending` and `In transit` deposits change when an account is suspended? Do they keep the same status?

**Comment by james-allan** [comment]
> How does the status of Estimated, Pending and In transit deposits change when an account is suspended? Do they keep the same status?

We (WC Payments server) stop estimating upcoming deposits when the account is suspended - ie there will no estimated deposit. `Pending` and `In-transit` ones are already in Stripe's processes so unlikely changed by an account being suspended.

**Comment by elizaan36** [comment]
This state feels like it deserves an alert notice style. 

First I tried the text "Deposits are temporarily suspended. Learn more" below the Deposit history header.

![Overview - Balances - Single currency - Manual deposits - No task](https://user-images.githubusercontent.com/5121465/228708740-f99655b5-a1ce-4805-ae75-95fa430cc8a8.png)

Then tried the notice in the same location, which seems to convey the information with the right level of urgency. What do you think?

![Overview - Balances - Deposits suspended](https://user-images.githubusercontent.com/5121465/228709246-41d16b6b-bf35-43ef-b2f9-aa7255133aef.png)

**Comment by james-allan** [comment]
> Then tried the notice in the same location, which seems to convey the information with the right level of urgency. What do you think?

That works for me. I agree that the notice does a better job of communicating the nature of the issue.
