### ISSUE TITLE
Simplify deposits UI - Add tooltips/help links to each balance fund type

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-payments#5724]
### Description

This issue is part of the larger Epic to add the Payments Overview Deposits card (https://github.com/Automattic/woocommerce-payments/issues/5581).

As part of this issue, the card should altered to include the following acceptance criteria:

### Acceptance criteria 

1. Check the design comments in Figma for the latest copy.

* **Available funds**: _"The amount of funds available to be deposited. Learn more."_
    - 🔗 https://woocommerce.com/document/woocommerce-payments/deposits/deposit-schedule/ 
    - If the available amount is negative, the text should display as: "Learn more about why your account balance may be negative." which links to: https://woocommerce.com/document/woocommerce-payments/fees-and-debits/account-showing-negative-balance/
* **Pending funds**: _""The amount of funds still in the X day pending period. Learn more."
    * 🔗 https://woocommerce.com/document/woocommerce-payments/deposits/deposit-schedule/
    - ❗ Note: The X will need to vary based on the merchant country and their pending period. https://woocommerce.com/document/woocommerce-payments/deposits/deposit-schedule/#section-2
* ✂️ **Cut from scope** ~~**Reserved funds**: _"The amount of funds being held in reserve. Learn more."_~~
    * ~~🔗 https://woocommerce.com/document/woocommerce-payments/our-policies/reserves/~~ 

2. Use `gridicons-help-outline` from https://github.com/Automattic/gridicons.
```tsx
import HelpOutlineIcon from 'gridicons/dist/help-outline';
<HelpOutlineIcon size={ 18 } />
```

![224232319-3dd3bb14-b0c8-469f-8fdc-8557fcc82199](https://user-images.githubusercontent.com/8490476/224243472-f0710153-98be-49af-85cf-0a0b9b7cb4cf.png)

### Designs

P2: paJDYF-7fi-p2

![image](https://user-images.githubusercontent.com/8490476/224232319-3dd3bb14-b0c8-469f-8fdc-8557fcc82199.png)

### Additional context

Project: pdjTHR-2i5-p2

**Comment by haszari** [comment]
We could potentially split this out to three separate issues (one per instance). 

Note – these help tooltips will contain links out to text so they behave different to other help icons in WooCommerce. We'll need to override the component to tweak behaviour:

- Tooltip should display on click (instead of hover). Mouse cursor should show clickable affordance (i.e. link hand pointer on mouseover/hover).
- Clicking anywhere outside tooltip will close it.
- Tooltip icon color should use store theme (link accent color).
- Tooltip clickable area should be at least 16px square ([ideally more](https://web.dev/accessible-tap-targets/#:~:text=A%20minimum%20recommended%20touch%20target,target%20size%20up%20to%2048px.)).

@elizaan36 please comment if I've missed any relevant details.

We could potentially split off a separate task for making a component/abstraction for the above; or implement as part of the first instance.

**Comment by Jinksi** [comment]
Is it suitable to write tests (e2e?) that verify that these links exist, in case of future changes to these urls?

**Comment by Jinksi** [comment]
We should keep links to public docs in a central location within the codebase to assist in updating them in the future.

**Comment by Jinksi** [comment]
The icon in the design looks like it matches one of the following:

1. `gridicons-help-outline` from https://github.com/Automattic/gridicons
```
import HelpOutlineIcon from 'gridicons/dist/help-outline';
```

<img width="74" alt="image" src="https://user-images.githubusercontent.com/3147296/225770872-0f86db75-ba1d-4f3e-9522-c6f629f101cc.png">

~2. The `wcicon-query` icon from https://github.com/woocommerce/woocommerce-icons.~

**Comment by elizaan36** [comment]
Nope we should use the `help` icon from WP/Gutenberg.

**Comment by Jinksi** [comment]
Thanks @elizaan36, I've edited the comment with that one and updated the description 👍

I was searching for icons starting with "qu" for "question mark". 🙄
