### ISSUE TITLE
Ability to measure view and user interaction with the Balance card on Payments > Overview page

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#5880]
We need to be able to:
- Count how many times user view the card. We might be able to use Payments > Overview page view ([read](https://github.com/Automattic/woocommerce-payments/issues/5771#issuecomment-1468699248)).

- Count user's interaction with the currency tab.

![224581592-419d1027-d343-4ccd-88a0-539c4219a8f9](https://user-images.githubusercontent.com/8490476/224584190-997203b1-3507-4441-b684-73782799602a.png)

- Count user's interaction, clicking, to open and close the tooltip.

![224232319-3dd3bb14-b0c8-469f-8fdc-8557fcc82199](https://user-images.githubusercontent.com/8490476/224243472-f0710153-98be-49af-85cf-0a0b9b7cb4cf.png)

**Comment by haszari** [comment]
@shendy-a8c are you in progress on this or should someone grab it and get a PR up today so we can hopefully include in WCPay 5.9 code freeze?

**Comment by haszari** [comment]
Regarding the events we could add, here's my thoughts:

- Count how many times user view the card. We might be able to use Payments > Overview page view (https://github.com/Automattic/woocommerce-payments/issues/5771#issuecomment-1468699248).
  - I agree, let's use existing event `wcadmin_page_view path=payments_overview_view`
- Count user's interaction with the currency tab.
  - I think this is an important event to track, since it's the primary purpose of the card. Could use a new event: `wcadmin_wcpay_overview_balances_currency_tab_click` with prop `selected_currency=GBP|USD|HKD` (etc)

> Count user's interaction, clicking, to open and close the tooltip.

I don't think we need to track help links / tooltips, consistent with not tracking notices (in other PRs).

@souravdebnath1986 let us know if there's any extra tracking you want us to implement – comment with the user events/interactions and the questions you want the tracking to answer. (i.e. if I've missed anything above)
