### ISSUE TITLE
Ability to measure view and user interaction with deposits detail page

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#5885]
We need to be able to:

- Count how many times user view the deposits details page.

- Count user's interaction with the search bar.

- Count user's click on the Download button.

- Count user's click on the column header to sort the table by.

- Count user's interaction with the column columns show / hide UI from the three dots button at the top right of the table.

<img width="1590" alt="Screenshot 2023-03-28 at 20 29 28" src="https://user-images.githubusercontent.com/73803630/228252712-a1980bea-f092-4cb8-be09-7d1226f0df8a.png">

ps: I see slight difference when deposit is estimated and not.

**Comment by brucealdridge** [comment]
> Count how many times user view the deposits details page.

This is currently trackable via `wcadmin_page_view` `path=payments_deposits_details`

> Count user's click on the Download button.

This is currently tracked via `wcadmin_wcpay_transactions_download`. There is no current way to differentiate between when this event is fired on the Transactions Page or the Deposit Details page. To rectify this #6281 adds `wcpay_deposits_detail_download` when a merchant starts a download from the deposit details page.

> Count user's interaction with the search bar.
> Count user's click on the column header to sort the table by.
> Count user's interaction with the column columns show / hide UI from the three dots button at the top right of the table.

I opted not to add any tracking to these events keeping in line with the changes in #6225. Rather than tracking all the things we should just add tracking to the most important interactions for now.
