### ISSUE TITLE
White text on white background

### ISSUE THREAD

**Issue by edmundaskozlovskis** [Automattic/woocommerce-payments#5958]
### Describe the bug
Invisible text in fields (card number, expiration, CVC). Card number value is not empty.

### To Reproduce

1. Go to checkout
2. Click on the field
3. Text invisible

### Screenshots
![image](https://user-images.githubusercontent.com/129834631/229720361-93c5b607-a4ae-487d-8a8c-ca17dadb6ae9.png)

### Expected behavior
I expected black color text if a wrong red text

### Desktop (please complete the following information):

* OS: win 10
* Browser: chrome
* Version: 111.0.5563.147

### Smartphone (please complete the following information):

* Device: Samsung s21
* OS: Android
* Browser: chrome
* Version

**Comment by csmcneill** [comment]
Howdy @edmundaskozlovskis! I wouldn't classify this as a bug, as this seems more of a conflict between WooCommerce Payments and the currently active theme.

By default, the card input field (`div.payment_box`) will have a light-gray background (`#f7f7f7`) with light-gray (`rbg(247, 247, 274);`) backgrounds in the input fields:

![Markup on 2023-04-09 at 19:56:48](https://user-images.githubusercontent.com/82999806/230805592-5e8399d2-4044-45c6-91bd-665ecc95d2b9.png)

However, even changing these colors to white (`#ffffff`) still shows the placeholder text (`--colorTextPlaceholder`) as a medium-gray (`#757680`):

![Markup on 2023-04-09 at 19:56:31](https://user-images.githubusercontent.com/82999806/230805838-02ab836a-be7f-4da8-863d-a671649094bc.png)

Since this does not appear to be a bug, please contact us at [WooCommerce.com > My Account > Support](https://woocommerce.com/my-account/create-a-ticket/?form=ticket). You may need to create an account before you can access that page. 

Please include a link to this issue thread so that we can keep track of what's already been done. We will be able to help you further there.

In the meantime, I will close this issue so that we can help you out via our direct support channels.
