### ISSUE TITLE
Success onboarding notice should be dismissable and with a different text

### ISSUE THREAD

**Issue by allie500** [Automattic/woocommerce-payments#5965]
### Description:

Earlier today, while testing a server PR, I needed to onboard a couple of new accounts. After successfully onboarding, I was shown the connection success notice. I _noticed_ that the header is missing the word _is_.

![wcpay-connection-success-card](https://user-images.githubusercontent.com/60988591/229902470-4fd63c1d-9841-4713-992d-d134328d20d5.png)

I believe the header string should read:

> Your store _is_ fully verified now!

### Acceptance criteria:

- The header is updated to: _"Your store is fully verified now!"_
- All tests pass.

**Comment by elizaan36** [comment]
I'll share the updated design here with the correct copy. There’s also an ellipses menu to dismiss the card.

<img width="709" alt="Screen Shot 2023-04-04 at 8 21 09 PM" src="https://user-images.githubusercontent.com/5121465/229957319-7a701c3d-eca5-4b94-8ac9-b1924def7899.png">

cc @daquinons Will you have a look at this as well? Is this part of the PO updates?

**Comment by daquinons** [comment]
@elizaan36 Thanks for the ping! Let's fix this, indeed :) 

Just so you know, two different messages are appearing on this success card. One after finishing the first step of PO, and the other one (the one this issue is about), after completing the second step or finishing the whole KYC. You can see the other message [here](https://github.com/Automattic/woocommerce-payments/pull/5742).

In the FINAL Figma, only the second one has the dropdown menu for dismissing.

My questions are:
- Do you want to modify both cards or only the one this issue refers to? (second step of PO and full KYC success messages). 
- I see the typography is also different from the previous design, with different font weights and letter spacing. Is this correct?
- Taking into account DropdownMenu is, according to [the Design guidelines from WordPress](https://developer.wordpress.org/block-editor/reference-guides/components/dropdown-menu/#when-to-use-a-dropdownmenu), a way to "choose an action or change a setting from a list", and here there is a single action ("Dismiss"), wouldn't a single x icon be more effective at providing a direct access to the action, with enough context for it being recognizable without the need of additional text?

Thanks!

**Comment by daquinons** [comment]
@elizaan36 An important note and extra context that I forgot to add: This notification is only shown once, after redirecting successfully from Stripe. Might not be necessary at all the dismissal of it, as is not something that will keep appearing after that first display :) I would understand a dismiss button if it was something fixed there!

Also, the rest of the notifications being displayed there are fixed and nondismissable, so if we want to make them dismissible, it would make sense to make all of them and not only this successful one! Still, I believe the dismiss action, because of the nature of the notifications, is not that necessary.

**Comment by elizaan36** [comment]
hey @daquinons 👋 

Yup, the copy has been updated for both screens since that PR. Here's the correct design from the Figma marked "Final" after copy review.

1. After finishing the first step of PO

<img width="707" alt="image" src="https://user-images.githubusercontent.com/5121465/230137266-e811543c-118c-43ad-add0-e06a4d032088.png">

There's no ellipses/dismiss action on this one in order to motivate the user to take their next steps. (Also, prior to getting any sales with WCPay the page is quite stark.)

2. After completing the second step or finishing the whole KYC

<img width="704" alt="image" src="https://user-images.githubusercontent.com/5121465/230137715-3f460972-ebbb-4cc8-bc54-52e62adde9f6.png">

The ellipses is a consistent pattern with the Dismiss action on the Woo Home tasklist. I don't think we should diverge from the style of other cards across the experience.

<img width="546" alt="image" src="https://user-images.githubusercontent.com/5121465/230138183-70b07fba-ac94-4f5b-82c2-cb2931812b75.png">

In this case, the dropdown would show "Dismiss" rather than "Hide this" since there's no way to show it again.

**Comment by elizaan36** [comment]
> Also, the rest of the notifications being displayed there are fixed and nondismissable, so if we want to make them dismissible, it would make sense to make all of them and not only this successful one! Still, I believe the dismiss action, because of the nature of the notifications, is not that necessary.

What are the rest of the notifications you're referring to here? Notices should be dismissible by default to give merchants control of the view. The "Things to do" task list can be hidden (with the control in the screenshot I shared above.)

**Comment by elizaan36** [comment]
> I see the typography is also different from the previous design, with different font weights and letter spacing. Is this correct?

The typography should ideally be using the WP components `Title Small` and `Body` for consistency overall. Text color is `Gray 900` for the title then for the body copy we have `Gray 700`.
