### ISSUE TITLE
Multicurrency - Geolocation users do not see Product Filter block picking up switched currency

### ISSUE THREAD

**Issue by nagpai** [Automattic/woocommerce-payments#5996]
### Describe the bug

When the Automatically switch customers to their local currency if it has been enabled option is enabled and the currency is set based on geolocation, the Filter by Price on a block-based shop page doesn’t update with the correct currency. 

### Actual behavior
The Price filter slider and the product price do not show the same currency

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### Additional context
Details and solution discussed here 
p1680614583759689-slack-CGGCLBN58

cc @daquinons  , @eduardoumpierre

**Comment by daquinons** [comment]
We were experimenting with some possible fix and at the end @dmallory42 suggested [this](p1680837059453189/1680614583.759689-slack-CGGCLBN58)

> Probably the easiest way is to update get_stored_currency_code to have an extra bool param like $fallback_geolocation and only use the new logic [you added](https://github.com/Automattic/woocommerce-payments/pull/4442) if that value is true (that way we can set it to false when we call it in other contexts)

Allie: Editing to pull the Slack link out of the anchor text 'this', it is returning a GH not found page:
p1680837059453189/1680614583.759689-slack-CGGCLBN58

**Comment by dwainm** [comment]
Moving this on to Sprint 6 where we might focus on multi-currency as a maintenance focus.

**Comment by tpaksu** [comment]
I've tried to fix this problem about blocks with several workarounds, but all of them were basically hacks, you can see the discussions about it in the https://github.com/Automattic/woocommerce-payments/pull/6052 and on p1681896818105739-slack-C02UBB1EPEF, but since the blocks are using StoreAPI, it pulls the data directly from the database, and we don't have any means to hook into that to convert the prices. There's no easy way to fix the integration w/ blocks. Since WCPay is just another plugin, which can't force another team to do adaptations to MC, I would suggest starting the discussions for moving multi-currency into WC Core. Putting this on-hold until it is solved.

**Comment by dwainm** [comment]
@tpaksu is there any change we can recommend in core to allow us to get this working? What should they change to make this easier for us and other plugins to affect those values?

**Comment by tpaksu** [comment]
@dwainm probably asking the relevant teams to add hooks that we can use in the StoreAPI for supporting currency conversions on the API level will be a good starter.

**Comment by bborman22** [comment]
Closing as a duplicate of #6024. I'm opting to keep #6024 because it captures the key part of the discussion here that this will require some work within core (Store API) and also provides some proof of concept branches for that work.
