### ISSUE TITLE
New UPE rollout recipe

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#6023]
### Description

The New UPE is essentially the split-UPE with deferred, server-side payment intent confirmation. Visually and functionally it appears basically the same as the existing split-UPE; however, the client-side is bereft of payment intent details, which can be confirmed securely on the server instead, and since we can perform this confirmation on the server with the UPE, we are now able to replace the card element with a new UPE payment element and still support WooPay.

We are working on a PoC that is actually an MVP in #5869; this feature will remain behind a client-side feature flag. This issue is to devise and decide how we will eventually release this feature to our users.

For users who are already using the split-UPE, this change should be relatively seamless and not really affect any of their interactions with the plugin. In theory, it appears as if would be relatively straight-forward to upgrade this subset of users automatically. However, for users who are still using the legacy UPE, we have not yet developed a natural way to migrate them to the split-UPE, without disabling and re-enabling the UPE. Similarly, there is no natural path to deliver the new UPE to them either.

Questions posed by this issue:
- In which scenarios should the new UPE feature flag be enabled for users?
- How can we migrate legacy UPE users?
- What kind of compatibility will we need to persist for legacy versions of the UPE, especially considering that legacy UPE is by its nature insecure? 

### Acceptance criteria

We will need to include many relevant WCPay stakeholders to ensure that we have a unified plan to release this new feature. This could culminate in a P2 post or alternatively a brief discussion and declaration of intent on this issue.

### Additional context

#5770

**Comment by FangedParakeet** [comment]
Seeking the wisdom of @c-shultz & @pierorocca here for guidance towards our eventual [new UPE](https://github.com/automattic/woocommerce-payments/issues/5770) rollout plan. 

As of now the original split-UPE is the default payment gateway offered to new WCPay users; existing WCPay users are able to enable the split-UPE via the "new checkout experience"; whereas legacy UPE users currently do not have a direct pathway to the split-UPE without manually disabling and re-enabling the "new checkout experience". 

Upgrading from the original split-UPE to the new UPE should not involve any visual or functional changes to either customers' checkout nor merchants' settings pages--other than the credit card fields changing to the newer payment element (see differences [here in this related issue.](https://github.com/Automattic/woocommerce-payments/issues/5273)). Theoretically, this upgrade could be somewhat seamless; however, upgrading legacy UPE users will obviously transform the checkout pages of those with additional LPMs enabled. Nonetheless the legacy UPE does leave us vulnerable to certain security risks, so it seems like upgrading these users should be a priority.

Having laid this groundwork, for split-UPE users, legacy UPE users, and those using neither, should we decide to automatically upgrade any of these store owner segments to the new UPE or should we instead provide a new toggle for store owners (like the previous "new checkout experience")? Additionally, from a developer perspective, it will be very desirable to one day unite all of our payment gateways into a single accepted solution: if the answer to the previous question is to initially provide users with a choice to opt-in to the new UPE, at what threshold will we desire to instead enforce users to enroll into the new UPE?

I am eager to hear your thoughts and thank you in advance for sharing them. 🙏

**Comment by pierorocca** [comment]
Apologies for the delay. Will have feedback inline with past guidance @FangedParakeet

**Comment by pierorocca** [comment]
@FangedParakeet thanks for bringing this up. What will help round out the plan is the timing of the Phase 2 work to implement Stripe's new API that resolves the security concern and the issue around intent control. See criteria section below.

**Goals**: 1) Get all merchants to a single version, Split UPE, of the WCPay gateway 2) Remove the merchant settings opt-in / opt-out of the "new checkout experience"
**Existing Merchant Segments**: 1) non-UPE 2) legacy UPE 3) Split UPE

**Short term:** 
1. No new merchants to be onboarded to legacy UPE which we've effectively done
2. non-UPE merchants that enable "new checkout experience" will be enabled on Split UPE. They are voluntarily opting into this
3. Legacy UPE merchants that opt-out and then opt-in will move to Split UPE

**Mid-term:**
1. Migrate non-UPE and Legacy UPE merchants to Split UPE
2. Remove the opt-in/opt-out merchant settings

In order to converge to a single experience that doesn't require an opt-in we need the **following criteria to be met:**

1. Phase 2 implement Stripe's new UPE API that plugs the security concern and gives us control of intents 
2. Sufficient production time and data that Split UPE has no critical or high impact bugs
3. That the Stripe UPE API is in a GA status
4. If available, a comparison between the Split UPE vs. Legacy UPE conversion rates. While we do want to retain control of the UI elements, the data could be valuable in determining if a horizontally or vertically aligned stack of payment methods performs better for regions with LPMs enabled
5. We'd need to work with the PayOps and Happiness teams on a date and a plan to notify merchants, track and monitor a migration effort and to update documentation.
6. A testing plan, a really thorough testing plan, on how and when we'd technically migrate merchants and how we could simulate that migration. A migration plan should include migrating merchants in waves to mitigate risk starting with merchants with lower daily transaction counts and ending with the largest accounts.

@c-shultz @bborman22 @bmccotter thoughts? Perhaps it's best we pull this out into a GSuite discussion and start mapping out a plan of attack based on the latest build and API status that Samir will provide?

**Comment by bmccotter** [comment]
@pierorocca lets please bring this out of GH and on to P2 for discussion around timelines. I'm aligned, just want it to also live on P2 since there are dependencies needed from marketing, docs work etc.

**Comment by frosso** [comment]
RFC with migration plan: paJDYF-8UK-p2
Plan with release timing: paJDYF-9xf-p2

@FangedParakeet will create separate issues for each milestone/release step implementation need.

Closing.
