### ISSUE TITLE
Preload progressive onboarding server data

### ISSUE THREAD

**Issue by ismaeldcom** [Automattic/woocommerce-payments#6104]
### Description
For the new onboarding flow we do two requests to the server, for business type and MCC data, and use them as options on multiple form fields.

Right now, while the data is requested the component just doesn't work, because there are no options. We need to preload that data ASAP, to reduce the possibility of showing a loading indicator later.

But also handle the loading state, to show a loading indicator, on those components, if for any reason the data is still loading.

If the data could not be loaded, the form cannot be completed, so we should handle the error. Here I see two options:
- Show a message to inform the merchant, recommending trying again later or contact support.
- Fail silently and redirect to full onboarding as usual.

### Acceptance criteria
- Both business type and MCC data are loaded as soon as possible.
- Affected components show a loading state if the data is still not available.
- Handle loading data error.

**Comment by vladolaru** [comment]
@ismaeldcom How would you feel if this data were cached PHP-side in a transient with a decent expiry (24 hours)? This data is not likely to change that often, especially for a new merchant. We would avoid complicating the JS and make things much faster for the frontend (no JS-based preloading).

**Comment by ismaeldcom** [comment]
We actually cache it on the PHP side, at least for [the already implemented business types](https://github.com/Automattic/woocommerce-payments/blob/d2c7c6023e44a1c2a9bd826fa2cfbb983eeef025/includes/class-wc-payments-onboarding-service.php#L57) 🙂 

But we need to also take into account internationalization, that will be on the server side for the MCCs. And the authorization, if we request business types before connecting to Jetpack it will throw. Although it's probably better to make it global like the MCC.

Said that, on slow connections the select fields might be rendered without options at first. Will be good to test that case, to see if we should preload them or just handle the loading state for that exceptional case.

**Comment by vladolaru** [comment]
Thanks for sharing that we already have DB-caching for business types.

On i18n side, it is not a problem since we can request localized data from PHP (the i18n happens on the server) with the store locale. We can clear the cache on store language change.

About the authorization, yeah didn't factor that in. I am thinking, in the interest of speed and scalability, that we could implement a wrapper endpoint for onboarding that would provide all static wizard-fields data in one go (leveraging existing controller logic). So nothing that would be contextual (apart from i18n). 

In our case, it would be the business types and MCCs tree, but we can pile more in the future. This endpoint would not remove the existing ones, just wrapping them, without authentication, since it would only return data that is safe, static, non-PII, etc.

And we preserve backward compatibility (I am not really sure if the site-specific URL would still work if we make the route global).

**Comment by vladolaru** [comment]
Mentioning here [the paired server PR](https://github.com/Automattic/woocommerce-payments-server/pull/3310) with the [client PR](https://github.com/Automattic/woocommerce-payments/pull/6167).
