### ISSUE TITLE
With non-Storefront theme, multi-currency settings look off

### ISSUE THREAD

**Issue by aheckler** [Automattic/woocommerce-payments#6182]
### Describe the bug

Using WC Pay's multi-currency settings page, the Store settings section looks a bit off with a non-Storefront theme enabled.

With Storefront:

<img width="1074" alt="Screenshot taken on 2023-05-01 at 19 21 55 UTC@2x" src="https://user-images.githubusercontent.com/5512652/235514995-027efea0-7d7d-49d1-8dee-0afc11a95d88.png">

Any other theme:

![Screenshot taken on 2023-05-01 at 19 22 45 UTC@2x](https://user-images.githubusercontent.com/5512652/235515129-d8fce01b-47b4-40b2-87c2-908dc07f7a1c.png)

The second line is accurate in that the widget is still available, but it just looks a bit odd like that on two lines. Maybe make both of those sentences on the same line?

### To Reproduce

1. WC Pay test site with WC Pay multi-currency and Storefront enabled.
2. Check `wp-admin/admin.php?page=wc-settings&tab=wcpay_multi_currency`.
3. See the first screenshot above.
4. Activate a different theme (e.g. Twenty Twenty-Two).
5. See the second screenshot above.

There's no real functional "bug" per se, everything works. It just looks a little weird?

**Comment by jessy-p** [comment]
According to Pc2DNy-3z-p2, this falls in Sigma @dwainm. Tagging as a part of Gamma Porter duties PcreKM-yM-p2.

**Comment by tpaksu** [comment]
Hi @aheckler, thanks for the issue! I would like a second opinion as the design team would have better explanation about why we did like this (It was David Levin who designed it like this by the way). 

@elizaan36 can you share your precious thoughts about this issue? I would say "because the two lines have different action suggestions (links)" but you'll know better. Having two links in one line (which are also not connected with the same context btw) would make it look weirder, and would reduce the strength of the messages trying to be given there (IMO).

**Comment by elizaan36** [comment]
The line "A currency switcher is also available in your widgets" is irrelevant without the Storefront theme so I think it should be removed with the checkbox. Just tested on my store and on block based themes the "Configure now" link goes to this screen, which isn't a good experience. Best to remove that line if the Storefront theme isn't active.

<img width="1495" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/41607b29-4340-4337-afb5-c52a70005440">

**Comment by aheckler** [comment]
That line still applies to non-block themes though. It goes here:

`https://www.example.com/wp-admin/widgets.php`

Where you can add the widget: 

![Screenshot taken on 2023-05-12 at 16 37 38 UTC@2x](https://github.com/Automattic/woocommerce-payments/assets/5512652/379f9277-52a7-4db6-b063-78c3bfb17e4a)

**Comment by elizaan36** [comment]
Since block based themes are going to be the default I'm thinking we should focus efforts on that experience. For non-block based themes, if we want to keep the "Configure" link I'd just update that line of text to a text link or button, "Configure currency switcher" and place in the footer of the card maybe. Here's a quick sketch.

![Frame 13421](https://github.com/Automattic/woocommerce-payments/assets/5121465/7f8daa9b-32fa-4c54-a178-aafb375402a9)

**Comment by jessepearson** [comment]
> For non-block based themes, if we want to keep the "Configure" link I'd just update that line of text to a text link or button, "Configure currency switcher" and place in the footer of the card maybe.

The easiest route here is to just remove the second line that's below the checkbox when Storefront isn't in use.

I did notice that the text doesn't really align with what's going on when Storefront isn't active, though, do we want to change this?

> Store settings allow your customers to choose which currency they would like to use when shopping at your store.
