### ISSUE TITLE
FRT meta not set on the order for non-upe failed card manual auth capture

### ISSUE THREAD

**Issue by dwainm** [Automattic/woocommerce-payments#6278]
### Describe the bug
Fraud meta not set when we expect it to be set.

### To Reproduce

**Payment started message - With manual auth capture (setting checked) - non-UPE**
Add an item to your cart and proceed to checkout, making sure not to do anything to trigger Your Rule.
Check out using card: `4000000000000002`
The transaction will be declined.
Go to WooCommerce > Orders in the admin and there should be a new Failed order, view/edit that order.

**Expected:**
The order should have a Fraud & Risk meta box, and Order notes similar to the one below.
The No action taken message is displayed because fraud filtering never took place.

<img width="288" alt="Screenshot 2023-05-11 at 23 00 30" src="https://github.com/Automattic/woocommerce-payments/assets/1713474/f501c5f1-3b2f-4ca3-9815-607c042ea47b">

**Actual:**
The risk meta box shows: Risk filtering through WooCommerce Payments was not found on this order, it may have been created while filtering was not enabled.
<img width="299" alt="Screenshot 2023-05-11 at 23 00 36" src="https://github.com/Automattic/woocommerce-payments/assets/1713474/8e13ab13-b090-4904-a0cb-ea709c49262b">

**Comment by tpaksu** [comment]
Another way to test this, enable the "Order Items Threshold" filter with a minimum item clause to set as 1. Since the items_count meta tag will not be appended, the rule engine will be skipped. I'll try to fix both this and #6416 in one PR.

**Comment by tpaksu** [comment]
I encountered something else with the manual capture mode. If the order gets blocked by the rule engine (with a valid card), the payment gets authorized, and the store proceeds to the order received screen, and the merchant can capture the payment. Maybe I'm doing something wrong.

Later edit: It works as expected for the normal payments, but not for the PfO method.

**Comment by tpaksu** [comment]
Ok, I've misunderstood the problem on your issue. But I'll include the fix on my PR.

**Comment by tpaksu** [comment]
@dwainm actually the fraud filters are run for the order and they pass in this scenario. The payment intent is first updated to contain the billing information, order id etc on Stripe's end before confirming it, and the fraud filters run on intent update. So "No action taken" is wrong IMO on this state, because if you are seeing "Your card is declined error", then it means rules are passed, which equals to "Allow". So the metabox that should be displayed there should be the green "No action taken" box. 

<img width="293" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/3295/7a480a8d-a6db-4d39-90d6-664d58d2cb3c">

The payment passed the fraud filtering, but couldn't be completed.
