### ISSUE TITLE
When UPE is enabled, WCPay cannot be enabled/disabled via the "All payment methods" page

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#6279]
### Describe the bug
When UPE is enabled, WCPay cannot be enabled or disabled via **WooCommerce > Settings > Payments > All payment methods**. The option disappears until UPE is disabled.

### To Reproduce
1. Navigate to **WooCommerce > Settings > Payments > All payment methods** while UPE is disabled.
2. Note that WCPay is an option.
3. Navigate to **Payments > Settings**.
4. Enable UPE.
5. Repeat step 1.
6. Note that WCPay is not an option.

### Actual behavior
This isn't that big of an issue as WCPay can be enabled/disabled directly from the **Payments > Settings** page. However, this doesn't match the expectations for other payment gateways and can cause confusion.

Additionally, we found an instance in 6273194-zen where this issue _may_ prevent the credit card fields from displaying in the following scenario:

1. UPE is enabled on a production site.
2. A staging site is created.
3. The account is transferred to the staging site.
4. A new account is onboarded on the production site.
5. EPMs display properly.
6. CC fields do not display.

For this merchant, we're asking them to disable UPE to see if this forces the card fields to display properly.

### Screenshots
![rzg0vz.png](https://github.com/Automattic/woocommerce-payments/assets/82999806/169fc3a8-e374-4c1e-973e-528c68a2befa)

### Expected behavior
When UPE is enabled, WCPay should be an option at **WooCommerce > Settings > Payments > All payment methods**.

**Comment by BusinessBloomer** [comment]
I can confirm this as well.

This is actually a major bug, because WooCommerce Payments is not "registered" as a payment, and therefore the 'woocommerce_available_payment_gateways' filter (e.g. to disable gateways based on billing country, or cart total, or shipping method, etc.) does not work

**Comment by sverleis** [comment]
When in Dev mode, if UPE is active, all card payment options for WCPay are not available. 
Tested on a JN site. 

Thus, subscription payments also cannot be made. Also labling this as a major issue.

**Comment by csmcneill** [comment]
Further investigation leads me to believe that this may also break recurring payments via Stripe Link, too. Discussion about that can be found at p1683696020812349-slack-C04DN7Q51KK

@FangedParakeet Can you help me determine if this is a split UPE issue?

**Comment by FangedParakeet** [comment]
>@FangedParakeet Can you help me determine if this is a split UPE issue?

I can confirm that this issue only occurs when the split-UPE is enabled. Cheers for raising it! 👍 

>This is actually a major bug, because WooCommerce Payments is not "registered" as a payment, and therefore the 'woocommerce_available_payment_gateways' filter (e.g. to disable gateways based on billing country, or cart total, or shipping method, etc.) does not work

WooCommerce Payments is always registered as a payment, but [we manually filter the list of gateways so that only WCPay is returned](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payments.php#L701) on this Settings screen. When the split-UPE is enabled and WooPay disabled, we erroneously filtered for the incorrect gateway and ended up removing them all. 

I've just whipped up a small PR that I believe resolves this issue: please see #6305 for more details on what I believe is occurring here and the little solution I've come up with.

>Further investigation leads me to believe that this may also break recurring payments via Stripe Link, too. 

Read through the discussion in that thread, but don't understand why Stripe Link would be connected to this issue. Can you please enlighten me, @csmcneill? I think that would be unrelated and I don't think #6305 would address this either.

**Comment by csmcneill** [comment]
> Read through the discussion in that thread, but don't understand why Stripe Link would be connected to this issue. Can you please enlighten me, @csmcneill? I think that would be unrelated and I don't think https://github.com/Automattic/woocommerce-payments/pull/6305 would address this either.

Great question @FangedParakeet! I'm flagging @dpaun1985 here as he was the one who suggested the two issues were possibly related.

**Comment by dpaun1985** [comment]
> Great question @FangedParakeet! I'm flagging @dpaun1985 here as he was the one who suggested the two issues were possibly related.

from what I could notice, Woocommerce Payments is not shown in the payment methods on transaction page, so I supposed that this could be the issue, and suggested linking them, and if the problem won't be solved to continue the investigations.

**Comment by FangedParakeet** [comment]
> from what I could notice, Woocommerce Payments is not shown in the payment methods on transaction page

@dpaun1985, did you mean on the "All payment methods" settings screen mentioned in this issue or the transactions page at **Payments > Transactions**--or some other page entirely? Sorry for my poor sense of direction here.

I left a little [explanation](https://github.com/Automattic/woocommerce-payments/pull/6305#issue-1710687821) in #6305 on why I believe this issue is occurring. I don't think my solution is in any way related to Stripe Link though; I think this problem only affected this singular Admin panel and I don't think it has any further reaching effect on checkout screens. Let me know if you have other ideas though or if there is some crucial information I'm lacking here!

**Comment by dpaun1985** [comment]
> > from what I could notice, Woocommerce Payments is not shown in the payment methods on transaction page
> 
> @dpaun1985, did you mean on the "All payment methods" settings screen mentioned in this issue or the transactions page at **Payments > Transactions**--or some other page entirely? Sorry for my poor sense of direction here.
> 
> I left a little [explanation](https://github.com/Automattic/woocommerce-payments/pull/6305#issue-1710687821) in #6305 on why I believe this issue is occurring. I don't think my solution is in any way related to Stripe Link though; I think this problem only affected this singular Admin panel and I don't think it has any further reaching effect on checkout screens. Let me know if you have other ideas though or if there is some crucial information I'm lacking here!

Thank you for the clarifications @FangedParakeet . I am reffering to the **Payments > Transactions** screen. 
In this case further investigations needs to be done for [#6261](https://github.com/Automattic/woocommerce-payments/issues/6261)

**Comment by imodouglas** [comment]
6310046-zen
