### ISSUE TITLE
`dispute funds have been withdrawn` order note is confusing

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#6380]
### Describe the bug

The following order note is added when orders are disputed. 

> Payment dispute funds have been withdrawn. See [dispute overview](https://woocommerce.com) for more details.

![Screenshot 2023-05-26 at 2 51 39 PM](https://github.com/Automattic/woocommerce-payments/assets/4167300/195bc2bc-3a42-4334-8815-47cd417ab4ee)

I don't understand this…

- What funds have been withdrawn - is this a dispute fee, or a transaction reversal?
- Where have they been withdrawn from? I assume this is a debit from merchant's WCPay account balance.
- When I click the dispute detail link, I don't see a dollar amount or `dispute funds` or `withdrawn` anywhere. The detail page should clarify / explain better (or we should not link to it!).

### To Reproduce
- Set up store – onboarded, products for sale, connected to WCPay etc in test mode.
- Also ensure your store can receive webhooks (on publicly-accessible hostname e.g. ngrok/jurassic tube). May not be necessary for this specific notice, but other [dispute handling relies on webhooks](https://github.com/Automattic/woocommerce-payments/issues/6379#issuecomment-1563742890) so recommended.

1. On front end, add a product to cart and proceed to checkout.
2. Complete checkout and [use a disputey card number](https://stripe.com/docs/testing#disputes), e.g. `4000 0000 0000 2685`. 
3. Go to `WP admin > Payments > Disputes`.
4. Click the most recent disputed order (the thing you just bought & disputed).
5. Review the order notes.

**Comment by zmaglica** [comment]
This issue impacts Dispute, so assigning to Helix (based on team responsibilities) @haszari   . Assigning as part of Gamma Triage process.

**Comment by haszari** [comment]
Labelling as medium priority. Would be good to tidy up the wording and UI around disputes, see also related design follow up issue:

- #7568

**Comment by souravdebnath1986** [comment]
> What funds have been withdrawn - is this a dispute fee, or a transaction reversal?
Where have they been withdrawn from? I assume this is a debit from merchant's WCPay account balance.

Great point, ideally the note should clarify that dispute and fees will be withdrawn as part of the next deposit. 
Example: 
`Payment dispute and fees have been deducted from your next deposit....` . I have used `deducted` as the transaction details uses this for disputes instead of `withdrawn`. 

The other part is calling our the deposit date (past, current date or `future deposit`) that the dispute is a part of in the dispute list view. We clearly call this out in the details view a part of the timeline. 

> When I click the dispute detail link, I don't see a dollar amount or dispute funds or withdrawn anywhere. The detail page should clarify / explain better (or we should not link to it!).

IMO, with the new designs that link `dispute overview` to the details screen, this should be clearer in the headline.

**Comment by nagpai** [comment]
>When I click the dispute detail link, I don't see a dollar amount or dispute funds or withdrawn anywhere. The detail page should clarify / explain better (or we should not link to it!).

The latest design of the details page seems to show the dispute as well as withdrawn fees amount clearly. This maybe as per the new design as mentioned by @souravdebnath1986 

![image](https://github.com/Automattic/woocommerce-payments/assets/4162931/32fc54f2-4a56-471f-8d7b-b2263822f5de)

I will submit a PR to amend the note.
