### ISSUE TITLE
Move CurrencySwitcherWidget and Block "this.form.submit()" to JS file because of CSP

### ISSUE THREAD

**Issue by Ninodevo** [Automattic/woocommerce-payments#6395]
#### Issue

Can we move the `onchange="this.form.submit()"` inline event handler to a Currency Switcher or Payments JS file?
This inline event handler makes it hard to add CSP rules without `'unsafe-inline'`.

#### Code

- [CurrencySwitcherBlock](https://github.com/Automattic/woocommerce-payments/blob/3fc29a529e30a8dd328f13121fb12e6806b77b46/includes/multi-currency/CurrencySwitcherBlock.php#L134)
- [CurrencySwitcherWidget](https://github.com/Automattic/woocommerce-payments/blob/3fc29a529e30a8dd328f13121fb12e6806b77b46/includes/multi-currency/CurrencySwitcherWidget.php#L108)

**Comment by zmaglica** [comment]
This issue impacts Multi-Currency, so assigning to Sigma (based on team responsibilities) @dwainm . Assigning as part of Gamma Triage process.

**Comment by dwainm** [comment]
Hi @Ninodevo ! Thank you for the suggestion. We've discussed this as a team and realized that for us to emphasize CSP without 'unsafe-inline' we'd need to take it back down the stack (WooPayments -> WooCommece -> WordPress). 

We've tracked a very old WP core ticket that shows that WordPress core is still figuring this out: https://core.trac.wordpress.org/ticket/32067, we also know that WooCommerce Core also contains quite a few instances where we're using similar techniques.

Instead of fixing this at the edge, we'd prefer that this comes in from the WP project level with more mature API's.

With that, we're closing this issue as something we will not fix at this stage. We're not saying we won't fix this in the future, but the emphasis there will be a more holistic approach to making sure our entire platform supports a simpler way to add a CSP without 'unsafe-inline'.
