### ISSUE TITLE
Test admin notice: Make it match the width of the content on the screen

### ISSUE THREAD

**Issue by v18** [Automattic/woocommerce-payments#641]
New direction:

@dechov [discussed](https://github.com/Automattic/woocommerce-payments/issues/641#issuecomment-726456162) with @LevinMedia once more, and it sounds like the best would be if it stayed as it is now but matched the width of the page content below it. I expect we'll want to do that by rendering inside of <Page>. Marking it as Good First Issue since that makes it a much simpler change, depending on familiarity with React perhaps.

**Comment by LevinMedia** [comment]
Hi Paul - lets make this scroll off the the top of the screen, as per the second gif. Thanks!

**Comment by dechov** [comment]
Discussed with @LevinMedia once more, and it sounds like the best would be if it stayed as it is now **but matched the width of the page content below it**. I expect we'll want to do that by rendering inside of `<Page>`. Marking it as Good First Issue since that makes it a much simpler change, depending on familiarity with React perhaps.
