### ISSUE TITLE
Warn about dev mode enabled on new onboarding flow choice

### ISSUE THREAD

**Issue by ismaeldcom** [Automattic/woocommerce-payments#6429]
### Description
Dev mode interferes with the new onboarding flow mode choice. If it's enabled, live will behave as test, and test will fail. So we should warn about dev mode being manually enabled.

### Acceptance criteria
- Show a warning letting know that dev mode is enabled, with a link to our documentation about it.
- Explain how the flow will work – Live will work as test, test will fail.
- Don't show the warning if dev mode is enabled via `wcpay_onboarding_test_mode`.

### Designs
We will need to define the warning copy, the current flow design looks like:
<img width="502" alt="Screenshot 2023-06-02 at 10 27 17" src="https://github.com/Automattic/woocommerce-payments/assets/7670276/f6333d14-1d17-42c6-8a35-06496418c93f">

**Comment by daquinons** [comment]
We've chatted about this here p1688615570770209-slack-C03KTTK2YMA and we think that it would make more sense:
- To fix why the test mode of the flow fails if the test mode is already enabled
- To add a notice in the live mode letting the user know that is going to be a test account because of their settings, linking to the settings screen to disable and documentation

**Comment by brandonwanA8C** [comment]
@ismaeldcom I'd like to understand the issue and the recommendations here:

1) If "Dev Mode" was enabled by default by installing the WCPay DevTool plug-in, how **is** Radio-1 vs Radio-2 working **today**?
2) If "Dev Mode" was not enabled to start with, what happens (behind the scene) when user choose Radio-2 ("test payments") option **today**?

**Comment by ismaeldcom** [comment]
Sure! Let me know if you need additional details @brandonwanA8C

1. Radio-1 will onboard a test account (dev mode enabled), and Radio-2 will fail after onboarding because we're using a different method to enable dev mode.
2. We add a new option (on the database) and hook into dev mode to alter its value and force it to be true. Later, when the user chooses to opt out of dev mode, we just clear that option and everything goes back to normal.

That's why we should update this, to ensure that there is no confusion while someone manually enabled dev mode through an alternative method, like WCPay DevTool plug-in or `WCPAY_DEV_MODE` constant.

**Comment by oaratovskyi** [comment]
Bumping the estimate after slack discussion p1690972397737029/1690972237.268759-slack-C03KTTK2YMA

**Comment by brandonwanA8C** [comment]
As a user, what are the core differences between Test_Mode vs. Dev_Mode?

Currently:
In [Dev_Mode](https://woocommerce.com/document/woopayments/testing-and-troubleshooting/dev-mode/): 
“If you want to test WooPayments on a site that will not need to process real payments, you can use Dev Mode. 
With Dev Mode, it’s possible to create a test account that requires no personal information. This account can then be used to process test transactions. It will only operate in [Test Mode](https://woocommerce.com/document/payments/testing/) and cannot be used to process live transactions.”

In [Test_Mode](https://woocommerce.com/document/woopayments/testing-and-troubleshooting/testing/):
“By default, WooPayments will accept real payment methods, such as cards, and actually charge your customers. To test payments, refunds, disputes, and other such processes, you need to switch WooPayments into test mode. If you are working on a staging or development site, such as one installed on a separate domain from the real site, you may wish to use [dev mode](https://woocommerce.com/document/woopayments/testing-and-troubleshooting/dev-mode/) instead.”

--------------------
As a user, they sound the same to me. How would I know when & how to enable "test_mode" but not "dev_mode", or vice versa?

**Comment by aheckler** [comment]
> As a user, what are the core differences between Test_Mode vs. Dev_Mode? [...] As a user, they sound the same to me. How would I know when & how to enable "test_mode" but not "dev_mode", or vice versa?

Test Mode is a state into which merchants can put there real live account if they want to run fake transactions. In other words, Test Mode is basically a feature of live merchant accounts. This means:

- I have to enter all my actual personal and/or business info during onboarding.
- There's no such thing as onboarding an account directly into test mode.
- If my account is in test mode, I can switch it back to live mode at any point.

On the other hand, Dev Mode is essentially creating an _entirely_ fake account with made-up KYC data. Crucially, these accounts can only process fake transactions, and they cannot be switched over into live mode to process real cards. This means:

- I can input a bunch of fake/dummy data during onboarding.
- I'm onboarding directly into Dev Mode to run fake transactions.
- I can't switch to live mode. I have to re-onboard with real data to do that.

The main use case for Test Mode is probably merchants who have already onboarded with real KYC data, but want to run some fake transactions through first in order to get a sense of the WooPayments workflow, and be sure it functions OK with their other plugins, etc. They want to do this without running real transactions on real cards of course.

The main use case for Dev Mode is likely developers or builders who are creating a store for a client. They don't want to onboard with WooPayments themselves. Their client should do that later on. However, they still want to be sure that the site's other functionality works with WooPayments. Thus, they enable Dev Mode, onboard with fake KYC data, and then do whatever compatibility testing. Once done, they can turn off test mode, hand over the site to the client, and help them onboard to WooPayments.

**Comment by oaratovskyi** [comment]
After discussion in Slack p1693401194349439-slack-C03KTTK2YMA we agreed that if we want to make it properly, we  need server endpoint to delete test account (separate server PR), that's why I bump estimate to 3.
