### ISSUE TITLE
Instant Deposits for Stripe-available countries.

### ISSUE THREAD

**Issue by sverleis** [Automattic/woocommerce-payments#6435]
### Description
Currently, instant deposits are only available for US-based merchants, whilst Stripe now has support for Canada, Singapore and the United Kingdom.

(https://stripe.com/docs/payouts/instant-payouts)
Available in: 🇺🇸 🇨🇦 🇸🇬 🇬🇧 

### Acceptance criteria
- Allow for instant payouts to available countries.

### Additional context
Requested on internal ticket 6333038-zen

Other tickets where instant deposits are requested:
- 5353250-zen
- 5381145-zen
- 4852423-zen
- 5736765-zen

**Comment by csmcneill** [comment]
Howdy @sverleis! I contacted PayOps about this enhancement here: p1685904976367449-slack-C03EE4CPPK5

**Comment by csmcneill** [comment]
Hi again @sverleis. After some discussion with PayOps, it's been noted that expanding instant deposits is on their radar: p1686077052635289/1685904976.367449-slack-C03EE4CPPK5

GitHub isn't the best place for adding an enhancement, as it doesn't give us an idea of the demand for new features. I've created new feature requests at https://woocommerce.com/feature-requests/woocommerce/ for adding instant deposits to new geos:

- CA: https://woocommerce.com/feature-request/expand-instant-deposits-to-canada/
- UK: https://woocommerce.com/feature-request/expand-instant-deposits-to-uk/
- SG: https://woocommerce.com/feature-request/expand-instant-deposits-to-singapore/

Since the feature request portal is better positioned to handle this, I will close this issue.
