### ISSUE TITLE
Use same notice wording in WC home "Things to do next" disputes task list item

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#6505]
Part of #6353.

The WC home dispute resolution task should match the Payments → Overview dispute resolution task as much as possible without significant effort or WC core PRs.

See #6371 for Payments → Overview dispute resolution task implementation.

![image](https://github.com/Automattic/woocommerce-payments/assets/3147296/a2d02019-7fbf-4404-b577-8d3e401e3202)

The dispute task class that is showing on WC Home "Things to do next" can be found [here](https://github.com/Automattic/woocommerce-payments/blob/99de2876c4bd5335d87136ddc4673db847235857/includes/admin/tasks/class-wc-payments-task-disputes.php).

**Comment by Jinksi** [comment]
There might be a way to use the JS logic from #6371 to update the WC home task here:

https://github.com/Automattic/woocommerce-payments/blob/2b3916d8015284fa48cce8a92ba3e95699852dda/client/index.js#L304-L311


There's some good documentation around adding tasks via PHP and JS [here](https://github.com/woocommerce/woocommerce/blob/6d4014042b3c7fbbdc1b77f1a1d9b71cc1b54543/plugins/woocommerce-admin/docs/features/onboarding-tasks.md#L330). It looks like API has changed since the original disputes task was implemented.

**Comment by shendy-a8c** [comment]
That is very useful, @Jinksi.

https://github.com/woocommerce/woocommerce/blob/7.5.0/plugins/woocommerce-admin/docs/features/onboarding-tasks.md

By the way, since WCPay [requires at least WC 7.5](https://github.com/Automattic/woocommerce-payments/blob/ff27f046cfa50032d1ce47369f82a37680f17a8e/woocommerce-payments.php#L11), we should rely on this [doc](https://github.com/woocommerce/woocommerce/blob/7.5.0/plugins/woocommerce-admin/docs/features/onboarding-tasks.md) instead. The [doc](https://github.com/woocommerce/woocommerce/blob/6d4014042b3c7fbbdc1b77f1a1d9b71cc1b54543/plugins/woocommerce-admin/docs/features/onboarding-tasks.md#L330) you provided was recently updated last month.

Also, [our current way](https://github.com/Automattic/woocommerce-payments/blob/ff27f046cfa50032d1ce47369f82a37680f17a8e/client/index.js#L294) is [depcreated](https://github.com/woocommerce/woocommerce/blob/47481490d8d44418ab7728b6a7f2b1bb99c4f2ee/packages/js/data/src/onboarding/deprecated-tasks.ts#L37) but I think it is not within the scope of this issue because https://github.com/Automattic/woocommerce-payments/blob/ff27f046cfa50032d1ce47369f82a37680f17a8e/client/index.js#L293-L313 is registering non-dispute tasks.
