### ISSUE TITLE
Possibility for uncaught exceptions in `WC_Payments_API_Client`

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#6566]
### Describe the bug
The `get_intent` and `get_timeline` methods in `WC_Payments_API_Client` do not have a try/catch to account for the possibility of exceptions being thrown in the `request` method. 

https://github.com/Automattic/woocommerce-payments/blob/6.0.0/includes/wc-payment-api/class-wc-payments-api-client.php#L220-L224

https://github.com/Automattic/woocommerce-payments/blob/6.0.0/includes/wc-payment-api/class-wc-payments-api-client.php#L734-L737

### Additional context

Came across this when trying to add code that used `get_intent` and purposely passed a bad intent ID to confirm what would be returned so I could handle accordingly.

**Comment by RadoslavGeorgiev** [comment]
@jessepearson that's expected. Most methods in the client (as well as request classes) don't have any error handling built-in. Do you see nay reason to treat those methods differently?

**Comment by jessepearson** [comment]
@RadoslavGeorgiev I haven't tried, but what if an intent ID was under a test account and `get_intent()` was called on it? If there's an exception thrown, the site will just error out rather than displaying something helpful.

I was working on a helper tool to fix Multi-Currency meta data in orders when it's missing and that's when I found this. I added a character to the end of my `_intent_id` and when using `get_intent()` I get an uncaught exception error.

Can you confirm why it would be expected to have uncaught exceptions in our code?

**Comment by RadoslavGeorgiev** [comment]
> Can you confirm why it would be expected to have uncaught exceptions in our code?

@jessepearson of course not :D

However, it does not make much sense to catch those exceptions in the API client or request classes, as neither of them are aware how to handle those errors. That's why the invoking code should be able to handle them. For example, the payment process has all of its code wrapped within a try-catch block, to simply be able to return an error message.

Similarly, the helper tool knows that it's performing a server request, and should be able to handle its failure.

That's all to say that it's not the API client or request classes' responsibility to handle errors. Instead, they throw exceptions to communicate what happened to the rest of the code.

**Comment by jessepearson** [comment]
@RadoslavGeorgiev If I am reading your response correctly, you are stating that code calling `get_intent()`, for example, should handle catching the exception thrown from the call to `request()` in the method?

**Comment by RadoslavGeorgiev** [comment]
@jessepearson exactly.

We could generally do a better job of including `@throws` tags in the documentation of methods, which do not handle exceptions coming from inner calls, but here that would be the case.

Our other option would be to return something like `null` in case an exception occurred, but `null` isn't very meaningful, and the caller would need to check for that regardless. That's why our better option is to throw (more) precise exceptions, letting the caller handle them accordingly.

**Comment by jessepearson** [comment]
@RadoslavGeorgiev I do not understand how it would be possible for me to be able to catch an exception if I call the `get_intent` method. Within the `get_intent` method, the `request` method is called, which throws the exception I am referring to. From there `deserialize_intention_object_from_array` is called, and code is then halted due to the exception not being caught.

```
	public function get_intent( $intent_id ) {
		$intent = $this->request( [], self::INTENTIONS_API . '/' . $intent_id, self::GET );

		return $this->deserialize_intention_object_from_array( $intent );
	}
```

**Comment by RadoslavGeorgiev** [comment]
@jessepearson if the exception is not caught in place, it bubbles up the call stack.

Consider this example:

```php
<?php
class HTTP_Exception extends Exception {

}

class HTTP {
	public function request() {
		throw new HTTP_Exception( 'Something went wrong' );
	}
}

class API_Client {
	private $http;
	
	public function __construct() {
		$this->http = new HTTP();
	}

	public function get_intent() {
		return $this->http->request();
	}
}

class Service {
	protected $api_client;

	public function __construct() {
		$this->api_client = new API_Client();
	}

	public function do_something_with_intent() {
		try {
			try {
				$intent = $this->api_client->get_intent();
			} catch ( HTTP_Exception $e ) {
				return 'There was an HTTP exception, could not do it.';
			}

			// do other stuff...

			return 42;
		} catch ( Exception $e ) {
			return 'There was a generic exception, could not do it.';
		}
	}
}

$service = new Service();
echo $service->do_something_with_intent();
```

When you run it, you will see `There was an HTTP exception, could not do it.`.

That's to say that handling exceptions is hard. The service should not return a message here, ideally the exception would either be bubbled further up, or handled accordingly (ex. retry).

In any case, I don't think that there is any meaningful way for the API client/request classes to handle the exception. Even if they returned `false` or `null`, that would be meaningless up the chain. The exception at least provides context.

**Comment by RadoslavGeorgiev** [comment]
Closing this issue for now, please reopen if needed.

**Comment by jessepearson** [comment]
Just want to note that I did add a `try/catch` block in my call to `get_intent` when adding it in the code, and I still received fatal errors, which is when I created this issue.

Currently the `get_intent` method does not have an `@throws` comment in the docblock, and both instances calling `get_intent` do not have exception handling added.
