### ISSUE TITLE
WooPay "Save my info" - cannot remove the numbered Step from the block editor because it's not in the block

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#6640]
If I turn off step numbers in the Blocks Checkout editor, I'm unable to remove the step number for WooPay because it's not visible in the editor. Oddly, if I turn Steps back on, WooPay checkbox get an appropriately numbered step.

![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/8274db0f-c805-4455-bc1b-668ca7f40cf8)

![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/7c0e526e-0377-49ae-a802-cc25baf2fd5a)

**Comment by cesarcosta99** [comment]
@pierorocca the "Save my info" is not an actual block, that's why it doesn't show up in the Blocks checkout editor. If we rely in the "Payment options" block to decide whether show or not the numbered step, would that work? It'd look like this:

<table>
<tr>
<th>Payment options with step number enabled</th>
<th>Payment options with step number disabled</th>
</tr>
<tr>
<td>
<img width="519" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/10233985/a2d2055c-aa00-4d65-a5ce-7b78f0c08d48">
</td>
<td>
<img width="525" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/10233985/c02ac2d4-1444-4be1-b487-0857e50881a7">
</td>
</tr>
</table>

In the example above, I only changed the "Show step number" option for the "Payment options" block.

**Comment by pierorocca** [comment]
I believe so. Given the UI impact ccing @elizaan36 for comment.

**Comment by cesarcosta99** [comment]
Awesome! I just submitted #6738 applying the changes I mentioned above, if that doesn't work I can tweak the PR, or open a new one.
