### ISSUE TITLE
Card gateway fails to load when purchasing a subscription with split UPE and WooPay

### ISSUE THREAD

**Issue by timur27** [Automattic/woocommerce-payments#6790]
### Describe the bug
Card gateway appears greyed out and fails to load during the subscription purchase, affecting both mixed carts with subscription scenarios and standalone subscriptions. The issue occurs with split UPE and WooPay enabled on the shortcode checkout page

### To Reproduce

1. Enable split UPE with more than one payment gateway and WooPay
2. Add a subscription product to the cart
3. Proceed to the shortcode checkout
4. Confirm that the card payment gateway isn't loaded and is greyed out

### Screenshots
<p align="center">
    <img width="250" height="1000" src="https://github.com/Automattic/woocommerce-payments/assets/22319444/ad773213-9c33-4d0a-b163-fde85e02b49f">
</p>

### Expected behavior
* The legacy card gateway should load properly and allow users to checkout successfully.
* A subscription bought with the legacy card gateway with split UPE can be renewed without errors.

### Additional context
💡 Blocks checkout page functions properly, purchasing and renewing a subscription.

**Comment by htdat** [comment]
@Automattic/quark - may you have a look at this issue?

**Comment by thenbrent** [comment]
@htdat while the issue requires purchasing a subscription, it surfaces with the split UPE, so seems more suited to be handled by Heisenberg (similar to the way https://github.com/Automattic/woocommerce-payments/issues/6366 surfaced with Subscriptions, but was caused by and handled by a fix in the Split UPE.)

@timur27 was the intention for Quark to look at this when opening the issue or was it keeping track of a fix for Heisenberg?

**Comment by timur27** [comment]
Hey @htdat @thenbrent - the intention was for Heisenberg to look at this, as it's probably the split-UPE part of implementation rather than subscriptions. I'm sorry for not saying this earlier.
