### ISSUE TITLE
Chip component alignment

### ISSUE THREAD

**Issue by elizaan36** [Automattic/woocommerce-payments#6794]
### Description
The great chip alignment has begun! Following the design proposed in p6riRB-8NZ-p2, the status chips in WooPayments will be unified in color, shape, and typography. Eventually, this update will be made across all of Woo admin, and a proposal will be made for inclusion in the Gutenberg library to achieve a holistic admin experience.

This update to the status chip in WooPayments is important to help users focus on critical information and prevent them from overlooking important actions to take on their disputes, transactions, and other tasks.

### Acceptance criteria
The updated `Chip` design should replace all instances of the `Chip` found in WooPayments. This includes but isn't limited to the following placements:
- Disputes list
- Payment details
- Deposits list
- Payments overview (Deposits card, Account card)
- [x] #6818

Note that this doesn't include any updates to the `Pill` component, which is usually a rounded pill shape with border outline used for marketing and informational purposes in announcements and settings.

### Designs

🎨 Status chip component in Figma: 4Lj84b3GdHAWVPFZmuhu8f-fi-1748_72561

![Atoms](https://github.com/Automattic/woocommerce-payments/assets/5121465/ce2e8d6b-753a-43a1-9ac0-6f2f9e33e27c)

Color can be used to indicate success, failure, that user needs to take action, and/or simply convey the process or condition of an item. All colors pass AAA contrast requirements. The color system uses consistently wp-0 (background) and wp-70 (text) values for gray, yellow, red, green, and blue.

The text size, padding, and aspect ratio of the variants remain consistent with the `Chip` component in Woo Admin, however this version would extend the existing Chip component to include a variation with no close button.

@Jinksi Let me know if I can provide any more details! @souravdebnath1986, Eric mentioned that this update could be included as part of the Disputes scope of work as this will be a massive improvement to the experience.

cc @nagpai @kalessil @mattallan @dwainm as you've been part of the conversation in the past and your feedback is valued here!

**Comment by Jinksi** [comment]
Question for anyone who may know – where are the `wp-` colours defined in code for us to use in WCPay?

Throughout WCPay we're using https://github.com/Automattic/color-studio colours which are similar but slightly different.

E.g. 
* [`studio-yellow-0`](https://github.com/Automattic/color-studio/blob/12f1804363fe86faccd33c496c5a4340ea542c27/dist/color-variables.scss#L90C27-L90C27) = `#f5f1e1`
* `wp-yellow-0` = `#FCF9E8` (4Lj84b3GdHAWVPFZmuhu8f-fi-447_2219)

I've also asked this in Slack: p1689649184093919-slack-CGGCLBN58

**Comment by Jinksi** [comment]
@elizaan36 in the WCPay codebase we have a bit of a mixup between `Chip` & `Pill`. This `Pill` component is very similar to the updated `Chip` component, but with more rounded corners.

Since #5872 we're using `Pill` for the deposit status UI on the **Payments → Overview** screen:

<img width="300" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/3147296/1335b911-9e7c-477c-9dc8-dea83d2a5367">

...and the **Payments -> Deposits** screen:

<img width="500" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/3147296/e274914b-5d5d-4883-bd63-44b4743d7d7e">

As part of this issue, we should change these deposit status UI elements to use this updated `Chip` component.

**Update**: Created issue #6818 for this

**Comment by elizaan36** [comment]
> As part of this issue, we should change these deposit status UI elements to use this updated Chip component.

+1. Sorry for the confusion and hoping this can align our process going forward as well.

Also wanted to point out one discrepancy, feel free to tell me it should be in a new issue.

The `Paid` status chip on the Transactions details is gray. 
<img width="1622" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/d529a275-0436-4718-bc43-33d01f0e6268">

But on the Deposits list it's green.
<img width="1628" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/2cd9f534-8906-4d22-a886-aa6367e2a743">

@nikkivias and I have been discussing this and we agree that the `Paid` status chip should be consistently green rather than gray to indicate a little moment of success. I'm curious though, why is the status chip not pulling in the same color across these areas of the plugin? Is this something we can unify?

**Comment by Jinksi** [comment]
> the Paid status chip should be consistently green rather than gray to indicate a little moment of success

@elizaan36 Ah, this is because deposit & transaction status colours are defined separately.
* The deposits "chip" ("pill") status colours are mapped to green if `paid` or `in_transit` ([code ref](https://github.com/Automattic/woocommerce-payments/blob/f1647d8f4eccb027ebebdbcb63317d27120a4b6a/client/components/deposit-status-pill/index.tsx)).
* The transaction status chip colours are mapped to gray if `refunded_partial`, `refunded_full` and `paid` ([code ref](https://github.com/Automattic/woocommerce-payments/blob/f1647d8f4eccb027ebebdbcb63317d27120a4b6a/client/components/payment-status-chip/mappings.js)).

If we want to change the transaction status → colour mappings, I'd recommend we handle this as a separate issue.
