### ISSUE TITLE
Modify BNPL methods copy in Settings page.

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#6799]
### Description

The BNPL methods are currently appearing with generic copy in the settings, “Expand your business with…”.
![image-37](https://github.com/Automattic/woocommerce-payments/assets/1553182/072d4524-0370-49ec-8a28-457fe82a609f)

This copy can be enhanced to indicate what the payment methods are to merchants who aren’t familiar.

### Acceptance criteria

* Modify current copy. The exact copy is TBD, please check this thread paJDYF-7XP-p2#comment-19185
* Add a link to relevant section in the public documentation

### Designs

TBD

### Additional context

paJDYF-7XP-p2#comment-19185

**Comment by elizaan36** [comment]
Here's the copy update provided by @aheckler. I used the phrase "your store currency" but for even more accuracy we could use the dynamic call for $account_currency.

<img width="734" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/9f2265e5-7796-4b0a-9d0e-f14d89cc98c4">

**Comment by aheckler** [comment]
My suggestion from Slack:

> Allow customers to pay over time with Affirm/Afterpay. Available to all customers paying in X.

... where "X" is the currency used by the merchant's Stripe account country. Those are:

| Account Country | Currency |
|--------|--------|
| Australia | AUD |
| Canada | CAD |
| New Zealand | NZD |
| UK | GBP |
| U.S. | USD | 

What we should *not* use, because it would incorrectly represent how BNPLs work:

- The merchant's default deposit currency from Stripe.
- The merchant's store currency from the core WC settings.
