### ISSUE TITLE
Authorizations - Level 3 data error while trying to capture partial amount

### ISSUE THREAD

**Issue by nagpai** [Automattic/woocommerce-payments#6806]
### Describe the bug

We had user reported issues where an error was seen while trying to capture amounts that are less than the authorized amount. In the reported cases it seemed to happen typically when tax or shipping cost was reduced due to changes in a pending capture order. 

Sample error from one of the case looked like: 

```
A capture of $1xx.xx failed to complete using WooCommerce Payments (pi_3******#####***** ). Error: Invalid level3: pricing must be consistent. Sum(unit_cost * quantity + tax_amount – discount_amount) + shipping_amount != total charged. In this case, 14447 != 12634.
```

### To Reproduce

The error is not reproducible on WC Pay 6.1.1 and WC 7.8. and one of the user reported the issue resolved after updating to latest version. We need to do a closer check of our codebase to see if we have this possibility covered. 

### Additional context

User reports - 
-- 6468891-zd-woothemes 
-- 6459778-zd-woothemes 
-- in both cases above - - WC Pay version 6.0.0,  WooCommerce core - 7.8.0

Discussion - p1688061570510729-slack-C02C00HCJ8J

Issue observed on WC Pay version 6.0 on user site

**Comment by mgascam** [comment]
The error is still reproducible if the merchant tries to capture from the payment details page (with the button in the capture notification). I **could not reproduce** it using the Capture charge action in the order details page. As stated in the description, the merchant needs to capture less than the initially authorized amount. These are my steps to reproduce:

1. Enable manual capture in merchant settings.
2. Set a flat rate shipping i.e. 10 *[qty].
3. As a shopper add 2 products to the cart and checkout.
4. As a merchant, go to the order details.
5. Reduce the quantity of products and also the amount of the flat rate.
6. Go to the payment details page and use the Capture button.
7. Notice there's an error.
8. Go back to the order details and check that there's a note with the error. 
`Error: Invalid level3: pricing must be consistent. Sum(unit_cost * quantity + tax_amount – discount_amount) + shipping_amount != total charged. In this case, 42000 != 28000.`

We seem to be trying to capture the original amount in the payment intent, instead of the updated amount of the order.
