### ISSUE TITLE
Add in-progress challenge reminder to Payments → Overview dispute notice.

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#6989]
Part of project Improving Dispute Response Part 2a: pdjTHR-2PC-p2

The dispute notice that appears on the Payments → Overview screen should show a notice initiated if a dispute challege has been initiated and saved using the **Save for later** button on the challenge form.

![Image](https://user-images.githubusercontent.com/3147296/260346931-570e34ec-7342-4b4b-af72-d308dac8c6bb.png)

Note this is an enhancement to an existing notice, shown when there are dispute(s) due in <7 days. This is the existing notice:

<img width="846" alt="Screenshot 2023-09-13 at 2 40 03 PM" src="https://github.com/Automattic/woocommerce-payments/assets/4167300/8ab8976e-5342-43ca-b70f-181ed65442c7">

### TODO
- [ ] Determine what to show when there are multiple disputes with an in-progress challenge 

See Figma RiEQmaKRI7u9USAI3lyZz0VX-fi-5482%3A443300

**Comment by haszari** [comment]
Picked this up. To show a notice on payments overview, we need to find any disputes with `.evidence_details.has_evidence`. 

Currently the overview page calls `GET /disputes` which doesn't include any evidence related data in the response. I _think_ we'll need to add that to show this notice.

**Comment by haszari** [comment]
Couple of considerations here:

1. We don't have the data (`evidence_details.has_evidence`) available in this screen via `GET /disputes`), and likely need to add it to WCPay server. We can do that but it's more effort (than we expected for this improvement) – SQL change on server cache DB.
2. Confirm the expected lift/importance of showing `Continue` rather than `Respond` in this scenario. Maybe this is a low-impact change (that we can remove from scope).
3. The existing notice is only shown for disputes with <7 days til deadline. So this might be a different notice: i.e. **`Continue` for disputes with draft response (no matter how many days left)** vs. tweaking the action/wording on the <7 day notice.

(1) is the biggest blocker – though as I understand it just takes time, does not need design/product input. 

(2) is a discussion with product – i.e. is this ok to descope/deprioritise.

(3) should be easy to resolve, ideally with input from design, but probably can make a call and confirm as part of final testing.

**Comment by haszari** [comment]
Discussed in Helix team meeting and decided to pull this from scope for WCPay 6.5 (i.e. this sprint) due to the server/schema changes needed, and the likely small improvement in response rate due to a tailored `Please continue responding to dispute` notice.

We can reconsider in future. If we think this will significantly improve response rates, we could prioritise in next sprint. For example, if we see data that many merchants start responding to dispute but then get stuck and forget about it.

FYI @souravdebnath1986 @nikkivias – let me know if you have any thoughts on this.

**Comment by haszari** [comment]
Closing this issue. Discussed with @souravdebnath1986 on P2 (pdjTHR-2UN-p2#comment-3746) and we'll reconsider this in next phase of disputes improvements (Disputes improvements 2B, likely for 2024).
