### ISSUE TITLE
Conversion indicator tooltip breaks table

### ISSUE THREAD

**Issue by tpaksu** [Automattic/woocommerce-payments#6991]
### Describe the bug
The conversion indicator tooltip on the transactions page breaks the table layout, possibly because of a CSS positioning issue. 

### To Reproduce

1. Start listening to Stripe webhooks on your local server.
2. Sell something using a different currency than the store currency
3. Go to administration screen
4. Go to transactions page
5. Move your mouse pointer over the exchange icon on the amount column.
6. See the UI error

### Screenshots
![Screen Recording 2023-08-14 at 13 39 08](https://github.com/Automattic/woocommerce-payments/assets/3295/373f0bfa-2a44-4a74-a905-914ea018d9bc)

**Comment by eduardoumpierre** [comment]
Hi Taha! I followed the testing steps that you provided, but I wasn't able to reproduce the issue. Could you provide more information about your setup? What browser are you using?

This is what I'm seeing with the latest `develop` branch:

https://github.com/Automattic/woocommerce-payments/assets/16882226/4a8231cf-cdf0-4bf2-9c8a-671ab8ad4eaf

**Comment by tpaksu** [comment]
Yes after pulling the latest code from `develop` and building the assets with `npm run build:client` I see the same output. The relative positioning problem of the tooltip has gone. But I wonder if it's displayed as it's supposed to show.. I'll try to find if there was a work on that tooltip that made it like this, or if it's an update from the core.

**Comment by tpaksu** [comment]
The fix was added 6 months ago with [this PR](https://github.com/Automattic/woocommerce-payments/pull/5656) but it seems the offset was modified on the Tooltip component itself on the components library. Maybe the `$gap` variable has been removed or changed it's name. I believe modifying [this](https://github.com/Automattic/woocommerce-payments/blob/25a87d1faf16d11e0c40d9ac48f3f47263efc469/client/transactions/list/style.scss#L19-L22) CSS definition may solve this.

https://github.com/Automattic/woocommerce-payments/blob/25a87d1faf16d11e0c40d9ac48f3f47263efc469/client/transactions/list/style.scss#L19-L22

**Comment by eduardoumpierre** [comment]
It appears that we are currently using an outdated version of [`@wordpress/component`](https://github.com/WordPress/gutenberg/blob/trunk/packages/components). Our version is [19.10.0 (2022-05-04)](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/CHANGELOG.md#19100-2022-05-04) while the latest version is [25.7.0 (2023-08-31)](https://github.com/WordPress/gutenberg/blob/trunk/packages/components/CHANGELOG.md#2570-2023-08-31). After reviewing the changelog, it seems that the `Tooltip` component underwent significant changes. If we had updated to a newer version, this change may not have been necessary.

Regarding the tooltip overlapping the icon/content, it appears that this was intentional. The `$gap` variable has a value of `16px` which matches the `-32px` translation of the tooltip. Additionally, there is a comment in the code explaining why this was added:

> // Positioning the tooltip in a higher position to avoid having it cropped by the bottom of the table 

Although we can reach out to David for clarification, I believe that the most effective solution to prevent similar issues in the future is to keep our components library up to date, even though it can be inconvenient.

Let me know what are your thoughts and the next steps for this issue.

**Comment by tpaksu** [comment]
When adding the FRT banner on the WC homescreen, I tried to use the `SlotFill` library added as a dependency in WCPay, but it was also outdated, and we solved it by using `window.wp.components.Fill` to get the WP version of the `Fill` component. Maybe importing the `Tooltip` component like that will solve that problem?

The fix was this: https://github.com/Automattic/woocommerce-payments/pull/5871/files#diff-e0b0a2ffe6626a484d8e52132220a2e9b4e1fd6e6c02e86ff8938039d4f9f3c8R106-R111

**Comment by eduardoumpierre** [comment]
Thanks for the suggestion, Taha. It worked just fine using the `window.wp.components.Tooltip`. I kept the regular tooltip component from `@wordpress/components` as a fallback just in case.
