### ISSUE TITLE
WooPay checkout appearance - store logo

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#6994]
## Description

The "Store logo" that needs to be displayed by default should reflect the store logo uploaded in the settings for the "Site identity".
If the merchant chooses, they can override the logo to a custom one just for WooPay.

At this time, it doesn't look like it's pulling in the store's default logo.

![Screenshot 2023-08-14 at 7 00 54 PM](https://github.com/Automattic/woocommerce-payments/assets/273592/ce436187-d6a4-4532-9d9c-0a840db716ae)

## Acceptance criteria
- By default, the "Store logo on checkout" setting needs to pull the site's logo
- The "Store logo on checkout" setting can be overwritten by the merchant

**Comment by reykjalin** [comment]
@frosso I just tried this and the logo worked fine:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2hWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e2da8216d9c4770e570d47858bba9cb5a4c8d00c/image.png)

Maybe something else went wrong for you there? 🤔

**Comment by reykjalin** [comment]
Oh, or do you mean that we should pull in the Site's logo by default instead of only relying on the custom one from the WooPay settings?

**Comment by reykjalin** [comment]
I've opened https://github.com/Automattic/woocommerce-payments/pull/7103 to address this issue 👍

**Comment by frosso** [comment]
@reykjalin the logo should be pulled from the theme's logo, if available, on first enablement.
If the merchant chooses, they can rewrite the logo with a custom one.

This ticket is part of an epic, which includes some discussion on the topic: https://github.com/Automattic/woocommerce-payments/issues/6639#issuecomment-1674143256

With your changes, would there be an opportunity for the merchant to not display a logo at all on WooPay? I wonder if that's a desired behavior CC @pierorocca

**Comment by pierorocca** [comment]
I'd keep the existing behavior of showing the store name in text if there's no logo. The key here for the shopper is continuity and knowing who they're making the payment to.

**Comment by reykjalin** [comment]
The current behavior in #7103 is:

| Site Logo | Custom WooPay Logo | Result |
|:---:|:---:|:---:|
| ❌ | ❌ | Store name/title |
| ✅ | ❌ | Show site logo |
| ❌ | ✅ | Show custom WooPay logo |
| ✅ | ✅ | Show custom WooPay logo |

@pierorocca does that sound correct? If yes we can go ahead and merge it, otherwise we'll have to make some changes.

For full context: the URL to the logo is sent with the `init` request to WooPay so we're always using the most up-to-date version of the logo available. If the custom logo is removed we'll fall back to the site logo, or the store name/title if there is no site logo.

**Comment by pierorocca** [comment]
Thanks for the added context. This all looks good to me.

**Comment by pierorocca** [comment]
PS love the matrix summary

https://github.com/Automattic/woocommerce-payments/assets/109928953/14032645-3101-486b-8aba-31e7a37a2582
