### ISSUE TITLE
[Payments Tab] Double indicators showing under Payments tabs

### ISSUE THREAD

**Issue by brandonwanA8C** [Automattic/woocommerce-payments#7042]
### Describe the bug
Seeing a double action indicator (1) showing under the "placeholder" Payments tab 

### To Reproduce
1. Set up a new Jurassic Site
2. Either complete or skip Store setup
3. Click on "Payments" tab to start onboarding WCPayments

### Actual behavior
Seeing two action indicators side by side, not knowing what each stands for

### Screenshots
<img width="1037" alt="Screenshot 2023-08-22 at 10 22 11 AM" src="https://github.com/Automattic/woocommerce-payments/assets/113071364/356a5ecf-1743-4906-a2ba-ddb2d6ebfc93">

### Expected behavior
Should be a single indicator, if multiple actions are required, should display (2) or more.

**Comment by brandonwanA8C** [comment]
fyi @daquinons @vladolaru @elizaan36

**Comment by daquinons** [comment]
Hey @brandonwanA8C ! I haven't been able to reproduce it with your instructions :( Is there something else that you might have done to trigger this condition?
<img width="1440" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/2612426/ba3d0236-344e-4f17-b7f4-72498c4cb546">
<img width="1440" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/2612426/cb1a7810-d838-41c9-917c-2950f25b5546">

**Comment by daquinons** [comment]
@brandonwanA8C  I'll add it to the upcoming sprint to give it another look, it would be helpful if you could record the steps to reproduce it :)

**Comment by PanosSynetos** [comment]
Hey @daquinons - It's not something that is consistently reproduced. I was just coming to report this, and I found Brandon's issue.

We have noticed it on some fresh Woo Express sites, here's an example
https://woo-secretly-delicate-suit.wpcomstaging.com/wp-admin/ (I can add you as an admin to further check)

![image](https://github.com/Automattic/woocommerce-payments/assets/2484390/8b14ddf4-9bcf-45f1-a37f-a8c48488e183)

**Comment by daquinons** [comment]
@PanosSynetos Thank you! Can you please invite @oaratovskyi?

**Comment by oaratovskyi** [comment]
@PanosSynetos thanks for sharing! 
I've reproduced the bug 🎉 

The steps would be:
- Set up a new Jurassic Site
- Either complete or skip Store setup
- Change `wcpay_activation_timestamp` option value to be > than 3 days ago. I used [options view](https://wordpress.org/plugins/options-view/) plugin for that.
- Click on "Payments" tab to start onboarding WCPayments

It happens because we have the code that add those badges in two places - Core and Payments plugins:
- In Payments: when `wcpay_activation_timestamp` option is more than 3 days ago, see https://github.com/Automattic/woocommerce-payments/blob/trunk/includes/admin/class-wc-payments-admin.php#L911. That condition allows `WC_Payments_Admin::add_menu_notification_badge()` to be called.
- In Core: for some weird reason, `WcPayWelcomePage::must_be_visible()` returns `true`. That allows [the following code](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/src/Internal/Admin/WcPayWelcomePage.php#L137-L148) that adds badge to be called.

Seems like that was introduced in https://github.com/woocommerce/woocommerce/pull/39958. There is a condition that checks the markup before adding the badge, but it still goes in. I'll fix it tomorrow!
