### ISSUE TITLE
Create fallback switch for deferred intent UPE rollout

### ISSUE THREAD

**Issue by FangedParakeet** [Automattic/woocommerce-payments#7115]
### Description

As our deferred intent UPE rollout rolls on, it would be nice to ensure we have some fallbacks in place, just in case, should things go wrong, we can offer a switch to temporarily disable the feature. As we have discussed that falling back to the split UPE is probably not a particularly reliable safety net to rely on, I think it makes more sense to return users to either the legacy UPE or legacy card--depending on whichever feature flag was enabled prior to upgrading to the deferred intent UPE. 

As we are repurposing the "new checkout experience" button to enable the deferred intent UPE, it also makes sense to use its accompanying disable button as our killswitch--though, I'm always open to other suggestions, if anyone has any wiser ideas! In my mind, choosing to disable the "new checkout experience"--and consequently the deferred intent UPE--should ensure that **both** deferred intent UPE and split UPE flags are disabled, which would return users to their previous state (either legacy card or legacy UPE), depending on whichever feature flags remain. We don't currently disable any of these former feature flags, so AFAIA this would be an effective way to return stores to their previous condition.

![Disable button](https://cdn-std.droplr.net/files/acc_1104206/MEfT37)
_New checkout experience disable button_

### Acceptance criteria

- Ensure that both split UPE and deferred intent UPE feature flags are disabled when store owners with the deferred intent UPE enabled decide to disable "new checkout experience".
- Ensure that stores return to previous state: either legacy card or legacy UPE, depending on which feature is enabled. 

### Additional context

#6023

**Comment by FangedParakeet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/7115?planning-poker) with Zenhub @frosso @gpressutto5 @mdmoore @timur27

**Comment by frosso** [comment]
Decision flow, based on the _current_ state of the application (WCPay 6.5.0)

<table>
<tr>
 <td> 1. Base state
 <td> 2. Click "Enable payment methods"
 <td> 3. Click "Disable" from kebab menu
 <td> 4. Click "Enable payment methods" again
 <td> 5. Click "Disable" from kebab menu again
<tr>
 <td> Legacy card
 <td> Enables dUPE
 <td> Back to Legacy card
 <td> Enables dUPE
 <td> Back to Legacy card
<tr>
 <td> Legacy UPE
 <td> N/A
 <td> Back to Legacy card
 <td> Enables dUPE
 <td> Back to Legacy card
<tr>
 <td> dUPE
 <td> N/A
 <td> Back to Legacy card
 <td> Enables dUPE
 <td> Back to Legacy card
</table>

After upgrade to WooPayments 6.6.0, where "Legacy UPE" merchants are migrated to dUPE
<table>
<tr>
 <td> 1. Base state
 <td> 2. Click "Enable payment methods"
 <td> 3. Click "Disable" from kebab menu
 <td> 4. Click "Enable payment methods" again
 <td> 5. Click "Disable" from kebab menu again
 <td> Notes
<tr>
 <td> Legacy card
 <td> Enables dUPE
 <td> Back to Legacy card
 <td> Enables dUPE
 <td> Back to Legacy card
 <td> No change from WCPay 6.5.0
<tr>
 <td> Legacy UPE, now "migrated" to dUPE
 <td> N/A
 <td> Back to Legacy UPE
 <td> Enables dUPE
 <td> Back to Legacy UPE
 <td> 
<tr>
 <td> dUPE (merchants that haven't been migrated)
 <td> N/A
 <td> Back to Legacy card
 <td> Enables dUPE
 <td> Back to Legacy card
 <td> No change from WCPay 6.5.0
</table>

After upgrade to WooPayments 6.7.0, where "Legacy card" merchants are _also_ migrated to dUPE
<table>
<tr>
 <td> 1. Base state
 <td> 2. Click "Enable payment methods"
 <td> 3. Click "Disable" from kebab menu
 <td> 4. Click "Enable payment methods" again
 <td> 5. Click "Disable" from kebab menu again
 <td> Notes
<tr>
 <td> Legacy card, now "migrated" to dUPE
 <td> N/A
 <td> Back to Legacy card
 <td> Enables dUPE
 <td> Back to Legacy card
 <td> 
<tr>
 <td> Legacy UPE, now "migrated" to dUPE
 <td> N/A
 <td> Back to Legacy UPE
 <td> Enables dUPE
 <td> Back to Legacy UPE
 <td> No change from WCPay 6.6.0
<tr>
 <td> dUPE (merchants that haven't been migrated)
 <td> N/A
 <td> Back to Legacy card
 <td> Enables dUPE
 <td> Back to Legacy card
 <td> No change from WCPay 6.6.0
</table>

@timur27, what are your thoughts on this decision flow?

**Comment by timur27** [comment]
@frosso Looks good, thanks. 

I think that the results your provided should be checked as part of https://github.com/Automattic/woocommerce-payments/issues/7221 and https://github.com/Automattic/woocommerce-payments/issues/7220. The corresponding adjustments need to be applied as part of those issues as well.

**Comment by timur27** [comment]
@frosso when dUPE falls back to legacy UPE, currently there's no button from the legacy UPE to enable payment methods. Do you happen to know if there was any discussion around this and how to accomplish our goal so that users can get back to the deferred UPE again?

![image](https://github.com/Automattic/woocommerce-payments/assets/22319444/1af7c24a-a907-4125-a3f2-aca3424a6c34)

**Comment by frosso** [comment]
@timur27 you're right, this is a pitfall on my part, I didn't realize we wouldn't have a way to enable the dUPE from the Legacy UPE.
Right now, I am thinking that maybe we just display the default notice for all Legacy UPE merchants, without allowing them to go back to dUPE. But even in this scenario:
1. the notice's date would become inaccurate
2. it's not ideal, since they would be migrated to dUPE at some point without too much notice (likely in a few weeks)

Maybe we _do_ need to add a way for them to enable the new experience? I'm not sure if you have other ideas.

**Comment by timur27** [comment]
Thanks @frosso, for all the considerations from your side. I _think_ ideally, we could implement the new banner similar to the banner shown currently for the legacy card users. And I _think_ we can try to show this banner only for users, who _explicitly_ disabled dUPE previously. To sum up, for legacy UPE users:

1. Never used dUPE? No banner and switch to dUPE
2. Migrated to dUPE already but clicked _Disable_ to return to the legacy UPE? Show banner to allow switching back to dUPE

I think to distinguish between group (1) and group (2), we can use `_wcpay_feature_upe_deferred_intent` FF with value `0` for group (1) and with value `disabled` for group (2) to emphasize, that the dUPE was disabled explicitly. I'll need to double-check the feasibility of such solution from the technical standpoint.

<img width="638" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/22319444/41bab5a0-c0f9-4250-b892-5c781c3a46f7">

**Comment by timur27** [comment]
> Maybe we do need to add a way for them to enable the new experience?

In case we'll allow them to switch back and forth after migration, like described in https://github.com/Automattic/woocommerce-payments/issues/7115#issuecomment-1729166892, then there won't be a need to add a way to enable the new experience. 

Otherwise, if we refuse going the direction described in https://github.com/Automattic/woocommerce-payments/issues/7115#issuecomment-1729166892, then we might want to add this possibility.

**Comment by frosso** [comment]
> I think to distinguish between group (1) and group (2), we can use _wcpay_feature_upe_deferred_intent FF with value 0 for group (1) and with value disabled for group (2) to emphasize, that the dUPE was disabled explicitly. I'll need to double-check the feasibility of such solution from the technical standpoint.

This makes sense, and it does sound like a good solution 👍 keep me updated if you find any blockers with this approach!

**Comment by timur27** [comment]
Prepared https://github.com/Automattic/woocommerce-payments/pull/7270 as an initial solution and asked for UX & design feedback in paJDYF-9xf-p2#comment-20862.

**Comment by timur27** [comment]
Fallbacks turned out to be not needed after the discussion in paJDYF-9xf-p2#comment-20862.

Instead: 
1. The server-side feature flag was introduced that can be toggled, thus allowing us to enable/disable dUPE by using `wp wcpay enable_dupe` and `wp wcpay disable_dupe` CLI commands https://github.com/Automattic/woocommerce-payments-server/pull/3963
2. Legacy UPE migration https://github.com/Automattic/woocommerce-payments/pull/7306 supports the server-side feature flag 
3. Legacy card migration https://github.com/Automattic/woocommerce-payments/pull/7328 supports the server-side flag as well

Having said that, I'm closing this issue.
