### ISSUE TITLE
Deactivating `WooCommerce Payment`  fails when `WooCommerce` is not active.

### ISSUE THREAD

**Issue by kt-12** [Automattic/woocommerce-payments#7303]
### Describe the bug
Deactivating `WooCommerce Payment` after deactivating `WooCommerce` leads to fatal error.

### To Reproduce
You need a site with active  `WooCommerce` and `WooCommerce Payment`
1. Go to `Plugins`
2. Deactivate  `WooCommerce`
3. Then  Deactivate `WooCommerce Payment`

### Actual behavior
`WooCommerce Payment` deactivation after `WooCommerce` throws an `Fatal Error`

### Screenshots
![screenshot_from_2023-09-21_12-11-00](https://github.com/Automattic/woocommerce-payments/assets/30643833/898507e6-52c6-4550-b617-eeba48a06a46)

### Expected behavior
`WooCommerce Payment` should get deactivated without error 

### Desktop (please complete the following information):

* OS: Ununtu
* Browser: Chrome
* Version: 117.0.5938.88 (Official Build) (64-bit)

### Smartphone (please complete the following information):
Not tested
### Additional context
N.A

**Comment by csmcneill** [comment]
This appears to be related to https://github.com/Automattic/woocommerce-payments/pull/6637

I'm unable to reproduce this with WooPayments version 6.2.2, as 6.3.0 is when the above PR was included.

Flagging this to @alefesouza as the PR author, @leonardola as the reviewer, and @frosso since this seems to be specific to WooPay code.
