### ISSUE TITLE
Missing Multi-Currency check could lead to errors in WooPay

### ISSUE THREAD

**Issue by jessepearson** [Automattic/woocommerce-payments#7329]
### Describe the bug
I was researching other things and found a chunk of code that uses `MultiCurrency::CURRENCY_META_KEY` and `MultiCurrency::CURRENCY_SESSION_KEY` without checking if MultiCurrency is enabled or not. If MC is not enabled, it will likely cause errors.

Code is here:

https://github.com/Automattic/woocommerce-payments/blob/e5e7f69b960452cda2d7b5f9cd085718533e4152/includes/woopay/class-woopay-session.php#L348-L357

Multi-Currency is enabled by default, but is able to be disabled by a merchant in their settings. The check to determine if it is enabled is `WC_Payments_Features::is_customer_multi_currency_enabled()`.

**Comment by zmaglica** [comment]
This issue impacts WooPay, so assigning to team Heisenberg (based on team responsibilities Pc2DNy-3z-p2) @frosso . Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by c-shultz** [comment]
I _think_ we're OK here, @jessepearson, but I'm totally open to being told differently. I tested this code path with multi-currency disabled and it would seem the MultiCurrency class is loaded either way, so these static class constants were still getting defined.

I don't claim to be confident about the nuances of autoloading, but I see multi-currency autloading was added in https://github.com/Automattic/woocommerce-payments/pull/2061. MultiCurrency is instantiated by the conditionally loaded file [here](https://github.com/Automattic/woocommerce-payments/blob/2ad0101c193eaeaadc392e17b4396289040401d8/includes/class-wc-payments.php#L462-L464), but from what I'm seeing, any static class references are safe to use whether or not the setting is enabled.

cc @bborman22 who introduced the code snippet in question

**Comment by bborman22** [comment]
Thanks for the ping @c-shultz. Without taking a deeper dive, one possible risk I could see is: 
- Merchant enables multi-currency
- A shopper sets their user currency
- Merchant disabled multi-currency
- This check still passes and the shopper's selected currency is used even though the merchant didn't want it to be.

I think we should definitely add this check into the condition for this reason (I'm unsure if user meta is cleared upon disablement), but I think that your assessment that it wouldn't cause errors is accurate though since all references are to statics and the class is autoloaded.

**Comment by c-shultz** [comment]
>This check still passes and the shopper's selected currency is used even though the merchant didn't want it to be.

💡 
Ah good catch, I had missed the point and only thought about this in terms of a hard PHP error.
