### ISSUE TITLE
Use error message from PM with redirect when payment fails

### ISSUE THREAD

**Issue by KarlisJ** [Automattic/woocommerce-payments#7335]
### Description
When a payment method with redirect fails payment, it usually provides a clear message of the error in the redirect. Still, when we redirect back to the checkout, we show a generic "We're unable to process this payment. Please try again later." message.

### Acceptance criteria
We should use the error message or code from the response to show the actual error message to the customers at checkout.

**Comment by jessy-p** [comment]
This issue impacts checkout UI, so assigning to Heisenberg (based on team responsibilities Pc2DNy-3z-p2) @FangedParakeet. Assigning as part of Gamma Triage process PcreKM-yM-p2.

Tagging as part of re-evaluating older issues in the backlog, please have a look and close if no longer relevant.

**Comment by gpressutto5** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/7335?planning-poker) with Zenhub @FangedParakeet

**Comment by gpressutto5** [comment]
The message returned by the API is for the merchant, not the shopper, so we can't use them.

**Closing Klarna modal:**
> Customer cancelled checkout on Klarna

**Declining iDEAL:**
> The customer did not approve the PaymentIntent. Provide a new payment method to attempt to fulfill this PaymentIntent again.

We can use the error code to display our own message, but in order to do that we need to get a list of errors we want to handle and write the messages for them. I couldn't simulate any error other than `payment_intent_authentication_failure`, which is as generic as our message. I talked to Stripe about this here p1713295748425959-slack-CU6SYV31A

Do you have any example of an error that we should handle @KarlisJ?

**Comment by gpressutto5** [comment]
As explained, the message returned by Stripe is not suitable for display to the shopper. We can handle the error codes, but the BNPL service handles all the errors I've been able to test for without returning the customer to the website. The only error I could reproduce was when closing the payment method, but in this case, there is no problem with displaying a generic error. Feel free to reopen this issue if other errors need to be addressed.
