### ISSUE TITLE
Fire a `order dispute notice render` tracks event so we can measure click-through rate for disputed order notice

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#7437]
### Describe the bug
In #6354 and particularly #6373 we implemented a new notice in the WooCommerce core order screen, to alert the merchant that the buyer has disputed the payment.

We want to know how effective this notice is at driving action, and ultimately, improving response to disputes. 

However, we don't have an event for when the notice is shown. This means our conversion funnel starts earlier (e.g. view order screen (any type of order) or view order screen (order is `on-hold` due to dispute or various other reasons).

The goal of this issue is to add an event when the disputed order notice is rendered. Then we can measure the % of notices that merchants click on (to view or respond to dispute), and ultimately better understand how this notice helps merchants.

##### Option 1: use generic notice event(s)
There may be a generic `inline notice` event already firing. If so, need to check this will work for our needs (e.g. has a prop to filter only dispute notices). 

##### Option 2: fully custom event for our notice only
We can fire an event just as the notice is rendered, e.g. here:

https://github.com/Automattic/woocommerce-payments/blob/703835a096cb03ed8b7595b9d13059d1dabae1d9/client/order/index.js#L332-L347

Might be worth adding some props for the notice colour / urgency.

**Comment by haszari** [comment]
Adding this tracks event is harder than I expected. Because `DisputeNotice` is a heavy component and has multiple different jobs:

1. Decide whether a notice should be shown – i.e. is the order disputed AND the merchant should take action
1. Render the notice – to drive the merchant to take action
1. Disable the refund UI elsewhere on the page 🚨 – this is using jQuery, and is a side effect – we should wrap it in a `useEffect`
1. Display UI to tell the merchant why refunding is disabled

I'm proposing that we break up the component into separate functions / components for each of the above jobs. This is more of an extensive refactor than I'd hoped, but … I can't leave the code in this state! 

The UI for item 4 (`tell merchant why refunding is disabled`) is making this more complicated IMO, because we are displaying it in the notice. That means the logic for disabling refunds and rendering the notice is coupled. 

I don't think this is appropriate – in fact, I think it makes the notice more confusing and less actionable. E.g. it says:

<img width="964" alt="Screenshot 2023-10-26 at 1 28 20 PM" src="https://github.com/Automattic/woocommerce-payments/assets/4167300/5fa2fceb-7b92-4858-91d5-49c2d3fc8123">

- This order is disputed for $10.
- Respond now!
- _By the way, you can't refund this order right now (because reasons)._
- [Button to respond]

I think this is much more powerful:

<img width="964" alt="Screenshot 2023-10-26 at 1 28 20 PM" src="https://github.com/Automattic/woocommerce-payments/assets/4167300/246e12f5-90cb-4f30-8197-5e435403ca7f">

<img width="968" alt="252547591-e72551c1-b92a-4f76-bc8f-9f8e0ec7b7c4" src="https://github.com/Automattic/woocommerce-payments/assets/4167300/91336bbc-6d3e-4de5-bc36-93738af1444b">

- This order is disputed for $10.
- Respond now!
- [Button to respond]

This might also be part of the reason why merchants aren't actioning to the notice (speculation!).

So … my proposal:

2. Use a wrapper component to decide whether to display a notice at all and get data ready. This keeps the UI component lean, reduces nested logic (ifs), and allows it to fire tracks in a `useEffect`.
1. Simplify the notice to just display the actionable info – order is disputed, respond now. (remove the `you can't refund` info)
2. Add another side effect (`useEffect`) to disable refund button when appropriate, with a tooltip.

I might be missing something here – I don't yet fully understand the logic in the component, as there are lots of boolean variables and logic. I am assuming we don't need to support a large number of cases (i.e. the code is more confusing than the UI) – but I might not understand completely.

@Jinksi @shendy-a8c let me know your thoughts on this ! I see you were involved in the earlier iterations, please check my assumptions 😁 

Also @nikkivias do you recall any details around the decision to show the `You can't refund` message in the notice, or elsewhere on the screen? I'm assuming this info is less important than the actionable dispute. I'm assuming it's ok to rely on button tooltip for this "secondary" info.

**Comment by haszari** [comment]
Started a new branch to try the above refactor: #7557

**Comment by nikivias** [comment]
Hey @haszari  the reason we added it in the notice is because we wanted to disable refunds AND order editing while the dispute is in place. 

There will be many places in the order page that will be disabled during disputes. So we added this message in the banner to proactively communicate about the page's disabled state rather than having the user poke around and find out. 

However looking at it again, I recognize your point about the last line diluting the main message. I consulted with other design folks on this, and in the end we agree that we will want to keep this notice as focused on the primary action we want the user to take as possible **_ERGO let's kill that last line 🔪_**

In line with this move, [the original proposal](https://www.figma.com/file/RiEQmaKRI7u9USAI3lyZz0VX/Dispute-Flows?type=design&node-id=7596%3A86883&mode=dev&t=eQDmEWD7dbuwOOtH-1) recommended removing the pencil icons from places like Billing and Shipping. Let's forgo that so we can trigger 'not allowed' tooltips instead.

![Screenshot 2023-10-27 at 1 02 59 AM](https://github.com/Automattic/woocommerce-payments/assets/99638528/53682683-1ef0-472f-adbc-1e81ebd93e37)
![Screenshot 2023-10-27 at 1 05 39 AM](https://github.com/Automattic/woocommerce-payments/assets/99638528/196db9e7-8d16-437d-a040-44244b87071f)

We will want to implement tooltips anywhere that is disabled in the interface, but instead of consolidating the message, let's make it specific to the UI elements. For example, if they hover over the Refund button, we say 'Refunding is disabled during disputes' and if they try an editing elements, we say 'Order editing is disabled during disputes'.

Let me know what you think.
——————

On another note— I am noticing that the text on the screenshots above is quite lengthy?

> The customer provided the following reason: [ the reason ] 

I would recommend to implement the below text and styling where the intro sentence is shorter and the only one in bold. The rest will be in normal weight. This would make the content of the notice appear less heavy and potentially at just 2 lines.

![Screenshot 2023-10-27 at 12 57 24 AM](https://github.com/Automattic/woocommerce-payments/assets/99638528/9b67fb89-66d9-4c56-a910-8fda166da0b5)

[(See the mockup on Figma)](https://www.figma.com/file/RiEQmaKRI7u9USAI3lyZz0VX/Dispute-Flows?type=design&node-id=7596%3A86883&mode=dev&t=eQDmEWD7dbuwOOtH-1)

——————

There is still also the subject of changing the CTA here from `Respond now` to `View dispute`, so I'm going to need to get consensus about it. Will update y'all.

**Comment by haszari** [comment]
Thanks for quick response @nikkivias ! There's a lot in your comment, we might want to handle some of it in separate issues (could get bogged down). 

> However looking at it again, I recognize your point about the last line diluting the main message. I consulted with other design folks on this, and in the end we agree that we will want to keep this notice as focused on the primary action we want the user to take as possible ERGO let's kill that last line 🔪

Sounds good to me! I have this in progress in current PR here: #7557

- #7557

> In line with this move, the original proposal recommended removing the pencil icons from places like Billing and Shipping. Let's forgo that so we can trigger 'not allowed' tooltips instead.
> We will want to implement tooltips anywhere that is disabled in the interface, but instead of consolidating the message, let's make it specific to the UI elements. 

This sounds like a good plan 😁 

Let's handle those changes as a separate issue – I don't want that change to block the refactor and the tracks event. Should be straightforward now the component is tidied up. I'll log an issue, feel free to add info. There may be some limitations with what we can do in the Woo-owned page (depends what capabilities we have in Woo-owned page; more DOM 'hack'ing => more risk/coupling) but we can likely do most of this.

> On another note— I am noticing that the text on the screenshots above is quite lengthy?
> I would recommend to implement the below text and styling where the intro sentence is shorter and the only one in bold. The rest will be in normal weight. This would make the content of the notice appear less heavy and potentially at just 2 lines.

I'm glad you picked up on this 🚀  I was thinking the same thing myself, especially since the text is 100% bold. I'll log an issue for this too.

**Comment by haszari** [comment]
> In line with this move, the original proposal recommended removing the pencil icons from places like Billing and Shipping. Let's forgo that so we can trigger 'not allowed' tooltips instead.
We will want to implement tooltips anywhere that is disabled in the interface, but instead of consolidating the message, let's make it specific to the UI elements.

Logged!

- #7567 

I don't think this is a high priority. Essentially all these changes are a band-aid to cover the fact that WooCommerce core doesn't understand that the order is disputed. The long term fix would be a new order status; I don't think we should invest significant time in disabling specific UI elements and showing tooltips.

**Comment by haszari** [comment]
> On another note— I am noticing that the text on the screenshots above is quite lengthy?
I would recommend to implement the below text and styling where the intro sentence is shorter and the only one in bold. The rest will be in normal weight. This would make the content of the notice appear less heavy and potentially at just 2 lines.

Logged:

- #7568

As I understand it, we should tidy this up at a priority, assuming there's no problems with the proposed wording.
