### ISSUE TITLE
Improve display of support phone number field in WooPayments settings

### ISSUE THREAD

**Issue by bradyv** [Automattic/woocommerce-payments#7512]
### Description
The support phone number field is styled differently than the other inputs on the page.
<img width="651" alt="Screenshot 2023-10-18 at 15 51 27" src="https://github.com/Automattic/woocommerce-payments/assets/889872/6534da54-540c-48c4-9329-3320e8202525">

### Acceptance criteria
We can fix this in two steps
- Change the class name from `input-text` to `components-text-control__input` which is the class used by other inputs
- Change the font size of the dial code from 16px to 13px

<img width="571" alt="Screenshot 2023-10-18 at 15 54 53" src="https://github.com/Automattic/woocommerce-payments/assets/889872/3441ccec-2154-4fa8-9495-550ab7fff2be">

### Testing instructions
1. Go to WooCommerce Settings -> Payments
2. Scroll down to Transactions

**Comment by bradyv** [comment]
@htdat Tagging you here as you were the one who added this field in #5471

**Comment by htdat** [comment]
Thanks for raising this concern @bradyv. 

At the moment, the phone input relies on an external dependency `intl-tel-input`. That's why this request looks easy but actually not. More context here paJDYF-85M-p2

However, good news is that @ismaeldcom could create and merge a native component for phone input to Woo core https://github.com/woocommerce/woocommerce/pull/40335

I think when our min supported Woo core version matches with the Woo core including this new phone input, we can refactor our current component `PhoneNumberInput` to base on it.

**Comment by jessy-p** [comment]
Could be related to https://github.com/Automattic/woocommerce-payments/issues/7529

**Comment by htdat** [comment]
👋 Hi @ismaeldcom, I am assigning this issue and #7529 to you so that you can answer and follow up them.

**Comment by ismaeldcom** [comment]
Thanks for the ping @htdat, as @elazzabi mentioned in #7529 the new input components lack some features to be used in WooPayments settings. It was designed with onboarding requirements in mind. So we will need to work a bit more on it before being able to replace the current one.

Being this work done only on cooldown weeks, it's probably better to fix the style of the current one rather than waiting 🙂

**Comment by htdat** [comment]
🙇 Thanks @ismaeldcom and @vladolaru for fixing this issue :D
