### ISSUE TITLE
Missing error handling with blocks checkout

### ISSUE THREAD

**Issue by c-shultz** [Automattic/woocommerce-payments#7587]
### Describe the bug
When checking out on a site with WooPayments + checkout blocks, invalid credit cards are causing the checkout to fail without a visible error notice. I entered a real credit card number but intentionally changed the expiration or CVC codes, and saw this in this console:
<img width="817" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/6209518/0c5f8a83-74eb-4318-ad98-0d64b56c66eb">

Additionally, entering valid test credit card numbers on a live site (used some numbers from [here](https://www.paypalobjects.com/en_GB/vhelp/paypalmanager_help/credit_card_numbers.htm)), resulted in the same checkout failure without notice, but created this error in the console:
<img width="812" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/6209518/51917e4e-2e69-4644-8d54-f7760245e03d">

I tested on the WooPay test site (https://woopaymerchantdemo.com/) and one live T51 customer site.

### To Reproduce

1. Add item to cart
2. Go to checkout
3. Enter invalid credit card details
4. Place order
5. Site remains on checkout screen after place order fails to complete and no error messages are shown

### Expected behavior
Shopper is informed about the error

**Comment by c-shultz** [comment]
@timur27, I see I've at least partially repeated #7561 . When #7562 is in testing, please test these cases to see if it will close this out as well.

**Comment by timur27** [comment]
The issue was fixed by https://github.com/Automattic/woocommerce-payments/pull/7653, which will be part of WooPayments `6.8.0` released on Nov 16th. 

### Error message now displayed
<p align="center">
<img width="1295" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/22319444/f71bd736-38ef-442b-81db-9db2bc296d03">
</p>


### Where to test (if someone wants to) 
You can use https://inclined-plover.jurassic.ninja/, which uses [the latest `6.8.0` test version](https://github.com/Automattic/woocommerce-payments/releases/tag/6.8.0-test-3).

Thank you for creating and communicating the issue!
