### ISSUE TITLE
Transactions can have a status of `Authorized` even if no true authorization occurs

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#7618]
### Describe the bug
When a payment is started but no true authorization has taken place, the payment details for an individual transaction at **Payments > Transactions** will say that the payment enters an `authorized` state in the timeline:

> Payment status changed to Authorized.

The word "authorize" here might have multiple meanings. However, given that the word `authorize` means something very specific to merchants in regard to the payment process, I think that it's important to only use this phrase when a payment truly enters an authorized state.

It seems as though this verbiage comes from here... https://github.com/Automattic/woocommerce-payments/blob/3b42d0f8f74deadf5e3da4e29420f14cce9efb54/client/payment-details/timeline/map-events.js#L43-L51 ...but I could be mistaken. Additionally, I'm not sure how Phase 4 of the UPE migration might affect these instances. Flagging @timur27 to determine if that may be the case.

### To Reproduce

1. Start a payment but do not provide payment details to start the authorization process 
- I couldn't reproduce this on my own site after updating to 6.7.0.
- 7250297-zen reportedly encountered this after an Affirm purchase was declined. They were running 6.7.0 and dUPE.
2. Check the transaction details in **Payments > Transactions**.
3. The transaction's timeline will indicate: 
> Payment status changed to Authorized.

### Actual behavior
Checking a transaction at **Payments > Transactions** can lead a merchant to believe a payment is authorized without it going through the authorization process.

### Screenshots
From 7250297-zen:
![image](https://github.com/Automattic/woocommerce-payments/assets/82999806/a828e0be-1068-4519-ba22-abe180802e79)

An image from my test site ~1 month ago:
![image](https://github.com/Automattic/woocommerce-payments/assets/82999806/5a9b4d1e-da51-4e2e-aef7-ebd11c2f9783)

### Expected behavior
The term `authorize` only refers to a true authorization of a payment.

### Additional context

7250297-zen
7102264-zen
p1698965627416799-slack-C05QSQ0GT0U
p1696356764381749-slack-C3NCP7ZJ6

**Comment by timur27** [comment]
I couldn't reproduce the issue on my local or JN sites. I attempted payments with Affirm and 3DS but rejected them, and the transactions list did not update with the transaction.

> Start a payment but do not provide payment details to start the authorization process

Could you please provide additional information regarding this particular testing step? I'd like to clarify what is meant by _start a payment but do not provide payment details_. If we are referring to making a payment using a method that requires additional steps, such as authentication on a third-party site (like 3DS or Affirm), then I have verified on my two sites that the transaction is not initiated while the `pi` is in the `requires_action` state.

**Comment by csmcneill** [comment]
We could reproduce this quite easily before the move to dUPE, as loading the card element on the checkout page would create an `Incomplete` payment in Stripe while also listing the transaction in **Payments > Transactions** (which is how I got the screenshot from my own site).

With the move to dUPE, I cannot reproduce this on my own test site (including testing via 3DS, Affirm, etc.). However, 7250297-zen encountered this issue with dUPE/6.7.0.

**Comment by darcie** [comment]
7382088-zen

**Comment by timur27** [comment]
Thanks for the report @darcie! I went through the ticket and I agree we should look into the wording there as well.

#### On `Pending` Sofort payments
Another thing mentioned in the ZenDesk ticket that is unrelated to this issue, but I've spent some time on trying to understand the issue is Sofort payments are `Pending`. This is pretty unexpected behavior. I set up a new Germany-based store, but unfortunately Stripe doesn't allow new stores to use Sofort because it will be deprecated soon (and kudos to you for providing the heads up to the customer as well).

However, I found another active Germany-based store with Sofort payments used extensively (I've left the link to this account in 7382088-zd-a8c). And this store also has `Pending` Sofort transactions, but they all start from the 28th of November. I also see that the first misbehavior occurs with the payments of version `6.8.0`, so it might be a good idea to search for updates that might have possibly impacted the behavior. 
Hope this helps.

**Comment by darcie** [comment]
Hey @timur27, I don't think this is only for Sofort or APMs. My hunch is that the first status is “Started” but we use Authorized because that's the first status available. Some screenshots of another case of a failed payment showing as authorized: p1703629216732269-slack-C05QSQ0GT0U

**Comment by gpressutto5** [comment]
This timeline is generated by wcpay server and the first status for every intent is always `authorized`, but it doesn't mean the payment was authorized, only that it was created. I created a thread to discuss the best way to resolve this p1706813634402009/1706813578.553399-slack-C0208C3BXHP

The issue is reproducible by failing 3DS
