### ISSUE TITLE
Update @woocommerce/components dependency in UI tests

### ISSUE THREAD

**Issue by vbelolapotkov** [Automattic/woocommerce-payments#765]
Components v4.0.0 were created in Dec 2019 and we're still using v3.2 in UI tests.

**Comment by vbelolapotkov** [comment]
The latest version is 5.1.2. h/t @dechov

**Comment by dechov** [comment]
I was attempting to update the `@wordpress/date` version to 3.9.0 (or higher) for the reason noted in https://github.com/Automattic/woocommerce-payments/issues/609, but it appears to make all of the same tests fail, apparently because the current `@woocommerce/components` version relies on an older version of `@wordpress/date` (i.e. 3.3.0, the one we are also currently depending on) and there's some conflict.

**Comment by vbelolapotkov** [comment]
@dechov there is some progress in PR #766 and dependencies problems seem to be resolved. IIRC there are only several tests failing but not related to `@wordpress/date`. Unfortunately, I don't have capacity at the moment to push that to the end, so if you have time and interest there feel free to push on top of the PR.

**Comment by dechov** [comment]
> dechov pinned this issue

Not that it's a bad idea but I didn't mean to do that and have no idea how it happened.

**Comment by vbelolapotkov** [comment]
That is ZH pipeline feature :)

**Comment by vbelolapotkov** [comment]
@Automattic/hydra I'd appreciate if someone can pick this work up and push it to the end.
