### ISSUE TITLE
Instant deposit API request should provide `currency` rather than `transaction_ids`

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-payments#7711]
### Description

We are removing the requirement for manual/instant deposits to be associated with specific transactions.

As part of this change, the `transaction_ids` parameter will be deprecated from the `POST deposits` endpoint. Without the transaction_ids, the server is unable to infer the currency to use.

**Comment by shendy-a8c** [comment]
@brucealdridge ~can't the currency be inferred from Stripe's Balance object, specifically the [instant_available.currency](https://stripe.com/docs/api/balance/balance_object#balance_object-instant_available-currency)?~

Never mind, that won't work because if there are multiple currencies of `instant_available.currency`, we need to know exactly which currency to be deposited and client needs to pass that information.

**Comment by Jinksi** [comment]
I've added the blocked label to indicate that the relevant PR #7828 should not be merged until the required server changes have been deployed (server PR 4061).
