### ISSUE TITLE
Payment request button language doesn't match site language

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#7727]
### Describe the bug
On this US site that supports Spanish and English languages, the WooPay button only renders in English and the GPay button only in Spanish regardless of the site language.

![comprar con woopay](https://github.com/Automattic/woocommerce-payments/assets/82999806/31521b54-d8d6-47fe-8f62-7f0e70d72219)

### To Reproduce
1. Create a Woo site with `Español` as the site language.
2. Onboard as a US account.
3. Enable Google and Apple Pay.
4. Enable WooPay.
5. Note that WooPay is in English, and Gpay is in Spanish

### Expected behavior
PRB button language should match the site language

### Desktop (please complete the following information):
MacOS, Chrome

Edit from @csmcneill: 
- I removed specific information about the merchant site where this was discovered, as this is a public repo. 
- I replaced it with general information that will also allow folks to test the issue on their own site.

**Comment by pierorocca** [comment]
cc @frosso

**Comment by pierorocca** [comment]
Thanks @csmcneill. Nice catch and helpful notes.

**Comment by frosso** [comment]
I believe this is happening because the WooPay translation is not available.
If the merchant implemented them on their site with [Loco Translate](https://wordpress.org/plugins/loco-translate/), the correct behavior will appear.
I tested this with the latest `dev` build.

![Screenshot 2023-11-21 at 5 07 17 PM](https://github.com/Automattic/woocommerce-payments/assets/273592/d1a66aca-6bb8-4e55-98f0-9d19bd3761eb)

![Screenshot 2023-11-21 at 5 07 08 PM](https://github.com/Automattic/woocommerce-payments/assets/273592/6d58909e-01e2-49ae-a1c2-1a2b23a5131b)

This isn't the ideal solution, since we would likely want to have standardized translations in https://translate.wordpress.com/projects/woocommerce/woocommerce-payments/ .
I also understand that WooPay isn't available outside of the US, at this time, but we'd like to expand the market (and it's still not an excuse, since there might be spanish-specific sites in the US as well).

I pushed a quick fix to get us closer: https://github.com/Automattic/woocommerce-payments/pull/7759

**Comment by frosso** [comment]
Discussed in maintenance meeting, closing for now
