### ISSUE TITLE
WooCommerce Core main screen should display a task for Sandbox mode accounts to go live

### ISSUE THREAD

**Issue by daquinons** [Automattic/woocommerce-payments#7736]
### Describe the bug
![image](https://github.com/Automattic/woocommerce-payments/assets/2612426/806645d1-8a47-463b-91e4-41de5aa0b1d6)

As part of the enhancements proposed by Design here paJDYF-bnR-p2#comment-21898

Follow-up of https://github.com/Automattic/woocommerce-payments/issues/7498, clicking on the action button in the task has the same behavior as #7498 prompts

**Comment by anu-rock** [comment]
I am looking to clarify some requirements.

1. **What happens when the task is clicked?**

The issue description says:

> Follow-up of https://github.com/Automattic/woocommerce-payments/issues/7498, clicking on the action button in the task has the same behavior as https://github.com/Automattic/woocommerce-payments/issues/7498 prompts

Double-checking if that means showing the `SetupLivePaymentsModal` React component. This is not possible in a straightforward, all-PHP solution such as https://github.com/Automattic/woocommerce-payments/pull/4418. We can only redirect to another page with an all-PHP solution.

To show the JS modal, we'll probably need to additionally follow [these instructions](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce-admin/docs/features/onboarding-tasks.md#step-2--register-the-task-in-javascript).

The quickest solution would be to simply redirect a merchant to the Payment Settings page and rely on the sandbox mode notice in general settings. But that doesn't sound ideal.

2. **When live payments have been enabled, should the task disappear or appear checked?**

cc @timmy5685 @vladolaru @dmallory42

**Comment by anu-rock** [comment]
**Update:** I found https://github.com/Automattic/woocommerce-payments/pull/7129 that can be used as a reference PR to add the go-live task.
