### ISSUE TITLE
Deposit details shows "paid" and "deposit date" for withdrawals

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-payments#7802]
### Describe the bug

On the deposit details page when the amount "deposited" is negative, Stripe has withdrawn the amount from the merchant's account.
Both the `Paid` status and `Deposit date` label could be clearer.

![image](https://github.com/Automattic/woocommerce-payments/assets/57298/1fec4e89-d923-42bc-ba63-b13005dc5033)

NB: On the deposits list page, we show correctly that it is a withdrawal.

![image](https://github.com/Automattic/woocommerce-payments/assets/57298/1a57c073-b528-4b5f-a37d-d905c34001bc)

**Comment by haszari** [comment]
Most merchants don't experience withdrawals, so I've marked as medium priority.

At the same time, this is important – `paid` is misleading and inaccurate, which could erode trust in WooPayments.

**Comment by jessy-p** [comment]
The "Type" column on the Deposits list page currently displays either Withdrawal or Deposit, depending on whether the amount is negative or not. However, on the Deposit Details page, the "Type" is not displayed. Instead, the "Status" of the deposit is shown, which is marked as "Paid". This labelling is confusing for Withdrawals.

@rogermattic, could you propose some modifications for the Details page to more accurately represent when the deposit is actually a withdrawal by Stripe?

**Comment by rogermattic** [comment]
Hey @jessy-p @rua @brucealdridge 

What do you think about swapping wherever we display a `Deposit` label (we do have that label in many places on this screen :D )  to `Withdrawal`  and then `Deducted` instead of `Paid` as a quick fix? 
<img width="1344" alt="Screenshot 2024-03-13 at 17 02 53" src="https://github.com/Automattic/woocommerce-payments/assets/94967682/a03554c2-5f43-426d-928c-36ffe40d19f8">

**Comment by haszari** [comment]
> What do you think about swapping wherever we display a Deposit label (we do have that label in many places on this screen :D ) to Withdrawal and then Deducted instead of Paid as a quick fix?

👌🏻  Totally, this is what I was thinking, just switch out the wording for the rare / unfortunate case where we need to pull funds back from merchant.

**Comment by rogermattic** [comment]
@haszari Awesome! Thanks:)

**Comment by nagpai** [comment]
@rogermattic - Should the color of the OrderStatus indicator be red for withdrawal? 



![Image](https://github.com/Automattic/woocommerce-payments/assets/4162931/f0272c79-9609-4791-aca9-f304e89a8bcb)

**Comment by rogermattic** [comment]
Hey @nagpai !  Good question, thanks for asking :) 
I think we should leave it green as, in my mind, the colour symbolises that the _action has been_ done. We have the status to explain what happened, which should make it clear to the user. Otherwise, the user may be confused and feel as if something wrong has happened. WDYT?
