### ISSUE TITLE
WooPay payment method fails to display at order received page for different themes

### ISSUE THREAD

**Issue by ricardo** [Automattic/woocommerce-payments#7836]
Context: p1701797157327209-slack-C022WMN88KG

### Describe the bug

The `woocommerce_order_get_payment_method_title` filter is not being triggered in themes other than Storefront. This filter is [currently responsible](https://github.com/Automattic/woocommerce-payments/blob/9df23da4852ece6cd2c5900856c7331fb5b34201/includes/class-wc-payments-order-success-page.php#L31) for displaying the payment method details.

We might need to use a different method for displaying the payment method, or understand why the current method doesn't work. This might also be related to some regression or change in the WC Core templates.

### To Reproduce

1. As a merchant, switch to the Twenty Twenty-Four theme.
2. As a shopper, checkout using WooPay.
3. Notice the missing payment method at the order received page on the merchant store.
4. Notice the payment method is displayed if you switch to the Storefront theme.

### Actual behavior

WooPay payment method fails to display at order received page for the Twenty Twenty-Four theme.

### Screenshots

![image](https://github.com/Automattic/woocommerce-payments/assets/5509901/14aa6c84-c805-4354-b8b1-a35e911004de)

**Comment by pierorocca** [comment]
@ricardo as this is not WooPay specific, let's update the component as appropriate. Nice catch. 

Not only is the payment method missing, the billing address and email address are missing. Mind tracking down when that was removed and by whom? Does WooPayments have the ability to override Core?

According to [Baymard research](https://baymard.com/premium/guideline-collections/echwd2/596), an Order Thank You page should contain:

> In testing, we observed that the following details were critical to include on the confirmation page for it to serve as a true order receipt:
> 
> Order Number
> **Email Address**
> Shipping Details
> **Payment Details**
> Items Ordered
> Order Cost Summary
> Order-Specific Details or Instructions

**Comment by ricardo** [comment]
> Mind tracking down when that was removed and by whom?

I [sort of flagged](https://a8c.slack.com/archives/C022WMN88KG/p1701797157327209) this in Slack, but from our end, the last change I tracked was https://github.com/Automattic/woocommerce-payments/pull/6740 which fixed the styling, but apparently made the payment information hidden for other themes.

It might also have to do with some change in WC core as @rafaelzaleski pointed out – Rafael, maybe you can confirm as you worked on #6740.

> the billing address and email address are missing

These should be displayed if the user is logged in.

> Does WooPayments have the ability to override Core?

I think so for this specific part, but given this might be a feature of WC core not disclosing PII of guest orders, we should probably be conscious about doing it differently.

**Comment by pierorocca** [comment]
>>the billing address and email address are missing

>These should be displayed if the user is logged in.

And also for guest checkouts where the user has not created an account. The typ must be able to show all the same information that a receipt would contain. I know core has made some changes to limit this data for security and I believe has opened up the shipping address token validity for 10 minutes. The same needs to be done with the billing info. Once the validity period passes then the shopper must rely on the email receipt for the order details.

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/WooPay-621412506e2a6700140b7aac/issues/Automattic/woocommerce-payments/7836?planning-poker) with Zenhub @cesarcosta99 @lovo-h @rafaelzaleski @ricardo

**Comment by rafaelzaleski** [comment]
I've identified that this issue began following the WC Core 8.3.0 update. I am currently working on finding a fix.

**Comment by rafaelzaleski** [comment]
[With WC 8.3.0, checkout blocks became the default for new installations using block-based themes](https://developer.woo.com/2023/11/16/woocommerce-8-3-0-released/#:~:text=Compatibility%20and%20Scope) (like TT3, TT4), integrating the Cart Block, Checkout Block, and the [new Blockified Order Confirmation template](https://href.li/?https://developer.woo.com/2023/10/03/woocommerce-blocks-11-2-0-release-notes/). 

This update initially altered the thank you page in the blockified confirmation template:

- [Payment method and emails are now displayed only for logged-in users.](https://github.com/woocommerce/woocommerce-blocks/blob/ab8ddb68949ef2189f3ac608947e8c66b3cda9a1/src/BlockTypes/OrderConfirmation/Summary.php#L35)

Currently, there are no filters to modify this, [but a recent PR has reversed this](https://github.com/woocommerce/woocommerce-blocks/pull/12072), meaning future WC Blocks versions will again show email and payment details for guest users. 

Lacking filters to adjust the behavior until a WC Blocks release in WC Core rectifies it, and since this issue primarily impacts block-based themes, we can consider closing this issue with no action on our end.

**Comment by rafaelzaleski** [comment]
View last comment
