### ISSUE TITLE
Localize Calendar Days vs Business Days Language in the Deposits Section of the Payments > Overview Page

### ISSUE THREAD

**Issue by CGA8C** [Automattic/woocommerce-payments#7900]
### Description

Update: per the [discussion](https://github.com/Automattic/woocommerce-payments/issues/7900#issuecomment-2481494581) below, we are going to remove the notice.

On the Payments > Overview Page, in the Deposits section, EU Accounts say "It may taken 1-3 business days for deposits to reach your bank account." but only the US, Australia, Japan, New Zealand, and the UAE use Business Days. Other countries should show Calendar Days here. 

![Markup on 2023-12-13 at 11:08:14 AM](https://github.com/Automattic/woocommerce-payments/assets/17998077/4b47052d-6df9-40f6-bd64-c9d7d8f2af3d)

### Acceptance criteria
* Have an Account not based in the US, Australia, Japan, New Zealand, or the UAE. (The screenshot above is from a German Account). 
* Check the Deposits Section of the Payments > Overview page.

**Comment by RadoslavGeorgiev** [comment]
This issue impacts Deposits, so assigning to Helix (based on team responsibilities Pc2DNy-3z-p2) @Automattic/helix.

Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by haszari** [comment]
Adding to Helix backlog at medium priority.

> only the US, Australia, Japan, New Zealand, and the UAE use Business Days. Other countries should show Calendar Days here.

@CGA8C  can you clarify this – do you mean that the language we're using is US/western centric (so this is akin to translation, localistion? 

Or is the issue that that the "type" of days is technically different in other markets? Feel free to link Stripe or other docs that explain how this works if the clearing time is conceptually different in "Calendar days" geos.

As I understand it, the `business` here is to essentially lower expectations and introduce some fuzzyness about when _exactly_ the money will clear/land. If we tweak this wording we need to be sure it doesn't increase expectations of exactly when funds will be available. An alternative would be to use a different word that is more common globally, e.g. "working days" or "approximately 1-3 days depending on bank" etc.

**Comment by haszari** [comment]
> As I understand it, the business here is to essentially lower expectations and introduce some fuzzyness about when exactly the money will clear/land. If we tweak this wording we need to be sure it doesn't increase expectations of exactly when funds will be available. An alternative would be to use a different word that is more common globally, e.g. "working days" or "approximately 1-3 days depending on bank" etc.

@souravdebnath1986 @CGA8C what do you think about making this language more generic, so we avoid the "bug" that business days is not accurate in some regions? I don't think it's worth making the message dynamic based on merchant country – over complicated for low benefit.

I think we should change the notice to something roughly accurate, and link to docs for more details:

> It may take 1-5 days for payouts to reach your bank account. [Learn more](https://woocommerce.com/document/woopayments/payouts/payout-schedule/)

Also keen for thoughts from @csmcneill  @aheckler

**Comment by aheckler** [comment]
Frankly, I think we should consider just doing away with that little info/notice thing completely. It's just trying to say the same thing that we already say in our docs [here](https://woocommerce.com/document/woopayments/payouts/payout-schedule/#pending-funds):

> NOTE: Most banks deposit money into your bank account as soon as they receive it, but some might take a few extra days to make it available. So, while the chart above shows the usual rolling delays, we cannot guarantee those timelines in every case.

Context: Stripe tries to initiate deposits with the right amount of lead time such that each deposit lands in your bank account when it should. For example, if Stripe knows that my bank takes 2 days to land a deposit from the time Stripe first sends it, and my next deposit is schedule for the Nov 20, Stripe will initiate the deposit/transfer on Nov 18 so that it lands on the correct day, the 20th. However, banks are banks, and sometimes things just take longer for no discernible reason, and this text is trying to accommodate that scenario.

If we want to keep some sort of warning about this, we should change the text to be more vague, e.g.:

> Payouts may take slightly longer to become available in your bank account, depending on your specific bank.

[Stripe's phrasing](https://docs.stripe.com/payouts#:~:text=Most%20banks%20deposit%20payouts%20into%20your%20bank%20account%20as%20soon%20as%20they%20receive%20them%2C%20though%20some%20might%20take%20a%20few%20extra%20days%20to%20make%20them%20available.) is:

> Most banks deposit payouts into your bank account as soon as they receive them, though some might take a few extra days to make them available.

That said, we might consider removing the warning since the **?** hover thing right above it already links to the relevant place in our docs where that warning is mentioned.

![Image](https://github.com/user-attachments/assets/5c7b5d74-ff08-49ca-8f74-a1a66e633b9a)

Anecdotally, I cannot recall ever encountering a support scenario where a specific bank delay like that played a factor in the situation, nor have I ever heard of such a case.

**Comment by haszari** [comment]
> `It may take 1-3 business days for deposits to reach your bank account.`

> Frankly, I think we should consider just doing away with that little info/notice thing completely. It's just trying to say the same thing that we already say in our docs [here](https://woocommerce.com/document/woopayments/payouts/payout-schedule/#pending-funds).

I agree @aheckler ! And this would declutter the UI a little – one less notice.

@rogermattic @souravdebnath1986 what do you think about Adam's suggestion to **remove** the `It may take 1-3 business days for deposits to reach your bank account.` notice, since we have clear info about payout timing and delays in the help tooltip on the schedule summary? 

![Image](https://github.com/user-attachments/assets/9d456c02-18cc-4284-b24b-9c0b0686cabf)

**Comment by rogermattic** [comment]
> @rogermattic @souravdebnath1986 what do you think about Adam's suggestion to remove the It may take 1-3 business days for deposits to reach your bank account. notice, since we have clear info about payout timing and delays in the help tooltip on the schedule summary?

IMO, we could remove this notice, but up to @souravdebnath1986. However, I wonder if we could add a Learn more link directing users to the [documentation](https://woocommerce.com/document/woopayments/payouts/payout-schedule/#pending-funds). This could be helpful for less experienced users, as the page explains that fund timing isn’t entirely within our control.

We should also monitor the support queue for a while after removing the notice. If we start seeing tickets like, 'It says my payout was scheduled for..., but I haven’t received my funds yet,' we could revisit this decision. 😊

**Comment by shendy-a8c** [comment]
To summarize, we're going to remove this notice.

![Image](https://github.com/user-attachments/assets/d4833697-8919-44f4-bc0a-2ed59dc5b411)


> However, I wonder if we could add a Learn more link directing users to the [documentation](https://woocommerce.com/document/woopayments/payouts/payout-schedule/#pending-funds).

The tooltip already has links to the docs. However, there is no link specific to the pending fund section. Should I add one more item like below @rogermattic ?

![Image](https://github.com/user-attachments/assets/8e4a087a-31ad-495e-a5b7-9690b24fcfbd)

Or maybe combine it with like this?

![Image](https://github.com/user-attachments/assets/a3f559bd-f7b5-4a37-932f-26b7811db6d6)

**Comment by aheckler** [comment]
IMHO we should consider making the tooltip more generic as well, as opposed to including more detail. Since [many _many_ factors](https://woocommerce.com/document/woopayments/payouts/payout-schedule/) go into when payouts are issued:

- Pending period (already mentioned in tooltip)
- Available funds (also already mentioned)
- Payout schedule (also already mentioned)
- Daily cutoff time (not mentioned)
- Business/working days vs. non-business/working days (also not mentioned)

... it might be counter-productive to try to mention them all.

So perhaps a better solution would be to:

- Remove the `It may take 1-3 business days...` notice completely as mentioned above.
- Adjust the tooltip to say something like: "Many factors can affect payout timing. [Learn more](https://woocommerce.com/document/woopayments/payouts/payout-schedule/)." 
  - Or slightly more verbose: "The exact timing and amount of your payouts can vary based on several factors. Please see our [payout schedule guide](https://woocommerce.com/document/woopayments/payouts/payout-schedule/) for more information."

**Comment by shendy-a8c** [comment]
Like this? I'll go with this for now and will monitor if there's further discussion.

![Image](https://github.com/user-attachments/assets/1297c974-a633-45f1-a1a2-4ce377efecbd)

**Comment by aheckler** [comment]
LGTM! @francoishvz @AashikP Any other thoughts here?

**Comment by AashikP** [comment]
Looks perfect to me!

**Comment by rogermattic** [comment]
I love the tooltip simplification that @aheckler suggested :) 

We can go with this version or as an alternative:
> The timing and amount of your payouts may vary due to several factors. Check out our [payout schedule guide](https://github.com/Automattic/woocommerce-payments/issues/7900#) for details. 

WDYT? @aheckler  @francoishvz @AashikP

**Comment by AashikP** [comment]
As part of this discussion (p6q7sZ-hU7-p2), we'll soon request further changes to the notice and tool tips. This needs to be a broader discussion, though. 

That said, I guess what we have above looks good for the moment.

**Comment by aheckler** [comment]
Sounds good @rogermattic!

**Comment by shendy-a8c** [comment]
Will follow the [latest copy](https://github.com/Automattic/woocommerce-payments/issues/7900#issuecomment-2506489574).

![Image](https://github.com/user-attachments/assets/b26d807f-cc79-4af0-ab4a-e65d68edeeba)
