### ISSUE TITLE
Investigate rate limit hits on endpoints

### ISSUE THREAD

**Issue by dmallory42** [Automattic/woocommerce-payments#7912]
### Describe the bug

We saw some rate limits being hit in test mode on the capabilities endpoints. (ref: p1702490673280149-slack-CGGCLBN58)
After investigation, the traffic on this endpoint looks normal for live accounts so this seems to be an issue of multiple requests being made to this endpoint for sites suffering an IDC.
We should investigate and prevent the request being made in this case to stop the endpoint getting spammed with requests that cannot succeed until IDC is resolved.

EDIT by @daquinons: There has been another case that we need to investigate (in live) that might or might not be the same root cause but it's not in the capabilities endpoint. More here p1703255489195439/1703148287.777159-slack-C03V0SP07SL This second one will get higher priority and then try to draw if the root cause is the same or not.

**Comment by RadoslavGeorgiev** [comment]
This issue impacts onboarding (IDC in this case), so assigning to Moltres (based on team responsibilities Pc2DNy-3z-p2) @Automattic/moltres.
Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by oaratovskyi** [comment]
I have discovered that the client with a live account has WooPayments 5.1.5. 
The errors started on Dec, 20 and stopped yesterday. Now their site https://uniformbizpos.com/ is not accessible, see p1703761847852589/1703148287.777159-slack-C03V0SP07SL

**Comment by oaratovskyi** [comment]
Pr is ready for the part of issue that's more important (live blog got rate limited by Stripe). 

As for the remaining part of the issue (`Testmode request rate limit exceeded, the rate limits in testmode are lower than livemode.`), this solution may work too. If it doesn't work after deployment, we could try rolling back changes in https://github.com/Automattic/woocommerce-payments/pull/7767/files and find better approach of how to resolve the next situation that creates a lot of confusion for a merchants and adds more work to support. It was resolved by that PR:
users click Back in the Stripe KYC and can re-onboard again in dev mode (due to no webhook from Stripe about the start of onboarding, we need to pull the data from Stripe manually bypassing the cached data).
