### ISSUE TITLE
Rename log title to woopayments

### ISSUE THREAD

**Issue by sukafia** [Automattic/woocommerce-payments#7927]
### Description

I was recently testing WooPayments and attempted to check the log. I searched the log dropdown for `woopayments`and no log was returned. I figured it's still using the old product name. Though not a significant change, I think it might be beneficial to update the log title to match the product name to ensure consistency. 

![diloRO.png](https://github.com/Automattic/woocommerce-payments/assets/60121732/150d7c26-f55b-4c7e-88a2-004818b26818)

The natural thing is to search for the product name (I also search for `woopayments` first when trying to find this repo. 😂

**Comment by csmcneill** [comment]
We had discussed renaming some aspects of WooPayments previously (e.g., the repo name) in paJDYF-7Sw-p2#comment-18893 — but renaming the logs might be a worthwhile approach as it is much more "customer facing" than what was originally discussed.

Flagging this to @oaratovskyi and @vbelolapotkov since y'all were involved in the original discussion.

**Comment by oaratovskyi** [comment]
@sukafia @csmcneill I have fixed it during Moltres cooldown week 🎉 
FYI I have also reached Corey Gehrke to double-check the best way to communicate this change to all HEs.
