### ISSUE TITLE
Viewing a test mode order while test mode is disabled produces errors

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#7967]
### Describe the bug

This may be related to https://github.com/Automattic/woocommerce-payments/pull/7898, which was included in the 7.0.0 release.

If an order is placed in test mode, and that same order is viewed after test mode is disabled, it produces a snackbar error:

```
Error retrieving transaction.
```

I suspect this is a result of a 500 error in the console...

```
/wp-json/wc/v3/payments/charges/ch_3OUYY42EHhK9IQzL0RyLhuof?_locale=user:1 
        
        
       Failed to load resource: the server responded with a status of 500 ()
```

...and this `500` network response:

```
{
    "code": "wcpay_get_charge",
    "message": "Error: No such charge: 'ch_3OUYY42EHhK9IQzL0RyLhuof'; a similar object exists in test mode, but a live mode key was used to make this request.",
    "data": null
}
```

Re-enabling test mode resolves the error.

### To Reproduce

1. Enable test mode.
2. Place an order.
3. View the edit order page for the order placed in step 2.
4. Disable test mode.
5. Repeat step 3.
6. Note the snackbar error.
7. Check your browser's console tool.
8. Check your browser's network tool.

### Actual behavior
A snackbar error is displayed when viewing a test transaction while WooPayments is not in test mode. This can create some confusion for the merchant.

### Screenshots

![snackbar error](https://github.com/Automattic/woocommerce-payments/assets/82999806/2a48b9ba-a5fa-4128-8b4b-84ca189b20cf)

### Expected behavior

To some extent, the network response and the resulting console error are expected because we are trying to access test mode data while not in test mode. However, suppressing the snackbar error here may be a good option to consider.

**Comment by csmcneill** [comment]
Flagging this to @htdat in case this is related to https://github.com/Automattic/woocommerce-payments/pull/7898

**Comment by htdat** [comment]
@csmcneill - thanks for tagging me. However, the cause of the issue is not related to https://github.com/Automattic/woocommerce-payments/pull/7898, as the new notice regarding Test Mode is generated based on the order meta. 

Instead, it's the Dispute notice trying to get charge data in the same screen. I think when constructing the request, it would consider adding `test_mode` param (based on the order meta) to avoid this error. 
https://github.com/Automattic/woocommerce-payments/blob/cdbb1d1584a18d5fa1d038760032b492c3be2e7e/client/order/index.js#L187-L192

cc @haszari (as the author of this commit https://github.com/Automattic/woocommerce-payments/commit/b57a3530c6e30ea58dc8a63b99e6cbdc97f5a8e7) also team @Automattic/helix to have a look.

**Comment by Jinksi** [comment]
This is the same as issue #7076 but highlights the error snackbar, which #7076 didn't mention. Adding to Helix maintenance board.
