### ISSUE TITLE
PHP Warning with v 7.0.0

### ISSUE THREAD

**Issue by WillBrubaker** [Automattic/woocommerce-payments#7975]
### Describe the bug

After updating to 7.0.0, a PHP warning is happening

```
Warning: The use statement with non-
compound name
'WC_Payment Gateway_WCPay' has no effect in /home/pravrse/adella.se/wp-
content/plugins/woocommerce-payments/includes/class-wc-payments-
payment-method-messaging-element.php
on line 13
```

### To Reproduce

1. Not sure what it takes aside from updating to 7.0.0
2. Perhaps Klarna needs to be enabled?

### Actual behavior
A PHP Warning

### Screenshots
![XMezHt.png](https://github.com/Automattic/woocommerce-payments/assets/2127470/1fcf06e6-b59b-4ac7-b6f9-0d3c938612ec)

### Expected behavior
No warning

### Desktop (please complete the following information):

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

### Smartphone (please complete the following information):

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

### Additional context
7536999-zen

**Comment by solstudioim** [comment]
The same thing showing on product page: ![eCp8rL.png](https://github.com/Automattic/woocommerce-payments/assets/17371139/7e63fb53-9552-4feb-b5c0-cea9724fecba)

Got the report on chat: 7537176-zd-a8c
Reverting to version 6.9.2 resolved the problem. 

The site that I interacted with has PHP version 7.4

**Comment by jessy-p** [comment]
@timur27 Please have a look in case its related to #7782

**Comment by timur27** [comment]
Thanks for reporting this. It's happening after https://github.com/Automattic/woocommerce-payments/issues/7782.

#### Behavior and steps to reproduce
* enable any number of the BNPL payment methods (Klarna/Affirm/Afterpay)
* store should match store currency and product price requirements depending on which BNPL is being used ([afterpay requirements](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/payment-methods/class-afterpay-payment-method.php#L33-L64), [affirm requirements](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/payment-methods/class-affirm-payment-method.php#L35-L47), [klarna requirements](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/payment-methods/class-klarna-payment-method.php#L35-L100)) e.g. USD & $50
* navigate to the product details page
* observe the warning
* refresh the page
* the warning is gone

This is happening because when BNPLs are enabled, we're loading `class-wc-payments-
payment-method-messaging-element.php`, which imports `WC_Payment_Gateway_WCPay`. Class `class-wc-payments-
payment-method-messaging-element.php` itself doesn't define any namespace so it's in a global namespace, same way as `WC_Payment_Gateway_WCPay` is. Because of that, the import statement `use WC_Payment_Gateway_WCPay;` is unnecessary. 

This warning happens when **all** of the below requirements are met:
* at least one of BNPLs enabled
* product details page
* first page load
* store currency and product price requirements are met ([afterpay requirements](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/payment-methods/class-afterpay-payment-method.php#L33-L64), [affirm requirements](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/payment-methods/class-affirm-payment-method.php#L35-L47), [klarna requirements](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/payment-methods/class-klarna-payment-method.php#L35-L100)) e.g. USD & $50

Moreover, if a user opens product details for a product which doesn't meet any of the above requirements and afterward opens a product which meets them, the warning is not appearing either.
