### ISSUE TITLE
Cannot restock items with a $0.00 refund

### ISSUE THREAD

**Issue by melek** [Automattic/woocommerce-payments#7984]
### Describe the bug
When trying to restock an item on an order which was refunded via the Transaction Page 'Refund in Full' option, I found I cannot perform a $0 refund on an order with WooPayments. In the case of a fully refunded order, a merchant has to fall back to manually editing the product's inventory.

This situation could be rare, but until #7969 is corrected it may come up.

### To Reproduce
1. Refund a linked order in full from the Transaction page.
2. Edit the order, increment the 'Quantity'. You must zero out the refund price and tax to get to $0 (since it is already refunded).
3. Make sure 'Restock refunded items' is checked!
4. Submit the $0 refund. See error.

### Actual behavior
The refund cannot be performed.

### Screenshots
![image](https://github.com/Automattic/woocommerce-payments/assets/220149/81b44472-d26f-4aff-945a-48dd5f96fe05)
![image](https://github.com/Automattic/woocommerce-payments/assets/220149/4254a628-1902-4d77-83c6-2e463cbd4850)

### Expected behavior
The $0 refund should be performed, restocking the items.

### Desktop (please complete the following information):

* OS: MacOS
* Browser: Firefox: 
* Version: Latest

**Comment by jessy-p** [comment]
This issue impacts Fees, Transactions (Auth and Capture), Refunds, Amazon Pay, In-Person Payments so assigning to Pulsar (based on team responsibilities Pc2DNy-3z-p2) @kalessil. Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by dmvrtx** [comment]
I think the problem here lies beyond the WooPayments scope. What is happening is that WooCommerce doesn't allow re-stock the order items without doing a refund. It is a clear functionality gap, since there are at least three separate scenarios possible:

 1. Merchant wants to refund, but do not re-stock items, e.g. in case of shipping issues.
 2. Merchant wants to re-stock but do not refund, e.g. if order has been disputed but not shipped yet.
 3. Merchant wants to refund and re-stock, e.g. if order has been cancelled before shipping.

I see why the merchant wants to use re-stock option from the order page, since manually adjusting stock for a large order for a shop with high volume of orders can be painful.

@Automattic/proton, I'd appreciate your input here, if this topic is on the radar or if there are other solutions, aside from manually adjusting the stock.

**Comment by barryhughes** [comment]
Hmm. Well, using only WC Core, refunding an entire order **does** seem to result in products being re-stocked by default, including if the order only contains a $0 product. 

So, I don't think there are implications here (and the invalid refund amount error appears to come [from here](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payment-gateway-wcpay.php#L2190C10-L2190C28) rather than WC Core).


> 1. Merchant wants to refund, but do not re-stock items, e.g. in case of shipping issues.
> 2. Merchant wants to re-stock but do not refund, e.g. if order has been disputed but not shipped yet.
> 3. Merchant wants to refund and re-stock, e.g. if order has been cancelled before shipping.

Again just thinking of WC Core with a generic gateway, all three scenarios seem possible (restocking can be toggled on or off, and a zero-dollar refund can be issued along with a re-stock).

Please do let un know if we've misunderstood, or if there are further questions :+1:

**Comment by dmvrtx** [comment]
@barryhughes, thank you for your review. What I find odd is the requirement for payment plugin to process a zero amount refund so that WC Core would re-stock an item. I understand, that it can be a common workaround for WooCommerce merchants, but, it doesn't mean that it should be that way.

I think there is a functionality gap in WC Core - ability to re-stock order items without touching payment at all.

For the WooPayments side I'll see what can be done to mitigate this issue in a short-term. Either through exiting early on zero amount refunds without further processing, or some similar approach.

**Comment by barryhughes** [comment]
> What I find odd is the requirement for payment plugin to process a zero amount refund.

Seen another way, if a plugin has implemented the `WC_Payment_Gateway::process_refund()` part of the payment gateway interface then they will be *notified* of the refund, but whether they do any further processing or not is up to the plugin.

If, for zero dollar refunds, this is **never** needed, then I guess it could be skipped. We're not the experts on that, though, so definitely would rely on you all/Transact for guidance (and we'd probably want to open this to public discussion, even).

> I understand, that it can be a common workaround for WooCommerce merchants, but, it doesn't mean that it should be that way.

I'm a little unsure how common this even is (my instinct would have been it's not very common, but I don't have any data to back that up). If it is quite common, that would be useful to know.

> I think there is a functionality gap in WC Core - ability to re-stock order items without touching payment at all.

As long as the vehicle for doing this is a refund, I tend to think it makes sense to notify the gateway associated with the order ... but to be clear, are you suggesting we should support re-stocking all items in an order without a refund? If the need exists, I'm sure we can do it. We'd want to think through the surrounding user stories in more detail first, though, and figure out what how to describe this process in a way that is clear to merchants.

Is there an example from other ecommerce solutions we can look to here?

**Comment by melek** [comment]
From a non-developer's perspective, I'd expect any gateway to process a $0 refund exactly as a built-in gateway would just for consistency of experience.

That said, the only reason I ran into this error was because this seemed to be the natural workaround to #7969, which is now resolved. Usually, a $0 order (such as a free trial subscription order) doesn't actually engage the gateway on the order, and could be "refunded" & restocked without issue. That is to say, unless there are more edge cases like this hanging around (I can't think of any), I doubt this is affecting many merchants. The question of safely incrementing / decrementing stock in Woo generally is certainly outside the scope of this issue!
