### ISSUE TITLE
UPE: compatibility with refunds (a case with disabled payment methods)

### ISSUE THREAD

**Issue by kalessil** [Automattic/woocommerce-payments#8058]
### Describe the bug

In the latest UPE variations, if a payment method is disabled on the settings page, refunds for orders made with that payment method are broken.

Broken in 2 ways:
- refunds from transaction details page: error, painting to the disabled gateway
- refunds from the order page: no errors, but gateway not requesting refunds via processor

### To Reproduce

- Place an order with a payment method (non-card)
- Disable the payment method in the setting
- Try refunding the order from the transaction and order pages

### Expected behavior

- Refunds via transaction and order pages are performed (incl. refund request on the processor side)

### Additional context

paJDYF-bPM-p2 and see also accepted comment as guideline to fix.

**Comment by zmaglica** [comment]
This issue impacts Refunds, so assigning to Pulsar (based on team responsibilities Pc2DNy-3z-p2) @kalessil . Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by kalessil** [comment]
@FangedParakeet: this ticket is the result of a conversation in paJDYF-bPM-p2. Which of our teams is a better fit for working on this (any heavy change in UPEs since November 2023)?

**Comment by FangedParakeet** [comment]
> In the latest UPE variations...

I just want to point out that since the deferred intent UPE project has been completed, there aren't any more UPE variations: there is one single implementation that services the entire plugin by using Stripe's payment element at checkout. Every payment method is now a UPE payment method, so I wouldn't necessarily use this feature alone to revert responsibility back to Heisenberg. 

That being said, it appears that the issue here is that independent of the implementation, if a payment method is disabled at checkout this should not mean that the payment gateway that supports this payment method is not registered at all. There is some precendence in the Stripe plugin that suggests that registering payment gateways solely on their availability at checkout is somewhat shortsighted and can have such side-effects inside WP Admin as are described in this issue. 

**I think this currently concerns refunds, but the greater issue is how payment methods are registered as gateways and resolving this may have further ramifications inside the admin dashboard. Since it concerns the non-card LPMs and BNPLs that Heisenberg has accepted responsibility for, as much as I would like to relieve our team of the duty here, we are probably best placed to make the refactor in a way that will not affect other checkout functionality.**

@KarlisJ, I think Heisenberg can take on this task, since refactoring how payment gateways are registered should probably be our responsibility. However, since we are not as knowledgeable as Pulsar on the specifics of how refunds are implemented, we would appreciate some help from your team in reviewing our solution to ensure that it remedies the rheumatism described in this issue. Let me know if that sounds agreeable or if you'd foresee some alternate path forward instead. 🙏

**Comment by kalessil** [comment]
@FangedParakeet: I agree that Heisenberg would be a better team to work on this as you have a better understanding of the latest UPE state. We'll surely support you with reviews and testing to ensure the refund-related issue is solved; thanks a ton!

**Comment by timur27** [comment]
To resolve the issue, the key actions include:

* Enabling all gateways for registration within WooCommerce Core, unlike the present approach that only includes gateways enabled for checkout.
* Guaranteeing that the gateway accurately manages its enablement status via the `enabled` object property.

Based on the analysis of the steps needed, I'm assigning `3` story points to this issue. I'm happy to align further if needed.
