### ISSUE TITLE
Provide a means to add a "here's how to request a refund" link to order emails sent to buyers

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#817]
To help merchants avoid unnecessary disputes, prompt merchant to provide a deep link to be included in order emails sent to buyers on how to request a refund.

paJDYF-Nm-p2

**Comment by thenbrent** [comment]
@allendav @LevinMedia given this can help all merchants, regardless of payment method, this seems like something better handled in core.

**Comment by kalessil** [comment]
Hey @allendav, @RadoslavGeorgiev 

It's not very clear from the discussion there what do we want to do here (@marcinbot mentioned "Inbox" functionality in WC though). Would you please share what you found out so far?

Vlad

**Comment by kalessil** [comment]
For myself: the inbox solution will require:

- [ ]  Apply the same approach as in \Automattic\WooCommerce\Admin\Notes\WC_Admin_Notes_Set_Up_Additional_Payment_Types (Title suggession TBD)
- [ ] Message to include https://woocommerce.com/posts/how-to-customize-emails-in-woocommerce/ for onboarding newer customers with emails customization
- [ ] Action to take customers directly to email customization (?) Action title suggession: "Yes, please!"
- [ ] A link to FAQ/Documentation where explaining why refunds is a good idea over disputes (AFAIK we don't have it yet)

As alternative the action can take customers to refunds vs disputes link and we include email customization links into notification body itself.

**Comment by kalessil** [comment]
Adding some ideas we discussed with @RadoslavGeorgiev (a P2 discussion TDB with gathering more ideas from HEs):

* We need to update documentation (e.g. https://docs.woocommerce.com/documentation/woocommerce-payments/) where we:
    * encourage customers to mention refunding in orders emails, explaining the benefits of doing so
    * providing email customization articles
* Since WooCommerce core doen't feature self-service refunds yet:
    * in the documentation advice customers how to organize this (via emails, contact forms and other alternatives)

We might also add "Managing Refunds with WooCommerce Payments" to the page above, to promote refunds over disputes.

I'll like p2 discussion where we want to collect feedback and more ideas once it's available.

**Comment by kalessil** [comment]
Additionally, to email/contact form option, there are third-party extensions like https://woocommerce.com/products/woocommerce-smart-refunder/
