### ISSUE TITLE
CC fields don't show up for products that cost more than ₡999,999.99 in Costa Rican colón (₡) cu

### ISSUE THREAD

**Issue by AashikP** [Automattic/woocommerce-payments#8208]
### Describe the bug

With Costa Rican colón (₡) as the store currency, we do not see the Credit card fields when the product costs ₡1,000,000 or more.

### To Reproduce

1. Set site currency to Vietnamese đồng (₫), and product price 1000000
2. You can checkout without any issues
3. Set site currency to Costa Rican colón (₡)
4. See no CC fields on checkout page:

    ![zjt9zR.png](https://github.com/Automattic/woocommerce-payments/assets/17475174/f7c2bda2-ca00-42a8-b128-3065f19bbf1a)
5. Try to use the Saved card and find these errors on checkout and order:

    ![eJDF1Y.png](https://github.com/Automattic/woocommerce-payments/assets/17475174/bde868f0-c390-4acc-9ecd-affd1f19e929)

    ![yqANC8.png](https://github.com/Automattic/woocommerce-payments/assets/17475174/049f0730-d5d0-46f0-b5c0-c8f6aa10362e)

### Actual behavior

Cannot checkout a product that's priced more than ₡999,999.99.

### Expected behavior

Since Stripe accepts anything less than $999,999.99, this error should not be seen:

![3NJFe2.png](https://github.com/Automattic/woocommerce-payments/assets/17475174/9f30ca83-e05c-4817-8963-522d47ccd6dd)

### Desktop (please complete the following information):

* OS: MacOS
* Browser: Chrome 
* Version: 121.0.6167.160 (Official Build) (arm64)

### Additional context

Reported in 7742887-zen. Follow-up ticket: 7742985-zen

Slack discussion: p1707984232274499-slack-C3NCP7ZJ6

[Stripe](https://woo.com/products/stripe/?aff=10486&cid=1131038) also throws this error in the checkout page:

![tUtgxN.png](https://github.com/Automattic/woocommerce-payments/assets/17475174/18536f89-0dc5-467a-8c6c-0cd2b826db19)

**Comment by AashikP** [comment]
Issue with Stripe extension discussed here: p1707987396717469-slack-C7U3Y3VMY

**Comment by zmaglica** [comment]
@kalessil do you think that this issue belongs to the team Fractal since it is related to auth and capture? If yes, can I move it to the Other Teams Queue as a part of the Gamma Triage process? If not, what do you think, who will be the better choice?

**Comment by csmcneill** [comment]
@AashikP AFAIK, this is expected as it is [a technical limitation](https://arc.net/l/quote/lppgmaia):

> The only limit to the maximum amount you can charge a customer is a technical one. The amount value supports up to twelve digits for IDR (for example, a value of 999999999999 for a charge of 9,999,999,999.99 IDR), and up to eight digits for all other currencies (for example, a value of 99999999 for a charge of 999,999.99 USD).

This does negatively affect weaker currencies, such as:
- Ugandan Shilling (UGX), which maxes at $25,854.60 as it is a zero-decimal currency.
- Costa Rican colón (CRC), which maxes at $1,932.35 USD
- Paraguayan Guarani (PYG), which maxes at $13,730.50 USD as it is a zero-decimal currency.
- Colombian Peso (COP), which maxes at $255.82 USD.
- Guinean Franc (GNF), which maxes at $11,617.78 USD as it is a zero-decimal currency.

**Comment by AashikP** [comment]
@csmcneill  True, and TIL. I thought the limit was max value of 99999999 USD. Didn't know it is 8 digits.

But... 1000000 would still be 7 digits?

Works fine with Vietnamese đồng (₫)

![5kLt1v.png](https://github.com/Automattic/woocommerce-payments/assets/17475174/c156aa71-41af-4def-b43a-fa9d19d6125d)

But not with Costa Rican colón (₡)?

![VXHgld.png](https://github.com/Automattic/woocommerce-payments/assets/17475174/35319581-4abc-474e-8495-3071b9577123)

I see no difference in the checkout page:

![iHRK3s.png](https://github.com/Automattic/woocommerce-payments/assets/17475174/a87f681e-c82b-4c56-83e9-576123a5e0da)

![0hB9aL.png](https://github.com/Automattic/woocommerce-payments/assets/17475174/68f1f5a9-a68e-4d9c-abc4-bc69dd74cdd5)

**Comment by csmcneill** [comment]
> Works fine with Vietnamese đồng (₫)

This is because the Vietnamese đồng (VND) is [a zero-decimal currency](https://docs.stripe.com/currencies#zero-decimal) much like the Japanese yen (JPY).

Per Stripe's documentation:

> All API requests expect amounts to be provided in a currency’s smallest unit. For example, to charge 10 USD, provide an amount value of 1000 (that is, 1000 cents).
> 
> For zero-decimal currencies, still provide amounts as an integer but without multiplying by 100. For example, to charge ¥500, provide an amount value of 500.

While the screenshots you provided are displaying the purchase price as ₫1,200,006.00 VND, this is likely due to the configuration at **WooCommerce > Settings > General**.

If you submit a payment for ₫1,200,006.00, I suspect that the actual value sent to Stripe would be `1200006` — which is seven digits — and not  `120000600`. This can be confirmed via the debug logs or the events in the Stripe dashboard. 

On the other hand, if you try to increase this amount to ₫101,200,006.00 (nine digits), it should produce the same error: 

![vnd 9 figures](https://github.com/Automattic/woocommerce-payments/assets/82999806/b1632b57-b70c-465b-837d-8d1d3610052c)

On the left is a purchase with eight digits (`73698960`), and on the right is a purchase with nine digits (`147397920`).

However, since the Costa Rican colón (CRC) is a two-decimal currency, it behaves just like other two-decimal currencies — meaning that a payment of ₡12.34 will be sent to Stripe as four digits (`1234`) and a payment of ₡1,234,567.89 will be sent to Stripe as nine digits (`123456789`).

**Comment by AashikP** [comment]
@csmcneill  Thank you so much for the context. That's another TIL, and explains why this is outside of the extension's control as of now.
