### ISSUE TITLE
Orders that fail due to AVS mismatch filters show "No Action Taken" in the Fraud & Risk metabox

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#8340]
### Describe the bug

If AVS mismatch filtering is enabled in the advanced fraud and risk tools, it can block transactions. However, if this setting is enabled and a transaction fails as a result of an AVS mismatch, the `Fraud & Risk` metabox on the edit order page shows "✔︎ No action taken". However, the order is blocked specifically due to a configuration in the fraud and risk tools.

### To Reproduce

1. Enable advanced fraud protection settings.
2. Enable `Block transactions for mismatched AVS` and save the settings.
3. Add a product to your cart.
4. Attempt to place the order while intentionally failing the postcode check.
- `4000000000000036` should do this in test/sandbox mode, but I can never get it to work.
- I wound up testing with a live account and a live card with an invalid postcode.
5. Note the order cannot be placed.
6. Navigate to **WooCommerce > Orders**.
7. View the details for the failed order placed in step 4.
8. Note that the `Fraud & Risk` metabox shows that there was no action taken.
9. Note the order notes, which indicate that the order failed due to an AVS mismatch.

### Actual behavior

The `Fraud & Risk` metabox provides inaccurate information about how it is protecting merchants if a payment is blocked due to the AVS mismatch filter.

### Screenshots

![CleanShot 2024-03-06 at 18 36 19](https://github.com/Automattic/woocommerce-payments/assets/82999806/beb65dde-ac75-4238-baab-991a812827d4)

### Expected behavior

The `Fraud & Risk` metabox should provide information about why the order did not complete as expected, since it did not complete due to a configuration in their fraud prevention settings.

### Dev Notes

- We should move the code that handles the `incorrect_zip` state to the `order_service`.

**Comment by htdat** [comment]
This issue impacts `merchant facing Risk Tools`, so assigning to @Automattic/sigma  (based on team responsibilities Pc2DNy-3z-p2) cc team lead @dwainm 
Assigning as part of Gamma Triage process PcreKM-yM-p2.

**Comment by tpaksu** [comment]
That's because we don't do the actual AVS check on our server code, we just toggle the AVS check setting on Stripe, so they can check AVS and fail if it doesn't verify. The server side checks happen before the AVS check on Stripe, and it will allow the payment request to pass through, meaning no actions taken (allow), so Stripe can do the AVS checks. And the AVS check result comes with the `payment_intent.failed` event asynchronously.

We can add something on the `payment_intent.failed` event that updates the fraud filter outcome as failed when the failure from Stripe is because of AVS though, right @eduardoumpierre? 

But I suspect that it would show two notes on the order notes section, one is from Stripe, and one is from our system, right @jessepearson?

**Comment by eduardoumpierre** [comment]
> We can add something on the payment_intent.failed event that updates the fraud filter outcome as failed when the failure from Stripe is because of AVS though, right?

I think we can't do it on the server because the fraud meta status that we show in the order details is stored in the client. I found that we are [setting that message](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-wc-payment-gateway-wcpay.php#L1196-L1207) for the `incorrect_zip` error, so we can change the logic to initialize the fraud meta box type with BLOCK instead.

What do you think?

**Comment by eduardoumpierre** [comment]
**Update:** Opened a PR on the client side to display the correct risk meta box, and will draft a possible solution for the timeline entry.

**Comment by eduardoumpierre** [comment]
**Update:** The PRs are ready, but I still need to work on the PR descriptions and testing instructions, which were delayed due to a shift in my focus. Since it will require a live account to validate the changes, the setup will be more complex than usual.

**Comment by dwainm** [comment]
Thanks for your update @eduardoumpierre , the other project related work is a higher priority at this stage.

**Comment by eduardoumpierre** [comment]
**Update:** https://github.com/Automattic/woocommerce-payments-server/pull/5057#issuecomment-2067322429
