### ISSUE TITLE
The amount format in the refunded order notes does not honor currency format options for refunds triggered on the order details page

### ISSUE THREAD

**Issue by mgascam** [Automattic/woocommerce-payments#8345]
### Describe the bug

There are two ways to issue a refund for an order:

- Via WP Admin, using the Refund button in the order details page
- Externally, using the Stripe Dashboard

In this PR, https://github.com/Automattic/woocommerce-payments/pull/8200 we implemented the support to handle external refunds (in other words, we implemented a webhook listener for refund events). After that, we noticed that the refunded amount displayed in the refunded order notes was different depending on how the refund was initiated, but only with the following currency options enabled:
 - Currency position: Right
 - Number od decimals: 0

### To Reproduce

1. Go to WooCommerce > Settings and set `Currency position: Right` and `Number of decimals: 0`
2. As a shopper, place an order.
3. As a merchant, issue a refund for the same order

### Actual behavior

The refunded amount in the order notes does not follow the currency formatting previously selected (see screenshot below)

### Screenshots

![310346195-53803bde-c1c1-4522-a7db-fd65ece6a6db](https://github.com/Automattic/woocommerce-payments/assets/1553182/6d3bd829-ac63-414b-b94f-981b83184a08)

### Additional context

- Refunds triggered from WP Admin are handled in WC_Payment_Gateway_WCPay::process_refund
- It's also worth checking the refund_line_items method https://github.com/Automattic/woocommerce.com/blob/c1833bf2c343be095c7fd6975a26c6cf8a57967b/plugins/woocommerce/includes/class-wc-ajax.php#L2137

**Comment by deepakpathania** [comment]
Discussing p1734525661198779-slack-C01BPL3ALGP.

**Comment by deepakpathania** [comment]
Moving back to the backlog and un-assigning for now since the solution is still being discussed.

**Comment by RadoslavGeorgiev** [comment]
### Interim findings

I tried to debug what's going on here, and the result is that rather than `wc_price()` ignoring the Woo setting, it's WooPayments altering the price format through the `wc_price_args` filter.

The filter is used in a few places, but the single one affecting this is Multi-Currency's `BackendCurrencies`:

https://github.com/Automattic/woocommerce-payments/blob/cd650bd4444cfb6487f05aa4238ae8b7d8044757/includes/multi-currency/BackendCurrencies.php#L68-L69

What happens here is that essentially, Multi-Currency is loading the correct currency format. cc @tpaksu for context.

AFAICT, this is expected. Even though Core settings are being ignored, it's actually using the correct format.

**Comment by tpaksu** [comment]
Hi, thanks for the ping @RadoslavGeorgiev . When MC is enabled, it overrides the formatting set on WC Core, and it uses the formats defined in the `i18n` folder, which is different per currency (and per locale). The wrong ones in the issue seems to be the ones received from the webhook, as they also should use the `wc_price` overrides via the BackendCurrencies hooks. Maybe the hooks are not attached for requests coming via webhook?

**Comment by deepakpathania** [comment]
Latest discussion p1735020572296739/1734961417.179049-slack-C01BZUL57SQ.
