### ISSUE TITLE
Move E2E test suite to its own repository

### ISSUE THREAD

**Issue by vbelolapotkov** [Automattic/woocommerce-payments#838]
There are two problems with current solution:
1. E2E tests run quite long holding CI pipeline.
2. E2E tests do not run on server PRs which leads to unexpected failures on the client after PR merged.

Solution:
1. Move tests out of Travis CI pipeline.
2. Make the run on each push to master branch for both client and server.

In case there are too many failures after PR merged we'll consider moving E2E suite into CI pipeline.

Relevant slack thread: p1598273695012600-slack-CGGCLBN58

**Comment by deepakpathania** [comment]
We have made some improvements to the CI tests as a part of [this epic](https://github.com/Automattic/woocommerce-payments/issues/3289), one of which was the [use the live server instead of the local instance](https://github.com/automattic/woocommerce-payments/issues/3293). With these changes in place, I feel we can close this issue, for now, in case this is still a concern due to other reasons, please feel free to re-open this we can start a discussion around the same.
