### ISSUE TITLE
Missing credit card fields on add payment method endpoint

### ISSUE THREAD

**Issue by johndcoy** [Automattic/woocommerce-payments#8383]
### Describe the bug

Credit card fields are missing on  `/my-account/add-payment-method/` 

### To Reproduce

1. Go to 'My Account > Add Payment Method
2. See error

### Actual behavior

The console returns the following error:

```
Uncaught (in promise) TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
```

My hunch is that jQuery is waiting for a window to do something, like expand before showing fields.

### Screenshots

![Screenshot](https://d.pr/i/utuKHQ+)
Screenshot link: https://d.pr/i/utuKHQ

### Additional context

This issue may be limited to sites hosted on WPCOM. 
zd-7870930

**Comment by csmcneill** [comment]
I can reproduce on my AT site, but not my local or self-hosted sites. ~~Updating the title as a result.~~

**Edit**: After some more testing, I could reproduce this on non-AT test sites (DigitalOcean, Pressable, JN).

Additionally, reverting to 7.2.0 resolves the issue. Since WooPayments is symlinked on AT sites, all AT sites using WooPayments are affected — so I'm adding an `impact: high` label.

I do see that https://github.com/Automattic/woocommerce-payments/commit/de8d1618214f16d8f6bc79c83738723c67342ed4 added these lines in 7.3.0:

https://github.com/Automattic/woocommerce-payments/blob/de8d1618214f16d8f6bc79c83738723c67342ed4/client/checkout/upe-styles/utils.js#L127-L142

But I don't know enough about JS or JS errors to determine if this is the underlying cause. cc @FangedParakeet and @brettshumaker for a gut check here.

**Comment by brettshumaker** [comment]
@johndcoy Which theme are you using?

> After some more testing, I could reproduce this on non-AT test sites...

@csmcneill Which theme are you using? And are the fields completely missing from the DOM or are they just not visible? Did you clear the appearance transients?

> I do see that de8d161 added these lines in 7.3.0:

Yes. We probably need to do a better job of being defensive and not assume that `document.querySelector()` will find an element.

This particular error shouldn't be causing the form fields to not load as it's not stopping the execution of JS.

**Comment by csmcneill** [comment]
> Which theme are you using?

On my JN site, I've tried using Twenty Twenty Four, Twenty Ten, and Storefront. 

> And are the fields completely missing from the DOM or are they just not visible?

They are completely missing from what I can tell:

![CleanShot 2024-03-14 at 15 00 11@2x](https://github.com/Automattic/woocommerce-payments/assets/82999806/994895ae-1e9c-46cf-8ba5-996c89955c24)

> Did you clear the appearance transients?

Yes :( (btw, thanks for adding that to the Dev Tools!)

Selecting the `Add payment method` button produces the following error:

```
Cannot read properties of null (reading 'submit')
```

![CleanShot 2024-03-14 at 15 03 40@2x](https://github.com/Automattic/woocommerce-payments/assets/82999806/3c22fbe9-65cb-41ce-b64c-443cc6cb1def)

> This particular error shouldn't be causing the form fields to not load as it's not stopping the execution of JS.

Good to know! Thank you!

**Comment by FangedParakeet** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/8383?planning-poker) with Zenhub @frosso

**Comment by shendy-a8c** [comment]
@frosso do you think the problem GlobalStep observed here p1710842265962199/1709623184.601419-slack-C011ENB20Q1 the same issue as what's reported in this issue?
The error is the same but they said it's intermittent.

**Comment by frosso** [comment]
@shendy-a8c yes, it looks like it's the same error. I think it might be intermittent because of the expired nonces - but it looks like it's the same error.
