### ISSUE TITLE
Epic: Show payment activity widget with payment volumes for the last 7 days, for the selected currency.

### ISSUE THREAD

**Issue by jessy-p** [Automattic/woocommerce-payments#8490]
~~UPDATE: blocked for redesign that may change the scope - p1712152065311419/1711574043.001329-slack-C06BBFTF6EM~~

Some merchants have multiple deposit currencies, so the activity widget will need to show insights for different currencies. 

This issue is about updating the Payment Activity Widget to work with a selected currency. Introducing the currency switcher is a dependency, see issue:

- https://github.com/Automattic/woocommerce-payments/issues/8765

-----

### Dev notes

We can use the `useSelectedCurrency` react hook to listen to the selected currency on the Payments → Overview screen.

https://github.com/Automattic/woocommerce-payments/blob/c363808a65a85ad2284821c35bef882694ffec1b/client/overview/hooks.ts#L26-L46

```[tasklist]
### Tasks
- [ ] #8865
- [ ] https://github.com/Automattic/woocommerce-payments-server/issues/5371
- [ ] anything else needed to hook it up, test, get it working 👌🏻 
```

**Comment by haszari** [comment]
FYI @jessy-p I added screenshots of the design for the page currency switcher. Possibly we might want to re-estimate.

**Comment by Jinksi** [comment]
> Possibly we might want to re-estimate.

I agree, the scope has changed significantly.

@jessy-p I've reset this issue's SP so it appears in our `needs SP` list. (Note the previous version of this was SP 3).

**Comment by haszari** [comment]
Assigning myself, I'm working on allowing the widget to show a specified deposit currency (for stores with multiple payout accounts. My plan is to implement this under the hood, no UI, since  @Jinksi is in progress on UI to switch currency (#8765). i.e. can edit JS to hard-code `USD` or `CAD` and the widget will show correct data.

There are two aspects to this:

- Adding currency prop/argument to the relevant components as needed. Mostly just `usePaymentActivityData` and `PaymentActivityQuery`.
- Ensure the server API request generates data based on the specified currency. 
  - This may be complex, as the [current SQL statement uses `charges_cache.currency` field](https://github.com/Automattic/woocommerce-payments-server/blob/0467e49e7d18591f4e86f0d6fb52373a6817de66/server/wp-content/rest-api-plugins/endpoints/wcpay/repository/class-transaction-repository.php#L379-L410).
  - Charge currency (aka presentment currency) is different to deposit currency, there's a mapping.

**Comment by haszari** [comment]
Added issues / tasks for plugin & server changes, I'm in progress but anyone is free to take over at any time :)
