### ISSUE TITLE
PRB tokenized cart on block-based cart and checkout

### ISSUE THREAD

**Issue by frosso** [Automattic/woocommerce-payments#8527]
```[tasklist]
### Compatibility
- [ ] Ensure compatibility with "Product Add-Ons"
- [ ] Ensure compatibility with "WooCommerce Deposits"
- [ ] Ensure compatibility with "WooCommerce Bookings"
- [ ] Ensure compatibility with base product types: simple, variable, downloadable, subscriptions, virtual products
```

```[tasklist]
### Functionality
- [ ] On PRB click, customer can check out with items on the cart
- [ ] Price, tax, shipping, line items are displayed accurately
- [ ] Order page reflects selected product and paid amount
- [ ] Uses Store API to update totals when a different shipping address/method is selected within the PRB dialog
```

**Comment by frosso** [comment]
I'm currently pausing this work in favor of implementing a sessionhandler.
To make the code review faster, we discussed as a team to copy the existing PRB implementation and then create a separate PR with the necessary modifications.
The first PR to copy the implementation has been implemented: https://github.com/Automattic/woocommerce-payments/pull/8989

While working on this, I also noticed that the data store has a different data contract than the Store API. All the utilities in the tokenized cart leverage the Store API data contract.
So we have two options:
- Modify the utilities to use both data contracts
- Massage the data from the data store into the Store API data contract

After consulting with the blocks team ( p1718815646160629-slack-C02TS23QJ1X ) , they recommended the second option - which is what I'll be going with.

**Comment by mdmoore** [comment]
While this issue was initially estimated as 3 story points, there were some unexpected challenges that took a bit more time to work through. Due to discrepancies in the shapes of the cart data object provided to the WC Blocks express payment method component and the shape of the cart object expected by the Store API, the data needed to be transformed before being sent to via the Store API. Because of that, I'm bumping up the estimate.
