### ISSUE TITLE
Use string constants instead of boolean flags in `Payment_Information` constructor

### ISSUE THREAD

**Issue by reykjalin** [Automattic/woocommerce-payments#860]
I want to get rid of the `bool` flag in the constructor since `new Payment_Information( $payment_method, $payment_token, true )` makes a lot less sense than `new Payment_Information( $payment_method, $payment_token, MERCHANT_INITIATED )`.

I'll get on this tomorrow.

_Originally posted by @reykjalin in https://github.com/Automattic/woocommerce-payments/pull/826#discussion_r478548954_

**Comment by reykjalin** [comment]
As per @dwainm's suggestion [here](https://github.com/Automattic/woocommerce-payments/pull/826#discussion_r478419627) we should add these string constants into a `WCPay\Constants` namespace.

I'd still like to throw it out there that extending `SplEnum` to create **types** around these string constants would probably be beneficial because the `Payment_Information` constructor can then accept a _type_ rather than just any `string` possible. I think that's a crucial distinction.

**Comment by reykjalin** [comment]
cc @dwainm & @allendav since they were involved in ^ discussion.

**Comment by DanReyLop** [comment]
I don't think `SplEnum` is a real option for WCPay, because it's not bundled with PHP and installing a PHP extension is not something we can do from plugin code. As an example, I have a pretty "vanilla" MAMP installation (Apache2 + PHP 7.4) and I don't have SPL installed/enabled. If we use SplEnum, the next release would crash my site, that's unacceptable.

Have you seen [this package](https://github.com/myclabs/php-enum)? Seems like everything we want, and it's installable through Composer. Alternatively, we can make our own Enum implementation stealing from [this Stackoverflow answer](https://stackoverflow.com/a/254543).

**Comment by reykjalin** [comment]
Thank you @DanReyLop for the response! Since @allendav brought up the same thing in the PR itself (https://github.com/Automattic/woocommerce-payments/pull/898#discussion_r487315078) I decided to follow up there instead 🙂
