### ISSUE TITLE
BNPL PMME messaging in cart doesn't appear immediately below the Total when Gift Card extension is enabled

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#8661]
### Describe the bug
BNPL PMME messaging in cart doesn't appear immediately below the Total when Gift Card extensions is enabled. I expect this is true for other extensions like Points and Rewards which add a similar field.

![image](https://github.com/Automattic/woocommerce-payments/assets/109928953/3a65d78f-bd82-434c-b6a9-9f6f9690b71a)

### To Reproduce
1. Download and enable Gift Card extension
2. Enable desired BNPL payment methods
3. Shop and add product to cart
4. Observe in cart that the PMME messaging is below the gift card code field rather than below the Total

### Expected behavior
PMME messaging is always the first element located below the Total

**Comment by brettshumaker** [comment]
The GC plugin is inserting their html at an earlier priority (`9`) than we are (`10`). I can insert ours earlier (`5`), but it's still best practice to leave some room for other plugins to hook in where they need to since we couldn't possibly imagine all scenarios where someone would want to add something there.

<img width="500" alt="Screenshot 2024-04-18 at 3 53 36 PM" src="https://github.com/Automattic/woocommerce-payments/assets/1558827/c0d78505-64c5-40b7-a5b3-081a36b16f57">

**Comment by pierorocca** [comment]
Thanks Brett. The two I can think of is gift cards and points and rewards. 

Related to BNPL I see Affirm, Afterpay etc. also populating that space.

Is there any governance or standard to determine priority to use?

**Comment by brettshumaker** [comment]
> Is there any governance or standard to determine priority to use?

Not really. The default priority is `10` so it's generally assumed that if it doesn't really matter _where_ your item is placed, you just use the default and adjust from there if you want it earlier/later. The common courtesy is to leave a little space between your position and default or other known uses, otherwise you'll end up relying on plugin load order or have to manually move other plugin's hooks.

**Comment by pierorocca** [comment]
Gotcha. Thanks for the insight.
