### ISSUE TITLE
Make Transaction List View searchable by the subscription ID (2/3)

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#867]
paJDYF-O8-p2

Related: #866 #868

**Comment by dechov** [comment]
Given that there could be multiple charges per subscription, would it be reasonable to enhance `map_search_orders_to_charge_ids` to expand each "Subscription #" term out to multiple `charge_id` terms? Or is there reason to adapt the server to accept multiple charge IDs in a single term? cc @luizreis

**Comment by luizreis** [comment]
> Given that there could be multiple charges per subscription, would it be reasonable to enhance `map_search_orders_to_charge_ids` to expand each "Subscription #" term out to _multiple_ `charge_id` terms

Yes, that approach makes sense. I haven't tested this, but I don't think we'd need to modify the server to accept multiple IDs in a single term because the search query already [uses `OR` between them](https://github.com/Automattic/woocommerce-payments-server/blame/47750b9d590084811f6829366158f06d111dfa55/server/wp-content/rest-api-plugins/endpoints/wcpay/utils/class-filter-utils.php#L102).

Allowing multiple `charge_ids` in a term might allow us to build smarter queries and remove some comparisons, but I'm not sure if it would be worth it.
