### ISSUE TITLE
Payment Activity Card shows an error for new accounts: `Error retrieving payment activity data.`

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#8708]
### Describe the bug

An error is shown when rendering the Payment Activity Card for new accounts who may not have added a deposit destination or verified identity.

<img width="283" alt="Error retrieving payment activity data" src="https://github.com/Automattic/woocommerce-payments/assets/3147296/bdfca7eb-4f53-41f1-8ba7-9a548d5791f1">

The response from `/wp-json/wc/v3/payments/reporting/payment_activity`:

```json
{
  "code": "wcpay_invalid_currency",
  "message": "Error: Invalid currency.",
  "data": null
}
```

> [!TIP]
> See server endpoint `/reporting/payment_activity` handler [here](https://github.com/Automattic/woocommerce-payments-server/blob/e98ddd8a6dee4d547de35196fca93b386fb17e97/server/wp-content/rest-api-plugins/endpoints/wcpay/class-reporting-controller.php#L111) 

### To Reproduce

1. Onboard as a fresh WooPayments account. **Don't** add a deposit destination (bank account) or very user identity _yet_.
2. Purchase a product to bring `Payments → Overview` total balance > 0.
3. Enable the feature flag: `wp option update _wcpay_feature_payment_overview_widget 1`
4. Visit `Payments → Overview`.
5. Notice the error in the bottom-right. `Error retrieving payment activity data.`
6. Notice the Payment Activity Card amounts are incorrectly rendered as `0`
7. In browser dev tools, notice the response from `/wp-json/wc/v3/payments/reporting/payment_activity` matches the error json response above.

### Screenshots

<img width="700" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/3147296/5eb9beb2-4007-474a-ac3e-73e22401e563">

### Expected behavior

For new accounts, the Payment Activity Card amounts should render with the correct amounts and without errors, or not render at all.

**Comment by jessy-p** [comment]
Able to replicate the issue.

Tested with an account not properly onboarded.
<img width="757" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/32092402/06950e87-b36d-4424-b554-0b4c07bbb7f3">

When there is no transactions, i.e. `lifetime_total_payment_volume' is 0, seeing the empty screen as expected
<img width="743" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/32092402/2c951eaa-9cf8-47a5-b0aa-480fc33fcf89">

We can skip adding payout account, but place orders so that the `lifetime_total_payment_volume' is non-zero, the API returns error and the values are 0.

**Comment by jessy-p** [comment]
Closed via server PR https://github.com/Automattic/woocommerce-payments-server/pull/5232
