### ISSUE TITLE
Show preset date ranges dropdown

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#8734]
Show a dropdown on the right of Payment Activity widget header.

<img width="349" alt="image-16" src="https://github.com/Automattic/woocommerce-payments/assets/73803630/f1eb7b4d-a208-44de-9e0f-ca652b66b27f">

Date range presets:
- Today
- Last 7 days
- Last 4 weeks
- Last 3 months
- Last 12 months
- Month to date
- Quarter to date
- Year to date
- All time

The dropdown can do nothing for the acceptance of this issue because functionality is covered in https://github.com/Automattic/woocommerce-payments/issues/8735.
```[tasklist]
### Tasks
- [ ] https://github.com/Automattic/woocommerce-payments/pull/8910
- [ ] Update new custom select component
```

**Comment by haszari** [comment]
Marking this as blocked, I think we should focus on getting the new component merged and then should be straightforward to hook it up: 

- #8896

That might be easier in a new PR, since #8910 has had tricky conflicts and includes a temporary UI. 

When hooking up the real component, whoever works on that please also include relevant tracks event, e.g. 

- #8736

**Comment by haszari** [comment]
@nagpai I'm removing `blocked` label since the selector component is now merged and we can use to implement time period selector 🎉  

Reminder – keep the issue up to date so our board matches reality as much as possible. Labels like `blocked` are a strong signal.
