### ISSUE TITLE
Payment activity card remaining in empty state

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#8737]
### Describe the bug

Testing the payments activity card on my test sites with a history of live and test payments shows an empty state.

Even after enabling the payments activity card and placing test orders, it continues to show an empty state.

### To Reproduce

1. Grab a WooPayments site that has a history of transactions (I can provide access as needed to a personal test site with a history of live and test transactions).
2. Navigate to **Payments > Overview**.
3. Note the information displayed in the existing dashboard.
4. Change `_wcpay_feature_payment_overview_widget` to `1`.
5. Refresh **Payments > Overview**.
6. Note the `Your payment activity` card is in an empty state.
7. Place an order.
8. Repeat steps 5–6.

### Actual behavior

The payment activity card is in an empty state when it shouldn't be.

### Screenshots

![CleanShot 2024-04-29 at 16 06 42](https://github.com/Automattic/woocommerce-payments/assets/82999806/1d24353f-886f-4b36-9b05-e067641f8ff2)

### Expected behavior

1. The payment activity card loads information retroactively.
2. The payment activity card accurately reflects test information if the account is in a test/sandbox state.

### Additional context

Discussed briefly in p1714423652412689-slack-C06BBFTF6EM

**Comment by csmcneill** [comment]
Pulling a comment from p1713525965107739/1713524614.770209-slack-C06BBFTF6EM into this issue:

> The one thing I missed is that the client reads off a cached account data.
My local store has some transactions, so I ran this query on my WCPay server's database.
> ```
> UPDATE wcpay_test_transactions_cache set stripe_account_id = 'acct_abc' where stripe_account_id = 'acct_abc-';
> ```
> After doing that, unexpectedly I see zeroes instead of the empty state. Turns out, it's because wcpaySettings.lifetimeTPV is stale because it is from [cached account data](https://github.com/Automattic/woocommerce-payments/blob/4f6ed1b9c11cf264f12d58877b3d551e757a2a1f/includes/class-wc-payments-account.php#L2108). I had to refresh the account data on WCPay Dev Tools.

**Comment by shendy-a8c** [comment]
This problem might be because `wcpaySettings.lifetimeTPV` is stale as it is from [cached account data](https://github.com/Automattic/woocommerce-payments/blob/4f6ed1b9c11cf264f12d58877b3d551e757a2a1f/includes/class-wc-payments-account.php#L2108).

**Comment by csmcneill** [comment]
> This problem might be because `wcpaySettings.lifetimeTPV` is stale as it is from [cached account data](https://github.com/Automattic/woocommerce-payments/blob/4f6ed1b9c11cf264f12d58877b3d551e757a2a1f/includes/class-wc-payments-account.php#L2108).

Clearing the account cache via WooCommerce > Status > Tools and clearing the server Stripe cache do not resolve this issue on my sites. 

1. Is there a way of forcing cached account data to update/refresh (either via UI or code)?
2. Is this the account cache or the server Stripe cache?

**Comment by aheckler** [comment]
FWIW I am able to see the card with no issues after installing `develop` on my test site (which is in fact a live site able to charge real cards). Once the option is set to `1`, the **Your payment activity** card appears.

![Screenshot taken on 2024-05-03 at 18 07 48 UTC@2x](https://github.com/Automattic/woocommerce-payments/assets/5512652/6b2c543a-0105-4a53-8061-bb44e940f500)

Having said that, I don't know how accurate the data is. It's claiming my TPV is only $50, when I've done way more than that (in test mode). If I switch to live mode, it says my TPV is $0, when that's not true either.

Anyway, happy to provide access to my "test" site if it helps troubleshooting this.

**Comment by aheckler** [comment]
Worth noting that my test mode account cache shows `lifetime_total_payment_volume` set to `500`, which doesn't seem to match the $50 TPV shown in the new dash. ¯\\_(ツ)_/¯

**Comment by Jinksi** [comment]
This is a bug related to project epic #8493, so I'll zero out the SP for this while this project remains in development.

**Comment by jessy-p** [comment]
👋  @csmcneill, @aheckler  Could you retest and let me know your findings on test site about
- Empty Payment screen (I hope it should be fixed by now)
- Accuracy of TPV

cc: @souravdebnath1986

**Comment by aheckler** [comment]
@jessy-p I'm not sure if I did something wrong, but I just built and installed `develop`, flipped `_wcpay_feature_payment_overview_widget` to `1`, but I don't see the "Your payments activity" card at all on **Payments > Overview**:

![Screenshot taken on 2024-06-07 at 14 05 18 UTC@2x](https://github.com/Automattic/woocommerce-payments/assets/5512652/8e2d625e-e95f-4456-a2c1-788d15097dc0)

**Comment by jessy-p** [comment]
@aheckler  Can you try clearing the server cache via MC
<img width="932" alt="image" src="https://github.com/Automattic/woocommerce-payments/assets/32092402/796718e2-8509-4452-b88b-8838b19dba41">

**Comment by csmcneill** [comment]
@jessy-p After clearing the Memcache via MC and installing 7.8.0-test-2, I am now seeing the card on my AT site (`acct_1LhhVSFk5Ng3VVfB`). However, the `Total payment volume` is `0.00` — I'd expect for it to be `31.68`. This is similar to Adam's observation [here](#issuecomment-2093516624)

I believe this is because the activity card currently defaults to the last 7 days as there is no date range picker currently available:

https://github.com/Automattic/woocommerce-payments/blob/7a73407d347752638528ac8b423e99f9b9177eb0/client/components/payment-activity/index.tsx#L23-L34

**Comment by jessy-p** [comment]
Thanks @csmcneill  We can retest after the time period selector is merged.

**Comment by Jinksi** [comment]
>  believe this is because the activity card currently defaults to the last 7 days as there is no date range picker currently available:

#8927 has been merged 🎉 which should resolve this.

**Comment by Jinksi** [comment]
There is also a discrepancy between `lifetime_total_payment_volume` for a **live** account that is in **test/sandbox** mode.

The account cache's `lifetime_total_payment_volume` uses live transactions ([server src](https://github.com/Automattic/woocommerce-payments-server/blob/5e3dc372ea0f10cab740439ff0ca1ebc7fa7715b/server/wp-content/rest-api-plugins/endpoints/wcpay/class-accounts-controller.php/#L914)) for this calculation. So if a live account with 0 live transactions switches to test mode with some test transactions, it will incorrectly see the empty state Payment Activity card.

I will open a new issue (#8958) for this since it seems related but distinct.

**Comment by aheckler** [comment]
Using a build of `develop` I just created, I can now see the PAC in live mode, with what seems to be correct data. 🎉 

A random thought: [fiscal years are weird](https://en.wikipedia.org/wiki/Fiscal_year#Chart_of_various_fiscal_years). Does the `moment.js` library account for how a quarter might be different from country to country? I didn't test this, just something I noticed that could maybe be an issue.

**Comment by aheckler** [comment]
Some other feedback items:

- There's no "View report" link for the fees, but in theory we could use the same URL as the TPV "View report" link, since in theory the fees should match.
- State doesn't seem to be remembered, i.e. if I use the dropdown to pick Month To Date or something, then click a "View report" link, then click back in my browser, the PAC has been reset to showing the last 7 days.
- I might slightly simplify the TPV help icon text to: "Total payment volume is the sum of all transactions in a given time period, minus refunds and disputes."
- The help icon text for Fees is unclear. It says "Fees includes fees on payments as well as disputes", but the PAC shows Disputes as a _separate_ item. I think what we're trying to say is that Fees can include fees on charges, but also dispute fees? If so, maybe the text should be more generic and include a link? Maybe: "Fees includes all types of fees charged by WooPayments. [Learn more](https://woocommerce.com/document/woopayments/fees-and-debits/fees/)."
- We can then clarify the issue in a new help icon tooltip in the disputes section: "Disputes includes the amount of any disputed charges. Dispute fees are included in the Fees section."

**Comment by souravdebnath1986** [comment]
> Does the moment.js library account for how a quarter might be different from country to country? 

We are not using fiscal years. The YTD calculation is based on calendar year. 

> There's no "View report" link for the fees, but in theory we could use the same URL as the TPV "View report" link, since in theory the fees should match.

True, and it does look a bit weird. The only reason we have avoided directing to the same transaction report is because it's would be the exact same link as the `View report` of Total Payment Volume. Also, an actual fee report should give a better breakdown of fees (base, fx, international, dispute etc.) which we don't have today. 

I agree on the improvements re: the other points.

**Comment by jessy-p** [comment]
@souravdebnath1986  Could you create tickets for the improvements that we would want to be implemented.

**Comment by souravdebnath1986** [comment]
Created 2 issues based on @aheckler 's feedback - 
1. [PAC: Selected state based on date range selected is not remembered](https://github.com/Automattic/woocommerce-payments/issues/8972)
2. [PAC: Help text improvements](https://github.com/Automattic/woocommerce-payments/issues/8973)

**1** is more important to fix before GA. **2** is improvements to texts and is a good to have but not a release blocker. 

@jessy-p Assigned both the issues to you

**Comment by jessy-p** [comment]
Closing this as the main issue has been addressed and other valid issues have been created seperately
