### ISSUE TITLE
WooPayments status and buttons are incorrect on Payments settings page when Stripe onboarding is started but not completed

### ISSUE THREAD

**Issue by timmy5685** [Automattic/woocommerce-payments#8813]
### Describe the bug
If a merchant reaches the first screen of stripe onboarding but exits, we display the toggle for WooPayments on the Payments settings screen as enabled and the button as "Manage" which is incorrect. It appears that we are not taking into account whether or not Stripe onboarding steps were completed by the merchant - we just assume after the first stripe onboarding screen is reached that the merchant has completed it.

### To Reproduce

1. Install WooPayments
2. Complete MOX and go to first step of Stripe onboarding.
3. Click "Back to WooPayments"
4. Go to WooCommerce > Settings > Payments
5. WooPayments status and button are incorrect in Payment Methods table.

### Actual behavior
WooPayments shows as enabled on payment settings screen and button says "Manage" even though the merchant did not complete the onboarding flow.

### Screenshots
<img width="1504" alt="Screenshot 2024-05-10 at 3 03 25 PM" src="https://github.com/Automattic/woocommerce-payments/assets/32650633/ad8e1e1f-f2e6-4bde-bb49-e9660d88c2a3">

### Expected behavior
WooPayments shows as disabled on payment settings screen and the button says "Finish set up" until the merchant completes the stripe onboarding flow.

**Comment by aheckler** [comment]
My two cents: 

I agree that this is suboptimal and should not happen, but I'm not sure if this issue is specific to WooPayments. For example, if I have a brand new Woo store and I click the toggle to enable the Direct Bank Transfer payment method, it gets enabled (and the button changes to say "Manage" after a page refresh) even though I haven't added my bank account info to it yet.

Same with the Stripe extension: if I install it and go a step or two into the onboarding flow, then return to my site, I see that it's enabled even though I never finished onboarding and cannot take payments or anything with it.

![Screenshot taken on 2024-05-13 at 10 14 52 UTC@2x](https://github.com/Automattic/woocommerce-payments/assets/5512652/c5fa2b9e-1a8c-4b34-8c4b-ea30df11c102)

![Screenshot taken on 2024-05-13 at 10 12 47 UTC@2x](https://github.com/Automattic/woocommerce-payments/assets/5512652/2cf1544b-fea9-4ed6-82c4-38c5dd1c3b87)

It may be that the larger issue here is that core should somehow be detecting when payment methods are ready to actually take payment vs. just being enabled. That seems like a larger discussion though.

**Comment by oaratovskyi** [comment]
@timmy5685 @vladolaru WDYT about @aheckler input above? Should I take it into the progress or let's hold-off until the further discussion?

**Comment by timmy5685** [comment]
@oaratovskyi - agree that this may be a larger issue and I don't know if we can solve this easily. Will defer to @vladolaru on this. Not sure if this is a can of worms...

**Comment by vladolaru** [comment]
This is a tricky one because it relates to our own internal status. I think we should mirror the state of our Payments menu item:
- if we show the Connect page, then it should be force disabled (without the ability to enable it - disabled switch control) and the button CTA be "Finish setup" linking to the Connect page 
- If we show the Payments Overview but the account didn't finish the initial onboarding, then it should be force disabled (with the switch control disabled) and the CTA should be "Finish setup" linking to Stripe (the same link we use for our Overview notices)
- If the merchant finished the initial onboarding, then we auto-enable only once and change the CTA to Manage linking to the Settings page.


WDYT @oaratovskyi and @timmy5685 ?

**Comment by elizaan36** [comment]
> It may be that the larger issue here is that core should somehow be detecting when payment methods are ready to actually take payment vs. just being enabled. That seems like a larger discussion though.

This is true, it's a WooCommerce core issue where the enable toggle doesn't actually indicate that the payment method is ready to accept payments on the front end. In @nikkivias 's recent post (pfHfG4-84), we're proposing to remove the toggle altogether from the top level because of this confusion.

While there should be nuance at the core level, I think we can solve this for the time being within WooPayments by only presenting the "Manage" link when the gateway is enabled successfully (connected to Stripe).

> if we show the Connect page, then it should be force disabled (without the ability to enable it - disabled switch control) and the button CTA be "Finish setup" linking to the Connect page
If we show the Payments Overview but the account didn't finish the initial onboarding, then it should be force disabled (with the switch control disabled) and the CTA should be "Finish setup" linking to Stripe (the same link we use for our Overview notices)
If the merchant finished the initial onboarding, then we auto-enable only once and change the CTA to Manage linking to the Settings page.

I agree the toggle should be automatically enabled upon connection with Stripe, however it shouldn't be force disabled in any case. The merchant can toggle on and off (which arguably doesn't really do anything but that needs to be solved at the core level). 

If the CTA remains as "Finish setup" that can be enough of an affordance that the method isn't set up properly.

Also I believe if the connection hasn't been made yet the additional top banner will appear, no?

**Comment by oaratovskyi** [comment]
My understanding is that we should be simple here and consistent with existing namings/behaviours in the other pages (agreeing with Vlad about mirroring statement). Though I am not sure about force-disabling stuff, since enabled/disabled is about the plugin active or not and internal status is about gateway status. 
My thoughts are similar to Vlad's just without force disabling: 
- if onboarding hasn't been started then CTA is "Finish setup", on click navigate them to connect page
- if onboarding has been started but not finished CTA is "Finish Setup", on click we can redirect them to Stripe KYC directly (same link as iverview notices)
- when KYC is completed CTA is "Manage" , on click redirect them to the WCPay settings page

**Comment by elizaan36** [comment]
+1. Makes sense!
