### ISSUE TITLE
Inconsistent notice style in WooPayments Settings

### ISSUE THREAD

**Issue by elizaan36** [Automattic/woocommerce-payments#8833]
### Describe the bug
The notice "One or more of your extensions alters checkout fields" should use the correct notice component. The correct notice is shown in the notice just below.

### To Reproduce

1. Go to Settings > WooPayments
2. Scroll to express payments section
3. See bug

### Screenshots
<img width="1813" alt="Screenshot 2024-05-14 at 7 27 37 AM" src="https://github.com/Automattic/woocommerce-payments/assets/5121465/6dfdd345-9a3c-43e0-8db2-5506b0ca71c3">

### Expected behavior
The notice should use the `inline-notice` component for a consistent experience in the admin.
The copy can be all on one line and use this simplified text string to clarify the problem.
> Your custom checkout fields may not be compatible with these payment methods. _Learn more_

cc @FangedParakeet @pierorocca

**Comment by pierorocca** [comment]
WooPay incompatibility notice also uses the previous notification design. While not necessarily a bug, there appears to have been a system design change that didn't get picked up.

Curious Samir if Figma and GH have any way of being component aware without  needing a dev to check manually each time if a component is still the active?

**Comment by frosso** [comment]
I noticed the same thing and it was irking me as well.
I ended up fixing it in here: https://github.com/Automattic/woocommerce-payments/pull/8837
It turns out that the WooPay compatibility one was using the incorrect component, compared to all the other notices in the settings.

This is the more consistent view - I also ended up adjusting the internal padding on the notices (between the icon and the text) to be consistent:
<img width="1117" alt="Screenshot 2024-05-17 at 1 44 31 PM" src="https://github.com/Automattic/woocommerce-payments/assets/273592/9c463d03-ff67-430b-a7ce-c3437730b889">

(I also ended up adjusting the copy as described in the ticket's description)

**Comment by elizaan36** [comment]
LGTM! Thanks @frosso . The only very small thing is on the WooPay notice, "Learn more" doesn't need a line break. It can wrap with the notice text.

**Comment by frosso** [comment]
@elizaan36 here are some examples of the messaging and the new wrapping:
<img width="1067" alt="Screenshot 2024-05-23 at 12 01 38 PM" src="https://github.com/Automattic/woocommerce-payments/assets/273592/4934e262-a243-40e5-8736-ab24271facb7">
<img width="1084" alt="Screenshot 2024-05-23 at 12 01 31 PM" src="https://github.com/Automattic/woocommerce-payments/assets/273592/4e6f3759-efc0-4032-a2d6-36d55a3bd8d0">
<img width="1084" alt="Screenshot 2024-05-23 at 12 01 15 PM" src="https://github.com/Automattic/woocommerce-payments/assets/273592/e71b3b8e-9a9e-4d20-8a90-c328c626ac97">

**Comment by aheckler** [comment]
Added a blurb about this [here](https://woocommerce.com/document/woopayments/compatibility/#plugin-compatibility). Also mentioned [here](https://woocommerce.com/document/woopayments/payment-methods/apple-pay-and-google-pay-compatibility/#faq-extra-fields-on-checkout).
