### ISSUE TITLE
Review Customer ID logic

### ISSUE THREAD

**Issue by kaushikasomaiya** [Automattic/woocommerce-payments#8892]
8247182-zen

This is based on my observation, please feel free to close this report if not relevant or incorrect. 

The user decided to migrate their site to GoDaddy but it seems something went wrong during migration and they started seeing failed renewals with the following message:

> A payment of $225.00 failed to complete with the following message: Error: The PaymentMethod pm_xx does not belong to the Customer you supplied cus_xx. Please use this PaymentMethod with the Customer that it belongs to instead.

User migrated back to Atomic hosting and we decided to help them with this issue. 

My suspicion is that meta _wcpay_customer_id_live might have gone missing and resulted in creation of new user on Stripe via `create_customer_for_user()`

This new customer ID created on Stripe was stored as `_wcpay_customer_id_live` meta and possibly the failed renewal order was updated with this new Stripe customer ID as well. My question is should we ensure subscriptions is always renewed with customer ID attached to the subscription or renewal order rather than user meta `_wcpay_customer_id_live`? 

I tried updating `_wcpay_customer_id_live` to the correct cus_ ID however it did not work even though there were no traces of the incorrect new cus_ ID at all in the database. It threw the same error.

Later I found `$customer_id = get_user_option( '_wcpay_customer_id_live', 207285275 );` returns the incorrect ID due to caching on Atomic hosting.

Clearing the cache helped fix the issue.

---

Edit:

Or perhaps what I am thinking is `get_user_option()` would have returned blank value when the database prefix changed on migration causing creation of a new ID? 

https://github.com/Automattic/woocommerce-payments/blob/1bd1b1d253cc8e5a7d3f57e4686abb5c6c7c1a91/includes/class-wc-payments-customer-service.php#L132

**Comment by deepakpathania** [comment]
@anu-rock Sending it your way to investigate further but let me know if that doesn't seem correct.

**Comment by kaushikasomaiya** [comment]
This might also create additional mess for the following scenario 

- Subs 123 attached to cus_123
- _wcpay_customer_id_live goes missing
- System creates new customer_456
- Meanwhile user adds a payment method and purchases new subscription subs 456 attached to cus_456
- Result is two subscriptions dependent on two different cus_ ids.

**Comment by kaushikasomaiya** [comment]
Or perhaps what I am thinking is `get_user_option()` would have returned blank value when the database prefix changed on migration? 

https://github.com/Automattic/woocommerce-payments/blob/1bd1b1d253cc8e5a7d3f57e4686abb5c6c7c1a91/includes/class-wc-payments-customer-service.php#L132

CC @luizreis @james-allan  as well.

**Comment by anu-rock** [comment]
@deepakpathania TBH, this looks like something @Automattic/quark is better equipped to help with. I've pinged them on Slack to check further p1718349497637419-slack-C055WHLA98D. Sending it back to the triage queue.

**Comment by james-allan** [comment]
> TBH, this looks like something @Automattic/quark is better equipped to help with.

Hey @anu-rock, this isn't something Quark have any product knowledge of. My read of this issue is that a merchant migrated to GoDaddy and they started to receive this error: 

```
A payment of $225.00 failed to complete with the following message: Error: The PaymentMethod pm_xx does not belong to the Customer you supplied cus_xx. Please use this PaymentMethod with the Customer that it belongs to instead.
```

That error indicates that WooPayments meta stored on the subscription/customer is invalid or incorrect. That's outside of WooCommerce Subscription's purview.  

As @kaushikasomaiya mentioned in the issue description, it looks like the `_wcpay_customer_id_live` user meta may have been corrupted or went missing in the migration process. That's well outside the scope of anything we can do as product teams, however what Kaushik is suggesting is that WooPayments may want to reconsider what it does when customer IDs go missing like that. 

He is saying that WooPayments created a new customer ID but that broke the subscription(s) that customer has because the saved payment method stored on the subscription is not attached to that new customer.

IMO there are kind of 2 solutions here:

1. WooPayments could store the customer ID (`cust_` on the subscription as well. This means that when the subscription goes to renew, WooPayments can form the payment request with a `pm_` and `cust_` pair that match.
2. When a customer ID seemingly goes missing, attempt to find it rather than create a new one. I don't know how feasible that is given you wouldn't want to mix or miss identify customers.

While this is Subscriptions-related, Quark doesn't look after WooPayments' subscription integration. 

The same issue would occur if I did the following:

1. Purchased a product and on checkout saved my token. 
2. Deleted the `_wcpay_customer_id_live` meta. 
3. Made a new purchase using a new card/payment method. 
   - According to Kaushik's theory this will create a new customer ID. 
4. Attempt to make a purchase using the token you saved at step 1. 

I suspect you will get a similar `The PaymentMethod pm_xx does not belong to the Customer you supplied cus_xx.` error. That's basically the same issue Kaushik is reporting here.

**Comment by kaushikasomaiya** [comment]
Thanks for the additional info @james-allan 
> what it does when customer IDs go missing like that.

I noticed we're using get_user_option which seems to be somewhere dependent on blog prefix. After moving back to atomic hosting from Godaddy, the following entries were found in their DB for a single user:

207285572 | wp_s568fztf7k__wcpay_customer_id_live |  cus_xxxx (Old but correct customer ID)
207285572 | wp_nkv0c9j996__wcpay_customer_id_live | cus_xxxx (Newly created)

But site's prefix is wp_nkv0c9j996 and the `wp_s568fztf7k` seems to be old site's prefix. Doesn't seem to be the case of missing ID in this ticket but blog prefix change?

Default update_user_option() value seems blog specific 

https://github.com/Automattic/woocommerce-payments/blob/0948bf90a1f137ee14e9f4517cb53e75abcf6842/includes/class-wc-payments-customer-service.php#L485

**Comment by kaushikasomaiya** [comment]
> WooPayments could store the customer ID (cust_ on the subscription as well. This means that when the subscription goes to renew, WooPayments can form the payment request with a pm_ and cust_ pair that match.

It does store it there already (postmeta), but when it doesn't find one in the usermeta table, it creates a new Cus_ ID and also updates the new one on the subscription

**Comment by james-allan** [comment]
> It does store it there already (postmeta), but when it doesn't find one in the usermeta table, it creates a new Cus_ ID and also updates the new one on the subscription

Ah, so to summerise your two most recent comments. WooPayments could resolve this by:

1. Attempt to collect the payment using the `cust_` stored in subscription meta even if it isn't stored in user meta, it could be valid.
2. Relook/rethink how WooPayments store customer IDs in `get|update_user_option()` because that's blog specific and migrations cause that to change. I suspect blog prefixed keys are used for multi-sites though. 

General question: do site migrations attempt to migrate user options like this? ie update user options from the old blog prefix to the new one? That seems like a good idea.

**Comment by vbelolapotkov** [comment]
I scanned through the conversation, and not really sure, there is anything to do or fix on WooPayments end. The behavior described is correct, because payment methods linked to certain customer objects, so if that linking is broken during migration the renewals are failing, which is expected.

So I'm leaning towards closing it. @james-allan @kaushikasomaiya any objections here?

**Comment by kaushikasomaiya** [comment]
@vbelolapotkov I spotted two more support cases from March: 7929037-zen and 7762422-zen with the same error and in both cases customers migrated to Godaddy which likely changed the blog prefix. James' last comment makes sense to me if we want to look into 1 & 2 otherwise I am fine to close or mark this low priority so other HEs can report more cases

**Comment by vbelolapotkov** [comment]
@deepakpathania @c-shultz looking at proposed approach to manipulating the customer object in the store, I feel it's in between payment processing and checkout focuses, closer to checkout IMO, because it's more about finding the right customer id to trigger payment processing flow. However, I'd like to check with you two before routing it to the best team. What's your opinion?

**Comment by deepakpathania** [comment]
Seems closer to checkout IMO, that is before the payment processing boundary starts.

**Comment by c-shultz** [comment]
>Seems closer to checkout IMO, that is before the payment processing boundary starts.

I'm comfortable with that call. Heisenberg has already been digging into similar areas, so it's not a bad match. I'll route to checkout.

**Comment by james-allan** [comment]
This issue has come up for merchants who migrate tokens from Stripe to WooPayments as well. We were discussing this with the Customer Success team as they've had a number of intermittent payment failures due to the customer ID stored in the user option being incorrect, or out of sync with the meta stored on the subscription and thats leading WooPayments to create a new customer. 

From our perspective, the potential fix [I mentioned above](https://github.com/Automattic/woocommerce-payments/issues/8892#issuecomment-2167475792) where the customer ID stored in the subscription's meta should take precedence over the one stored in the user option is what we believe should happen here.

So what does that mean for what this fix looks like:

The `WC_Payment_Gateway_WCPay_Subscriptions_Trait::scheduled_subscription_payment()` function is the one responsible processing a renewal payment. 

It generates a `Payment_Information` instance and then calls the `process_payment_for_order()` function. This is a core WooPayments function for collecting payment - it's used in a front-end-checkout context, and a subscription renewal context.

That `process_payment_for_order()` function is the function that is then responsible for fetching the customer via [this `manage_customer_details_for_order()` call](https://github.com/Automattic/woocommerce-payments/blob/e85cc3ba48ffb659d5e51317a388cd1062040715/includes/class-wc-payment-gateway-wcpay.php#L1452). The [`manage_customer_details_for_order()` function](https://github.com/Automattic/woocommerce-payments/blob/e85cc3ba48ffb659d5e51317a388cd1062040715/includes/class-wc-payment-gateway-wcpay.php#L1383-L1392) attempts to pull the customer ID from the user option. 

In a subscription's renewal context, you'll almost never want to create a new stripe customer. The Stripe customer ID stored in the Subscription's meta data (`_stripe_customer_id`) is inextricably linked to the saved payment method and so creating a new customer and then attempting to use the saved token will never work. 

**WooPayments should always attempt to use the Stripe customer stored in the subscription's meta.** 

There's a number of ways you could do that. I've listed some ideas below, but definitely go with your own approach if there's a better one available.

1. Change the `Payment_Information` to allow setting a customer ID. That customer ID would take precedence in `process_payment_for_order()`. 
   - `WC_Payment_Gateway_WCPay_Subscriptions_Trait::scheduled_subscription_payment()` could then set the customer ID from the subscription's meta data when it creates the payment information instance. 
3. Change `manage_customer_details_for_order()` to check if the provided order is a renewal order and then use the customer ID stored in the renewal order's meta. 
   - You could change the `$customer_details_options` ([code link](https://github.com/Automattic/woocommerce-payments/blob/e85cc3ba48ffb659d5e51317a388cd1062040715/includes/class-wc-payment-gateway-wcpay.php#L1449-L1451)) given it looks like that's the way to provide context to `manage_customer_details_for_order()`.
   - If you go with this approach, you may need to be careful with manual renewal order payments. In that context the customer is logged in an using the cart flow, so forcing the customer id to the one stored in subscription/renewal order meta is less important.

**Comment by FangedParakeet** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Heisenberg-63586f2ec60359001310fa6a/issues/Automattic/woocommerce-payments/8892?planning-poker) with Zenhub @danielmx-dev
