### ISSUE TITLE
Live accounts without transactions cannot view the Payment Activity Card in test mode

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#8958]
### Describe the bug

When a live account with 0 live transactions switches to test mode with 1+ test transactions, the Payment Activity card will show an empty state Payment Activity card rather than values reflecting the test transactions

This may be caused because the empty state is shown if the account cache's `lifetime_total_payment_volume` = 0. `lifetime_total_payment_volume` uses live transactions ([server src](https://github.com/Automattic/woocommerce-payments-server/blob/5e3dc372ea0f10cab740439ff0ca1ebc7fa7715b/server/wp-content/rest-api-plugins/endpoints/wcpay/class-accounts-controller.php/#L914)) for this calculation. 

> [!TIP]
> This issue affects the Payments Overview Card which is behind feature flag `_wcpay_feature_payment_overview_widget`

### To Reproduce

1. Use an account onboarded in live mode, without any live transactions
3. Enable WooPayments test mode
4. Make some test purchases
5. Enable feature flag `_wcpay_feature_payment_overview_widget`
6. Visit Payments → Overview
8. Notice the empty state on the Payments Overview. We should see Payment Activity for test mode transactions.
	- You may also see a network error, related to issue #8960

### Additional context

Mentioned here https://github.com/Automattic/woocommerce-payments/issues/8737#issuecomment-2164733164

**Comment by jessy-p** [comment]
@aheckler / @csmcneill  Do you have a live account with both live and test transactions to check this?

**Comment by aheckler** [comment]
> Do you have a live account with both live and test transactions to check this?

I do! But I think what's actually needed is a live account with ZERO live transactions and some transactions in test mode, yes?  :) Anyway, my situation:

- Latest stable release of WordPress, WooCommerce, and WooPayments.
- I have a couple live transactions and many test transactions. 
    - Because I've refunded all the live mode transactions, the PAC shows my lifetime TPV as $0.
    - However, my account meta contains: `'lifetime_total_payment_volume' => 500`
- `_wcpay_feature_payment_overview_widget` is set to `1`.

In that scenario, here's how things look in live mode:

![Screenshot taken on 2024-06-20 at 09 10 00 UTC@2x](https://github.com/Automattic/woocommerce-payments/assets/5512652/abe4ad26-a97a-41f8-bdf1-1fdb5715c7f9)

If I flip to test mode and refresh, the PAC starts to load, but then disappears, and I get `Error retrieving payment activity data`. Looking in the error log, I see the `wcpay_invalid_currency` message.

So since `lifetime_total_payment_volume` might need to actually be `0` for this, I onboarded a new live account using JN. Here's how the PAC looks in live mode with no transactions in live mode or in test mode yet:

![Screenshot taken on 2024-06-20 at 09 38 38 UTC@2x](https://github.com/Automattic/woocommerce-payments/assets/5512652/fcfb6ac9-8c8f-46d8-953f-a136f6e140a0)

Looks the same in test mode too.

If I then complete a transaction in test mode and refresh the PAC page in test mode, I still see an empty state.

**Comment by Jinksi** [comment]
@haszari you've marked this in progress. Do we know who is assigned/working on it?

**Comment by haszari** [comment]
> you've marked this in progress. Do we know who is assigned/working on it?

Woops, meant to check in with @jessy-p , I understood she was working on it, though maybe I'm conflating two similar issues. Feel free to grab it!

**Comment by nagpai** [comment]
Noting my freeflow observations here. 

~Tricky!~

<s>The [calculation of lifetime TPV](https://github.com/Automattic/woocommerce-payments-server/blob/c005eaab62158931bec726cc36d9342049b71242/server/wp-content/rest-api-plugins/endpoints/wcpay/class-accounts-controller.php#L901), ultimately uses [WCPay\Repository\Transaction_Repository::get_volume_processed_in_usd](https://github.com/Automattic/woocommerce-payments-server/blob/c005eaab62158931bec726cc36d9342049b71242/server/wp-content/rest-api-plugins/endpoints/wcpay/repository/class-transaction-repository.php#L682). The function seems to account for test mode and would query the table accordingly. I wonder why would `lifetimeTPV` resolve as `0` </s>

While [calculating](https://github.com/Automattic/woocommerce-payments-server/blob/c005eaab62158931bec726cc36d9342049b71242/server/wp-content/rest-api-plugins/endpoints/wcpay/class-accounts-controller.php#L901) `lifetime_total_payment_value` on server side, we use `$account->is_test`. This will always resolve as false unless the account itself is in sandbox mode. It homes in to the account status, and not the plugin status.  

For an account that is already live, but switched to test mode in the plugin, I see the following in Dev tools:
* In account cache contents `'is_live' => true,` 
* The local WCPay Gateway Settings shows `'test_mode' => 'yes',`

Need to explore further, how do we get test mode TPV instead of live, for a live account in test mode.

💡  - Use `$request->is_test()`
