### ISSUE TITLE
Duplicate saving of 3DS card entry after checkout

### ISSUE THREAD

**Issue by timur27** [Automattic/woocommerce-payments#8997]
### Describe the bug
After using a saved 3DS card during checkout, it gets re-saved on the store.

### To Reproduce

1. Perform checkout, use a 3DS card, and save it
2. Checkout again but use the saved 3DS this time
3. Open the checkout page and you will see the saved 3DS entry is duplicated now

### Additional context
This behavior could potentially be related to our recent fixes for saving 3DS cards in https://github.com/Automattic/woocommerce-payments/commit/0635be28ae20d5c5743b1f127ce1c66cc3a524de.

**Comment by mdmoore** [comment]
This issue is the result of [this fix](https://github.com/Automattic/woocommerce-payments/commit/0635be28ae20d5c5743b1f127ce1c66cc3a524de) for 3DS subscriptions missing payment methods and failing renewals as a result. Previously, tokens were only added when the `payment_method_id` was present in the request, which is only the case when saving a payment method. This meant that 3DS payment methods were not stored in subscriptions. The solution was to get the `payment_method_id` from the intent. This means that now the `payment_method_id` is always present and 3DS tokens are saved again when paying with a saved 3DS card.

I think rather than just checking for the presence of a payment method id [here](https://github.com/Automattic/woocommerce-payments/blob/aac2f270fa282260326e5dc0677c80fed23353b3/includes/class-wc-payment-gateway-wcpay.php#L3497), we need to check whether the payment method is intended to be saved, indicated either by the save payment method checkbox or when the order is a subscription order.
