### ISSUE TITLE
Hong Kong addresses always fail validation via Apple Pay

### ISSUE THREAD

**Issue by zoupkat** [Automattic/woocommerce-payments#9123]
**Describe the bug**

Apple Pay currently sends us an address in a format we don't expect; the Hong Kong Region (e.g. "New Territories") is put into the postalCode property of the paymentRequest object, instead of the region like we would expect.

This makes it so that when you try to pay via Apple Pay with a Hong Kong address the payment always fails with a very cryptic error message.

This means customers are unable to pay merchants through Apple Pay when using a Hong Kong address.

__FYI_: This was an issue that was also present in WC Stripe but they managed to fix it/close it: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1630

This was also discussed [in a Slack thread internally](https://a8c.slack.com/archives/CU6SYV31A/p1721236582584489?thread_ts=1721236162.125269&cid=CU6SYV31A) (access only available to Automattic agents) before creating the report here._

**To Reproduce**

Reproduction and testing steps available in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1593

**Expected behavior**

Address validation succeeds for valid addresses and payments can be processed.

**Comment by AashikP** [comment]
User report in 8488611-zen

**Comment by pierorocca** [comment]
I've pass this along to our contacts at Apple Pay. There's definitely a challenge if a wallet provide maps addresses differently than what's expected by the core platform and by WooPayments. We'll have to look at a temporary workaround if Apple isn't able to place `Region` into `Region`.

**Comment by tamhas** [comment]
Okay we, and every other business in HK are using WC Stripe now then ... not really everyone else is using Shopify 😂
Hope you can fix though, so my few HK clients at least can enjoy WooCommerce for their online bookings and ordering.
Thanks

**Comment by tamhas** [comment]
Honestly, surprised you wouldn't just look how at WC Stripe has done it and implement that! Wordpress is open source you know

**Comment by pierorocca** [comment]
Additional ticket related to this issue. 9069128-zd-a8c. I have talked to the Apple Pay team about this issue. Their response is that because addresses are at the core OS level, resolving this is more challenging as they need to engage teams outside of Apple Pay.

I'll check in again with the Apple team to see if there's an ETA. If not, we'll have to consider implementing a similar workaround.

**Comment by pierorocca** [comment]
@bborman22 a good candidate to consider for the next round of maintenance.

**Comment by bborman22** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/9123?planning-poker) with Zenhub @asumaran

**Comment by reykjalin** [comment]
There's potentially a lot of useful information on this in pc4etw-bY-p2. The gist is that – if nothing has changed since that post - the Apple Pay address format for Hong Kong addresses is uniquely "wrong" in terms of the address format WooCommerce expects. The fix will likely include something similar to what we did in https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1593.

**Very heavy** quotation marks around "wrong" here because the WC address format is very US-centric, and this creates all sorts of conflicts, (likely) including this one.

We had a big back-and-forth with Apple on this, including a team member of theirs that lives in Hong Kong, and were able to determine that Apple Pay does format Hong Kong addresses in an unexpected way. They said they had logged an issue internally, but they haven't changed anything yet to my knowledge.

**Comment by pierorocca** [comment]
> We had a big back-and-forth with Apple on this, including a team member of theirs that lives in Hong Kong, and were able to determine that Apple Pay does format Hong Kong addresses in an unexpected way. They said they had logged an issue internally, but they haven't changed anything yet to my knowledge.

That's correct. They know it's a bug. However, it's a bug in Core Apple OS rather than being an Apple Pay specific issue. I'm told in Apple's structure, core changes are harder to initiate and take longer to implement. I haven't heard anything yet that would indicate a solve is immenent.

**Comment by asumaran** [comment]
@reykjalin should we port https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1593/ then to WooPayments? I see that you’ve conducted an in-depth study on the topic, and I imagine it’s the same issue occurring with WooPayments, with the potential solution likely being the same.

**Comment by reykjalin** [comment]
> I haven't heard anything yet that would indicate a solve is immenent.

They've known about this since 2021, so no, I wouldn't say a solve on their end is imminent :)

> should we port https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1593 then to WooPayments?

Yes, I think we should. The biggest piece of that is just moving over the HK address mapping file, that should give you all the tools you need to fix the issue :)

**Comment by pierorocca** [comment]
> They've known about this since 2021, so no, I wouldn't say a solve on their end is imminent :)

lol so true!
