### ISSUE TITLE
Indicate in UI that payment activity card dates/times are in UTC

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-payments#9133]
Part of https://github.com/Automattic/woocommerce-payments-server/issues/5858 and https://github.com/Automattic/woocommerce-payments-server/issues/5868

The goal of this issue is to show in the UI (or at least in docs!) that the payment activity card uses UTC (for consistency with list views).

**Comment by haszari** [comment]
Update – I propose that we don't need to make any changes to show "UTC". Here's why:

- Our UI is currently inconsistent. Most/many times are in UTC, but some are localised.
  - https://github.com/Automattic/woocommerce-payments/issues/9135
- The times in list views are generally UTC (to be confirmed), and are not labelled as UTC.

Perhaps we can just check the documentation to ensure it's not misleading/confusing.

**Comment by aheckler** [comment]
_Copy-pasting my comments from the internal Slack thread: p1721342420625239-slack-C06BBFTF6EM_

Our docs [mostly don't mention](https://www.google.com/search?q=site%3Awoocommerce.com+inurl%3Adocument%2Fwoopayments+%22utc%22) UTC or [timezones](https://www.google.com/search?q=site%3Awoocommerce.com+inurl%3Adocument%2Fwoopayments+%22timezone%22). 

[This mention](https://woocommerce.com/document/woopayments/deposits/deposit-schedule/#daily-cutoff-time) and [this mention](https://woocommerce.com/document/woopayments/in-person-payments/getting-started-with-in-person-payments/#faq-estimated-shipping) are only present because deposit cutoff times and card reader shipment times are directly determined by Stripe and are out of our control. The only time we mention UTC when it's something we could control is [here](https://woocommerce.com/document/woopayments/taxes/documents/#downloading-an-invoice), and IIRC that note is only there due to a specific support ticket we got about the transactions contained in an invoice.

My two cents: we should be showing dates/times in the merchant timezone everywhere, it's surprising to me that we aren't, and it's also surprising we don't hear more about this via support.

Frankly, the fact that's it's gone (mostly) undocumented for so long actually seems like an argument for not even bothering to document it for the PAC either. ¯\\_(ツ)_/¯

**Comment by haszari** [comment]
Closing - we don't want to add specific timezone hints in the UI, long term we need to shift to using merchant/store timezone consistently.

**Comment by haszari** [comment]
Marking as zero estimate – not planned.
