### ISSUE TITLE
Ensure Equal Vertical and Horizontal Spacing Between ECE Buttons and WooPay Button

### ISSUE THREAD

**Issue by lovo-h** [Automattic/woocommerce-payments#9169]
### Description

Currently, the vertical spacing between ECE buttons and the WooPay button is not equal. The fix for this issue will ensure that the vertical and horizontal spacing between ECE buttons and the Woopay button are equal.

### Acceptance criteria

* Ensure the vertical spacing between ECE buttons are equal.
* Ensure the vertical spacing between ECE buttons and the WooPay button is equal.
* Ensure the horizontal spacing between ECE buttons are equal.
* Ensure the horizontal spacing between ECE buttons and the WooPay button is equal.
* Ensure the vertical and horizontal spacing is equal.
* Ensure the implementation matches the designs in c8VYjXqluE9vlVSE1RgJix-fi-858_15405.

### Designs

An example of vertical and horizontal space not being equal:
![image](https://github.com/user-attachments/assets/fc970748-c0cc-40ee-a0a8-1c5b34db3a04)

An example of the vertical and horizontal space being equal:
![image](https://github.com/user-attachments/assets/2584552e-8eb7-4a9d-b2d2-d3af4a1c995d)

### Testing instructions

1. As a shopper, navigate to the merchant shop, add an item to the cart, and navigate to the cart page.
2. Ensure the vertical and horizontal spacing of the buttons are equal.
3. Navigate to the checkout page.
4. Ensure the vertical and horizontal spacing of the buttons are equal.

### Additional context

* See the following thread for additional context: p1721680636834669-slack-C01BZUL57SQ

**Comment by pierorocca** [comment]
Noting this occurs on PDP, Cart, Checkout and both blocks and shortcode.

**Comment by bborman22** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Fractal-62a0f7b955648b001e1f5e1f/issues/Automattic/woocommerce-payments/9169?planning-poker) with Zenhub @lovo-h @cesarcosta99 @asumaran @reykjalin

**Comment by asumaran** [comment]
According to the acceptance criteria of this issue: 
> Ensure the implementation matches the designs in [c8VYjXqluE9vlVSE1RgJix-fi-858_15405](https://href.li/?https://www.figma.com/file/c8VYjXqluE9vlVSE1RgJix/?node-id=858-15405).

@pierorocca, should I focus only on the spacing issues, or should I also make changes so that the buttons look identical to the Figma file?

For example, on the Cart page, the ‘Proceed to checkout’ button is located after the express checkout buttons, whereas in the Figma design, it is placed at the top.


| Currently  | Design |
| ------------- | ------------- |
| <img width="427" alt="Screenshot 2024-08-11 at 6 55 49 PM" src="https://github.com/user-attachments/assets/5b7b38a4-2eff-40d2-9069-f352301eb331"> | <img width="438" alt="Screenshot 2024-08-11 at 6 43 25 PM" src="https://github.com/user-attachments/assets/28fefd2e-1fa2-49c1-a64d-1b0370864457">  |

On the checkout page, the title of the ‘Express checkout’ section is centered and currently it's aligned to the left.

| Currently  | Design |
| ------------- | ------------- |
| <img width="756" alt="Screenshot 2024-08-11 at 6 56 59 PM" src="https://github.com/user-attachments/assets/5344bb8b-ffe3-45c3-b031-9ce40c5aa021"> | <img width="697" alt="Screenshot 2024-08-11 at 6 43 19 PM" src="https://github.com/user-attachments/assets/263ffffb-7033-470c-9b35-83e6ec987fe9"> |


Additionally, on checkout page's design, the three buttons are shown to take up the entire width of their container. However, currently, they are distributed in columns, switching to full width when the browser viewport is narrowed. Will the ECE buttons be displayed in rows or columns and rows depending on the viewport width? If so, at what point does it change from columns to rows?

**Comment by pierorocca** [comment]
Just the spacing for now. I think those other design elements are Blocks specific and are being updated by Alex.

**Comment by asumaran** [comment]
It seems that the spacing between the ECE buttons on the shortcode-based cart and checkout pages cannot be adjusted because they are within an IFRAME. The design cannot be applied to those instances. Is that okay, @pierorocca? – Block-based pages look good because each button is a separate instance of ECE, allowing each button to be spaced independently

The space between buttons according to the designs is `14px` while Stripe is using "8px".

<img width="612" alt="image" src="https://github.com/user-attachments/assets/3092eb83-8d01-4e89-b970-32929dc0ecc2">

<img width="821" alt="Screenshot 2024-08-12 at 12 12 48 PM" src="https://github.com/user-attachments/assets/dfdd6e5f-3be7-4443-bab6-390b171c80a7">

@pierorocca would you like me to use the same spacing that Stripe uses so that the buttons appear correctly spaced? (only on shortcode)

<img width="472" alt="Screenshot 2024-08-12 at 12 20 31 PM" src="https://github.com/user-attachments/assets/49e72f28-cf65-496e-9d31-eda1536d1672">

<img width="821" alt="Screenshot 2024-08-12 at 12 20 51 PM" src="https://github.com/user-attachments/assets/963f3bee-7b9f-4cab-9e0e-5f4999a5cc33">

**Comment by pierorocca** [comment]
Yes, let's reduce to align with Stripe since that seems like our only option here. I prefer the reduced spacing. I find that the increased spacing creates a barcode stripe like effect that's distracting. 


@nikkivias we have a technical limitation here that will have impact in a multi gateway scenario.

@asumaran could we double check with Stripe just in case? I don't think gridrowspacing and gridcolumnspacing can be used for ECE buttons.

**Comment by asumaran** [comment]
>@asumaran could we double check with Stripe just in case? I don't think gridrowspacing and gridcolumnspacing can be used for ECE buttons.

I'll double check their documentation.

**Comment by asumaran** [comment]
@pierorocca, good call on recommending the Elements appearance variables. `gridRowSpacing` and `gridColumnSpacing` don't apply in this case, but I was able to customize the spacing by setting the `spacingUnit` variable.

<img width="456" alt="image" src="https://github.com/user-attachments/assets/4fbd3a20-cc48-4054-a642-e9f8ee863c6b">

<img width="829" alt="Screenshot 2024-08-12 at 2 20 07 PM" src="https://github.com/user-attachments/assets/c42dc33c-1446-4d15-80cc-15afde53f1aa">

The space looks as the proposed design now.

**Comment by pierorocca** [comment]
Cool. @asumaran could we get side by side at 8px and 14px? The extra spacing looks unpleasant to me when the buttons are stacked. I'd like to do a quick informal poll on what people prefer and why.

**Comment by pierorocca** [comment]
Oops sorry see the other version above...

**Comment by pierorocca** [comment]
Quick poll @csmcneill @c-shultz @bborman22 @frosso @reykjalin @leonardola @asumaran which do you prefer left or right?

![image](https://github.com/user-attachments/assets/fc899b9b-70b9-40bb-9906-1c46782f09b2)

**Comment by asumaran** [comment]
@pierorocca here's how it looks with "8px" padding. Same as Stripe.

**Product page**
<img width="817" alt="Screenshot 2024-08-12 at 3 32 34 PM" src="https://github.com/user-attachments/assets/b47c365b-63cb-484c-a8df-68f3ed59efba">

**Cart Block**
<img width="434" alt="Screenshot 2024-08-12 at 3 36 12 PM" src="https://github.com/user-attachments/assets/2a57d7c5-607a-465a-bd58-89aed7f5bcb5">

**Checkout Block**
<img width="467" alt="Screenshot 2024-08-12 at 3 33 07 PM" src="https://github.com/user-attachments/assets/38426af6-5771-4846-861b-c3ba3dbbf3cd">

**Cart Shortcode**
<img width="461" alt="Screenshot 2024-08-12 at 3 33 43 PM" src="https://github.com/user-attachments/assets/065ea2ca-db98-4098-adf0-5300a9ea003c">

**Checkout Shortcode**
<img width="822" alt="image" src="https://github.com/user-attachments/assets/7dbd157c-e517-4deb-8de4-104315714362">

**Comment by pierorocca** [comment]
OK 8px looks too tight.

One more data point - Shopify If I'm reading it right is using 11px grid spacing?

![image](https://github.com/user-attachments/assets/41922569-f5cd-4ceb-b304-9572bdf4452d)

**Comment by asumaran** [comment]
@pierorocca I prefer the right option. The one that has less space between buttons.

**Comment by asumaran** [comment]
>One more data point - Shopify If I'm reading it right is using 11px grid spacing?

Yes, technically, Shopify is using `1.1rem` internally which translates to 11px.

**Comment by leonardola** [comment]
@pierorocca I like the right one more

**Comment by asumaran** [comment]
@pierorocca let me know what value we want to use `8px` or `11px` or `14px`.

**Comment by pierorocca** [comment]
8px is looking really tight now that I've had time with it. @nikkivias thoughts on compromising down to 11px from 14px to avoid what to my eyes looks like a banding or striping effect at 14px?

@asumaran regarding the - OR - separation, that was removed on shortcode for compatibility not because we preferred it. Too many sites had multiple - OR -, often in the wrong place or where there should have been none. We made a call to remove it to eliminate the compatibility issue at the expense of nice separation between Add to cart and Proceed to checkout buttons.

**Comment by asumaran** [comment]
>@asumaran regarding the - OR - separation, that was removed on shortcode for compatibility not because we preferred it. Too many sites had multiple - OR -, often in the wrong place or where there should have been none. We made a call to remove it to eliminate the compatibility issue at the expense of nice separation between Add to cart and Proceed to checkout buttons.

@pierorocca, are you suggesting that I should remove the "or" separator from the block-based pages as well, or should I restore it on the shortcode-based pages?

**Comment by pierorocca** [comment]
> @pierorocca, are you suggesting that I should remove the "or" separator from the block-based pages as well, or should I restore it on the shortcode-based pages?

Neither. Just fyi to an earlier question of yours :) Blocks doesn't suffer the same issue of extra and rogue - or - separators. And we don't want to restore it on shortcode because it'll bring back all of the problems we got rid of.

**Comment by csmcneill** [comment]
I prefer more spacing, but that could also be my deteriorating eyeballs 👀

Some questions:
- Is the limit three payment request buttons? Are there instances where we can have more buttons rendered?
- Would more or less spacing be preferable if other buttons were added via a different extension (e.g., PayPal Payments)?

**Comment by pierorocca** [comment]
Amazon Pay is a possibility for a 4th button and Link could potentially be a 5th. Buttons from other gateways will add to the count, but I don't think they should look different or be spaced differently. The [design guidelines](https://developer.woocommerce.com/docs/category/payments-guidelines/) don't mention vertical spacing between buttons which may create inconsistencies over time in multi-gateway scenarios.

Visually if it's 1 or 5 buttons, they should feel like a cohesive block. There's a point where if the spacing is too big and the buttons are decently wide, to my eyes it creates a banding effect similar to, but not as extreme, as the attached image.

![image](https://github.com/user-attachments/assets/e01059bd-3c56-4b77-9681-7d6f9185c535)

@asumaran mind adding an 11px option here for comparison?

**Comment by asumaran** [comment]
@pierorocca here's some screenshots with `11px` separation between buttons.

<img width="421" alt="Screenshot 2024-08-13 at 11 19 43 AM" src="https://github.com/user-attachments/assets/032933c7-af37-4dfd-9a67-a7f322c47c2d">
<hr />
<img width="853" alt="image" src="https://github.com/user-attachments/assets/e7615e5d-5671-4ab7-a22a-e4ab3b05e36b">
<hr />
<img width="814" alt="image" src="https://github.com/user-attachments/assets/61d58e33-6eb8-4cd1-9813-128b4581be9b">

**Comment by pierorocca** [comment]
14px here for reference. I think 11px is the best balance of space but not too much space that the buttons looks like they're not part of a block of buttons. Up to @nikkivias here to make the final call since the size we pick, and add to the 3P guidelines, will impact everyone.

![image](https://github.com/user-attachments/assets/e10cd4bb-faf1-4fc6-b891-15c91789e943)

**Comment by nikivias** [comment]
Hi team. Vertical and horizontal spacing MUST be equal. 

From Slack:
> Shopify uses 11px and to my eyes that creates less of a banding or stripe effect visually than 14px.

It could be good to reference if it works with Shopify. We just want to use an even number gap, so I used 12PX instead. [Here is the Public figma file](https://www.figma.com/design/c8VYjXqluE9vlVSE1RgJix/%5BPublic%5D-Cart-%26-Checkout-Blocks?node-id=858-15405&t=7OnWS0DaISZ1VWTb-1)

![CleanShot 2024-08-14 at 12 03 10](https://github.com/user-attachments/assets/eed1671b-1bf2-4af0-a13b-b579fe05e0f7)

**Comment by pierorocca** [comment]
Thanks @nikkivias! That takes us down from almost 27% larger spacing to 9% relative to Shopify.

**Comment by asumaran** [comment]
I updated the [PR](https://github.com/Automattic/woocommerce-payments/pull/9258) with 12px spacing and marked it as ready for review.

**Comment by alexflorisca** [comment]
Hi @nikkivias this seems to clash with the changes from your figma file that I implemented in https://github.com/woocommerce/woocommerce/pull/50644 where I set it to `14px`. Which one is the right one here?

**Comment by pierorocca** [comment]
@alexflorisca correct changing to 12px to be more space efficient and to soften what I was seeing as banding or striping effect at the larger spacing. We looked at Stripe's spacing (8px) and Shopify's spacing (11px) and settled on 12px. 14px puts us at almost double Stripe's spacing and 30% above Shopify's spacing.

Sorry for the changeup. OK to update your PR to 12px?

**Comment by alexflorisca** [comment]
Sure no problem
