### ISSUE TITLE
Payment method duplicates warning still thrown despite disabling the Stripe gateway

### ISSUE THREAD

**Issue by pierorocca** [Automattic/woocommerce-payments#9271]
### Describe the bug
I had the WooPayments and Stripe gateways installed, activated, and enabled. Both had Apple Pay and Google Pay enabled. Doing so displayed the inline notification warning in WooPayments settings as expected.

I then disabled the Stripe gateway, without first disabling Apple Pay and Google Pay, and the error still persists. Though the warning is dismissible, the logic should if possible be aware that the gateway has been disabled and hide the warning.

![image](https://github.com/user-attachments/assets/982de48e-e630-484b-9070-922444176896)

**Comment by mdmoore** [comment]
👋 @pierorocca @Automattic/heisenberg - I haven't been able to reproduce this one. I've activated WooCommerce Stripe Gateway alongside WooPayments and enabled Apple/Google Pay in both plugins. I get the duplication notice when both plugins are active, but when deactivating WooCommerce Stripe Gateway (without first disabling Apple/Google Pay), the duplication notice disappears. Looking at the [`Duplicates_Detection_Service`](https://github.com/Automattic/woocommerce-payments/blob/develop/includes/class-duplicates-detection-service.php) class, each check (CC, APM, Payment Requests) first checks for enabled gateways or registered payment methods. Those checks should be covering this since inactive plugins wouldn't have registered gateways. Can anyone still reproduce this? Here's what I'm getting:

https://github.com/user-attachments/assets/06e68637-acd9-4cb1-9b54-6d6af1b2f265

**Comment by pierorocca** [comment]
Hey @mdmoore instead of deactivating the plugin, try disabling the gateway through the toggle in WooPayments settings.

**Comment by mdmoore** [comment]
Thanks for clarifying, @pierorocca. That's clear in your description. Not sure why I was stuck on deactivating the plugin 🤦‍♂️. I was able to reproduce the issue when disabling the gateway. Solved with #9663.
