### ISSUE TITLE
Remove `'-` sign in fees column for plugin-generated transaction CSV files (plugin and service CSVs are inconsistent)

### ISSUE THREAD

**Issue by wyter** [Automattic/woocommerce-payments#9303]
### Description

> [!IMPORTANT]  
> This issue occurs upstream in the `@woocommerce/csv-export` package – I've reopened the related issue in the WC repo: https://github.com/woocommerce/woocommerce/issues/25379
> I've marked this issue as `blocked` while we resolve the issue upstream.

We received this in one of our support requests:

> When the report download is emailed to me, it is great (see screenshot attached called 'fine'). However, when the report downloads immediately, which is most of the time, there are the symbols `'-` in front of every figure in the 'fees' column (see screenshot titled 'not fine'). This is very frustrating, as Excel is not able to recognise the figures and automatically create a total for me underneath, so I have to manually remove the `'-` symbols from every single row of the fees column.

Here's the "fine" screenshot from emailed reports, doesn't have `'-` symbols:

![fine, has no symbols](https://github.com/user-attachments/assets/0a069c32-f93a-41b3-af38-871d97898236)

Here's the "not fine" screenshot from automatically downloaded transaction reports, has `'-` symbols:

![has symbols, not fine](https://github.com/user-attachments/assets/268bd1d3-cf65-4a37-b9c6-e9eba3ecc91c)

**Request:** Since the emailed transaction CSV files do not have the symbols  `'-`, could we consider removing these symbols in the automatically-downloaded transaction reports?

### Acceptance criteria

Removal of  the symbols `'-` before transaction fees in automatically downloaded transaction CSV files.

### Designs
The fees column in the automatically-downloaded transaction reports should look like this:
![fine, has no symbols](https://github.com/user-attachments/assets/52124872-2773-4442-88e2-a583eab012ac)

### Testing instructions
1. Go to WP-Admin → Payments → Transactions on a WooPayments account that doesn't have many transactions (you can use the advanced filters in the "show" dropdown if the account has many transactions to reduce the number of transactions shown to ~20 or so)
2. Click on the download button to automatically download the WooPayments transactions
![download transactions](https://github.com/user-attachments/assets/af4d0ebf-3051-47c1-94ec-44eac05b5d4e)
3. Open the downloaded CSV file, check the Fees column and check if the fees has the symbols `'-`. Ideally, these shouldn't show if this improvement is made.

### Additional context
Reported on 8635657-zen

**Comment by Jinksi** [comment]
🤔 It looks like the `'` prepended to negative values is not a bug, it is expected as part of the escaping process from `@woocommerce/csv-export` to prevent a [CSV injection exploit](https://owasp.org/www-community/attacks/CSV_Injection):

https://github.com/woocommerce/woocommerce/issues/25379

https://github.com/woocommerce/woocommerce/blob/dbb8ab8d1e875528da6c81469df7855792a85e5f/includes/export/abstract-wc-csv-exporter.php#L355-L378

> To remediate it, ensure that no cells begin with any of the following characters:
> Equals to (=)
> Plus (+)
> Minus (-)
> At (@)
> Tab (0x09)
> Carriage return (0x0D)

Forcing all values to a string before `@woocommerce/csv-export generateCSVDataFromTable()` does not bypass this escaping process.

Note, this is only a problem for untrusted user input, which should not be a problem here since WooPayments is generating the values after [fetching from the `/transactions` REST endpoint](https://github.com/Automattic/woocommerce-payments/blob/dec673364f742fdbf835a13d12ca93959b36d874/includes/admin/class-wc-rest-payments-transactions-controller.php#L112-L122).

**Comment by Jinksi** [comment]
I've confirmed this issue also exists in WC Analytics and negative values.

An example of a WC Analytics → Revenue exported CSV opened with Apple Numbers:

<img width="650" alt="image" src="https://github.com/user-attachments/assets/b1b82cb4-530d-4cf7-9608-f069ffecc261">
 
[revenue_2024-09-26_page-wc-admin_period-custom_compare-previous-year_chart-net-revenue_path--analytics-revenue_per-page-100_orderby-net-revenue_interval-week_order-asc_paged-1_after-2023-06-01_before-2023-06-30.csv](https://github.com/user-attachments/files/17141304/revenue_2024-09-26_page-wc-admin_period-custom_compare-previous-year_chart-net-revenue_path--analytics-revenue_per-page-100_orderby-net-revenue_interval-week_order-asc_paged-1_after-2023-06-01_before-2023-06-30.csv)

**Comment by Jinksi** [comment]
I've re-opened the upstream `@woocommerce/csv-export` issue, so we can move the discussion there: https://github.com/woocommerce/woocommerce/issues/25379.

I'll mark this as `blocked` until we can resolve upstream by potentially bypassing the escaping process if values are from a trusted source.

**Comment by Jinksi** [comment]
This is related to a prior WooPayments issue #7307, where tab chars were previously prepended rather than `'`. [A subsequent PR](https://github.com/woocommerce/woocommerce/pull/41163) to `@woocommerce/csv-export` changed the tab char to a `'` char, as recommended by [OWASP](https://owasp.org/www-community/attacks/CSV_Injection).

**Comment by haszari** [comment]
> I'll mark this as blocked until we can resolve upstream by potentially bypassing the escaping process if values are from a trusted source.

- If this is fixed in Woo core, will we get the fix "for free" or will we need to rebuild with an updated woo package?
- Can we start work on a fix upstream in WooCommerce ourselves, i.e. open a PR that would satisfy our merchant needs (not break the CSV) AND do so safely, i.e. if someone managed to get a sneaky formula into the chain somewhere, it would be escaped?

As I understand it, the escaping is not working correctly, it is breaking the CSV – it should (IMO) be transparent, especially to valid data.

**Comment by Jinksi** [comment]
> If this is fixed in Woo core, will we get the fix "for free" or will we need to rebuild with an updated woo package?

We'll need to update the woo package `@woocommerce/csv-export`. WooPayments is on the [latest version 1.9.0](https://www.npmjs.com/package/@woocommerce/csv-export?activeTab=versions) though, so should not be a problem.

> Can we start work on a fix upstream in WooCommerce ourselves

Yes 💯 – but firstly we should determine if escaping in this way is a hard requirement or not, which I see you're considering in the upstream issue discussion https://github.com/woocommerce/woocommerce/issues/25379#issuecomment-2420832679  🙏

**Comment by Jinksi** [comment]
A fix for this upstream in `@woocommerce/csv-export` has been merged: https://github.com/woocommerce/woocommerce/pull/52727. Awaiting release (DRI @Jinksi) before opening a PR to bring this fix to WooPayments.

**Comment by Jinksi** [comment]
I've moved this back from `In Progress` to `Next` since I'm no longer working on this – the CSV deduplication project (pdjTHR-4t9-p2) will likely solve this when removing JS-based CSV exporting (#9969).

**Comment by haszari** [comment]
> I've moved this back from In Progress to Next since I'm no longer working on this – the CSV deduplication project (pdjTHR-4t9-p2) will likely solve this when removing JS-based CSV exporting (https://github.com/Automattic/woocommerce-payments/issues/9969).

Maybe we can just optimistically close? Instead of keeping it open and distracting us.

- #9969

**Comment by Jinksi** [comment]
> Maybe we can just optimistically close? Instead of keeping it open and distracting us.

I've linked #9986 as solving this – so it will be closed soon with a breadcrumb trail to the solution.

**Comment by Jinksi** [comment]
**Update**: since we want to import the latest [`@woocommere/csv-export`](https://www.npmjs.com/package/@woocommerce/csv-export/v/1.10.0) into WooPayments anyway, to keep our deps up-to-date, I'm going to open a PR (#10028) with this fix regardless of the changes in PR #9986.

I will probably be able to get this fix in a release before the #9969 is merged – looking at the project thread, #9969 may require more feedback and alignment.

**Comment by shendy-a8c** [comment]
Once https://github.com/Automattic/woocommerce-payments/pull/10028 is merged and released in WooPayments 8.7.0, customer needs to update to WooPayments 8.7.0 *and* use WooCommerce 9.6 ([currently not yet released](https://github.com/woocommerce/woocommerce/releases/tag/9.6.0-beta.1)) or newer.

**Comment by Jinksi** [comment]
Thanks for pointing that out here @shendy-a8c. The fact that we are tied to the `csv-export` version used/imported by WC core is a quirk that I was not aware of until I wrote the testing instructions for #10028.
