### ISSUE TITLE
Direct Checkout not working with third-party cookies disabled

### ISSUE THREAD

**Issue by leonardola** [Automattic/woocommerce-payments#9313]
### Describe the bug
Direct checkout is not working for users without third-party cookies disabled.

### To Reproduce
**Setup**
- Merchant site running WooCommerce >= 9.2.1
- Customer has blocked third party cookies in their browser
- Customer is not logged in to merchant site
- Customer is logged in to WooPay

**Bug**
- As a customer add a product to cart
- Visit the cart page
- Open the developer tools > Network panel
- Click the Proceed to Checkout button
- Notice that you'll get forwarded to `woopaydomain/woopay/?checkout_redirect=1...`
- Notice that you'll get quickly forwarded back to the merchant site checkout page

This happens because customer is null [here](https://github.com/Automattic/woocommerce-payments/blob/ecb997675795ffaa11d879922591549c6edc2362/includes/woopay/class-woopay-session.php#L515)

https://github.com/user-attachments/assets/c3e51c85-e42a-4d79-88c8-b41cbbca75a6

**Comment by alefesouza** [comment]
This issue was introduced to https://github.com/woocommerce/woocommerce/pull/47704 and is related to [this](https://github.com/woocommerce/woocommerce/pull/47704/files#diff-0f71ccfe806e1eb743a9e5157ee84489aa4961090e28f6d8bdfc9c4030fe0feeR26-R28) and [this](https://github.com/woocommerce/woocommerce/pull/47704/files#diff-0f71ccfe806e1eb743a9e5157ee84489aa4961090e28f6d8bdfc9c4030fe0feeR37-R39) condition.

**Comment by alefesouza** [comment]
This issue was introduced on https://github.com/woocommerce/woocommerce/pull/47704 and is related to [this](https://github.com/woocommerce/woocommerce/pull/47704/files#diff-0f71ccfe806e1eb743a9e5157ee84489aa4961090e28f6d8bdfc9c4030fe0feeR26-R28) and [this](https://github.com/woocommerce/woocommerce/pull/47704/files#diff-0f71ccfe806e1eb743a9e5157ee84489aa4961090e28f6d8bdfc9c4030fe0feeR37-R39) condition.
