### ISSUE TITLE
[ECE] Replace SVGs with ECE buttons in the Blocks Editor preview

### ISSUE THREAD

**Issue by rafaelzaleski** [Automattic/woocommerce-payments#9417]
### Describe the bug
In the Cart & Checkout Blocks, the Editor preview currently renders ECE buttons as static SVGs instead of interactive, fully styled buttons. This limits the ability to accurately visualize the button layout within the editor.

The new `buttonAttributes` API (integrated with WooPayments in [this PR](https://github.com/Automattic/woocommerce-payments/pull/8888)) was designed to ensure that express checkout buttons are rendered with their correct layout in the Editor preview, reflecting styling adjustments such as `height` and `borderRadius`. 

To achieve this, we need to replace the SVGs currently in use with real ECE buttons, similar to how they are rendered in the WooPayments settings page for express checkout.

**Comment by alexflorisca** [comment]
Additionally, in order to improve the merchant UX, we've added the ability for payment extensions to declare support for styling controls that the buttons can implement. See https://github.com/woocommerce/woocommerce/pull/51296. This should be done as part of this PR, once the full buttons are rendered in the editor, please add the `supports.style` property to the options object of `registerExpressPaymentMethod`. Failure to do this may mean the controls will not be visible (more details in https://github.com/woocommerce/woocommerce/pull/51296 how this works)

```
registerExpressPaymentMethod( {
  ...
  supports: {
    style: [ height', 'borderRadius' ]
  }
...
}
```
