### ISSUE TITLE
Add a tracks event for when the user is returned from KYC

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#943]
We have `wcpay_connect_account_clicked` when KYC is started. It would be good to see how leaky KYC is by having an event fire when the user returns from KYC.

cc @oneillo @thenbrent 

See also paJDYF-OD-p2 3292

**Comment by allendav** [comment]
Assigning my best guess at size. Feel free to counter with a different size.

**Comment by vbelolapotkov** [comment]
It might be a bit trickier than it is because we're going to ask merchants to enable tracking after KYC completed. https://github.com/woocommerce/woocommerce-admin/pull/5248

**Comment by vbelolapotkov** [comment]
Just discussed with @thenbrent. It's worth tracking via parameter whether existing or new account is connected. It would allow us to detect issues when a merchant is trying to connect the same account multiple times.

**Comment by ilyasfoo** [comment]
>It might be a bit trickier than it is because we're going to ask merchants to enable tracking after KYC completed.

I'm thinking a possible way is to:
1. Store the status of an existing account connection in LocalStorage before a user clicks on "Set up".
2. After returning from KYC, store a flag in LocalStorage.
3. Somewhere in our JS always checks for the flag and submits track with the connection information as an event parameter if it exists and tracking is enabled.

@vbelolapotkov Let me know what do you think?

**Comment by vbelolapotkov** [comment]
> Store the status of an existing account connection in LocalStorage when the user clicks on "Set up".

`Set up` button is only top of the iceberg. Many merchants onboard from home page task list or payments tasks page. So local storage might be not the best option. But we might try to utilize store option for this, e.g. `_wcpay_kyc_source`.

> After returning from KYC, store a flag in LocalStorage.

Here we can send option value with wcpaySettings.

> Somewhere in our JS always checks for the flag and submits track with the connection information as an event parameter if it exists and tracking is enabled.

This could be done in ToS modal code. I.e. if tracking enabled send track immediately, if disabled - wait for modal, and send it after tracking enabled (if enabled).

**Comment by ilyasfoo** [comment]
That makes much more sense. Thanks, @vbelolapotkov!

**Comment by ilyasfoo** [comment]
Hi @vbelolapotkov, a couple questions if you don't mind:

> It's worth tracking via parameter whether existing or new account is connected.

By "new account", do you mean a different account than the one that's currently connected to the site?

> It would allow us to detect issues when a merchant is trying to connect the same account multiple times.

Excuse my naivete here. Are there any example scenarios for this issue? It would also be great if it is something that we can manually induce.

**Comment by vbelolapotkov** [comment]
> Hi @vbelolapotkov, a couple questions if you don't mind:

Sure @ilyasfoo!

With `new account` I mean new Stripe account created. The idea is to spot the cases when a single merchant is going through KYC flow multiple times without creating new Stripe account, i.e. connecting with same account (created earlier on the server). I don't remember exactly where it comes from, but I think it's related to cases when same existing Stripe account was connected to the site (e.g. due to Jetpack IDC/cloning the site or other issues). This will need changes on the server side as well.

**Comment by ilyasfoo** [comment]
@vbelolapotkov I have a concern to raise about `new account`. My logic to determine `new account` is by comparing existing `stripe_account_id` with the newly connected account ID returned from Stripe.

In WCPay server's OAuth receiver, before obtaining the returned Stripe account ID from token, a [condition checks](https://github.com/Automattic/woocommerce-payments-server/blob/e96a4c383cda910901f3a456b1aa3539426d2475/server/wp-content/rest-api-plugins/endpoints/wcpay/class-oauth-redirect-controller.php#L144-L157) for cases such as user refresh to prevent a Stripe token used twice, which shorts circuits to return early:
```php
if ( ! $is_new_connection && $existing_account->is_live && ! $force_on_boarding ) {
  // An account already exists for this blog, is live, and the force onboarding flag is not set.
  // Just redirect back to the site with existing data.
  // Prevents an error where the user would refresh or otherwise call this endpoint twice with the same connect token,
  // resulting in the token being posted twice and Stripe invalidating it and deleting the newly-created account on their side.
  // We do not do this for the test accounts to allow them to be switched from dev to live.
  $this->logger->log_debug( "Found an existing account record for blog $blog_id. Redirecting back with the existing data." );
  return $this->get_success_redirect_response(
    $return_url,
    $secret,
    $existing_account->stripe_account_id,
    $existing_account->is_live
  );
}
```
The problem is, this condition is where I would think where most users who attempt to connect to the same account multiple times end up. Without having the returned Stripe account ID, we won't be able to determine whether user is connecting to the same account or otherwise.

A possible solution would be to have a storage of "used" tokens so that we can change this check, but I feel the complexity it adds is more than what I'd like. Please let me know if I missed anything, or if this change would be desirable? Thanks!
