### ISSUE TITLE
Editing the Checkout Block displays express payment method buttons even when they are disabled

### ISSUE THREAD

**Issue by csmcneill** [Automattic/woocommerce-payments#9465]
### Describe the bug

Express payment method buttons are displayed when editing the Checkout Block even when the payment method is disabled in the WooPayments settings.

> [!NOTE]
> This only seems to affect Apple Pay and Google Pay.

### To Reproduce

1. Go to Payments > Settings
2. Disable all express payment methods.
3. Open the Checkout Block page in the editor
4. See that the Apple Pay and/or Google Pay buttons are still rendered in the editor

### Actual behavior

Express payment method buttons are visible in the editor when they are disabled in settings.

### Screenshots

![CleanShot 2024-09-18 at 21 12 26](https://github.com/user-attachments/assets/b7bb5440-78ee-4851-bdff-bc3df43f7f45)

### Expected behavior

Express payment method buttons should not be visible in the editor when they are disabled in settings.

### Potential solution
We should only call `registerExpressPaymentMethod` if it is enabled from the WooPayments settings page

### Additional context
Originally reported for Stripe for WooCommerce: https://github.com/woocommerce/woocommerce-gateway-stripe/issues/3437

**Comment by bborman22** [comment]
Thanks for flagging this @csmcneill! Just leaving a note here for whoever picks this up, this is likely due to these currently being SVGs and so not going through the normal rendering process. I believe we have an [upcoming task](https://github.com/Automattic/woocommerce-payments/issues/9417) to change the SVGs to actually render the buttons which may address this issue at the same time.
