### ISSUE TITLE
Links in tooltips are too light color, hard to read / click

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#9559]
### Describe the bug

The link in this tooltip looks too light.

![Image](https://github.com/user-attachments/assets/7a512d63-9cff-41b1-b526-840d7c3adb3a)

### To Reproduce

1. Go to the deposits list page, ie wp-admin > Payments > Deposits (or Payouts)
2. Click on the deposit schedule tooltip like the screenshot above.

### Actual behavior

Links' color is too light making it almost unreadable.

### Additional context

Discovered while working on https://github.com/Automattic/woocommerce-payments/pull/9528.

**Comment by haszari** [comment]
Marking as `high` since this is clearly a regression and makes WooPayments harder to use (accessibility issue).

Note that this affects all tooltips, so likely an upstream/general style change somewhere.

Some other examples:

![Image](https://github.com/user-attachments/assets/a6703e92-2596-46a1-8759-628ddfc1943e)
![Image](https://github.com/user-attachments/assets/bb6d4d83-9f48-4756-924d-a92b94eeb262)
![Image](https://github.com/user-attachments/assets/d1722f3a-3d24-4914-89a5-b69ae3120b34)

**Comment by Jinksi** [comment]
Related to #9273, which changed the text color for dark-background tooltips, inadvertently impacting light-background tooltips.

**Comment by Jinksi** [comment]
See https://github.com/Automattic/woocommerce-payments/blob/e398dd77bbf6a5ba07f18ded4109caae508e9cd1/client/components/tooltip/style.scss#L58-L61
