### ISSUE TITLE
Payments → Overview highlight colours are inconsistent for users with a custom admin theme enabled

### ISSUE THREAD

**Issue by Jinksi** [Automattic/woocommerce-payments#9584]
### Describe the bug

For users who have a custom WP admin theme enabled, highlights on the Payments → Overview screen are inconsistent, with some elements using the theme highlight colour and others using a hard-coded blue colour.

> [!IMPORTANT]  
> **This issue is blocked due to accessibility concerns with WP-admin themes.**
> Contrast ratios in some themes, e.g. "Sunset", may not be sufficient to meet accessibility standards for text legibility. We should fix these theme accessibility concerns upstream in Gutenberg or wp-admin before incorporating these theme accent colours in WooPayments. See https://github.com/Automattic/woocommerce-payments/pull/9641#issuecomment-2516187770.

**Also note** that this issue assumes that links should be, which is probably incorrect, and these should inherit the default WP-admin link text colour.

It is common for users to have a custom admin theme enabled, as some WordPress themes introduce additional admin themes that may be selected by default for users.

For example, WPCOM-hosted sites have custom admin themes available, including "Classic Dark" which was the default WooExpress theme, with magenta highlights.

### Screenshots

![Image](https://github.com/user-attachments/assets/7995e27f-709b-44c2-8edc-2af473733575)

![Image](https://github.com/user-attachments/assets/d59ae2d8-aaa1-49a9-91b7-cc136c5c0b13)

### To Reproduce

1. In WP Admin, navigate to Users → Profile
2. Select a different admin theme
  ![Image](https://github.com/user-attachments/assets/b076c3b2-6b55-41f5-a83a-22a85b33f2b5)
4. Navigate to Payments → Overview
5. Notice that some links are coloured blue, while some match the admin theme colours.

### Expected behavior

Highlights should use custom theme colours. Maybe links should too.

### Additional context

Discussed in PR #9571
Accessibility concerns raised in https://github.com/Automattic/woocommerce-payments/pull/9641#issuecomment-2516187770.
Discussion on Slack about accessibility concerns: p1730304032554459-slack-CNGQYA3B9

**Comment by Jinksi** [comment]
Assigning this with `focus: deposits` and `focus: reporting` since most/all of the problematic links are within related cards on the overview screen.

**Comment by haszari** [comment]
Shifting this back to `In progress` while we're waiting on [input from design](https://github.com/Automattic/woocommerce-payments/pull/9641).

**Comment by nagpai** [comment]
I am moving this from the WooPayments 8.6.0 milestone to that of 8.7.0, since we are expecting design inputs for the PR.

**Comment by haszari** [comment]
I've removed the status from this so I can take another look at it & re-triage.

**Comment by haszari** [comment]
Thanks @Jinksi for diving in and figuring out what's happening here 🙌🏻 

From your [comment on the abandoned PR](https://github.com/Automattic/woocommerce-payments/pull/9641#issuecomment-2516187770):

> Contrast ratio issues in “Sunset” theme accent colours highlight an accessibility concern with custom wp-admin themes.
Possible fix A: Adjust SCSS mixins in Gutenberg to meet standards while preserving theme integrity. We can then revisit this issue in WooPayments once these changes have occurred.
Possible fix B: Align wp-admin and Gutenberg colour systems via a “theme provider” for algorithmic scales.
Either way, I think we should close this PR because we don't want to introduce accessibility issues into WooPayments UI elements.


Summarising the issue as I understand it:

1. Users can change admin colour scheme or admin "theme" in WordPress core, in [user profile](https://wordpress.org/documentation/article/users-your-profile-screen/). 
2. WooPayments (and maybe Woo and other plugins) inconsistently use the theme colours. For example, some links are blue (default) when they should be yellow (theme colour).

So far so good, sounds like a bug. However…

3. The admin colour schemes may not be good for accessibility, specifically `Sunset` theme links have low contrast ratio with background ( 🙇🏻  @rogermattic  ). 
4. We don't know how important this issue is for merchants – we haven't had any reports, and don't know if admin colour schemes are commonly used (vs. uncommon).
5. If we were to fix the bug in WooPayments, the theme-coloured links would be less accessible (for e.g. `Sunset` users).

So here's what I think we should do:

- Ensure the admin colour scheme accessibility issue is logged in WordPress core. (I haven't searched, @rogermattic  @Jinksi do you know if it's logged anywhere?) It needs to be fixed upstream, priority unknown, but should be relatively straightforward – refresh the colour schemes so they are accessible!
- Close this issue. Why? TLDR it's not actionable or high enough priority.
  - (5) accessibility is more important than respecting custom admin theme colours
  - (4) if it is affecting merchants then we will get more reports (was reported internally)
  - We could keep the issue open, `blocked` and waiting for upstream fix, but I'd rather close as known issue and reopen if & when things change in core. 


> 
The parent issue https://github.com/Automattic/woocommerce-payments/issues/9584 can remain open with clarification that a broader WP-admin design system accessibility overhaul may be required before we should use these colours in WooPayments.

So I'm going to close! But feel free to comment to discuss priority or reopen if appropriate.
