### ISSUE TITLE
Update URL of deposits docs

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#9587]
Deposits docs' URL (https://woocommerce.com/document/woopayments/deposits/) will change (read pdjTHR-4ja-p2#comment-6250).

We need to update all the deposits docs URL in the code after a redirect has been in place.

Please coordinate with @aheckler who will put a redirect in place from e.g. `/payouts` to `/deposits`.

**Comment by aheckler** [comment]
As of now, all WooPayments docs URLs that include the word "deposit" or "deposits" have had their URLs changed to use "payout" or "payouts". No actual docs _content_ has been changed though (with one exception noted below), so "deposits" is still used throughout the doc text.

Various redirects are in place so that visitors to the old URLS are sent to the new ones. For example, this URL:

https://woocommerce.com/document/woopayments/deposits/scheduled-deposit-vs-instant-deposit/

... now redirects to this URL:

https://woocommerce.com/document/woopayments/payouts/scheduled-payout-vs-instant-payout/

The full list of doc URLs that have changed is [here](https://docs.google.com/spreadsheets/d/1MyMrd6thw9Mo9CmDCkhXQNLuTK22aEnoQq-N06gTJsc/edit). 

Please note that this doc URL:

https://woocommerce.com/document/woopayments/payouts/deposits-and-payouts/

... is a special case for two reasons:

- The URL still includes "deposits" because the doc itself discusses why WooPayments uses the word "deposits" and not "payouts."
- Since we are switching from "deposits" to "payouts" after all, I went ahead and updated the doc content to include a notice to that effect.

Engineering should now be able to do a careful find/replace in the code and swap out docs URLs.

**Comment by aheckler** [comment]
An additional note... Using this regex:

`^.*document\/woopayments.*#.*(deposit.*#?.*|#.*deposit.*).*$`

... I found [two places in this repo](https://github.com/search?q=repo%3AAutomattic%2Fwoocommerce-payments%20%2F%5E.*document%5C%2Fwoopayments.*%23.*(deposit.*%23%3F.*%7C%23.*deposit.*).*%24%2F&type=code) we link to anchor links that contain the word `deposit`.

I have now altered those two anchors in the WooCommerce.com docs so that replacing `deposit` with `payout` in the hardcoded links will work as expected.

EDIT: @shendy-a8c I also used the above regex in the server repo and found 4 instances of anchor links with `deposit` in them. I changed those in our docs too. Bottom line: y'all should be unblocked to change docs links everywhere now.

**Comment by nagpai** [comment]
PR #9627 merged with feature branch to resolve this issue.
