### ISSUE TITLE
Rename 'deposit' to 'payout' on WooPayments docs about deposit

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-payments#9599]
Docs pages (not limited to):
- https://woocommerce.com/document/woopayments/
- https://woocommerce.com/document/woopayments/deposits/

**Comment by aheckler** [comment]
I'm working on this in my own GH project board [here](https://github.com/orgs/Automattic/projects/1038/views/1?pane=issue&itemId=69527090&issue=Automattic%7Cpayops-content-and-quality%7C60). Note that we won't start replacing actual docs _content_ until after 8.5.0 is released.

**Comment by jessy-p** [comment]
👋  @aheckler  Would the URLs of the docs also change or just the content? If the URLs are changing, could the old ones redirect to the new URLs?

**Comment by aheckler** [comment]
@jessy-p I left a comment about the URLs over [in the appropriate issue](https://github.com/Automattic/woocommerce-payments/issues/9587).

**Comment by aheckler** [comment]
Just left an update on this [here](https://github.com/Automattic/payops-content-and-quality/issues/60#issuecomment-2476077355). TLDR: Word updates already done, working on screenshots.

**Comment by aheckler** [comment]
Screenshots in the docs are now all up to date with one exception: the [progressive onboarding / gradual signup doc](https://woocommerce.com/document/woopayments/startup-guide/gradual-signup/). This is because getting a free PO slot (they are very limited) is challenging. I've DM'ed @dmallory42 to see if he can grab some images for me. Otherwise, this is done.
