### ISSUE TITLE
Add inbox note to encourage merchant to complete onboarding

### ISSUE THREAD

**Issue by thenbrent** [Automattic/woocommerce-payments#989]
If a merchant activated the WC Pay plugin 3 days ago, and hasn't completed onboarding to create an account, send an inbox notification to remind and encourage them to complete the sign-up.

More details: paqDfi-Pt-p2#comment-2483

**Comment by dechov** [comment]
See also https://github.com/woocommerce/woocommerce-admin/issues/4494

**Comment by rogermattic** [comment]
@daquinons @brandonwanA8C  I'd propose closing this ticket since we have a task on the Home Task list, that basically serves the same purpose. 

<img width="881" alt="Screenshot 2022-11-07 at 18 15 37" src="https://user-images.githubusercontent.com/94967682/200373227-71f1891a-0d2a-4c24-80e8-401476c4b26d.png">


If anything, we could consider highlighting the payments task if not completed after a few days (or when the user doesn't follow the order of tasks, and keeps avoiding the payments setup) perhaps?


<img width="605" alt="Screenshot 2022-11-07 at 18 21 15" src="https://user-images.githubusercontent.com/94967682/200374202-f470a2da-3fbe-476f-9cc7-f385c8377583.png">

**Comment by brandonwanA8C** [comment]
@rogermattic @daquinons 
based on my understanding, I agree with Magda's PoV - the "inbox notification" should capture ALL potential tasks the merchant needs to complete, not specific to Payments.
@rogermattic in your screenshot example above, the user has "5 inbox notifications", do you know if the notifications have any instructions on "what's the next best-possible task Woo recommends - out of the 5"? 

As a user, if the 5 notifications were to ask to "must do this", "must do this", "must do this...", I'd be overwhelmed or annoyed with these "reminders".

**Comment by daquinons** [comment]
Thank you! Closing the issue then for now, in case you need to discuss, you can continue here and if there is any action to be done, create a new one 🙏

**Comment by rogermattic** [comment]
@daquinons @brandonwanA8C  I've taken this thread out of Github, to Slack so that we don't need to discuss anything more here:)
