### ISSUE TITLE
Transaction Payment Details View: Session Child

### ISSUE THREAD

**Issue by allendav** [Automattic/woocommerce-payments#99]
Add the following view to the Transaction Payment Details View

Child of #83 

<img width="838" alt="session-child" src="https://user-images.githubusercontent.com/1595739/59634931-bb502800-9104-11e9-84f4-1ae626cbd3e3.png">

**Comment by dwainm** [comment]
I started working on this just to realize that getting the data may not be that straightforward. I scanned all the API docs to look for user agent and charged IP address but this bit of information seems to come from the risk analysis tool( Radar).

<img width="1178" alt="Screenshot 2020-10-09 at 15 20 18" src="https://user-images.githubusercontent.com/1713474/95588359-9ee7a580-0a43-11eb-945e-752cf43f227e.png">

I'll reach out to Stripe and ask for more information.

**Comment by dwainm** [comment]
There may be a way to get this via the review API:

https://stripe.com/docs/api/radar/early_fraud_warnings/list

**Comment by dechov** [comment]
@dwainm The review object is an expandable property of both the charge and the payment intent objects, so we can still get by without any additional requests 👍

**Comment by dwainm** [comment]
Expanding the review object doesn't work on the test platform account. Stripe support will look into the issue and get back to me.

**Comment by dwainm** [comment]
I propose we close this issue because payment session data comes from Radar and we do not have that activated for our merchants. 

I've been in touch with Stripe's support without any success. I can see a risk insights section on our dev account, but the risk section is not included for our merchants when viewing the dashboard as an account.

**Tech**
For the review item to be expanded a review ID needs to be sent along with the Payment Intent. What I'm gathering now is that all of our payment intent objects do not have this review id as the review property value is always set to `null`.

<img width="1027" alt="Screenshot 2020-11-03 at 09 02 38" src="https://user-images.githubusercontent.com/1713474/97957863-bac93780-1db4-11eb-9694-2452c76ebfda.png">

cc @thenbrent @bmccotter  @allendav  @vbelolapotkov @LevinMedia

**Comment by allendav** [comment]
@dwainm wrote

> I propose we close this issue because payment session data comes from Radar and we do not have that activated for our merchants.

Thank you for digging into it. I agree that this issue is OK to close. Maybe we'll revisit this someday, maybe not.

**Comment by dwainm** [comment]
One last email from Stripe that I'll investigate:

> I'd recommend using the API to pull this data. Using the "List all open reviews" API call[1], you can pull data on all ongoing reviews on the connected account. You can specify the connected account to pull data from using the Stripe account header, see the link below[2].

> To automatically pull review data as they are opened, you track the 'review.opened' event[3], using webhooks[4]. 

> I hope this helps clear things up Dwain, but if you have any other questions or concerns, please don't hesitate to reach right back out! I'll be happy to help in any way I can!

[1] https://stripe.com/docs/api/radar/reviews/list 
[2] https://stripe.com/docs/connect/authentication#stripe-account-header 
[3] https://stripe.com/docs/api/events/types#event_types-review.opened 
[4] https://stripe.com/docs/connect/webhooks#connect-webhooks

**Comment by thenbrent** [comment]
@LevinMedia thoughts on closing this one?

I personally really like it and I'm sure we can get the same data from our side if we really wanted to add it, but don't think it's worth that effort right now. I'm happy to close it and move it to an [Idea](https://ideas.woocommerce.com/forums/133476-woocommerce?category_id=382132) to see if it's a popular request before pushing it onto the roadmap.

**Comment by dwainm** [comment]
@thenbrent closing this as after more testing I see that we don't really have access to the data. Reviews are only accessible if 1. The account has radar and 2. if a review was opened due to meeting specific rules on an account. 

Adding the data from our side is a good option if this is something that our customers request.

I've created an idea for this: https://ideas.woocommerce.com/forums/133476-woocommerce/suggestions/41910010-show-card-session-details-on-payment-details-page
